### ISSUE TITLE
vaadin-grid-selection-column default width should be customizable with CSS

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1002]
The current fixed `52px` value works for some cases. But for example, with the Valo checkbox, it’s too narrow, and the right edge of the checkbox is clipped.

<img width="79" alt="screen shot 2017-09-26 at 11 55 28" src="https://user-images.githubusercontent.com/66382/30851561-a13a7ba2-a2b1-11e7-8984-23fe918063a7.png">

Alternatively, the padding of the selection column should be adjustable separately.

**Comment by tomivirkki** [comment]
The default width was increased to `58px` by https://github.com/vaadin/vaadin-grid/commit/bbd821b89b71652c38d2d47f9f2da73b19dc446d and width can be further customized with the `width` property like any other column. Can't use CSS for this as the width property is needed for calculating a parent column group width.

https://github.com/vaadin/vaadin-grid/issues/1481 enables column-specific cell styling.
