### ISSUE TITLE
Last cell of grid's row drops to the next row (Material Theme)

### ISSUE THREAD

**Issue by mike392** [vaadin/vaadin-grid#1004]
Can you, please, help me with the following issue?
I have the following code snippet defining the grid:
_@Bean
    @Scope("session")
    public Grid<DisplayPolygon> getGrid() {
        Grid<DisplayPolygon> grid = new Grid<>();
        grid.setSizeFull();
        grid.addColumn(DisplayPolygon::getFrequencyBand).setCaption(columnNames[0]);
        grid.addColumn(DisplayPolygon::getEirp).setCaption(columnNames[1]);
        grid.addColumn(DisplayPolygon::getBandwidth).setCaption(columnNames[3]);
        grid.addColumn(DisplayPolygon::getSatelliteName).setCaption(columnNames[2]);
        grid.setStyleName(MaterialTheme.TABLE_COMPACT);
        return grid;
    }_
When it's rendered - then you can see that last cell of the second row is pushed to the next row. 
![image](https://user-images.githubusercontent.com/16647651/30852516-ac2d566c-a2b4-11e7-927b-9ded8c8bf51e.png)
When I try to remove the specification of width in the browser - like that:
![image](https://user-images.githubusercontent.com/16647651/30852660-3574c73e-a2b5-11e7-8147-0663d58a5656.png)
It moves back to the end.

I've tried plenty of things:
- setWidthUndefined(true);
- setExpandRatio(1) for all the columns
- setMaxWidth for first, last and all columns

Thank you so much in advance!!!

**Comment by mike392** [comment]
I also tried to create customStyleGenerator and set the created style to width: auto - but still no luck...

**Comment by tomivirkki** [comment]
Hi @mike392 
This issue relates to the Vaadin framework Grid (not `<vaadin-grid>` element). Please report the issue at https://github.com/vaadin/framework

**Comment by jouni** [comment]
And since you are using the Material theme, the more correct place to report might actually be https://github.com/vaadin/material-theme-fw8
