### ISSUE TITLE
[4.0.0-alpha3] Computed functions in vaadin-grid-column templates called with empty or null item objects

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-grid#1024]
Not sure where exactly this issue resides, but if you have a computed function in a `vaadin-grid-column` template, it gets called way more often than you would think. Beyond just a performance issue, there is the problem that the `item` object can be empty or `null` for some reason during the calls. **It will throw JS errors out when you scroll the grid** as `null` objects are sent to the function. I have a jsbin that illustrates the point:

https://jsbin.com/libiyiy/edit?html,console,output

Run the JS, you will see empty objects, scroll to the bottom, you will see `null` objects and JS errors in the console.

**Comment by tomivirkki** [comment]
Good catch, thanks for reporting. Fix in https://github.com/vaadin/vaadin-grid/pull/1027
