### ISSUE TITLE
Question: how to reset/clean the filter/sorter after reload items?

### ISSUE THREAD

**Issue by robertop87** [vaadin/vaadin-grid#1028]
Hi,

Currenty I hava a vaadin-grid to show different lists, each list is open after to click in a menu.
In the background I'm using the same vaading-grid, but I'm facing the next issue:
1. Open a list
2. Filter and sort for any criteria
3. Open another list
4. The filter and sort criterias set in step 2 still being applied to the new list.

My question: is there a property or method to clean/remove all filter and sorter criteria? ideally after to replace the items arrays.

Thanks in advanced

**Comment by tomivirkki** [comment]
Hi @robertop87 
You can set `sorter.direction = null` for each of the `<vaadin-grid-sorter>` element to reset them.

Questions on how to use a feature should preferably be posted on our [Gitter](https://gitter.im/vaadin/vaadin-core-elements) or [Slack](https://polymer.slack.com/messages/vaadin) channels. It's generally also much faster way to get help.
