### ISSUE TITLE
Row hover styles are broken in Safari (vaadin-grid v3.0.1)

### ISSUE THREAD

**Issue by madfriend** [vaadin/vaadin-grid#1033]
I tried to set `--vaadin-grid-body-row-hover-cell` mixin and update the background color of all cells, but in Safari (v11.0) it behaves strangely: only some cells get the new background on hover, sometimes with a huge delay.

**Comment by Eugenitals** [comment]
This issue is really annoying. We even have no workaround to fix it right now :(

**Comment by web-padawan** [comment]
The bug is still there also in Safari 13 and in fact it is most likely a ShadyCSS issue.

We no longer support `vaadin-grid` version 3, and now it is very outdated. Please consider using the most recent version (currently 5.x) which gets all the fixes.

Closing as won't fix.
