### ISSUE TITLE
Replacing items array while scrolled results in odd behavior

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-grid#1037]
Version: Grid 4.0.0-alpha3
Browser: Chrome 61/Mac

Scenario: Replace the items array after scrolling down 
Expected result: Scroll position is reset to top
Actual: Gaps appear in the rows

![grid-set-items-scrolled](https://user-images.githubusercontent.com/883698/31408151-6d040fd6-adbc-11e7-9bf2-eea8aa56ba28.gif)

**Comment by marcushellberg** [comment]
Just noticed alpha4. Can't reproduce with it. Closing

**Comment by marcushellberg** [comment]
.. after a while it did get into this again. Not sure what triggers it. But still an issue in alpha4, it seems

**Comment by tomivirkki** [comment]
Closing again :) Reopen if it reproduces again. At least can make this happen in https://expensemanager.demo.vaadin.com/
