### ISSUE TITLE
Add lastrow and lastcolumn mixins

### ISSUE THREAD

**Issue by hotforfeature** [vaadin/vaadin-grid#1039]
Feature request for the 3.x grid, I haven't looked into the 4.x's new styling so I don't know if this feature will be necessary.

According to the Material Design spec, the last row of a table should be 56dp tall. This is normally the footer row, but without a footer it applies to the last row of a table (rows are normally 48dp tall). So when using `<vaadin-grid>` without a footer and following the design spec, we need to add padding to the last row.

It looks like we're already styling some things by adding [`[lastrow]`](https://github.com/vaadin/vaadin-grid/blob/2.x/vaadin-grid-table.html#L207) and [`[lastcolumn]`](https://github.com/vaadin/vaadin-grid/blob/2.x/vaadin-grid-table.html#L258) attributes. What would the feasibility be of adding some mixins to expose styling the last row cells and last column cells to the end user?

**Comment by manolo** [comment]
Hi, we don't have any plans for adding new features to old major versions, we only guarantee bug fixes. If you cannot style your cells by using CSS selectors in the light dom, then I suggest that you might send a PR for the old branch, and the team could discuss the feature during the review process. 
ping @jouni

**Comment by hotforfeature** [comment]
I'm so sorry @manolo, I had my version numbers completely off. I'll edit the OP to reflect. I'm currently looking at the 3.x grid and I haven't looked into the new 4.x alpha release to see if there's anything that would allow last row customization with the new style theming.

**Comment by jouni** [comment]
In 4.x, there’s `last-column` attribute added for the last cell in a row, so you can style that using `[part~="body-cell"][last-column]` (or (`[part~="cell"][last-column]` if you want to target header and footer cells as well).

But no attribute for the last row. I think that would be a nice addition.

**Comment by web-padawan** [comment]
We are not going to add new features to grid versions older than 5.0 so I'm closing this issue.
