### ISSUE TITLE
Hover Cell creates little white box

### ISSUE THREAD

**Issue by justinplatz** [vaadin/vaadin-grid#1043]
I am using the most recent version of the vaadin-grid component. I am noticing a strange behavior whenever I hover a cell a little white box appears.

![image](https://user-images.githubusercontent.com/6657079/31620458-4ea4c230-b265-11e7-8e4d-0c51a5c487f2.png)

**Comment by justinplatz** [comment]
`      vaadin-grid.vaadingrid{
        height: 70vh;
        background: var(--bd-offwhite-solid);

        --vaadin-grid-header-cell: {
          background: var(--bd-offwhite-solid);
          font-family: IBMBold;
          font-size: .85em; 
          color: var(--bd-black);
        };
        --vaadin-grid-footer-cell: {
          background: var(--bd-offwhite-solid);
          font-family: IBMBold;
          font-size: .85em; 
          color: var(--bd-black);
        };

        --vaadin-grid-body-cell: {
          background: var(--bd-offwhite-solid);
          font-family: IBMRoman;
          font-size: .85em; 
          overflow-x: scroll;
          height: 5vh;
          color: var(--bd-black);
        };

        --vaadin-grid-body-row-hover-cell: {
          background-color: var(--paper-grey-200);
        };

        --vaadin-grid-body-row-selected-cell: {

        };

      }`

This is my code for styling of the grid. Nothing should be creating these boxes AFAIK.

**Comment by justinplatz** [comment]
If you have questions about how to reproduce this bug please let me know. In the meantime I will be switching out the vaadin-grid for another polymer component

**Comment by cqst** [comment]
Hello @tomivirkki 
Could you please provide an example of applying such a plain CSS you talked about ?
We are testing vaadin 4 and we can't find how to style header-cell for now...

**Comment by tomivirkki** [comment]
Hi @cqst 
The ground level approach in styling Vaadin elements is to define a style module with an additional “theme-for” attribute. The styles in the module are then injected into the template of the corresponding element. For example:

```
<dom-module id="my-app-grid-styles" theme-for="vaadin-grid">
  <template>
    <style include="vaadin-grid-default-theme">
      [part~="header-cell"] {
        background: blue;
      }
    </style>
  </template>
</dom-module>
```

The parts and state attributes (of `<vaadin-grid>`) you can target in the modules are currently documented here: https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid.html#L137

Vaadin also ships complete customizable theme packages (currently wip: Valo, Material) that you can just drop on a page with Vaadin elements. The themes can be customized on a higher level with CSS properties. Documentation on this at: https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha3/demo/

`<vaadin-grid>` with Valo theme: https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha3/demo/grids.html

Generic styling documentation: https://cdn.vaadin.com/vaadin-valo-theme/0.3.1/demo/customization.html

**Comment by web-padawan** [comment]
We no longer support `vaadin-grid` version 3, and now it is very outdated. As mentioned above, it's recommended to use the most recent version (currently 5.x) which gets all the fixes.

There hasn't been any activity in this issue for a while. Closing as stale.
