### ISSUE TITLE
[4.0-alpha5] Filters with vaadin-text-field

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-grid#1047]
Now that the input for `vaadin-grid-filter` is a `vaadin-text-field`, 

1. It would be nice to have a `placeholder` attribute on `vaadin-grid-filter`. That's one of the few reasons to have a standard `input` inside the element.

2. Using a theme for `vaadin-text-field` will affect the filter field too. This can have some unfortunate styling. A way to easily mitigate this would be nice.
<img width="474" alt="screenshot 2017-10-18 at 10 31 15 am" src="https://user-images.githubusercontent.com/1920405/31727638-b07edb04-b3ef-11e7-92e5-a4c14647b01e.png">

**Comment by tomivirkki** [comment]
A workaround for both of the issues is to override the default input with a custom one as done in https://cdn.vaadin.com/vaadin-grid/4.0.0-alpha5/demo/#grid-sorting-filtering-demos

**Comment by moderndeveloperllc** [comment]
@tomivirkki Yep, you can see that I did that for Last Name. Just wanted to point out a couple of things that might not have come up in testing, etc. I figure the fewer the workarounds, the higher the uptake. Thanks.
