### ISSUE TITLE
[v3.0.2 stable] Rendering lot of columns is slow (polymer 2.0)

### ISSUE THREAD

**Issue by yveslange** [vaadin/vaadin-grid#1048]
Hi,

I'm trying to render a table with 94 columns and 20 rows but <vaadin-grid> doesn't seem to support that much columns. It becomes very very slow. With 34 columns, <vaadin-grid> is usable but a bit slow. 

- I'm creating the columns using a `<template is="dom-repeat" ...>`
- Resizable is enabled
- Sort is enabled
- Filter is enabled

```html
<vaadin-grid aria-label="loim-grid" id="grid" items="[[_data]]" multi-sort="true">
  <template is="dom-repeat" items="[[_columns]]" as="column">
    <vaadin-grid-column flex-grow=1 width="[[column.width]]" resizable>
      <template class="header">
          <vaadin-grid-sorter path="[[column.name]]">
            <vaadin-grid-filter aria-label$="[[column.name]]" path="[[column.name]]" value="[[column.filter]]">
              <input slot="filter" placeholder="[[column.name]]" value="{{column.filter::input}}" focus-target>
            </vaadin-grid-filter>
          </vaadin-grid-sorter>
      </template>
      <template>
        <input id="first-[[index]]" value="[[get(column.key, item)]]" on-input="_storeFirst">
      </template>
    </vaadin-grid-column>
  </template>
</vaadin-grid>
```

In the console, when setting to `verbose` I see a lot of warnings:

![debounce](https://user-images.githubusercontent.com/17984393/31728362-658aca9e-b42c-11e7-9133-4b47dd5458d9.PNG)

Sidenote: I have tried to render the table using basic `<table><thead><tbody>...` tags and I takes 1sec to render it and scrolling is pretty fast compare to <vaadin-grid>. Just saying that it's not the computer or something else.

Is this normal ? Is there I way to speed it up ?

**Comment by tomivirkki** [comment]
Hi @yveslange. There was a similar discussion about this at https://github.com/vaadin/vaadin-grid/issues/997

`<vaadin-grid>` 4 is currently at version 4.0.0-alpha5, so you might want to give it a shot. But still, 90 columns is a lot so utilizing the column hiding feature to not have all columns visible at once (if this is an option for you) should help a lot.

**Comment by yveslange** [comment]
Sadly, I have already tested version `4.0.0-alpha5` this morning. It works but it is not faster :(
