### ISSUE TITLE
Can't get dynamic columns working

### ISSUE THREAD

**Issue by nvining-work** [vaadin/vaadin-grid#1050]
I'm a bit lost. I'm not sure if this is a bug or a feature, but I'm hoping somebody can shed some light on this. I have dynamic columns passed from a web server that consist of a header name, and a series of values. They're not organized as rows, they're organized as columns, and I would like to print them. What I would expect to work:

```
<vaadin-grid>
           <template is="dom-repeat" items="{{item.TableColumns}}" as="column">
                                    <vaadin-grid-column width="150px">
                                        <template class="header">[[column.Header]]</template>
                                        <template is="dom-repeat" items="{{column.Elements}}" as="element">{{element.Value}}</template>
                                        <template class="footer">Here, randomly, is a test footer.</template>
                                    </vaadin-grid-column>
</template>
</vaadin-grid>
```

Here element.Value is one member of a thing in the column (other stuff includes tooltips, etc.) This doesn't work: it produces column headers, but no elements are displayed. If I look in the inspector, no <vaadin-grid-cell-content> seems to be generated in the DOM. I would also expect this to work:

```
<vaadin-grid>
           <template is="dom-repeat" items="{{item.TableColumns}}" as="column">
                                    <vaadin-grid-column width="150px">
<template><p>Here is a column.</p><template>
                                    </vaadin-grid-column>
</template>
</vaadin-grid>
```

This doesn't seem to work either. I'm sure I'm being an idiot, but it's very unclear what I'm missing and if I have hit a bug or a feature.

**Comment by yveslange** [comment]
Did you try using the `[[column]]` in your template ? I'm using a dom-repeat for dynamic columns and it works

**Comment by nvining-work** [comment]
Can you give me an example in context? I'm not sure I understand the response - sorry, HTML and all things web are not my forte. :)

**Comment by yveslange** [comment]
1. It seems that you didn't close correctly your template tag 

`..n.</p><template>` should be `..n.</p></template>` 

2. Make sure that you are hitting the correct variable:

`items="{{item.TableColumns}}"` where the variable `item.TableColumns` is something like that:

```javascript
item.TableColumns = [ "Column1", "Column2"}....]
```

Finally, this is working for me:

```javascript
<vaadin-grid>
  <template is="dom-repeat" items="{{tableColumns}}" as="column">
    <vaadin-grid-column width="150px">
      <template>[[column]]</template>
    </vaadin-grid-column>
  </template>
</vaadin-grid>

....

static get properties(){ 
  return {
    
    ...

    tableColumns: {
      type: Array,
      value: () => {
        return ["Column1", "Column2"]
      }
    }
}
```

**Comment by web-padawan** [comment]
@nvining-work if you are still experiencing difficulties, please take a look at this [jsfiddle](https://jsfiddle.net/webpadawan/zjLey3z6/). As you can see, passing dynamic columns into `dom-repeat` works, but you still have to provide `items` as an array, or use a `dataProvider` instead.

So I suggest you refactoring either the code which generates JSON, or client-side code, which processes response from the server. I assume this is not something impossible to handle. 

Passing `column.elements`, as you expect in the first example, looks a pretty uncommon use case and is not supported at the moment. Therefore I am closing this issue.

Feel free to comment if you need more help, at least an example JSON would be nice so we could explain how to convert its structure. You can also ping us in Polymer Slack, see [#vaadin](https://polymer.slack.com/messages/C6ULJ2F7S/) channel.
