### ISSUE TITLE
Sorting support in a paginated vaadin-grid 

### ISSUE THREAD

**Issue by anikavaish** [vaadin/vaadin-grid#1051]
If pagination is implemented in a vaadin-grid then sorting feature sorts only the current page not the entire grid data.
Please help.

**Comment by madiganz** [comment]
Are you sorting the data after you fetch it? This will result in sorting just the current page. Need to use the sorting params of vaadin grid in your data query. Something like:
/mydata?page=1&pageSize=50&sort=' + params.sortOrders[0].path + ' ' + params.sortOrders[0].direction

**Comment by sudipta1411** [comment]
I have the same issue. I am fetching all data at once. But it only sorts the current page.

**Comment by tomivirkki** [comment]
Grid only has access to the data you provide. If you implement the paging functionality with `items` array, grid obviously can't populate a certain page with results sorted from your whole data set. So if you wan't to combine `items` with pagination and sorting, you'll need to sort the data yourself and provide grid the items for current page.
More natural/straightforward approach for this combination would be to use a `dataProvider`.

**Comment by anikavaish** [comment]
Please share an example for the same.
Thanks.

**Comment by nexuslifeline** [comment]
I also encountered this issue. What I did here is I handle the sorting on sorter-changed event. Everytime this event is fired, Im sorting the entire list based on the path and direction before implementing my pagination logic. By the way, I'm using v3 where sorter-changed event doesnt have details for path and direction. That's why on my forked version I've added this to event details.

**Comment by sudipta1411** [comment]
@nexuslifeline  thanks. Can you please share some example code.

**Comment by nexuslifeline** [comment]
Hi, sorry for my late response. 
![1](https://user-images.githubusercontent.com/16952835/32483175-c45ed4e4-c3d5-11e7-9d83-b13e1e0f4fdb.PNG)
![2](https://user-images.githubusercontent.com/16952835/32483176-c49ae18c-c3d5-11e7-9751-9d0c7c736a80.PNG)

**Comment by anikavaish** [comment]
Thanks for sharing this example.
It helped.

**Comment by nexuslifeline** [comment]
Welcome.

**Comment by jouni** [comment]
Sorting and filter should be considered if/when we implement pagination support (#452)

**Comment by web-padawan** [comment]
Closing in favor of #452 per above comment.
