### ISSUE TITLE
Document & demo for notifyResize()

### ISSUE THREAD

**Issue by iosifa** [vaadin/vaadin-grid#1060]
Currently, if we implement some basic CRUD operations (like inline editing) by using our custom web component (not native html such as  input, select, etc) the grid-row doesn't resize correctly. Only after we click on the largest custom web component  the grid row resize correctly.

**Comment by tomivirkki** [comment]
Does it help if you invoke `grid.notifyResize()` when the content changes dynamically? Can you provide a live example of the issue?

**Comment by iosifa** [comment]
Yes `grid.notifyResize()`  worked perfectly. Thanks

**Comment by yveslange** [comment]
Hi @tomivirkki, I had the same problem and this fixed it. Can I ask you a favor ? Where is this documented ? :)

**Comment by tomivirkki** [comment]
Hi, it's `iron-resizable-behavior` feature documented [here](https://github.com/PolymerElements/iron-resizable-behavior/blob/master/iron-resizable-behavior.html#L81). But yes, we should indeed document it and have a demo of it for `<vaadin-grid>` also.

**Comment by yveslange** [comment]
Yes that would be very good to have all the API callable functions that are accessible through `grid.`
