### ISSUE TITLE
Column resizing should be disabled whed d&d column 

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1076]
![recorded](https://user-images.githubusercontent.com/6059356/32325758-ef3dbb9a-bfd8-11e7-9e78-91db41ea11c9.gif)

Expected: when in d&d mode, resizing indicators should now work, the cursor should not be changed, dragging should not be interrupted.

Chrome/Linux

**Comment by jouni** [comment]
The same applies vice-versa, btw: if you resize the last frozen column, that will trigger column reordering. Reproducible here: https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha4/demo/grids.html#column-grouping-column-resizing-frozen-columns-and-footers

**Comment by web-padawan** [comment]
@jouni I can confirm this, thanks. Will investigate more deeply.

**Comment by web-padawan** [comment]
Actually, I think this second bug is better to fix in a separate PR. Will submit another issue for that.
