### ISSUE TITLE
Unable to slot column content

### ISSUE THREAD

**Issue by stramel** [vaadin/vaadin-grid#1085]
Tested in 3.0 and master

https://jsbin.com/yukafuv/edit?html,output

@tomivirkki

**Comment by yveslange** [comment]
I am having the same issue. I want to "inject" a component or template into the cells (or the slot column content)

MY APPLICATION <my-app>
```
<dom-module id="my-app">
  <template>
    <style>...</style>

    <my-grid>
      <template>
        A dynamic template
      </template>
    </my-grid>

  </template>
  ...
</dom-module>
```
  

MY ELEMENT <my-element>

```
<dom-module id="my-gird">
  <template>
    <style>...</style>

    <template is="dom-repeat" ...>
      <vaadin-grid>
        <vaadin-grid-column>
          <template class="header">some header...</template>
          <slot></slot>  <---------- I want a slot here !!! :)
        </vaadin-grid-column>
      </vaadin-grid>
    </template>
  </template>
```

**Comment by yveslange** [comment]
I also tried to stamp the template inside the `dom-repeat`. As you might already know, it's not possible :(

**Comment by yveslange** [comment]
vaadin-grid-column.html

It seems that this is because of the current implementation

```javascript
L187    _prepareBodyTemplate() {
L188      return this._prepareTemplatizer(this._findTemplate('template:not(.header):not(.footer)' || null, {}));
L189    }
```

**Comment by tomivirkki** [comment]
Prototyped this in a separate [branch](https://github.com/vaadin/vaadin-grid/tree/slotted-templates). Does this work for your case?

**Comment by yveslange** [comment]
Yes, with your branch I was able to insert a `template` in a slot. I noticed that trying something else than a template will not work since `vaadin-grid` takes implicitly a template to render the cell content. Few months back, it was difficult (for me) to understand this point without reading the src code of the `vaadin-grid-column`. The `vaadin-grid-column` takes the first non `header` or `footer` template as the cell content.

*Works:*
```
    <my-grid>
      <template slot="cell">
        [[item.firstName]]
      </template>
    </my-grid>
```

*Won't work:*
```
    <my-grid>
      <div slot="cell">
        Constant string
      </div>
    </my-grid>
```

But this is fine, it is possible to pass a template that contains a `<div>`.

Cheers

**Comment by stramel** [comment]
@tomivirkki It does appear to work properly

https://jsbin.com/lojefifida/edit?html,output

**Comment by stramel** [comment]
Will wait to close until the changes are fixed in master.

**Comment by yveslange** [comment]
Any updates ?

**Comment by tomivirkki** [comment]
Sorry, no updates on this front yet. We're focusing 100% on the "Valo as default theme" migration and new releases currently. We'll fix this but a PR would really speed this up ;)

**Comment by stramel** [comment]
@tomivirkki Do you have an update?

**Comment by tomivirkki** [comment]
Sorry for the delay, the fix is now in review: https://github.com/vaadin/vaadin-grid/pull/1251
