### ISSUE TITLE
Style individual columns

### ISSUE THREAD

**Issue by jay8t6** [vaadin/vaadin-grid#1087]
Is it possible to style individual columns differently? Say I want a different bg for each column?

**Comment by tomivirkki** [comment]
Hi @jay8t6 
You can define a wrapper element in your column template with a specific class name:
```
<vaadin-grid-column>
  <template class="header">Address</template>
  <template>
    <div class="address-column">
      [[item.address.street]], [[item.address.city]]
    </div>
  </template>
</vaadin-grid-column>
```

And then target `.address-column { background: blue; }` with CSS

**Comment by jay8t6** [comment]
@tomivirkki  Great, thanks. I'll give that a try.

**Comment by web-padawan** [comment]
Here is a [jsbin](http://jsbin.com/legayuf/edit?html,output) demonstrating the above comment. As you can see, there is a padding which you might need to tweak as well. Please see the docs about extending default theme the `vaadin-themable-mixin` [wiki](https://github.com/vaadin/vaadin-themable-mixin/wiki/Extending-the-Default-Theme-Module).

So basically the answer is: yes, it is possible. Therefore I am closing this issue.

**Comment by anikavaish** [comment]
How to dynamically style a cell in a column based on a value?
