### ISSUE TITLE
Buggy inconsistent behavior for row details in Firefox

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1089]
Sometimes when I click 'Show Details' row jumps and covers a preceding row:

![recorded](https://user-images.githubusercontent.com/6059356/32483973-e1b5ce0a-c3a6-11e7-9309-731f200e2269.gif)

Firefox/Linux

**Comment by tomivirkki** [comment]
This happens probably because there's an image in the template. During details row height measure, the images might not have been loaded yet so the rows end up overlapping. You can fix the issue by invoking `grid.notifyResize()` once the image has been loaded.

**Comment by tomivirkki** [comment]
This was actually a style scoping issue in our demos. Added a fix.
