### ISSUE TITLE
Issues with dynamic vaadin-grid-selection-column

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1096]
Live demo: https://jsfiddle.net/6r5htd05/72/

When `vaadin-grid-selection-column` restamped dynamically, I'm getting following exception:

```
Uncaught TypeError: Cannot read property 'items' of undefined
    at HTMLElement._onSelectedItemsChanged (vaadin-grid-selection-column.html:223)
```

After restamping `this._grid` is undefined.

![recorded](https://user-images.githubusercontent.com/6059356/32662056-e23fbc72-c631-11e7-8e59-73c64709e847.gif)

**Comment by web-padawan** [comment]
Released in https://github.com/vaadin/vaadin-grid/releases/tag/v5.2.2
