### ISSUE TITLE
Issues with dynamic filterable column

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1097]
Live demo: https://jsfiddle.net/6r5htd05/71/

Steps to reproduce:
- check the 'Show first name' checkbox
- type 'Ellie'
- uncheck the 'Show first name' checkbox
- check the 'Show first name' checkbox
- remove 'Ellie'

Expected result: all data is shown

Actual result: only Ellie is shown, filters aren't updated dynamically

![recorded](https://user-images.githubusercontent.com/6059356/32662821-7786445c-c634-11e7-9430-0a293142c12a.gif)

**Comment by limonte** [comment]
Use `hidden` instead of restamping: https://jsfiddle.net/6r5htd05/73/

**Comment by tomivirkki** [comment]
:+1: You can still consider `dom-if` as long as you clear the filter value from a column that's removed
