### ISSUE TITLE
It should be possible to style the checkboxes inside `vaadin-grid-selection-column`

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1113]
Valo uses different font size for the header cells than for the body cells and the sizing of vaadin-checkbox is based on the font-size. This makes the select-all checkbox smaller in the header, which is unwanted.

**Comment by jouni** [comment]
Would it be enough for the selection column to extend `ThemableMixin`?

**Comment by tomivirkki** [comment]
I don't think that would be enough as the checkboxes aren't rendered inside the shadow of `<vaadin-grid-selection-column>`. We could decorate the checkboxes in the column's [default template](https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-selection-column.html#L14) with some identifying class names. "selection-column-header-checkbox" and "selection-column-body-checkbox"?

**Comment by jouni** [comment]
You could use `::slotted`, right?

Having a decorator class would also work, but that forces the theme to put the needed styles into the `vaadin-checkbox` theme module, instead of in one of the grid’s theme modules. Right?

**Comment by tomivirkki** [comment]
They're not slotted into `<vaadin-grid-selection-column>` either. The checkboxes end up in grid's light dom the same way as any user defined content...Do we need `<vaadin-grid-checkbox>` extension?

**Comment by jouni** [comment]
Ah, of course.

Would be handy if there was a way to define a class for the wrapping cell element. What if we copied the `classList` from the templates to the cell content elements? The current `.header` and `.footer` classes could be a bit too generic, though, and we would probably have to use something else than `class` for those.

**Comment by tomivirkki** [comment]
Sure, classes sound fine to me. Another option would be to use different tag names: `<vaadin-grid-cell-content>`, `<vaadin-grid-header-cell-content>` and `<vaadin-grid-footer-cell-content>` for example?

**Comment by jouni** [comment]
Actually, if we would propagate `class`, it should probably be from the `<vaadin-grid-column>` element, not from the templates inside it.

Your suggestion about different tag names sounds interesting as well. But that’s a breaking change, isn’t it?

**Comment by tomivirkki** [comment]
No one _should_ be targeting the `<vaadin-grid-cell-content>` elements directly as they are generated element (by the grid) that happen to be in the same style scope for reasons. But maybe it's safer still not to change the tags.

Copying the class list of the column to `<vaadin-grid-cell-content>` almost sounds like a new feature and for the above reasons wouldn't add it right now. Would static class names be enough for Valo at this point?

**Comment by jouni** [comment]
> Copying the class list of the column to <vaadin-grid-cell-content> almost sounds like a new feature and for the above reasons wouldn't add it right now. 

Yes, agreed.

> Would static class names be enough for Valo at this point?

Static class names on the checkboxes you mean? That would be enough at this point (a class on the header checkbox is even enough). I’m just wondering if that is going to be a long-term solution that we want to keep?

This is not a blocking issue for Valo, just a minor inconvenience that the select all checkbox is smaller.

**Comment by tomivirkki** [comment]
Adding class names to the checkboxes might not help as you wouldn't be able to target those from a grid style module (them not being direct children of grid).

> Static class names on the checkboxes you mean?

Meant for the cell content wrappers. Here's a working proto: https://github.com/vaadin/vaadin-grid/tree/cell-content-classes Would this do the trick?

**Comment by jouni** [comment]
How would we target the checkboxes in that prototype?

**Comment by tomivirkki** [comment]
Right, we still can't apply styles to the checkbox from themes for the grid. I guess the only working approach would be to add a style name to the checkbox and adding a new style module for it after all.
So let's add "vaadin-grid-select-all-checkbox" class name to the selection column header checkbox?
