### ISSUE TITLE
How to dynamically style a cell in a column based on a value?

### ISSUE THREAD

**Issue by anikavaish** [vaadin/vaadin-grid#1119]
Suppose i want to change the background of a cell in a column to red color if value is less than 90 otherwise the background color should be green.
Columns are dynamically getting populated.
Please help.

**Comment by anikavaish** [comment]
Suppose i want to change the background of a cell in a column to red color if value is less than 90 otherwise the background color should be green.
Columns are dynamically getting populated.
Please help.

**Comment by web-padawan** [comment]
This can be achieved this using computed function, see this [jsbin](https://jsbin.com/waqedo/edit?html,output). You could also bind to `style$=""` attribute instead of `class$=""`, e. g. if you need to apply some gradients generated depending on value.

**Comment by jouni** [comment]
Closing as a question (not an issue).
