### ISSUE TITLE
If I have 10000 records and use pagination, it shows up 1000 page numbers below the grid.

### ISSUE THREAD

**Issue by swapnilbhattad** [vaadin/vaadin-grid#1123]
Is there a way I can handle pagination properly and  select page number to jump to or atleast display a few page numbers and then click on next or some workaround to get UI look good.
If this feature is not present, any external plugin that I can use along would also be helpful.

**Comment by jouni** [comment]
Pagination is not a built-in feature yet. We only have the pagination example, which you can use as a base for more customization.

Here’s one pagination component I found with a quick search on webcomponents.org, which you should be able to use for navigating the grid: https://www.webcomponents.org/element/Prhythm/prism-pagination/

**Comment by jouni** [comment]
Closing. Pagination feature is tracked in #452
