### ISSUE TITLE
Passing 'null' as filter breaks grid.

### ISSUE THREAD

**Issue by bennypowers** [vaadin/vaadin-grid#1128]
### Description
If `null` is passed as a filter value, vaadin-grid throws a `TypeError: Cannot read property 'toString' of null.`

One use case where this bug may surface is when programmatically setting the filter, e.g. from a Redux store reducer. If the developer neglects to check for `null` in the reducer, this runtime error will surface.

### Expected outcome
No error should be thrown, instead, the filter should be set to the empty string.

### Actual outcome
`TypeError: Cannot read property 'toString' of null.`

### Live Demo
https://jsbin.com/hawafen/edit?html,console,output

You'll likely have to break on vaadin-grid-array-data-provider-behavior.html:127 to see the error.

### Steps to reproduce

1. Put a `vaadin-grid` element in the page.
2. Add `vaadin-grid-filter` element to the column header template.
3. Set filters value to null.
4. Receive error.

## Proposed Solution

Check for `filter == null` in `_filter` method in vaadin-grid-array-data-provider-behavior.html and substitute with a properly-boxed empty string as needed. Happy to provide PR upon request.

### Browsers Affected

- [x] Chrome
- [x] Firefox

**Comment by limonte** [comment]
Hello @bennypowers and thank you for such a detailed issue-report!

> Happy to provide PR upon request.

Go ahead :rocket: It would be perfect if you can include the test with the issue verification.

**Comment by limonte** [comment]
> Ok. Should I fork against master?

Yes.
