### ISSUE TITLE
Shadow DOM parts available for styling in V4.0.0

### ISSUE THREAD

**Issue by HendrikThePendric** [vaadin/vaadin-grid#1132]
### Description
After upgrading from V3 to V4 the styles defined for shadow DOM parts are not applied.

### Expected outcome
When styling a shadow DOM part via previously working syntax, the styling is applied.

### Actual outcome
None of the styles are applied. After reading the API docs for 4.0 I suspected it could have something to do with renaming, but that turned out not to be the case.

### Live Demo
https://jsbin.com/paqofog/1/edit?html,output

### Steps to reproduce
See jsbin example. I have specified styles for shadow dom parts in two ways, but they are not applied at all.

### Browsers Affected

- [ X ] Chrome
- [ X ] Firefox
- [ X ] Safari
- [ X ] Edge
- [ X ] IE 11
- [ ? ] iOS Safari
- [ ? ] Android Chrome

**Comment by jouni** [comment]
We are no longer using CSS mixins for styling the internals of our elements. This applies to all of our pure Polymer 2, ES6 class-based elements. At the moment, it looks like CSS mixins are not going to become a CSS standard, and they have limitations which we can’t live with, so we don’t want to use them anymore.

Instead, we are aiming to be future-compatible with the proposed `::part/::theme` CSS spec, and have a proprietary ”theme module” solution for the time being (`ThemableMixin`), which is more flexible than CSS mixins.

Read the documentation for `ThemableMixin` to learn how to apply styles for the shadow dom parts: https://github.com/vaadin/vaadin-themable-mixin/wiki
