### ISSUE TITLE
Weird display when using dom-repeat for row details (v4.0.0)

### ISSUE THREAD

**Issue by PBM42** [vaadin/vaadin-grid#1141]
### Description
Using row details with dom-repeat on v4.0.0 (v4.0.0-alpha 2 not affected)

### Expected outcome
Normal display

### Actual outcome
Details are expanded over the rows, hiding them. When multiples details are expanded, it displays properly.  Expand a previously expanded row will behave as expected.

### Live Demo
https://jsfiddle.net/jx80nm35/6/

### Steps to reproduce
1. click on `Show Details`

### Browsers Affected
- [X] Chrome
- [X] Firefox

**Comment by tomivirkki** [comment]
Hi @PBM42,
Polymer's `<dom-repeat>` [renders changes to its data asynchronously](https://www.polymer-project.org/2.0/docs/devguide/templates#synchronous-renders). When you open the details row, grid measures the height of the content (synchronously) to positions the rows correctly. But in this case, the dom-repeat hasn't actually yet rendered at the time of measuring so the result looks broken.

You can fix the issue in you app by:
1. Invoking `grid.notifyResize()` asynchronously to request grid to remeasure
2. Wrap your details row content inside a fixed-sized container

We should add synchronous invocation to `Polymer.flush()` when the details row is opened. That would resolve the issue in this case, but generally, grid can't catch dynamic changes to content height.
