### ISSUE TITLE
[Grid-sorter] data-binded direction doesn't provide sortOrders with dataProvider

### ISSUE THREAD

**Issue by PBM42** [vaadin/vaadin-grid#1149]
### Description
When binding `direction` of `vaadin-grid-sorter`, it doesn't appear in `params.sortOrders`.

### Expected outcome
 `params.sortOrders` should not be empty. It works well without dataProvider (using items) or when dataProvider call vaadin's callback synchronously

### Actual outcome
Table is not sorted

### Live Demo
https://jsfiddle.net/o5whbmbh/7/

### Browsers Affected

- [X] Chrome
- [X] Firefox

**Comment by tomivirkki** [comment]
Wondering if this got fixed at some point. At least the grid in the linked jsfiddle is initially sorted as expected. Please re-open if this is still an issue.
