### ISSUE TITLE
Can not select item after refresh

### ISSUE THREAD

**Issue by amahdy** [vaadin/vaadin-grid#1150]
### Description
After `clearCache`, `selectItem` does not work.

### Expected outcome
Item to be selected in grid.

### Actual outcome
Nothing is selected

### Steps to reproduce
1. Keep a reference of currently selected item from the grid.
2. Call `clearCache`.
3. Call `selectItem` with the reference you have.

**Comment by tomivirkki** [comment]
Once you clear the cache, grid asks the `dataProvider` for new data. An item you've saved before clearing is no longer the same instance you have after clearing. By default, grid uses reference to compare items.

You can change this by specifying [`itemIdPath`](https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-data-provider-mixin.html#L137) (introduced in grid 4.1). It can be used to specifying an item sub-property that should be used for comparison instead.

**Comment by amahdy** [comment]
Is there any different way to refresh grid? I'm still on 3.x and not sure I can upgrade at the moment.

**Comment by tomivirkki** [comment]
Well I guess you can mimic `itemIdPath` behaviour in your `dataProvider`. So once it's requested for new items, catch the new item that equals to your stored selected item and set the new item as the selected item in grid.

**Comment by amahdy** [comment]
Awesome, this tricked worked and I loved the fact that after `clearCache`, the scroll position is maintained. Because in my case the data is lazily loaded.

Thank you!
