### ISSUE TITLE
Selection using Active Item is NOT coloring selected row

### ISSUE THREAD

**Issue by GoceRibeski** [vaadin/vaadin-grid#1163]
### Description

[Selection using Active Item
](https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/selection.html#selection-using-active-item) is NOT coloring selected row when used inside Polymer(2.0) Starter Kit

### Expected outcome

Selected row should be colored  darker than the other rows

### Actual outcome

Selected row has same color as orher rows.

### Steps to reproduce

1. Put a `vaadin-grid` example in the Polymer Starter Kit default view.

**Comment by tomivirkki** [comment]
Works for me, even inside the Polymer Started Kit app. Are you sure you're changing the selection value when active item gets changed (like in the demo that you linked)? By default, active item row doesn't have any visual difference from other rows.

**Comment by GoceRibeski** [comment]
Thanks, you are right, it's working fine.

My mistake was calling `_activeItemChanged` from` on-change` event instead from `property observer`(although I don'n know what is the difference between them)

```
      <vaadin-grid 
                         on-active-item-changed="_activeItemChanged"
                   ...
```
instead of 
       ```
 activeItem: {
                             observer: '_activeItemChanged'
                           }
```

**Comment by tomivirkki** [comment]
Polymer uses "{propertyName}-changed" events to notify host elements of property changes to enable two-way binding. The property observer should work also as long as you two-way bind the grid's `activeItem` property to your host context (as done in the "Selection using Active Item" -demo: `active-item="{{activeItem}}"`).
