### ISSUE TITLE
Schrödinger's data - it shouldn't be there, but it's there

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1166]
### Description
If I go to the offline mode and then scroll down I expect only 50 rendered rows and 150 empty rows. 

![](https://i.imgur.com/kCGS7sH.png)

### Expected outcome
The first page (50 rows) was loaded and rendered, other 150 rows are empty, just indexes as grid should know indexes.

### Actual outcome
200 rows are rendered, the first page (50 rows) was loaded, but I have no clue what's inside other 150 rows. There shouldn't be any data, the data wasn't loaded.

### Live Demo
https://cdn.vaadin.com/vaadin-grid/5.0.0-alpha3/demo/#grid-data-demos

### Steps to reproduce
1. Go to the 'Assigning Remote/Function Data' demo example
2. Go to the offline mode
3. Scroll down the 'Assigning Remote/Function Data' grid

**Comment by jouni** [comment]
I think this is because Valo doesn’t apply the correct styles for rows/cells which are still loading.

**Comment by jouni** [comment]
Actually, I think that CSS should be part of the core styles.

**Comment by tomivirkki** [comment]
The [CSS was part](https://github.com/vaadin/vaadin-grid/blob/06afe6cc18a029b9b7830aaa4d45d391e0adac7a/vaadin-grid-styles.html#L346) of the default theme in version 4. As default themes were dropped, the rule should be restored to version 5 core styles.
