### ISSUE TITLE
Uncaught TypeError: Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by stijnkoopal** [vaadin/vaadin-grid#1167]
### Description
When we are using vaadin-grid 4.1.0 with [polymer-webpack-loader](https://github.com/webpack-contrib/polymer-webpack-loader), we are getting the following stacktrace:

```
vaadin-grid-selection-mixin.html?6b4c:80 Uncaught TypeError: Cannot read property 'items' of undefined
    at HTMLElement._selectedItemsChanged (vaadin-grid-selection-mixin.html?6b4c:80)
    at Object.runMethodEffect [as fn] (property-effects.html?af9b:813)
    at runEffectsForProperty (property-effects.html?af9b:159)
    at runEffects (property-effects.html?af9b:125)
    at HTMLElement._propertiesChanged (property-effects.html?af9b:1703)
    at HTMLElement._flushProperties (properties-changed.html?0a1e:324)
    at HTMLElement._flushProperties (property-effects.html?af9b:1551)
    at HTMLElement.ready (property-effects.html?af9b:1656)
    at HTMLElement.ready (element-mixin.html?5cf0:549)
    at HTMLElement.ready (dir-mixin.html?6ee1:140)
```

With vaadin-grid 3.x this was not the case.

### Expected outcome
No errors

### Actual outcome
A stacktrace

### Live Demo
https://github.com/stijnkoopal/vaadin-grid-bug

### Steps to reproduce
1. Clone https://github.com/stijnkoopal/vaadin-grid-bug
2. Run `yarn`, `bower install` and `yarn start`
3. Open Chrome (64.x): http://localhost:9011
4. Open developer tools

### Root cause
The `vaadin-grid` element does not have a template attached. Therefore, it does not get [`this.$`](https://github.com/Polymer/polymer/blob/master/lib/mixins/element-mixin.html#L545) attached either.

The problem starts in `vaadin-themable-mixin.html`:`18`, `super.template` is null for `GridElement`.
The `super.template` call eventually invokes `static get template()` in `class.html`.
The `this` in this function is `function DataProviderMixin`, so `this.is` resolves to `"vaadin-grid-scroller"` (instead of `"vaadin-grid"`).
Hence, the `template` cannot be imported properly.

### Browsers Affected

- [x] Chrome

**Comment by tomivirkki** [comment]
Hi,
Thanks for the excellent demo app, really helps in debugging. Looks like the following simple Polymer element fails with `polymer-webpack-loader` as well. The problem with `<vaadin-grid>` is caused by the same root issue. Still investigating this.

```
<dom-module id="my-element">
  <template>
    Hi
  </template>
  <script>
    class MyElement extends Polymer.Element {
      static get template() {
        return super.template;
      }

      static get is() {
        return 'my-element';
      }
    }
    customElements.define(MyElement.is, MyElement);
  </script>
</dom-module>
```

**Comment by tomivirkki** [comment]
Ok, looks like Babel doesn't transpile static getters correctly with `loose` flag enabled. Set `loose` to `false` in `.babelrc` to fix this

**Comment by stijnkoopal** [comment]
Cool, much appreciated!
