### ISSUE TITLE
webcomponents.org demo is instable

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1168]
https://www.webcomponents.org/element/vaadin/vaadin-grid/v5.0.0-alpha3

Sometimes it works, sometimes not (chances are 50/50):
 
![peek 2018-01-02 16-05](https://user-images.githubusercontent.com/6059356/34486140-f0844d1a-efd6-11e7-9e30-5b628af5cb85.gif)

**Comment by tomivirkki** [comment]
Seems to be due to `<iron-ajax>` not working reliably. Forcing it to fetch data will populate grid.

**Comment by tomivirkki** [comment]
master no longer uses iron-ajax
