### ISSUE TITLE
Weird and hard to reproduce rendering bug

### ISSUE THREAD

**Issue by pdesjardins90** [vaadin/vaadin-grid#1171]
### Description
(Table is `height: auto`, data is set through the `items` property, and columns are dynamically created with dom-repeat)

Data rows are sometimes stacked over the header row and table height is not adjusted.

### Expected outcome
Data rows are listed below the header row and table height is adjusted normally.

### Actual outcome
![capture d ecran 2018-01-04 a 12 22 12](https://user-images.githubusercontent.com/6752776/34576150-1c0a9384-f14b-11e7-82bc-abd880382872.png)
![capture d ecran 2018-01-04 a 12 22 34](https://user-images.githubusercontent.com/6752776/34576151-1c2aa584-f14b-11e7-803d-e2a3e77538b1.png)

### Steps to reproduce
As stated, this is very hard to reproduce. Could you perhaps point me in the most probable bug direction so I can find a surefire way to reproduce it?

### Browsers Affected

- [ X] Chrome
- [? ] Firefox
- [ ?] Safari
- [ ?] Edge
- [ ?] IE 11
- [ ?] iOS Safari
- [ ?] Android Chrome

**Comment by pdesjardins90** [comment]
When rendering the table with few items, say 2, then changing the number of items to alot more, say 20, only 2 items of the 20 appear and the table gets really tall and a scroller appears.

I'm trying to reproduce the behavior in a small separate app, but still no success

**Comment by pdesjardins90** [comment]
This seems to be caused by the structure of my app, which contains multiple nested `<iron-pages>`. It looks like the async rendering of iron-pages clashes with the way vaadin-grid is rendered. I'll continue to investigate but I'll close this issue since the problem may be in iron-pages instead.

**Comment by tomivirkki** [comment]
Ok, thanks for reporting. Let us know if this is something we could fix in the grid core. A jsfiddle for reproducing this would be helpful also.

**Comment by pdesjardins90** [comment]
I think I've found the problem, but it doesn't concern this component at all it seems. I'll just leave my investigation result here, in case it helps someone:

iron-pages v2.0.1 still relies on the legacy IronResizableBehavior and IronSelectacleBehavior for backward compatibility. When I converted iron-pages and these behaviors to full Polymer 2 files (es6 class-based element and mixins), the problem stopped. 

I think it has to do with IronResizableBehavior specifically and the timing by which iron-pages is upgraded in the document when using legacy behaviors vs when using mixins. 

Since vaadin-grid (v.4.1.0) is a polymer 2 only element (class-based), my guess is there's a difference in the rendering of iron-pages and vaadin-grid, but it's becoming way too deep for me. 

I'll post a link to our v2 only fork and link the issue in iron-pages later.

**Comment by pdesjardins90** [comment]
That fixed it:
```javascript
/* 
* On the parent element, observe when the data passed to the grid has changed
* and call an iron-resize after the next render
*/
static get properties () {
  return {       
    data: Array         
  }
}

static get observers () {
  return [
    '_dataChanged(data.*)'
  ]
}

_dataChanged (changeRecord) { 
  Polymer.RenderStatus.afterNextRender(this, () => this.raise(‘iron-resize’))
}
```
