### ISSUE TITLE
Horizontal "invisible" scrollbar handle can't be grabbed on Chrome

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1174]
When "invisible scrollbars" (OSX feature) is used, the horizontal scrollbar handle, while visible, can't be grabbed with mouse. This occurs on Chrome at least.

**Comment by jouni** [comment]
Possible to grab the handle on Safari. It doesn’t expand before clicking it, though, like a normal scrollbar does.

**Comment by tomivirkki** [comment]
Looks like horizontal scrollbar can't be grabbed in other scrolling containers either (with Chrome). Closing this.

**Comment by jouni** [comment]
Well, at least I am able to grab the scroll bar in my Chrome: 
![chrome-grab-scrollbar](https://user-images.githubusercontent.com/66382/35208286-38e569da-ff50-11e7-8707-e0bb613418a2.gif)

**Comment by tomivirkki** [comment]
But that's the vertical scrollbar. At least I can't grab the horizontal one.

**Comment by web-padawan** [comment]
BTW, this makes me sad when looking at the current Grid demos header (scrolling tabs). So as a user I can scroll with the trackpad or magic mouse but probably not with the usual mouse.
