### ISSUE TITLE
row-details template can't be changed dynamically

### ISSUE THREAD

**Issue by elmot** [vaadin/vaadin-grid#1196]
### Description
This feature is required by vaadin-grid-flow. Programmatically  changed row details template must be supported.

### Live Demo
http://elmot.xyz/grid-element-bug/

### Steps to reproduce
1. Open the page
1. Click any row
1. Observe "No details" label
1. Click "add details" button
1. Click any other row

### Expected outcome
*Hi! My name is ???*

### Actual outcome
No Details

**Comment by platosha** [comment]
Editing template contents on-the-fly like shown in the Live Demo is not supported by Polymer. Every template is compiled once, and does not allow editing after compilation, to my knowledge.

What we could do is to support changing the template as a whole in the grid, e. g.:

```javascript
grid.removeChild(grid.querySelector('.row-details'));
const newTemplate = document.createElement('template');
newTemplate.classList.add('row-details');
newTemplate.innerHTML = "Hi! My name is [[item.firstName]]";
grid.appendChild(newTemplate);
```

**Comment by elmot** [comment]
Template handling fixed, still does not work.
