### ISSUE TITLE
Lumo theme confusing with grid in details

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-grid#1197]
Grids inside row details have issues with color/transparencies which lead to confusion guessing which are the selected rows, e.g.

<img width="718" alt="screen shot 2018-01-24 at 20 11 06" src="https://user-images.githubusercontent.com/851745/35352126-38b747fe-0143-11e8-9549-c38ce764ffb4.png">

All rows in the inner grid seem selected, as if the default background color is transparent and the details background is azure; plus, the "empty" part of the grid is white.

Note: I'm producing the grid with Flow.

**Comment by jouni** [comment]
Thanks for the special use case! I’m actually fixing and refactoring the grid theme right now, and I think I’ve already fixed this by not applying the selected row color on the details cell.

**Comment by jouni** [comment]
I’ll refer to this issue in the PR once I get it ready.

**Comment by jouni** [comment]
Forgot to update here: the theme refactor is already in master, and released in the latest alpha, so please try that out and see if you still have problems.

Not sure what version is currently bundled with Flow, though.

**Comment by jouni** [comment]
This should be fixed already a while ago.
