### ISSUE TITLE
Grid content scrolls without any reasons when focus moves from header to the content 

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1199]
Live demo: https://jsfiddle.net/6r5htd05/115/

### Steps
 - focus a header cell
 - press Tab

### Actual 

![](https://i.imgur.com/gvYX4XA.png)

### Expected 

![](https://i.imgur.com/Lv7oEnS.png)

**Comment by jouni** [comment]
Can’t reproduce in Safari.

**Comment by limonte** [comment]
Reproducible in Chrome both on Linux and Windows

**Comment by jouni** [comment]
Can’t reproduce on Chrome or Edge on Windows 10 (virtual machine).
