### ISSUE TITLE
grid should have a default width, otherwise it's not visible in a flex container

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#1202]
grid has a default height of 400px, but not default width, hence this code does not show any grid  unless you define a width for the grid.

```
    <div style="display: flex">
      <vaadin-grid items='[1,2,3,4,5,6,7,8,9,10,11,12,13,14]'>
        <vaadin-grid-column>
          <template>row [[item]]</template>
        </vaadin-grid-column>
      </vaadin-grid>
    </div>  
```

IMO, it should have `width: 100%` as default.
Additionally, it should be nice if it also has a `flex: auto`

**Comment by platosha** [comment]
Confirm, it collapses indeed.

I would prefer `flex: auto;` though:
- `width: auto;` is a CSS default, having to change that is odd
- `flex: auto;` is scoped to flex layouts only, where this problem manifests
- It’s nice in both row and column flexbox layouts around grid. Live demo with column flexbox: http://jsbin.com/fayezubodo/1/edit?html,css,output
