### ISSUE TITLE
In iOS grid with `flex: auto` does not set correctly scrolling height

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#1203]
in iOS, when having a vaadin-grid into a vertical container, items does not cover all available height because scroller has a 400px size instead of adapting to the host size which is correct.

### Code

```
    <div style="width: 100vw; height: 100vh; display: flex; flex-direction: column">
      <div>TOP</div>
      <vaadin-grid items='[1,2,3,4,5,6,7,8,9,10,11,12,13,14]' style="width: 100%; flex: auto">
        <vaadin-grid-column>
          <template>row [[item]]</template>
        </vaadin-grid-column>
      </vaadin-grid>
      <div>BOTTOM</div>
    </div>
```

### Screeshot

![grid](https://user-images.githubusercontent.com/161853/35448183-eced8798-02b9-11e8-98d4-6f36ad74cc34.gif)

### Browsers Affected
- [x] iOS Safari

**Comment by jouni** [comment]
This is a known limitation. The internal scroller requires an explicit height (and relies on the parent elements to provide that). `flex: auto;` is not an explicit height, unfortunately.

**Comment by jouni** [comment]
This applies to macOS Safari as well.

**Comment by jouni** [comment]
As a workaround, use a wrapper div and absolute positioning for the grid:

```html
  <div style="width: 100vw; height: 100vh; display: flex; flex-direction: column">
    <div>TOP</div>
    <div style="position: relative; flex: auto;">
      <vaadin-grid items='[1,2,3,4,5,6,7,8,9,10,11,12,13,14]' style="position: absolute; top: 0; right: 0; bottom: 0; left: 0;">
        <vaadin-grid-column>
          <template>row [[item]]</template>
        </vaadin-grid-column>
      </vaadin-grid>
    </div>
    <div>BOTTOM</div>
  </div>
```

**Comment by manolo** [comment]
So, probably it should work if `grid` has a children wrapping the actual `scroller` and we could workaround  in the component, I mean something like 

```
<vaadin-grid style="position: relative; flex: auto;">
  #shadow 
    <div id="scroll-wrapper" style="position: absolute; top: 0; right: 0; bottom: 0; left: 0;">
       <div id="scroller">
       </div>
    </div>
</vaadin-grid>
```
@jouni  WDYT?

**Comment by jouni** [comment]
Possibly. I can try to prototype that, I’m currently working on theme updates anyway.

**Comment by manolo** [comment]
But wait ... , seems that I cannot reproduce anymore with that setup. Need to spend more time to figure out how to reproduce

**Comment by jouni** [comment]
Seems that this issue has been fixed in some Safari update. I can reproduce it still in iOS 9.3.

**Comment by jouni** [comment]
But yeah, if this needs to be fixed, it seems like it’s just a matter of changing the [core styles](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-styles.html#L27-L33) to:

```css
#scroller {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  transform: translateY(0);
}
```

@tomivirkki, WDYT? Do you see some possible risks with that?

**Comment by tomivirkki** [comment]
I'm pretty sure the feature presented in "Dynamic Height" demo wouldn't work properly with this change though.

**Comment by manolo** [comment]
Apparently it works if `position: relative` 
http://g.recordit.co/y0UtE79fg9.gif

**Comment by manolo** [comment]
But `relative`, seems not to work in iOS  😞

**Comment by manolo** [comment]
> "Dynamic Height" demo wouldn't work properly with this change though.

Thinking a little more about this, isn't this a corner case? I cannot see a real app where the user needs a component like the grid if he wants height based on the internal number of rows. But otherwise, I can see most cases where the grid adapts to it's external container. IIRC fw grid does not have that feature.

But anyways, it could be a feature to enable via some config property or theme, or better if the scroller was a themable part.

**Comment by heruan** [comment]
What is the status of this? I agree with @manolo about the common need for the grid to adapt to its container, e.g. `vaadin-vertical-layout`.
