### ISSUE TITLE
Allow developer to style the active item (regression from v3)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1205]
In v3, it was possible to style the active item/row using the `--vaadin-grid-body-row-active-cell` mixin. There’s no state attribute for that in v4/5.

We should add the `active` state attribute for the active row, to make it possible to style the active row using `[part~="row"][active]`.

**Comment by krumware** [comment]
Hi folks! just wondering if there has been any update to this one.

**Comment by tomivirkki** [comment]
This feature is moving into development in the upcoming sprints: https://github.com/vaadin/vaadin-grid/issues/1297

After it's done, the following should work:

Add "active" class name to the row that represents the currently active row:
```
grid.rowClassGenerator = rowData => grid.activeItem === rowData.item ? 'active' : '';
```

...Style the active row normally with a style module:
```
<dom-module id="grid-active-item-styles" them-for="vaadin-grid">
  <template>
    <style>
      [part~=row].active [part~=cell] {
        background: red;
      }
    </style>
  </template>
</dom-module>

```

Meanwhile, you could [set the active item as selected](https://cdn.vaadin.com/vaadin-grid/5.1.0/demo/#grid-selection-demos) and style the selected row instead.

**Comment by krumware** [comment]
Thanks Tomi! 

@sarahspencer @grudra7714 @ncraley for tracking and feedback

**Comment by web-padawan** [comment]
Note, the class name generator function should look like this:

```js
grid.cellClassNameGenerator = (column, rowData) => {
  return grid.activeItem === rowData.item ? 'active' : '';
}
```

**Comment by web-padawan** [comment]
For now the cell class generator API is the way to go. Closing per above comment.
