### ISSUE TITLE
Two way binding on grid data

### ISSUE THREAD

**Issue by jariberi** [vaadin/vaadin-grid#1208]
With this:
```html
Item 0 quantity: [[base_items.0.quantity]]
<vaadin-grid items="{{base_items}}">
    <vaadin-grid-column width="80px" flex-grow="0">
        <template class="header">Cantidad</template>
        <template>
           <vaadin-text-field pattern="[0-9].*" prevent-invalid-input value="[[item.quantity]]"></vaadin-text-field>
         </template>
     </vaadin-grid-column>
 </vaadin-grid>
```

When change the "quantity" field in `vaadin-text-field` the data in base_items changes, but the "Item 0 quantity" above still blank. Two way binding is not working.

**Comment by tomivirkki** [comment]
This kind of binding to an array sub-property is not supposed to work without additional change notifying, right? Tried the example with `<iron-list>` and I get the same outcome.

Re-open if I misunderstood something.

**Comment by jouni** [comment]
If I’m looking at it correctly, the text-field value is not 2-way bound, only 1-way (`[[]]` vs `{{}}`).

**Comment by tomivirkki** [comment]
That too, tested this with corrected syntax though

**Comment by jariberi** [comment]
@tomivirkki, 1-way binding was a typing error, it should be 2-way.
With `iron-list`works correctly:
```html
Item 0 quantity: [[base_items.0.quantity]]
<iron-list items="{{base_items}}">
    <template>
        <paper-input value="{{item.quantity}}"></paper-input>
    </template>
</iron-list>
```

**Comment by tomivirkki** [comment]
Thanks for the updated example, got it working with iron-list also. Seems to be broken in grid indeed. Reopening.

**Comment by tomivirkki** [comment]
Looks like `<iron-list>` has special handling for notifying `items` array sub-property changes. Added the same functionality to `<vaadin-grid>` in https://github.com/vaadin/vaadin-grid/pull/1209
