### ISSUE TITLE
vertical scrollbar is shown when data is empty

### ISSUE THREAD

**Issue by hariprasadiit** [vaadin/vaadin-grid#1221]
### Description
if we set `vaadin-grid` height to auto, then empty data causes `vaadin-grid` to show vertical scrollbar

### Expected outcome
No vertical scrollbar

### Actual outcome
Shows vertical scroll of `scrollTop` equal to `header`

### Live Demo
https://jsbin.com/fojujafawo/edit?html,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by BennerGe** [comment]
This also occurs when the table is filled and row details are enabled. 

## Demo
https://jsbin.com/qayomozuha/edit?html,output
