### ISSUE TITLE
Annoying repeated exception from touch support detection

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-grid#1222]
`ColumnReorderingMixin` defines a `_touchDevice` property that is initialized separately each time a `GridElement` instance is created. The detection logic depends on an exception being thrown, which makes things annoying when `Pause on caught exceptions` is enabled in the browser debugger when trying to pinpoint other problems.

If the obtrusive detection logic cannot be avoided, then it should at least only be run once instead of every time a `GridElement` is initialized.

Using version 5.0.0.beta1.

**Comment by Legioth** [comment]
And then there's a similar one in `GridOuterScrollerElement`, and maybe also in some other locations that I didn't yet encounter.

**Comment by platosha** [comment]
I can’t find any other reliable detection than checking if `document.createEvent('TouchEvent')` throws.

Checked the grid’s source, seems that we don’t have any template bindings for `_touchDevice`.  This means we can drop the `<vaadin-grid>`’s property in favour of something that runs just once.
