### ISSUE TITLE
Header style scoping breaks in Firefox when rendered inside vaadin-split-layout and HTML imports are nested

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1227]
Importing `vaadin-grid.html` and `vaadin-split-layout.html` with a combined `imports.html` file causes grid style scoping to break in Firefox when placed inside `vaadin-split-layout`.

## Works:
```html
<!doctype HTML>
<script src="../../webcomponentsjs/webcomponents-loader.js"></script>

<link rel="import" href="../../vaadin-split-layout/vaadin-split-layout.html">
<link rel="import" href="../../vaadin-grid/vaadin-grid.html">

<vaadin-split-layout>
  <vaadin-grid>
    <vaadin-grid-column>
      <template class="header">Header</template>
      <template>Body</template>
    </vaadin-grid-column>
  </vaadin-grid>
</vaadin-split-layout>
```
<img width="360" alt="screen shot 2018-02-19 at 0 18 40" src="https://user-images.githubusercontent.com/66382/36357715-7e318486-150a-11e8-90ed-69efd4a998c7.png">

## Doesn’t work:
```html
<!doctype HTML>
<script src="../../webcomponentsjs/webcomponents-loader.js"></script>

<!-- A file with the previous imports -->
<link rel="import" href="imports.html">

<vaadin-split-layout>
  <vaadin-grid>
    <vaadin-grid-column>
      <template class="header">Header</template>
      <template>Body</template>
    </vaadin-grid-column>
  </vaadin-grid>
</vaadin-split-layout>
```
<img width="359" alt="screen shot 2018-02-19 at 0 20 30" src="https://user-images.githubusercontent.com/66382/36357723-b9c48b10-150a-11e8-9c94-feb388e79a05.png">

Looking with the inspector, at least the `th` element is missing `class="style-scope vaadin-grid"`.

I’m suspecting this is happens with other wrapping elements as well, not just `vaadin-split-layout`.

**Comment by web-padawan** [comment]
I was unable to reproduce the issue with Firefox 58.0.2 and given code snippet above, could you point out what versions do you have installed and check for any errors in the console?

**Comment by jouni** [comment]
No errors in the console. Using 5.0.0-beta3.

You can also reproduce it using https://github.com/vaadin/vaadin-lumo-styles/blob/master/test/sink.html

**Comment by web-padawan** [comment]
Now I can confirm the issue with the `sink.html`, the first `<tr>` element and all of the `<th>` elements inside it do not have the style-scope classes.

**Comment by web-padawan** [comment]
UPD: this appears not to be related to the HTML imports. I have tried again and was able to reproduce with both cases.
Also I have noticed that this can be workarounded by setting the `slot="primary"` on the `vaadin-grid` explicitly. So it looks like a polyfill issue.

**Comment by pdesjardins90** [comment]
This happens to me as well, just using vaadin-grid and generated columns with dom-repeat. The class="style-scope vaadin-grid" is not applying itself. The workaround I did was this: 

```javascript
      _columnsChanged (columns) {
        Array
          .from(this.$.table.shadowRoot.querySelectorAll('#header>tr'))
          .forEach(row => row.classList.add('style-scope', 'vaadin-grid'))
      }

```
The columns property is what I pass to my dom-repeat to generate column templates
