### ISSUE TITLE
Column reordering doesn't work properly when some columns are in vaadin-grid-column-group

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1229]
### Description
When some columns are inside `vaadin-grid-column-group` and some aren't, those columns without  `vaadin-grid-column-group` are not reordable:

![peek 2018-02-20 10-47](https://user-images.githubusercontent.com/6059356/36414603-8a464096-162b-11e8-8379-fad90b73474d.gif)

### Expected outcome
I'm able to switch places of Address and Email columns

### Actual outcome
I'm not able to switch places of Address and Email columns

### Live Demo
https://jsfiddle.net/6r5htd05/132/

**Comment by jouni** [comment]
As a workaround, add an empty header template for the column group.

**Comment by limonte** [comment]
It would be great to have a proper fix :)

![image](https://user-images.githubusercontent.com/6059356/36414813-4414030a-162c-11e8-8417-6a0fc03c9545.png)

**Comment by jouni** [comment]
Patches welcome 😅 

But seriously, this seems like an issue that needs a proper fix. I’m just wondering about the use case you have – why do you use a column group if you don’t specify a header or a footer for it? Is is specifically to limit the user from reordering the columns outside that group?

**Comment by limonte** [comment]
> why do you use a column group if you don’t specify a header or a footer for it? Is is specifically to limit the user from reordering the columns outside that group?

Yes, it's only for making reordable groups. In px-data-grid there are data columns and action columns, in order to prevent mixing those columns I decided to put action columns into the group, data columns will be untouched.
