### ISSUE TITLE
Grid doesn't scroll on Android/Firefox

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid#1231]
### Description
The app at https://vaadin-kotlin-pwa.herokuapp.com/ contains a simple Grid which correctly scroll on touch when using Android Chrome, but it doesn't scroll when using Android Firefox.

### Expected outcome
The Grid should scroll its contents on touch.

### Actual outcome
The Grid contents are not scrolled.

### Live Demo
https://vaadin-kotlin-pwa.herokuapp.com/

### Steps to reproduce
1. Open https://vaadin-kotlin-pwa.herokuapp.com/ in Firefox in your Android phone
2. Try to scroll the grid

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome
- [x] Android Firefox

**Comment by web-padawan** [comment]
Confirmed the issue with the Android Firefox 59.0.2. Can be also reproduced in Expense Manager, as well as the latest demos for v5.0.0-beta7. Note that `iron-list` demos are scrollable.

**Comment by JoergW24** [comment]
With mobile Firefox 68.2.1 and the latest version of the grid component with Vaadin 14.0.3 we have the same problem in our project. The problem can be reproduced with the Demo from your website too. The grid content can't be scrolled. No scroll bars are visible in Firefox mobile. With mobile Chrome it works without problems. So at the moment the grid component can't be used at FireFox mobile.

**Comment by tomivirkki** [comment]
Just to clarify, officially we only support Safari on iOS and Chrome on Android as mobile platforms. Firefox is supported on desktop only. See https://vaadin.com/features

**Comment by mvysny** [comment]
So we're not going to fix the scrolling on Android+Firefox?

**Comment by tomivirkki** [comment]
As it's not an officially supported browser, fixing it is not on our priority list. Fixing the issue would also require adding Firefox Android to our CI test setup which in turn would require us to make any future changes also compatible with Firefox Android.
