### ISSUE TITLE
Random uncaught exception when shrinking items while scrolled

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-grid#1240]
### Description
`ScrollMixin._reorderRows` does arithmetics based on the `index` of the first entry in `items`. This may fail in cases when the number of items in Grid has recently been reduced to less than the number of physical items, since in that case the `index` property of the first item might not have been updated to take the new size into account. This in turn causes `Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'` to be thrown.

Whether this happens depends on whether the first entry in `items` is within the range of items that are actually used with the new reduced number of items. It might thus appear as though the issue occurs randomly, though it seems like the same scroll position will always produce the same result.

### Live Demo
https://jsbin.com/loriwerena/1/edit?html,console,output

### Steps to reproduce
0. Ensure polygit is not giving `500` responses
1. Click the `scroll` button
2. Click the `refresh` button
3. Enjoy the firework in the console

**Comment by tomivirkki** [comment]
Can this be produced with public API? Currently the jsbin uses private "scrollToIndex"

**Comment by Legioth** [comment]
You can reproduce without private API by manually scrolling to an appropriate location. `scrollToIndex` is used only to ensure you always scroll to a problematic position.

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/vaadin-grid/pull/1284
