### ISSUE TITLE
Viewport resize causes Vaadin-Grid scrollbar in Firefox and Edge

### ISSUE THREAD

**Issue by s3b89** [vaadin/vaadin-grid#1243]
### Description
The Demo [https://cdn.vaadin.com/vaadin-grid/3.1.0/demo/pagination.html](url) works for me in FF as well as in Edge, but in my application, there appears a scrollbar, if I resize the window. It actually is the 
`<vaadin-grid-table id="scroller">` that changes its size. Even if i set a fixed height and min-height for the vaadin-grid, I get a smaller `<vaadin-grid-table id="scroller">`. I actually tried to edit the CSS at runtime but I didn't find a way to archive this. I use Polymer 1.11.3 as well as the vaadin-grid 3.1.0.

### Expected outcome
In Chrome and IE the Grid is correctly displayed and you can get to the bottom of the page by scrolling the application.
![complete](https://user-images.githubusercontent.com/37110545/37036704-bf4c6f42-2150-11e8-85b7-faf537e9323b.PNG)

### Actual outcome
In FF (V 58.0.2) and in Edge (V 41.16299.15.0) I get an unneccessary scrollbar. 
![smaller viewport](https://user-images.githubusercontent.com/37110545/37036716-c808d08a-2150-11e8-8e01-3306e9025475.PNG)

By the way, I get two scrollbars, if i just set height="auto" for the vaadin-grid.
![two scrollbars](https://user-images.githubusercontent.com/37110545/37037773-4e7ab230-2153-11e8-8354-eb08f2208854.PNG)

### Browsers Affected

- [] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by s3b89** [comment]
Any news or fixes for this one? I can't just use Vaadin Grid 4 or 5 because I started my project with Polymer 1 and upgrading isn't that easy at this stage.
Thanks in advance and best regards!

**Comment by tomivirkki** [comment]
Hi, would really need a live example in order to be able to debug this better.
Since you're running Polymer 1, you might want to try vaadin-grid 2, which is primarily targeted for Polymer 1. Grid 3 is a hybrid version. The APIs haven't changed in between so switching should be easy.

**Comment by web-padawan** [comment]
We no longer support `vaadin-grid` version 3, and now it is very outdated. It is recommended to use the most recent version (currently 5.x) which gets all the fixes.

There hasn't been any activity in this issue for a while. Closing as stale.
