### ISSUE TITLE
Edge scrolling performance

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1249]
For some reason, scrolling performance is way worse on Edge with the latest Grid 5 than for example Grid 2.

This is especially evident in grids with many columns and custom elements in the cell templates.

Not the fairest comparison but still:

Grid 2:
https://cdn.vaadin.com/vaadin-grid/2.0.2/demo/dev.html

Grid 5:
https://cdn.vaadin.com/vaadin-grid/5.0.0-beta5/demo/dev.html

**Comment by limonte** [comment]
I can confirm that as well. `dev.html` is practically unusable on Edge (native, not VM).

The grid in Expense Manager kinda works but UX on Edge is quite bad.

**Comment by jouni** [comment]
Is this still relevant? I remember us doing a couple of Edge specific performance optimizations lately?

**Comment by limonte** [comment]
> Is this still relevant? 

Yup, still relevant for the latest stable version.

**Comment by bbaumgartner** [comment]
Hi Jouni
Does issue-backlog mean that it is not planed to fix this issue (any time soon)? 

Best Regards
Benno

**Comment by jouni** [comment]
@bbaumgartner `issue-backlog` means that this issue is at least kept on the radar of the dev team (it’s more visible in their [Waffle board](https://waffle.io/vaadin/vaadin-core)).

**Comment by tomivirkki** [comment]
We've tried to improve grid's scrolling performance on Edge on multiple occasions already but as Edge still relies on web components polyfill, it's difficult to get it working as smoothly as on the other browsers. Luckily Microsoft has announced that Edge will be rebuilt on top of Chromium; this should help a lot since it will bring native Web Component support to the browser. We'll see again if we could find some low-hanging fruits to improve this meanwhile.
