### ISSUE TITLE
Row hover styles should be disabled during scrolling and always on touch devices

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#126]
The hover styles for rows in the grid should be disabled during scrolling to prevent unnecessary paints.

They also don’t serve a purpose on touch devices and look distracting while scrolling using touch, as the row you drag gets the hover highlight.

**Comment by cwayfinder** [comment]
Can we add a css class to the grid body on scroll start and remove it on scroll end and just use selector like  `.vaadin-grid-body:not(.scrolling) tr:hover`?

**Comment by jounik** [comment]
If that’s possible, I would like us to try how it feels.
