### ISSUE TITLE
Undesirable scrollbar when a mouse is connected

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/vaadin-grid#1266]
### Description
An undesirable scrollbar is displayed in `vaadin-grid` when is displayed when a mouse is connected

### Expected outcome
<img width="367" alt="screen shot 2018-03-29 at 4 39 33 pm" src="https://user-images.githubusercontent.com/900868/38092031-d5c65d6a-336f-11e8-9c13-101d04ba71ed.png">

### Actual outcome
<img width="378" alt="screen shot 2018-03-29 at 4 39 09 pm" src="https://user-images.githubusercontent.com/900868/38092160-27fbcac0-3370-11e8-992a-0410d943a5a8.png">

### Steps to reproduce
1. Put a `vaadin-grid` element in the page.
2. Open the page in a web browser.
3. Connect a mouse and refresh

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari

[Context](https://vaadin.slack.com/archives/C3TGRP4HY/p1522331726000742)

**Comment by jouni** [comment]
This is normal macOS behavior. You can change it from System Preferences -> General (“Show scrollbars: When scrolling”).

As for the scrollbar styling, that could warrant its own issue.
