### ISSUE TITLE
Theme practices

### ISSUE THREAD

**Issue by robrez** [vaadin/vaadin-grid#1270]
### Description
I'm wondering if all themes should use an explicit host selector for each rule...

In an application I've been working on, we are using vaadin-grid for two different contexts. One is wierd and suffice it to say we've created a custom theme for it. The other, however, works wonderfully with the lumo theme.

The problem we've encountered is that some of the lumo rules end up targeting our "wierd" grid.

We _could_ resolve this by copying lumo... but I was wondering if it might be a better practice for themes to add something like this to each rule:

```
:host([theme~="lumo"])  /*the existing selector*/ {
```

Arguably, a downside of this is that each grid must explicitly state that the lumo theme should be used... where most people probably are content with every grid using the same theme
```
<vaadin-grid theme="lumo"/>
```

Thanks

**Comment by robrez** [comment]
After having more time to play with vaadin-inspired part/theme styling within our own elements, I can definitely concede that explicit theme selectors really sucks if you just want every/most instances to look a particular way.

Closing

**Comment by jouni** [comment]
If it was still supported, `:host-context` would be the perfect solution for this.
