### ISSUE TITLE
Lumo theme doesn't seem to work as documented in HTML Examples

### ISSUE THREAD

**Issue by jlk4p** [vaadin/vaadin-grid#1281]
### Description

The Lumo theme variations do not seem to work when applied to vaadin-grid component. After reviewing the HTML examples for this I applied no-border, row-stripes and wrap-cell-content together. But this doesn't change the appearance of the grid content.

### Expected outcome
No border, row-stripes, and wrapped content in each cell.

### Actual outcome

Border around grid. No striped rows. Content cuts off in columns.

### Live Demo

https://www.library.virginia.edu/services-dev

### Steps to reproduce

1. Put a `paper-input` element in the page.
2. Put a `paper-toggle-button` element in the page.
3. Put a `vaadin-grid` element in the page.
4. Add theme="no-border row-stripes wrap-cell-content" to the `vaadin-grid` element.
5. Add `vaadin-grid-sorter` element to the column header template.
6. Open the page in a web browser.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome
I did not test all browsers when those above on OS X did not work.

I'm wondering if there is some simple file reference I'm missing that is not specified in the documentation. I've got the following included in my page component:
&lt;link rel="import" href="../vaadin-grid/vaadin-grid.html"&gt;
&lt;link rel="import" href="../vaadin-grid/vaadin-grid-sorter.html"&gt;

**Comment by web-padawan** [comment]
You're apparently using `vaadin-grid` v4.1.7 which does not have Lumo theme by default.
Please switch the dependency in your `bower.json` to look like this:
```
"vaadn-grid": "^5.0.0"
```
This will pick up the latest beta as well as the stable release once we publish it, which is expected to happen quite soon. For 4.x, we used to have theme in the separate repo, but that one is now deprecated, and the 5.x should be now used instead.

Please also pay attention to that we only backport some fixes to the 4.x branch, but the master already has a couple of performance improvements which are unlikely to be backported. So the latest beta should work significantly faster, especially in IE11, and we strongly recommend switching to it.

**Comment by jlk4p** [comment]
Thanks for that suggestion. I had tried using 5.0.0 before submitting this. But nothing was displaying, though I wasn't seeing any errors. I've tried that again. This time I removed some CSS I had in place:
        vaadin-grid {
          height: auto;
        }
Now I can see the content in my local window it just isn't full size. 
Thanks again.

**Comment by web-padawan** [comment]
Yes, the API has been changed and now the grid has the opt-in attribute `height-by-rows`, in case if you need to grow and shrink the grid in height depending on the number of rows. So you should use that, but keep in mind that it might affect performance for large data sets.

**Comment by jlk4p** [comment]
Thanks. I did read about potential performance issues with large data sets yesterday and will keep that in mind.
