### ISSUE TITLE
Grid notifyPath for subproperty not updating wildcard computed functions for items

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-grid#1293]
### Description
The `vaadin-grid` does not update computed functions when subproperty changes using two-way data binding in template. Seems that [this test](https://github.com/vaadin/vaadin-grid/blob/master/test/templates.html#L402) is insufficient.

### Expected outcome
The two-way binding for subproperty of the item object should invoke the wildcard observers and computed functions for the `"items"` array, e. g. using `items.*`

### Actual outcome
The computed function or observer does not get triggered, although [this row](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-templatizer.html#L128) is expected to handle it.

### Live Demo
https://jsfiddle.net/webpadawan/dx33oqx0/

### Steps to reproduce

1. Open the jsfiddle above
2.  Start typing in the text-field, see the subtotal updated
3. Remove `on-value-changed` listener from the text-field
4. Repeat the step 2. but no updates anymore

**Comment by tomivirkki** [comment]
Not sure if that kind of binding can be expected to work. Changed the demo to use iron-list and the same issue produces: https://jsbin.com/yafegawexu/edit?html,output

**Comment by web-padawan** [comment]
My bad. Adding two way binding for the `items` fixes the issue: https://jsfiddle.net/webpadawan/dx33oqx0/5/
