### ISSUE TITLE
Support custom classnames/attributes for grid themable parts (row/cell class generators)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1297]
API:
```
grid.cellClassGenerator = function(rowData, column) {
  //  The returned class names, separated by spaces, will be added to the class list of the corresponding cell
  return ('row-' + rowData.index) + ' ' + column.path.replace('.', ' ');
};
 ```

TBD:
- Should we add `grid.cellStyleGenerator`?
 ```
grid.cellStyleGenerator = function(rowData, column) {
  // The object has style property - value pairs that are applied as inline styles to the corresponding cell
  return {'color': rowData.index === 3  ? 'red' : 'green' };
};
 ```

- Dedicated API for programmatically invoking the generators?

**Comment by tomivirkki** [comment]
Early prototype at https://github.com/vaadin/vaadin-grid/tree/feature/class-generators

Still unclear how to set custom class names to
- header rows
- footer rows
- details cell

**Comment by Legioth** [comment]
I think it's quite acceptable that headers, footers and details cells are without support for custom class names. There are relatively few copies of those elements, which means that it's not too much overhead to wrap the contents in an element with the class name.

**Comment by tomivirkki** [comment]
Related: https://github.com/vaadin/vaadin-grid/issues/1205

**Comment by sverkera** [comment]
This doesn't appear to be working: 
https://vaadin.com/forum/thread/17533251/grid-column-classname-generator-not-working
