### ISSUE TITLE
accessing element in vaadin grid

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-grid#1298]
This is my code which is running perfectly.
     <vaadin-grid aria-label="Array Data Example" items="[[items]]">

      <vaadin-grid-column width="60px" flex-grow="0">
        <template class="header">#</template>
        <template>[[index]]</template>
      </vaadin-grid-column>

      <vaadin-grid-column>
        <template class="header">First Name</template>
        <template>[[item.firstName]]</template>
      </vaadin-grid-column>

      <vaadin-grid-column>
        <template class="header">Last Name</template>
        <template>[[item.lastName]]</template>
      </vaadin-grid-column>

    </vaadin-grid>

I am accessing an element as `[[item.firstName]]` (for example). But suppose the element name (`firstName` in this case) is in another object `columns`(for example). How can I access the value now?
Is it `[[item.columns.firstName]]`?
Thank you

**Comment by tomivirkki** [comment]
Hi @sudipta1411 
Yes that's right. In the following live example the `[[item.name.first]]` is bound in the template. https://vaadin.com/components/vaadin-grid/html-examples/grid-selection-demos (the first demo)

**Comment by sudipta1411** [comment]
Thanks for the answer.
What I mean is `columns` is a different object. In pure javascript one would do `item[columns[firstName]]`.

**Comment by tomivirkki** [comment]
Ah, ok in that case you might be better off with a computed bindind (Polymer): `[[__getFoobar(item)]]`

And then create a function _getFoobar in your class:
```
__getFoobar(item) {
  return item[this.columns[firstName]];
}
```
