### ISSUE TITLE
Grid Editor. Problems with editing the first Element. 

### ISSUE THREAD

**Issue by pepkaQQ** [vaadin/vaadin-grid#1302]
### Description
First 'vaadin-grid' element create a bag when you want to edit its(getEditor().setEnabled(true)).  Solution is to make mouse scroll. 

### Expected outcome
Open editor.
![image](https://user-images.githubusercontent.com/12900632/40228935-52504c9a-5a9b-11e8-9b5c-dce3fd9f0e4b.png)

### Actual outcome
-Doesn't open Editor without mouse scroll. 

-If double click or **.editRow()** on first element, then click button 'Esc' **addOpenListener()**  create _NullPointerException_.  

-Disappear column names  

![image](https://user-images.githubusercontent.com/12900632/40229105-f9c60348-5a9b-11e8-92c6-b4046fa2a3c7.png)

### Steps to reproduce
1. Open the first 'vaadin-grid element'

### Browsers Affected
-all

Vaadin-Version 8.4.1, 8.4.2

**Comment by limonte** [comment]
This is the right place for questions about Vaadin 8: https://github.com/vaadin/framework/issues 

Please ask this question there.
