### ISSUE TITLE
Keyboard support in vaadin grid

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-grid#1305]
Hi, 
Is there support for keyboard shortcuts in vaadin-grid? I have seen that it responds to `page-up` and `page-down`  as well as `up` and `down` keys. I want some custom callbacks to be invoked when some particular key combination is pressed, for example if some row is selected, the one pressing `space` should open a dialog. How can this be done?

**Comment by tomivirkki** [comment]
Hi @sudipta1411 
Please only use this issue tracker for reporting issues. Questions should be asked at https://gitter.im/vaadin/web-components or https://polymer.slack.com/messages/C6ULJ2F7S

When a cell is selected, hitting space will "activate" that item, so you can use grid's `activeItem` property for that. (corresponding event would be `active-item-changed`)
