### ISSUE TITLE
How to customize row style

### ISSUE THREAD

**Issue by Waynezhi** [vaadin/vaadin-grid#1311]
I want to use custom class for specific row with condition, but can i use **vaadin-grid-column** to get that or must use **dom-repeat** ?
thanks for your response.

**Comment by tomivirkki** [comment]
Hi @Waynezhi There's no feature for adding custom class names to the table rows (inside the shadow root). If it serves your purpose, you can bind the class name to wrapper elements inside the cells on a certain row/item.

```
<template>
  <div class$="[[_itemClass(item)]]">[[item.data]]</div>
</template>
```

**Comment by Waynezhi** [comment]
Hi @tomivirkki, thanks for your response, but each <vaadin-grid-cell-content> has its padding, that i can not set a style like background.

**Comment by tomivirkki** [comment]
Will be fixed by https://github.com/vaadin/vaadin-grid/issues/1297

**Comment by jouni** [comment]
>  but each vaadin-grid-cell-content has its padding, that i can not set a style like background.

You can override the padding with a custom style/theme module, and move that the nested divs instead.
