### ISSUE TITLE
Add API for getting the target item from a mouse event

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid#1318]
To make it easier to use `<vaadin-context-menu>` with `<vaadin-grid>`, it would be nice to have public API for the logic of retrieving the item based on the clicked row, that is used for selection:
https://github.com/vaadin/vaadin-grid/blob/6d78144cb760c80f914e5dd4312c42c01a67444c/src/vaadin-grid-cell-click-mixin.html#L24

Otherwise I need to copy this logic for the Flow component implementation:
```javascript
grid.addEventListener('vaadin-contextmenu', function(e) {
      const path = e.composedPath();
      const cell = path[path.indexOf(grid.$.table) - 3]; // <td> element in shadow dom
      var key;
      if (cell && cell._instance.item) {
        key = cell._instance.item.key;
      }
      grid.$server.updateContextMenuTargetItem(key);
    });
```
Now if the web component changes, it breaks the Flow component until we make the same changes for our code.

It could also improve the frontend DX for using `<vaadin-context-menu>` with `<vaadin-grid>`. The current demo adds the item index to the cell contents, which is not very convenient: https://cdn.vaadin.com/vaadin-context-menu/4.1.0-alpha1/demo/#context-menu-advanced-demos

**Comment by tomivirkki** [comment]
The planned API:
`grid.detailedEvents = ['dblclick', 'mouseout'];`

Grid would then emit "detailed events" whenever any of the specified native event occurs inside of it. The detailed events are named after their native counterparts but with a "detailed-" prefix  (in this case "detailed-dblclick" and "detailed-mouseout") and they contain contextual information about the event:
- the grid section the event took place at (header/body/footer)
- The "row data" in case the section is body (use `__getRowModel()`)
  - index
  - item
- whether the event occurred on details cell
- Reference to the column element (if not the details cell)
- reference to the native event

**Comment by tomivirkki** [comment]
Also make sure that keyboard events aren't stopped by the grid when focused https://github.com/vaadin/vaadin-grid/issues/1464

**Comment by pekam** [comment]
It could be useful to add a convenience method for better DX, like this:
```
grid.addDetailedEventListener('click', e => {});
```
Internally it would just add `click` to `detailedEvents` if it's not there yet, and add the given listener for `detailed-click` event.

IMO that would be more convenient than this:
```
grid.detailedEvents = ['click'];
grid.addEventListener('detailed-click', e => {});
```

As discussed f2f, the `detailedEvents` array is still needed so it can be set declaratively. So this convenience API can be considered separately after the core feature has been implemented.
