### ISSUE TITLE
Extends Vaadin.GridElement

### ISSUE THREAD

**Issue by Bellski** [vaadin/vaadin-grid#1327]
### Description
I want to extend `Vaadin.GridElement` to override `getItemId()` function.

### Expected outcome
Default working grid component

### Actual outcome
![fail](https://user-images.githubusercontent.com/7370042/43149690-c875cda0-8f70-11e8-8c24-4d3166005a1d.png)

### Live Demo
[https://jsfiddle.net/exneb3gj/65/](Demo)

### Steps to reproduce
1. Replace `vaadin-tree-grid` on `vaadin-grid`

### Browsers Affected
- [+ ] Chrome

**Comment by web-padawan** [comment]
Thanks for the issue, and sorry for not answering earlier. We do not recommend using `cdn.vaadin.com` in the jsbins and recently updated the issue template.

So, cold you reproduce the issue using this glitch? Just press "Remix this" in the menu and apply any changes you need: https://glitch.com/edit/#!/kindly-postbox?path=index.html:1:0

**Comment by web-padawan** [comment]
This was fixed. Note that there is limitation related to element name, see https://github.com/vaadin/vaadin-grid/issues/1584#issuecomment-476715884

Here is a demo confirming the error is no longer thrown for `vaadin-tree-grid`.

https://glitch.com/edit/#!/extend-vaadin-grid?path=tree-grid.html:1:0

So I'm closing this as fixed, let's discuss extending grid in #1584.
