### ISSUE TITLE
Moving id last hides/shows a horizontal scrollbar when hiding/showing it

### ISSUE THREAD

**Issue by mikkoi-vaadin** [vaadin/vaadin-grid#1329]
Moved from Gitlab. Reported by Artur. 
--
https://vaadin.com/elements/vaadin-grid/java-examples/configuring-columns
"Column API Example"

"Toggle user reordering of columns"
"Drag ID last"
"Toggle visibility of the ID column"
"Toggle visibility of the ID column"
"Toggle visibility of the ID column"

Should not show a horizontal scrollbar

**Comment by web-padawan** [comment]
This is the issue in the Java examples so moving the issue to the Flow component repo.
Checked the link and the demo appears now to be totally broken because of the different error:

```
vaadin-grid-flow-selection-column-2.0.0-808e687c.cache.html:1 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at vaadin-grid-flow-selection-column-2.0.0-808e687c.cache.html:1
```

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-grid-flow#297
