### ISSUE TITLE
[FR] Consider a way to get a cell given col and row indexes

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#1340]
This is useful when e.g. adding actions to elements in a cell that modifies elements in other cells, specially when using renderers.

Right now the way is to update some attribute in the rendered content including the index, or using  private API
```
column._allCells.filter(cell => cell._model && cell._model.index === index)[0]
```

API might be `grid.getCellContent(col, row)` or `column.getCellContent(idx)`

**Comment by tomivirkki** [comment]
The proposed API isn't consistent because it returns different results depending on the user's scroll position/number of rows iron-list renders to the dom etc. For example, if you're scrolled to row 1000, what should `grid.getCellContent(0, 0)` return?

**Comment by manolo** [comment]
I meant `row` represents the item index not the actual cell in iron-list. If it's not rendered it should return null meaning that it's out of the grid viewport
