### ISSUE TITLE
Replace iron-ajax with fetch in demos

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-grid#1367]
Several demos use `<iron-ajax>` for fetching data. As of P3, when the component is a JS file, it feels very strange to define the data fetching as HTML inside of a string instead of using `fetch` directly in JS. 

Using `fetch` would also make the demos less Polymer bound and easier to approach for non-Polymer devs.

**Comment by moderndeveloperllc** [comment]
@marcushellberg Y'all just need to make `vaadin-ajax` that uses `fetch` under it all ;-)

**Comment by moderndeveloperllc** [comment]
@marcushellberg Honestly, I just like the ancillary functions around debouncing, [query string encoding](https://github.com/PolymerElements/iron-ajax/blob/master/iron-ajax.html#L327), lifecycle event firing, etc. I already have a custom component for my API calls that does a
```
this.request = document.createElement('iron-ajax');
```
I'll probably switch that over to `fetch` at some point in time, but that would mean recreating all the above functions, or finding a good npm package that already does.

**Comment by tomivirkki** [comment]
The demo files are loaded dynamically, so the source must be in ES5 (in order for them to function on IE11)

**Comment by web-padawan** [comment]
We can consider using [fetch polyfill](https://github.com/github/fetch) but need to make sure it would be properly loaded by demos hosted on https://vaadin.com

**Comment by tomivirkki** [comment]
The demos have been updated and `<iron-ajax>` is no longer used. The one demo that fetches data from an external source uses XHRs https://cdn.vaadin.com/vaadin-grid/5.2.0-alpha4/demo/#grid-data-demos
