### ISSUE TITLE
Column filter components should shrink to fit column width

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-grid#1371]
### Description
The components (e.g. text-field, combo-box, etc) rendered as column filters in the grid header do not seem to take column width into account in any way, but instead render according to their normal default width. If the column is narrower than the component's width (+ cell padding), the component is simply clipped.

### Expected outcome
The filter component should shrink to accomodate the available space.

(Ideally, it should also be possible to easily make the component stretch to fill the column width, but this should be optional.)

### Actual outcome
The filter is clipped if the column is narrower than the filter component's default width.

### Steps to reproduce
1. Put a `vaadin-grid` element in the page.
2. Add a largeish number of non-expanding columns to the grid.
2. Add `vaadin-grid-filter` elements to the column header templates.
3. Open the page in a web browser.
4. Observe the filters getting clipped.

### Browsers Affected

- [x] Chrome
- [x] Firefox
(probably all the others too)

**Comment by TatuLund** [comment]
Why this issue is open, while #1176 is already closed?

**Comment by tomivirkki** [comment]
Closing
