### ISSUE TITLE
npm package: Unable to find a readme for @vaadin/vaadin-grid@5.1.0

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1374]
https://www.npmjs.com/package/@vaadin/vaadin-grid

Actual:

![image](https://user-images.githubusercontent.com/6059356/44458756-e0bcf400-a60f-11e8-9485-9fb266fb88ff.png)

Expected: readme :)

**Comment by web-padawan** [comment]
The file is present in published package. Looks like an npm issue to me.

**Comment by web-padawan** [comment]
Starting from the 5.2.0 (including the alphas) this is fixed and readme is displayed correctly. 
I don't really think we can somehow make the readme appear in `5.1.0`, so closing this issue.
