### ISSUE TITLE
Polymer template binding examples are removed from demo descriptions

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1375]
For example, the `[[index]]` and `[[item.prop]]` texts from the [Basics](https://github.com/vaadin/vaadin-grid/blob/master/demo/grid-basic-demos.html#L69) demo page are not rendered in the final output: https://cdn.vaadin.com/vaadin-grid/5.2.0-alpha1/demo/#grid-basic-demos

**Comment by web-padawan** [comment]
Fixed by b638a5e
