### ISSUE TITLE
aria-level not valid on role="gridcell"

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-grid#1377]
The ARIA property `aria-level` is not valid on a `<td>` with a `role` of `gridcell`. According to [the documentation](https://www.w3.org/TR/wai-aria/#aria-level), this should only be set on the `row` role

I think the offending code is:
https://github.com/vaadin/vaadin-grid/blob/35ee83a2a8f8c81e0bca9892c447e18a667c9145/src/vaadin-grid-a11y-mixin.html#L73-L76

**Comment by web-padawan** [comment]
Fixed by #1456. Sorry about not answering earlier, and thanks for reporting!
