### ISSUE TITLE
SyntaxError: redeclaration of const $_documentContainer (Firefox)

### ISSUE THREAD

**Issue by sahshaurya** [vaadin/vaadin-grid#1379]
### Description
Use of vaadin-grid shows **redeclaration of const $_documentContainer error in vaadin-grid-styles.js** 
in dev environment. Works fine after the build.

### Expected outcome
No error should be thrown and vaadin-grid should render properly with all functionality even in dev environment.

### Actual outcome
vaadin-grid is rendered in the following manner with functions like resizable-column not working.
![vaadin-grid-on-firefox](https://user-images.githubusercontent.com/20743768/44706640-ec049980-aabf-11e8-95da-c48988127ff6.png)

### Steps to reproduce
1. Put a `vaadin-grid` element in the page.
2. Populate grid with values.
2. Open the page in a web browser.

### Browsers Affected

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Hello, what do you mean by "dev environment"? 
Are you using `polymer serve --npm` and if so, what version of Polymer CLI do you have?

**Comment by sahshaurya** [comment]
@web-padawan Yes using polymer serve.
Polymer CLI version - 1.7.2

**Comment by web-padawan** [comment]
Consider updating to at least 1.7.7, there has been a number of AMD loader improvements during 1.7.x
In the file itself, there is no redeclaration, so I assume it is incorrectly transformed / processed.

**Comment by sahshaurya** [comment]
@web-padawan Updated to 1.8.0
Still shows the same error.

**Comment by web-padawan** [comment]
I have commented in the Polymer tools issue linked above. Hopefully Tools team will be able to handle this, as there is nothing to do from our side (maybe some crazy workaround could be done, but we would need to understand the reason first).

Note that problem does not happen when using webpack, see working example: https://github.com/web-padawan/polymer3-webpack-starter

**Comment by limonte** [comment]
This is the issue of polymer tools, therefore I'm closing it. Please subscribe to https://github.com/Polymer/tools/issues/315 to be on track.

**Comment by web-padawan** [comment]
Workaround released in https://github.com/vaadin/vaadin-grid/releases/tag/v5.2.8
