### ISSUE TITLE
Doesn't shrink itself in the flex container when height-by-rows is set

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1415]
### Description
The `vaadin-grid` element doesn't shrink itself inside any container with `display: flex; flex-direction: column;` when `height-by-rows` is set

### Expected outcome
The `vaadin-grid` element shrink itself to the height of all rows.

### Actual outcome
The `vaadin-grid` element doesn't shrink itself.

### Live Demo
https://glitch.com/edit/#!/dog-scarecrow?path=index.html:7:0

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by limonte** [comment]
solution proposal: setting `flex-grow: 0` for the grid with `height-by-rows`

**Comment by tomivirkki** [comment]
> Solution proposal: setting flex-grow: 0 for the grid with height-by-rows

Not enough. Try that fix inside a flexbox with `flex-direction: row`.

**Comment by limonte** [comment]
Fixed in https://github.com/vaadin/vaadin-grid/releases/tag/v5.2.5 and https://github.com/vaadin/vaadin-grid/releases/tag/v5.3.0-alpha5
