### ISSUE TITLE
It should be possible to get a column reference with a column name, not just index

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#143]
Currently it is only possible to reference a certain column using it’s index in the columns array. It would be helpful if you could access a column using it’s name property, in cases when the order or the columns array is not known or is changed by user input.

E.g.

``` javascript
grid.columns = [
  {name: "user.name.last"},
  {name: "user.name.first"}
];

grid.columns["user.name.last"].renderer = function(...) {
  ...
};
```

**Comment by cwayfinder** [comment]
What do you think about 

```javascript
grid.columns = [
  {name: "user.name.last"},
  {name: "user.name.first"}
];

grid.getColumnByName("user.name.last").renderer = function(...) {
  ...
};
```
?

**Comment by cwayfinder** [comment]
What if the `name` property is not specified for some of the columns?

**Comment by jounik** [comment]
Current workaround:

```javascript
var nameCol = grid.columns.filter(function(col) { return col.name == "user.name.first"; })[0];
```

**Comment by elmot** [comment]
+1

**Comment by jounik** [comment]
> What if the name property is not specified for some of the columns?

Those columns can’t be accessed with name, obviously.

**Comment by jouni** [comment]
Wontfix. Use the provided workaround if needed.
