### ISSUE TITLE
Nested grid-sorter + grid-filter overflows a narrow column

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1438]
Nesting `<vaadin-grid-filter>` inside `<vaadin-grid-sorter>` does not scale the contained filter text field to fit the column width.

Test case: https://github.com/vaadin/vaadin-grid/blob/master/demo/dev.html#L116-L118

The `<vaadin-grid-sorter>` element should have similar `max-width: 100%` defined as `<vaadin-grid-filter>` has.

**Comment by vances** [comment]
Is there a workaround for this problem? We would really like sort but really _need_ filter.

**Comment by jouni** [comment]
As a workaround (until the PR is merged and a release made), you can add the following CSS in the same style scope as your `<vaadin-grid>` element. So this isn’t a global fix, you need it in all shadow roots where you have a grid.

```css
vaadin-grid-sorter {
  max-width: 100%;
}
```
