### ISSUE TITLE
Allow custom event handlers for rows

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#144]
A developer should be able to define custom event handlers for rows, such as double-click listener for opening an editor for the clicked row item.

It would be best if this could be done declaratively, but it should be possible at least programmatically. This most likely relates to declarative renderer support as well.

Declarative examples:

``` html
<vaadin-grid>
  <table>
    <tbody>
      <!-- Define column renderers using a template and a handler for the click event -->
      <template is="vaadin-grid-items" items="[[data]]">
        <tr on-click="_editItem(item.index)">
          <td>[[item.user.name.first]]</td>
          <td>[[item.user.name.last]]</td>
        </tr>
      </template>
    </tbody>
  </table>
</vaadin-grid>
```

The previous is probably not technically feasible right now, since the GWT code manages the creation of all of the `tr` elements. I’m not sure if it would be possible to define the event handles on the `tempalate` element directly? If it is, then I think column specific templates might work equally nicely (not sure if this actually makes any sense):

``` html
<vaadin-grid>
  <table>
    <tbody>
      <template is="dom-bind" on-click="_editItem(item.index)" name="user.name.first">
          [[data]]
      </template>
      <template is="dom-bind" on-click="_editItem(item.index)" name="user.name.last">
          [[data]]
      </template>
    </tbody>
  </table>
</vaadin-grid>
```

Programmatic example:

``` javascript
grid.addEventListener("vaadin-grid-row-click", function(e) {
  this._editItem(e.item.index);
});
```

Events that would be nice to support:
- click/tap
- double-click/double-tap
- mousedown/mouseup
- tap-and-hold/long-tap
- swipe

**Comment by jounik** [comment]
I wrote another possible declarative example as a gist, which seems more feasible (replace the light DOM `table` element with a `template` element instead): https://gist.github.com/jounik/aa496bbc1b3ae6ddfd8f

**Comment by Ablu** [comment]
+1

**Comment by bnason** [comment]
Hey @jounik any update on this? I'm needing this and wondering if I should hack it or if there is something I can test/possibly add to.

**Comment by jounik** [comment]
@bnason Hi!

No update, unfortunately. I guess you would be happy with just having the custom event. Or would you need the declarative support as well?

Which event in particular do you need the most?

**Comment by bnason** [comment]
At the very least I need a simple custom row click event with ability the cancel the selection so I can implement double click functionality. Ideally it would be declarative as well but that isn't required if its too difficult.

**Comment by jouni** [comment]
The upcoming 2.0 covers the use cases presented in this issue (use custom event listeners in column templates). Wontfix for 1.x.
