### ISSUE TITLE
Translation of rows seems to be wrong with lots of rows and columns

### ISSUE THREAD

**Issue by yveslange** [vaadin/vaadin-grid#1442]
### Description
The vaadin-grid v5.2.0-alpha4 scrolling feature acts weirdly when dealing with a lot of rows.

### Expected outcome
The translation of rows should not generate an empty space between the header and the first row.
![capture1](https://user-images.githubusercontent.com/17984393/46132672-fe006600-c23e-11e8-82ca-44d7e4bb1acf.png)

### Actual outcome
The translation of the first row seems to be wrong.
Rows: ~100'050
Columns: ~50
![capture](https://user-images.githubusercontent.com/17984393/46132711-1f615200-c23f-11e8-86ab-89be463d46ea.PNG)

### Steps to reproduce
1. Put a `vaadin-grid` element in the page with 2 columns and 10 rows.
2. Generate columns using a template dom-if
3. After the grid is created:
    a. After the grid is created, push 100'050 to the items
    b. Updated the columns from 2 to 60
4. Start scrolling down

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
Hello Yves,
tried to reproduce the issue according to the the steps you described but it's working fine for me:
https://glitch.com/edit/#!/ancient-arithmetic

The image looks like something you could try fixing with `grid.notifyResize()` as a workaround.

**Comment by yveslange** [comment]
Thanks Tom for testing it,

I think that I found the issue. I have updated the vaadin-grid thead value

```
<dom-module id="custom-vaadin-grid-style" theme-for="vaadin-grid">
  <template>
    <style>
      thead { max-height: 34px; }
      ....
```

Removing this line seems to fix the issue. Does this make sense ?

Best regards, 
YL
