### ISSUE TITLE
Follow design guidelines for labels `Sentece case` instead of `Title Case`

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#1453]
There is a 'UI text writing guidelines' coming soon specifying that text should be sentence case, ping @jouni 

Autogenerated column headers should have only the first letter capitalised and not each word in the label

<img width="997" alt="screen shot 2018-10-04 at 14 44 28" src="https://user-images.githubusercontent.com/161853/46474856-3b876500-c7e4-11e8-9212-3a7616c4f616.png">

**Comment by tomivirkki** [comment]
The header "titles" are generated in Title Case currently (not CamelCase)
