### ISSUE TITLE
Using Filter and Sorter in Polymer 3 (LitElement) applications

### ISSUE THREAD

**Issue by sebastianroming** [vaadin/vaadin-grid#1461]
I'm using `5.2.0-beta2` and the example posted in #1451. That works perfectly fine for me, but I'm trying to use a sorter **and** a filter in one column. 

The example provided [here](https://cdn.vaadin.com/vaadin-grid/5.2.0-beta2/#/elements/vaadin-grid-filter) doesn't work, so: is there any possibility to make use of both items in one column?

Thanks!

**Comment by web-padawan** [comment]
Updated the glitch: https://glitch.com/edit/#!/lying-blanket?path=app.js:73:2

Using the header renderer you can combine filter + sorter helper elements.
Note the `.headerRenderer="${this.emailHeaderRenderer}"` row: here the property should be assigned as a camelCase (as LitElement works with properties), not as dash-case.

Closing as answered and as this is not an issue with the component. Please consider asking the questions like this in our Slack channel: https://polymer.slack.com/messages/C6ULJ2F7S
