### ISSUE TITLE
Make it possible to propagate keyboard events from the grid.

### ISSUE THREAD

**Issue by nobba75** [vaadin/vaadin-grid#1464]
### Description
Keyboard events is not propagated from the vaadin-grid.

### Expected outcome
Let the developer decide what happens with the event by letting it propagate from the grid if desired. Make it possible to control this behaviour.

### Actual outcome
The grid traps the keyboard event when in focus.

### Steps to reproduce
Use either mousetrap or iron-a11y-keys-behaviour to implement a general keyboard shortcut management for a page.
Add a vaadin-grid to the page.
The result is that the keyboard components work as expected when the grid is not in focus. But when it is then it traps the keyboard event in the keydown handler of the keyboard-mixin used by the grid.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
Closed in https://github.com/vaadin/vaadin-grid/pull/1473
