### ISSUE TITLE
Grid column reordering not working on Windows 10 Firefox and Chrome (touch device)

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid#1467]
### Description
I tried to use the column reorder functionality of the flow grid. It does not work on Chrome nor Firefox under Windows 10. Same for our official component demo at https://vaadin.com/components/vaadin-grid/html-examples/grid-columns-demos#reordering-and-resizing-columns.

I use a Surface Book 2, that has a touch screen, but I use mouse / touch pad. When using the touch screen directly, it works.

### Expected outcome
Column's reorder overlay should appear.

### Actual outcome
Column's header text is selected.

### Steps to reproduce
1. Use a Win 10.
2. Open Chrome / Firefox
3. Goto https://vaadin.com/components/vaadin-grid/html-examples/grid-columns-demos#reordering-and-resizing-columns
4. Try reorder - text will be selected

### Browsers Affected
- [ x ] Chrome, Version 69.0.3497.100 (Official Build) (64-Bit)
- [ x ] Firefox, 62.0.3 (64-Bit)
- [ ] Safari - no idea
- [ ] Edge - works
- [ ] IE 11 - works
- [ ] iOS Safari - no idea
- [ ] Android Chrome - works

Windows is at version 10.0.17134 Build 17134

**Comment by web-padawan** [comment]
We have similar Surface detection issue in the `vaadin-upload` component, too:
https://github.com/vaadin/vaadin-upload/issues/255#issuecomment-374156229

**Comment by OlliTietavainenVaadin** [comment]
I can only reproduce this in Firefox 66.0.5 (and ESR 60), in Chrome 74.0.3729.131 it works for me.

**Comment by stefanuebe** [comment]
Works on FF and Chrome for me. Edge only allows reordering by mouse.
