### ISSUE TITLE
Grid's select all checkbox doesn't check accordingly

### ISSUE THREAD

**Issue by imneeazmi** [vaadin/vaadin-grid#1476]
### Description
Select All checkbox doesn't act accordingly.

### Steps to reproduce
1. select all grid (Select All checkbox is checked)
2. un-select a row, then select unselected row again (Select All checkbox is unchecked)

### Expected Result
Select All check should be checked in **step 2**. Also happens when switching between pages.

![gridselectallcb](https://user-images.githubusercontent.com/22928748/47481074-13c87180-d865-11e8-81c8-af841f5a43cf.gif)

**Comment by tomivirkki** [comment]
Hi @imneeazmi
This seems to be working fine at https://cdn.vaadin.com/vaadin-grid/5.2.1/demo/#grid-selection-demos

![grid-select-all](https://user-images.githubusercontent.com/1222264/47482048-20859f00-d83e-11e8-9830-3b889db37a6c.gif)

**Comment by limonte** [comment]
Hello @imneeazmi !

As @tomivirkki mentioned it works fine in our demos and I can't reprocuce the issue. Could you please help up to debug it and create a glitch, here's the template: https://glitch.com/edit/#!/best-ninja?path=index.html:7:84

**Comment by tomivirkki** [comment]
This issue was moved to vaadin/vaadin-grid-flow#387
