### ISSUE TITLE
Get Header column name dynamically

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/vaadin-grid#1478]
### Description
I need to access to the header column name of vaadin-grid
Someone has an idea ?
Thanks

**Comment by web-padawan** [comment]
Sorry about not answering earlier. You can only achieve that by using private API:
```
const column = grid.querySelector('vaadin-column');
const name = column._headerCell._content.textContent;
```

At this point, we do not have plans to expose it as a global getter. So let me close this issue.

It is generally better to ask questions like this in our `#vaadin` room in Polymer Slack channel:
https://polymer.slack.com/messages/C6ULJ2F7S
