### ISSUE TITLE
Third resizable header causes TypeError

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid#1480]
### Description
When grid has more than two layers of headers on top of each other, trying to resize columns by dragging from the third or upper layer header throws:
```
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at HTMLElement._onHeaderTrack (vaadin-grid-combined-mixin.html:407)
    at Object._fire (gestures.html:696)
    at Object._fire (gestures.html:1038)
    at movefn (gestures.html:935)
    at HTMLDocument.upfn (gestures.html:943)
```

### Expected outcome
Can drag to resize on any header

### Actual outcome
Dragging on third or upper header causes `TypeError` and dragging has no effect

### Live Demo
https://glitch.com/edit/#!/friendly-hydrogen

### Steps to reproduce
1. Add column-group on top of a column-group on top of a column
2. Make all columns and column-groups `resizable` 
3. Try to resize the top-most headers by dragging

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Need to verify if it happens on master also.
