### ISSUE TITLE
Could have floating column visible only mouse hover ?

### ISSUE THREAD

**Issue by Waynezhi** [vaadin/vaadin-grid#1484]
### Description
A column has some action buttons, which are displaying all the time

### Expected outcome
Show buttons only hover on a row (like gmail)

thanks

**Comment by web-padawan** [comment]
This is actually implemented for grid column sort icons in the Material theme:
https://cdn.vaadin.com/vaadin-material-styles/1.2.0/demo/grids.html

Is it what you mean? We don't have any other "action buttons", e.g. filtering does not use it.
In case if you need Material theme, change your import to look like this (if you are on Polymer 3):

```js
import '@vaadin/vaadin-grid/theme/material/vaadin-grid.js';
```

**Comment by web-padawan** [comment]
In case you would like to implement it in your custom theme, this is how it is done in Material:
https://github.com/vaadin/vaadin-grid/blob/9d5fc30e3b5cbbfd51d6034f47880ebafb135adc/theme/material/vaadin-grid-sorter-styles.html#L56

We do not have plans to change existing appearance of the Lumo, which is a default theme.
Therefore I'm closing this issue as answered, but feel free to comment if you need more help.
