### ISSUE TITLE
Fix RTL issues

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1490]
- Frozen translate direction
- Sort arrows should have space on the other side also
- Multi-sort indicator is on the wrong side
- Tree toggle arrow faces wrong direction
- Column borders variant places the borders on the wrong side

**Comment by JonUihlein** [comment]
Hello. Apologies if this is the wrong place to report additional RTL inconsistencies, but I believe there is also an issue with `<vaadin-grid-selection-column>` when setting `frozen` to `true` when direction is RTL. The column seems to be hidden behind other columns. Could be an issue with frozen columns in general.
