### ISSUE TITLE
v-grid: selecting a continuous range of rows

### ISSUE THREAD

**Issue by MarcusJT** [vaadin/vaadin-grid#15]
It would be great if v-grid supported selecting a contiguous range of rows via the common shift-click (i.e. select first row in desired range then shift-click last desired row in range) interaction pattern.

Being able to click-drag to progressively select & unselect rows in a similar manner would be handy too, but this is less conventional.

**Comment by jounik** [comment]
There is actually a drag selection functionality available, but it’s currently disabled because it doesn’t work correctly if there are multiple v-grids on the page.

Shift/ctrl-clicking is a nice to have feature, definitely considering that.

**Comment by jouni** [comment]
As there are two separate issues in this one (shift/ctrl-click and drag-selection), and since we have separate issue for those now (#815 and #816), I’m closing this one as a duplicate. @MarcusJT, please subscribe to those newer issues if you’re still interested in this.
