### ISSUE TITLE
Reconfigure Travis to retry a failed automatically 5 times

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#150]
Random Travis build failures:

- npm install fails for some reason in travis
- stuff is built and served, sauce labs can’t find it, 404
- test are actually run, there are timing issues
  - grid.then() issue, according to @tomivirkki 

The issue is relevantly small, so kicking the build a few times usually fixes it, but takes time to do manually.

**Comment by tepi** [comment]
Review at https://github.com/vaadin/vaadin-grid/pull/153

Seems to work now (see https://travis-ci.org/vaadin/vaadin-grid/builds/80189640). Retry count seems to be hard-coded to 3 but that should be enough for most cases.

**Comment by tomivirkki** [comment]
"Using the new --retry option has the benefit of giving you finer control about the total amount of retries." [http://docs.travis-ci.com/user/build-timeouts/](http://docs.travis-ci.com/user/build-timeouts/)
