### ISSUE TITLE
Grid renders as a horizontal line in Firefox

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1505]
Grid inside a `<vaadin-vertical-layout>` without a defined height gets rendered as a horizontal line (no height). This occurs on Firefox.

**Comment by limonte** [comment]
Fixed in https://github.com/vaadin/vaadin-grid/releases/tag/v5.2.5 and https://github.com/vaadin/vaadin-grid/releases/tag/v5.3.0-alpha5
