### ISSUE TITLE
User testing

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#151]
Conduct remote user testing for vaadin-grid with two new users.

Would be ideal if we can get a new data source service up and running before these tests: https://github.com/vaadin/vaadin-grid/issues/148

**Comment by tuomasnironen** [comment]
Update: Sent out a remote test for one candidate (agreed to test) and requested to arrange a test date with another candidate.

**Comment by tuomasnironen** [comment]
Update: Booked a testing session with another candidate for Wednesday 24 Sep.

**Comment by tuomasnironen** [comment]
User testing summary #1: https://docs.google.com/document/d/1cae7BUdqQFi-PLN6T9ELCF6CcjtTfZjrIwpLKi_rHYg/

**Comment by jounik** [comment]
Still waiting for one user to respond (after a few weeks of silence). Let’s close this issue now and handle the incoming test results separately, if they ever appear.
