### ISSUE TITLE
Slow scrolling in Huawei Mate 10 Pro Chrome

### ISSUE THREAD

**Issue by lochehong** [vaadin/vaadin-grid#1518]
### Description

Vaadin Grid Table scolling very slowly in android chrome with huawei mate10 pro.

### Expected outcome

smooth scrolling

### Actual outcome

jerky scrolling

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [Y ] Android Chrome

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/vaadin-grid/pull/1791 and https://github.com/vaadin/vaadin-grid/pull/1797
