### ISSUE TITLE
Add documentation to theme variant demos

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-grid#1519]
The theme variants displayed here: https://cdn.vaadin.com/vaadin-grid/5.2.5/demo/#grid-theme-demos could use a short textual description telling what the variant actually does. It might not always be obvious from the variant name alone. For example, 
* Where exactly does the compacting apply? Cell top and bottom padding? How about left and right? Font size? 
* Row border still shown with `no-border`, why is that? (the reason is CSS border)
* What are Row Stripes?

**Comment by jconlon** [comment]
> What are Row Stripes?
Stripes every other row.

**Comment by OlliTietavainenVaadin** [comment]
> Stripes every other row.
Yes, but what's a "stripe"?

**Comment by jconlon** [comment]
It background colors or shades every other row to make them easier to distinguish.  Was needing this common way to visualize rows and thought I need to use styles to do it, but saw that this functionality was in the themes and it was easier to use the themes to get it.

**Comment by OlliTietavainenVaadin** [comment]
Just the kind of description I was looking for in the demos! :smiley:

**Comment by web-padawan** [comment]
### Compact theme

The following styles changes are applied internally by setting `theme="compact"`:

- header cells: 
  - min-height is decreased from `--lumo-size-xl` to `--lumo-size-m`
- body and row details cells: 
  - min-height is decreased from `--lumo-size-m` to `--lumo-size-s`
  - vertical padding is decreased from  `--lumo-space-m` to `--lumo-space-s`

### No Border theme

When setting `theme="no-border"`, the outer border on the grid is removed.

### No Row borders theme

When setting `theme="no-row-borders"`, all the borders on the grid rows are removed.

### Column borders theme

When setting `theme="column-borders"`, all the cells (except row details) have the border-right set. This doesn't apply to the last column, to ensure proper outer grid border appearance.

### Row stripes theme

When setting `theme="row-stripes"`, all the even grid rows (their body and details cells) are filled with the background of `--lumo-contrast-5pct`. The odd rows cells appearance is left unchanged.

**Comment by web-padawan** [comment]
Fixed by #1585
