### ISSUE TITLE
Importing vaadin-components.html removes class names from the body element

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#152]
My body tag has ```class=" v-generated-body v-sa v-ch v-webkit v-mac valo foo bar"```and after adding an import for vaadin-components.html the body tag has ```class="v-generated-body valo foo bar"```

**Comment by cwayfinder** [comment]
There was a task for that https://trello.com/c/yfAwAjaR/131-remove-browser-specific-selectors-from-the-body-element

**Comment by cwayfinder** [comment]
and commit https://github.com/vaadin/vaadin-grid/commit/3e0297c5d39881bd07056aac258fd6d2cfe86a68
