### ISSUE TITLE
headerRenderer breaks grid if the column count decreases

### ISSUE THREAD

**Issue by Avocher** [vaadin/vaadin-grid#1522]
### Description
It seems that using `headerRenderer` breaks the header if the column count decreases.

### Live Demo
https://glitch.com/edit/#!/alive-chalk

### Steps to reproduce
Look at the table

**Comment by tomivirkki** [comment]
Hi, taking a look. Meanwhile, forcing the header row visible could be used as a workaround:
```
this.columns = this.columns5;
requestAnimationFrame(() => {
  grid.$.header.children[0].hidden = false;
  grid.notifyResize();
});
```
