### ISSUE TITLE
Grid detail view is flickering when scrolling grid

### ISSUE THREAD

**Issue by jbreitung** [vaadin/vaadin-grid#1527]
### Description
When having a grid with a detail view and the grid has enough entries to be scrollable, the components of the detail view will flicker during the scrolling.

### Steps to reproduce
1. Add a grid with enough entries to be able to scroll
2. Add a detail view generator to this grid
3. Add some components to the detail views layout
4. Open the detail view of one entry and scroll the grid

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [?] Safari
- [?] Edge
- [?] IE 11
- [?] iOS Safari
- [?] Android Chrome

**Comment by tomivirkki** [comment]
I don't see flickering with the row details demos at https://cdn.vaadin.com/vaadin-grid/5.2.5/demo/#grid-row-details-demos Are you using a `rowDetailsRenderer` for the details content? If so, make sure it doesn't re-generate the content on every invocation but reuses/updates existing, previously generated details row content where possible.

**Comment by web-padawan** [comment]
@jbreitung please submit the issues related to Framework 8 to https://github.com/vaadin/framework
