### ISSUE TITLE
vaadin-grid cells don't take content's width into account; they don't stretch

### ISSUE THREAD

**Issue by alshakero** [vaadin/vaadin-grid#1529]
Hi! Thanks for the awesome work! 

### Description
It seems to me that `vaadin-grid` cells don't consider their content's width and stick to a certain width even if their content was wider. 

### Expected outcome
The cell should stretch if its contents need that.

### Actual outcome
The cell doesn't, giving the grid the impression that it's smaller, hence the gird will crop it. 

### Live Demo
https://plnkr.co/edit/fy2tPggjkpTxg0D18U7l?p=preview

### Steps to reproduce
1. Just scroll horizontally to the end and you'll see a cropped button.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge

**Comment by web-padawan** [comment]
Thanks for the issue. Threre are already two related issues, #1233 is what you expect and #1287 is also similar. They are in our backlog, although not for a nearest term. You can follow these issues, and let me close this one as a duplicate.

**Comment by alshakero** [comment]
Great. I apologize for not finding those.
