### ISSUE TITLE
using renderer on <vaadin-grid-sort-column> will break sorting

### ISSUE THREAD

**Issue by paulkirspuu** [vaadin/vaadin-grid#1535]
Example: 

```
const column  = document.querySelector( 'vaadin-grid-sort-column[header="Column name"]' );

column.renderer = ( root, columnData, rowData ) => {
    // Anything here, can even be empty - still breaks.
}
```

Code above breaks selected column data sorting. Without it the sorting works fine.

Is there a way to maintain sort functionality while working with data via renderer? Or another callback function to be used for data processing / adding event listeners?

**Comment by lkraav** [comment]
@paulkirspuu first, define "breaks". I am not sure anyone is able to decipher right now what it really means in your context.

**Comment by paulkirspuu** [comment]
Without renderer numbers are sorted properly (descending / ascending), when clicking on header sort icon.

When using renderer, sort functionality is not working as intended. Meaning the header sort icon changes its state but data inside the column is not sorted.

**Comment by tomivirkki** [comment]
Here's an example with a sort column using a custom renderer that renders the cell content in bold (the "first name" column): https://jsbin.com/vigarodugu Works fine.

**Comment by paulkirspuu** [comment]
Thanks for the response. Indeed, works with strings.

Try replacing
`root.innerHTML = `<b>${model.item.firstName}</b>`;` with `root.innerHTML = `<b>${model['index']}</b>`;`

Does not seem to function with numbers, unfortunately.

**Comment by tomivirkki** [comment]
Note that the `model.index` isn't actually reflecting the index of the item in your data, but rather the order in which it's displayed by the grid. If you want to assign indexes for your data, you can either do that programmatically with something like `myItems.forEach((item, index) => item.index = index)` before assigning it to grid and then rendering `model.item.index` in the renderer.

**Comment by paulkirspuu** [comment]
This was more a simple example of random numbers in the column just to demo the problem, it can be any numbers for that sake.

**Comment by tomivirkki** [comment]
Here's an example using indexes bound to the items: https://output.jsbin.com/qepidoyize

**Comment by paulkirspuu** [comment]
When assigning data via model.item, it works.
But when assigning data via vaadin template path attribute, and later trying to render that data, it doesn't work.

Either way, we can use your solution and tweak the code a bit to make it work.

Thanks a bunch!

**Comment by tomivirkki** [comment]
> But when assigning data via vaadin template path attribute, and later trying to render that data, it doesn't work.

What doesn't work in this exactly? Can you provide an example so we can take action in case there is an issue.

**Comment by paulkirspuu** [comment]
As said in initial issue description, when data is assigned via template, and renderer is used on that column, code inside it can even be empty and sorting will break.

Additionally, one would think `root.innerHTML = `<a>${root.textContent}</a>`;` could be a sane way to add an element to column cell. Unfortunately, this behavior does not maintain sorting.

**Comment by T3rm1** [comment]
It also breaks when doing this in Java.

For example:
`grid.addColumn(new NumberRenderer<>(RealEstate::getPricePerSquareMeter, NumberFormat.getCurrencyInstance())).setHeader("€/m²").setSortable(true)`

It's not possible to sort the column any more. Tested with Vaadin 12.0.4
