### ISSUE TITLE
ColumnReorderListener

### ISSUE THREAD

**Issue by Springrbua** [vaadin/vaadin-grid#1537]
### Description
Columns can be reordered in `vaadin-grid` using drag-and-drop.
However, it does not seem to be possible to get this new column-order.

### Expected outcome
The `vaadin-grid` should fire an event when the columns are reordered.
The event should contain the new column order.

### Actual outcome
The columns are reordered but it is not possible (or extremely complex) to get this new order.

### Usecase
I would like to create a configurable grid. The users can reorder and resize the columns to their needs.
I would like to be able to save their current configuration, so that they get the same grid, when they refresh the page.

**Comment by web-padawan** [comment]
In theory, tracking the reordering could be achieved by the extension:

1. add the following mixin:

```js
const ReorderingPropertyMixin = base => class extends base {
    static get properties() {
      return {
        reordering: {
          type: Boolean,
          notify: true,
          readOnly: true
        }
      };
    }
    /** @protected */
    attributeChangedCallback(name, oldValue, newValue) {
      super.attributeChangedCallback(name, oldValue, newValue);
      if (name === 'reordering') {
        this._setReordering(newValue);
      }
    }
  };
```

2. extend the grid like this:
```js
class CustomGrid extends ReorderingPropertyMixin(Vaadin.GridElement) {
  static get is() {
    return 'custom-grid';
  }
}
customElements.define(CustomGrid.is, CustomGrid);
```

This would solve part of the problem. Actual columns order is being stored in the protected `_columnTree` property, so the extension will need to provide its own API on top of that.

**Comment by Springrbua** [comment]
Thank you for the information.  
As I am using `vaadin flow`, I would also need a connection between this extension and the `vaadin-grid-flow`.
Is there any documentation on how to achieve this?
