### ISSUE TITLE
Vaadin Grid Sort Multiple Sequence

### ISSUE THREAD

**Issue by fireplace009** [vaadin/vaadin-grid#1541]
### Description

When using multiple column sorting, is it possible to indicate behavior differently?
Currently the last column you sort, becomes the most important. 
Could it be possible to change this behavior so that the last column clicked, remains the less important column in your sorting.

### Currently
1. Sort on column 1 (this becomes the first sorting (showing nr 1 in the label)
2. Sort on column 2 (this becomes the first sorting (showing nr 1 in the label, and switching column 1 to nr 2 in the label)

### Requested behavior
1. Sort on column 1 (this becomes the first sorting (showing nr 1 in the label)
2. Sort on column 2 (this becomes the second sorting (showing nr 2 in the label)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x Android Chrome

**Comment by tomivirkki** [comment]
Hi @fireplace009, the current behaviour is a convenience default when using the `items` array, use a custom `dataProvider` for full control over how sorting/filtering affects the data.

**Comment by fireplace009** [comment]
Hey @tomivirkki, Sure, we could implement this in a dataprovider, but how to force the labels on the columns to be correct then? I presume that the second column clicked, would still show Nr 1 in the label (eventhough our dataprovider would use this second column as the second sorting criteria)

**Comment by tomivirkki** [comment]
That's a good point yeah, grid controls the state of the sorters internally at https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-sort-mixin.html#L62

One (dirty) option would be to patch that method. Another would be to wrap your sorters as custom elements so that grid doesn't register them as sorters and doesn't take control over them.

**Comment by fireplace009** [comment]
ok, thank you for the support.

(I'll look at adding some code to make this configurable, and I'll create a pull-request)
