### ISSUE TITLE
vaadin-grid-column: column-width-changed is no longer supported ?

### ISSUE THREAD

**Issue by fireplace009** [vaadin/vaadin-grid#1543]
### Description
Moving from vaadin-grid 2 to the 5.2.6
And I used to have a way to listen to changes to the columns (width resizing or reordering)
I'm looking now to implement this in the 5.x version but don't find a hook to get this info.

### Before
on-property-changed="_onColumnPropertyChanged"

But now ?

tried with 
- on-column-width-changed (doesn't exist anymore I think)
- Gestures.addListener(this.$.grid, 'track', e => this._onColumnPropertyChanged(e));
(works, but I don't get the column information)

Any ideas how to proceed?
Thank you,
b;

**Comment by tomivirkki** [comment]
Hi, unfortunately there's no API for this. Totally agree that `width` property _should_ be marked as `notify` so column would fire `width-changed` events on resize.

A workaround for now would be to patch the observer function with:
```
const f = column._widthChanged;
column._widthChanged = width => {
  f.call(column, width);
  console.log(`Width changed: ${width}`);
}
```

**Comment by fireplace009** [comment]
Ok, thanks.
In the end I went with the Gestures listening to 'track' and getting the column width from the grid itself.
eg: this.$.grid._getColumns()[3]._cells[0].style.width
