### ISSUE TITLE
vaadin 12.0.4 has a Error: Cannot read property '__getRowModel' of undefined

### ISSUE THREAD

**Issue by a497314013** [vaadin/vaadin-grid#1553]
vaadin 12.0.4 has a Error: Cannot read property '__getRowModel' of undefined, Who can tell me what should I do?  The issue #78,#1416 is closed, but no ways provided.

**Comment by limonte** [comment]
Hello @a497314013 

Could you please provide a code you're using?

**Comment by a497314013** [comment]
Hi,
![image](https://user-images.githubusercontent.com/45581625/51823713-28604e00-231b-11e9-8413-5a0b206797be.png)
![image](https://user-images.githubusercontent.com/45581625/51823738-3615d380-231b-11e9-8786-a7e61ccafc8f.png)
above are error info,
![image](https://user-images.githubusercontent.com/45581625/51823801-68273580-231b-11e9-919d-8a771379a441.png)
this is key code,when i comment the codes,it can be shown normally, and it also can be shown well at vaadin 10.0.5

**Comment by a497314013** [comment]
@limonte extra information here you are.

**Comment by limonte** [comment]
Thank you for the provided information @a497314013 

This seems like a bug indeed, for some reason `this._grid` in undefined here: https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-column.html#L259

**Comment by a497314013** [comment]
Thansks @limonte 
So, this bug doesn't be fixed yet, and my problem has no way to resolve it,right?

**Comment by yuriy-fix** [comment]
Dear @a497314013,
I have tried to reproduce the issue with the code snippet provided and versions for vaadin 12.0.4  ("jsVersion": "5.2.8", "javaVersion": "2.1.5") and I didn't get the error.
Could you provide more info on this case? Have you created an extension of the Grid?
BTW, why do you need to use `insertChild` for the column? It will be added with `addColumn`.

**Comment by yuriy-fix** [comment]
Closing as inactive.
