### ISSUE TITLE
Loading spinner Vaadin grid 5.2.7'

### ISSUE THREAD

**Issue by RogueOne23** [vaadin/vaadin-grid#1555]
### Description
Just upgraded to Polymer 3 and the version of vaadin grid that I am using is 5.2.7'. In Polymer 2; vaddin 2.7.2 there was a loading spinner that appeared when the data is loading. This spinner is no longer present in vaadin grid 5.2.7. Was it removed?, can it be turned on? or do users have to implement their own loading spinner?

### Expected outcome
Loading spinner to appear until data appears on the grid. 

### Actual outcome
No spinner and blank grid until data is loaded.

### Browsers Affected
- [ ] Chrome

**Comment by web-padawan** [comment]
The spinner was removed from grid, we have introduced the `loading` property instead:
https://github.com/vaadin/vaadin-grid/blob/f33301b154aa6ddfd0b1648775f9de39c142fdde/src/vaadin-grid-data-provider-mixin.html#L121

You can use it like this, to show custom spinner if you wish:
```html
<vaadin-grid items="[[items]]" loading="{{loading}}">
```

Also, note that `loading` is set as an attribute on the grid element so you can use that for styling.

**Comment by RogueOne23** [comment]
You're the man!. Thank you!!!
