### ISSUE TITLE
zero height Component

### ISSUE THREAD

**Issue by zalevan** [vaadin/vaadin-grid#1557]
I use two view with grids. I have boolean value and use ComponentRenderer<CheckBox, ...> for it column. 
When i first open grid all is ok. I see checkbox. Then i switch to another view and back. I see zero height for ComponentRenderer element and check box not visible.

**Comment by web-padawan** [comment]
Closing as duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/557 which is fixed by https://github.com/vaadin/flow/pull/5223
