### ISSUE TITLE
13.0.0.beta1,beta2,beta3 - Grid causes grid._physicalitems is null

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/vaadin-grid#1565]
Vaadin 13.0.0.beta1 results in a browser error "(TypeError): grid._physicalItems is null" in a grid that uses TemplateRenderer. The issue was not seen in any previous Flow versions up to 13.0.0.alpha4. The issue is not consistent, I'm using template renderer elsewhere in the app and those seems to work fine.

I've not been able to isolate the issue enough to attach a code sample, but will attach one later if I can find a way to reproduce it in a stand-alone app.
<img width="587" alt="screen shot 2019-02-15 at 2 05 51 pm" src="https://user-images.githubusercontent.com/6271003/52926159-4a396900-32fa-11e9-9528-09ad45fec4ee.png">

**Comment by martinisraelsen** [comment]
Update:

I recreated the issue using a regular grid. The issue seems to happen because there is another polymer component before the grid that has a label referenced by @Id. 

The issue does not happen if the if the polymer component doesn't use @Id (but rather TemplateModel) or if the polymer component is added after the grid.

The attached zip contains the code to reproduce the error.

[Vaadin-basestarter.zip](https://github.com/vaadin/vaadin-grid/files/2937258/Vaadin-basestarter.zip)

**Comment by martinisraelsen** [comment]
Happens in 13.0.0 main release too. 

Also noted that the issue does not appear to happen if grid items is loaded manually after the view has been rendered in the browser (e.g. by clicking a button).

**Comment by tomivirkki** [comment]
I guess this is also fixed by https://github.com/vaadin/vaadin-grid-flow/pull/517

**Comment by martinisraelsen** [comment]
Can confirm that this issue is solved in 13.0.1
