### ISSUE TITLE
Grid crashes whole tab in Samsung Internet (Android)

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-grid#1566]
### Description
Vaadin Grid demos crash the whole tab in the default browser of Samsung phones (Samsung Internet). Reproducible at least on Samsung Galaxy S8 (running Android 8.0.0).

### Expected outcome
The tab should not crash and `<vaadin-grid>` should work.

### Actual outcome
The whole tab crashes immediately on load and you can't even see the page.

### Live Demo
- https://cdn.vaadin.com/vaadin-grid/5.3.2/demo/
- https://cdn.vaadin.com/vaadin-grid/5.3.0/demo/

(maybe also other versions but these are the ones I tested)

### Steps to reproduce
1. Go to https://cdn.vaadin.com/vaadin-grid/5.3.2/demo/ with "Internet" app on a modern Samsung phone.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome
- [x] Samsung Internet (default browser on Samsung phones, app shortcut is named just "Internet")

**Comment by web-padawan** [comment]
Could you provide us with the version installed please?
One thing we need to know what Chromium version does it contain.

Also, can you try the LTS version on the same device?
https://cdn.vaadin.com/vaadin-grid/5.0.3/demo/

If the LTS version works, than it could be that awful bug in Chromium 65 which we had to workaround by combining mixins into the big one (LTS version still contains that fix).

If the LTS version is broken too, than it is most likely different issue.

**Comment by Haprog** [comment]
My device that I tested with has Samsung Internet 8.2.01.2 (apparently latest atm.) I can't find any other relevant version info. No idea what version of Chromium it has.

What do you mean with LTS in this context? I can try whatever I can install.

**Comment by web-padawan** [comment]
Sorry, I mean vaadin-grid 5.0.3 which is part of V10 LTS. Does the link above also crash?

**Comment by Haprog** [comment]
https://cdn.vaadin.com/vaadin-grid/5.0.3/demo/ Seems to work fine, no crashing and grid looks ok.

**Comment by web-padawan** [comment]
So, apparently Samsung Internet is indeed using broken Chromium 65 release :scream:

**Comment by web-padawan** [comment]
Looks like the latest beta is based on Chromium 67 which contains the fix:
https://medium.com/samsung-internet-dev/new-year-new-samsung-internet-b74f282e4429

**Comment by Haprog** [comment]
My Galaxy S8 got an Android update. Now it's running Android 9, One UI 1.0, Samsung Internet 9.0.01.80.

With this new browser version, all of the above demos seem to be working fine (and also the newer 5.3.3 release).

Not sure if this is still an issue for some other Samsung devices which might not have the update available (yet) though?

**Comment by web-padawan** [comment]
Closing as there is nothing to do for us with that broken Chromium version. In case anyone needs to make it work for older Samsung Internet versions, `vaadin-grid` 5.0.x is the way to go.
