### ISSUE TITLE
Cannot show scrollbar on Chromebook with mouse over

### ISSUE THREAD

**Issue by brp-jimmy** [vaadin/vaadin-grid#1578]
### Description
When I use the grid component on my Samsung Chromebook I cannot get the scrollbar to show on mouse over. If I scroll in the grid, the scrollbar appears and then I can move the mouse cursor and grab it. But when I just try to get it to show by moving my mouse pointer over it, it remains hidden.

It is not a problem with other inner layouts, just the grid. And it is only a problem on Chromebook due to the default setting to hide overlay scrollbars. Setting chrome://flags/#overlay-scrollbars to Disabled works, but it is inconvient to our users.

### Expected outcome
Scrollbar appearing on mouse over.

### Actual outcome
Scrollbar still hidden,

### Steps to reproduce
1. Go to grid examples on Vaadin website. https://vaadin.com/components/vaadin-grid/java-examples
E.g. Grid with lazy loading.
2. Move mouse pointer to where the scrollbar shall be.

### Browsers Affected
- [x] Chrome on Chromebook

**Comment by web-padawan** [comment]
As described here, the chrome://flags/#overlay-scrollbars flag was removed on Chromebook: https://support.google.com/chromebook/thread/1918063?hl=en&msgid=25644385

Many sites might be affected by this behavior but it's not specific to `vaadin-grid`. That's how Chromebook works:

> scroll bars are not really needed - just use two fingers on your touchpad, and you can easily scroll up and down
 
I don't think we can do anything about this issue, it should be fixed on Chromebook side. Closing as won't fix.
