### ISSUE TITLE
TreeGrid hierarchy breaks after consecutive data provider refreshes

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/vaadin-grid#1581]
On tree grid, after calling refreshAll on data provider, grid keeps previous position. However, if refreshAll is called too frequently, tree grid cannot update the hierarchy correctly. 

**Example**

	private TreeDataProvider<Bean> provider;

	public MainView() {
		TextField field = new TextField();
		initializeDataProvider();
		field.setValueChangeMode(ValueChangeMode.EAGER);
		field.addValueChangeListener(evt -> provider.refreshAll());
		field.setSizeFull();

		TreeGrid<Bean> treeGrid = new TreeGrid<>(provider);
		treeGrid.addHierarchyColumn(Bean::getValue).setHeader("Bean");

		add(field, treeGrid);
	}

	private void initializeDataProvider() {
		TreeData<Bean> treeData = new TreeData<>();
		List<Bean> rootItems = generateChildren(null);
		treeData.addRootItems(rootItems);
		rootItems.forEach(parent -> {
			List<Bean> children = generateChildren(parent);
			treeData.addItems(parent, children);
			children.forEach(child -> treeData.addItems(child, generateChildren(child)));
		});
		provider = new TreeDataProvider<>(treeData);
	}

	private List<Bean> generateChildren(Bean bean) {
		String base = bean != null ? bean.getValue() + "." : "";
		List<Bean> beans = new ArrayList<>();
		for (int i = 0; i < 5; i++) {
			beans.add(new Bean(base + i));
		}
		return beans;
	}

**Screen recording**

![tree-grid-problem](https://user-images.githubusercontent.com/33827141/54361938-c06a8a80-4670-11e9-8fd9-664c8307cc37.gif)

Vaadin version : 13.0.1
Browser : Chrome Version 72

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #588](https://github.com/vaadin/vaadin-grid-flow/issues/588) via [**ZenHub**](https://www.zenhub.com/)
