### ISSUE TITLE
<vaadin-grid> - itemDetailsRenderer with nested grid: content not rendered for CompomentColumn(s)

### ISSUE THREAD

**Issue by silvan-lincan** [vaadin/vaadin-grid#1587]
### Description

Vaadin Version 13.0.3

For a Grid which has a nested Grid inside the itemDetailsRenderer, the content for ComponentColumn(s) is not rendered in Chrome Version 73.0.3683.86 (Official Build) (64-bit)

### Expected outcome
![image](https://user-images.githubusercontent.com/47028355/55611745-b6770b80-5786-11e9-9e6a-00767a163779.png)

### Actual outcome
![image](https://user-images.githubusercontent.com/47028355/55611829-ffc75b00-5786-11e9-9c79-26e4dba3fc1a.png)

Please see an example attached:
[demo-nested-grid.zip](https://github.com/vaadin/vaadin-grid/files/3046869/demo-nested-grid.zip)

### Steps to reproduce
1. Put a `vaadin-grid` element in the page.
2. Add a nested `vaadin-grid` as content of itemDetailsRenderer
3. Add a column to this nested `vaadin-grid` as ComponentColumn (e.g. TextArea)
4. Open the page in Chrome web browser (73.0.3683.86).
5. TextArea should be rendered.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by gianluca-valentini** [comment]
Any news about it? I remember your twitt on 20th Feb:
![image](https://user-images.githubusercontent.com/3224592/56287550-f4781600-611c-11e9-8dee-67d96cb13787.png)

But currently, we are talking about Vaadin 13.0.4, it does not work yet.
So Vaadin 13 cann be used on production environment

**Comment by silvan-lincan** [comment]
Verified again with latest version of Chrome: 74.0.3729.108 (Official Build) (64-bit) and latest version of Vaadin 13.0.4 and now it seems that it is working.

@gianluca-valentini it seems that now is working with version 74.0.3729.108

**Comment by web-padawan** [comment]
Yep, it should be fixed in Chrome 74. See https://github.com/vaadin/flow/issues/5025#issuecomment-462693358

Closing as there is nothing to do here in the web component. The problem could be only reproduced in Flow counterpart. The workaround for Chrome 72 and 73 was implemented in vaadin/flow#5060

**Comment by silvan-lincan** [comment]
@web-padawan Thank you.

**Comment by gianluca-valentini** [comment]
@silvan-lincan @web-padawan thanks a lot
