### ISSUE TITLE
Flatten data properties

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#160]
The current nested properties syntax for some of the API is not very Polymer-like, and seems more complex than needed.

### Proposal:

```
data.source (array) -> items
data.source (function) -> datasource
data.sortOrder -> sortOrder (notify: true)
data.clearCache() -> clearCache()
data.getItem() -> getItem()
```

Keep the old API available, but output a deprecation warning to the browser console that the old API will be removed in the next minor version.

Collateral damage (needs to be done also):
- [x] Update code examples
 - Polymer integration example should be refactored to showcase the Polymer “databindability”
- [x] Update API docs
- [x] Update tests
- [x] Write clear release notes / migration guide about the changes
- [ ] Update JSFiddles
- [x] READMEs
- [ ] Notify marketing to update demos

**Comment by jounik** [comment]
We could still keep the current API working at the same time, but deprecate it.

**Comment by Saulis** [comment]
Heres a first draft for the Polymer integration examples: https://gist.github.com/Saulis/487e5d2c6d7acaf93a6a 

Not sure what you meant by "databindability" :-)

**Comment by jounik** [comment]
Not sure where I should comment, but added one comment in the Gist :)

**Comment by Saulis** [comment]
What shall we do with `data.getItem(rowIndex, callback, onlyCached)` ?

**Comment by Saulis** [comment]
Should something happen when user tries to assign an array to dataSource / function to items? Error?

**Comment by jounik** [comment]
data.getItem() should also be flattened, thanks for the reminder. Added it to the description.

Agreed that we should provide descriptive errors for most of our API, i.e. log a console error if the user assigns an incorrect type to a property.

**Comment by Saulis** [comment]
@jounik Grid already fires `sorted` event when sorting, so thinking if `sortOrder (notify: true)` should be `notify: false` ?

**Comment by jounik** [comment]
@Saulis perhaps so. If we have notify:true, the event name would be `sort-order-changed`, right? Would it be weird to have both?

**Comment by Saulis** [comment]
Yes it would :-)

**Comment by tomivirkki** [comment]
Umm...so we're not supporting 2-way databinding with this property?

**Comment by Saulis** [comment]
Discussed with @tomivirkki, I'm gonna remove the old `sort` event and modify the way how GridComponent and `sortOrder` property interact. It shall be sweet.
