### ISSUE TITLE
treegrid missing after install of vadin-grid

### ISSUE THREAD

**Issue by ray007** [vaadin/vaadin-grid#1602]
### Description
I followed the instructions at https://vaadin.com/components/vaadin-treegrid/install and did
```
npm i @vaadin/vaadin-grid --save
```
### Expected outcome
There should be a file `vaadin-treegrid.js` in `node_modules/@vaadin/vaadin-grid`

### Actual outcome
There is no such file:
```
$ ls -l node_modules/@vaadin/vaadin-grid/
total 24
-rwxrwxrwx 1 root root 10761 Oct 26  1985 LICENSE
-rwxrwxrwx 1 root root  5534 Oct 26  1985 README.md
-rwxrwxrwx 1 root root    38 Oct 26  1985 all-imports.js
-rwxrwxrwx 1 root root  3081 Apr 18 14:07 package.json
drwxrwxrwx 0 root root   512 Apr 18 14:07 src
drwxrwxrwx 0 root root   512 Apr 18 14:07 theme
-rwxrwxrwx 1 root root    51 Oct 26  1985 vaadin-grid-column-group.js
-rwxrwxrwx 1 root root    45 Oct 26  1985 vaadin-grid-column.js
-rwxrwxrwx 1 root root    52 Oct 26  1985 vaadin-grid-filter-column.js
-rwxrwxrwx 1 root root    45 Oct 26  1985 vaadin-grid-filter.js
-rwxrwxrwx 1 root root    55 Oct 26  1985 vaadin-grid-selection-column.js
-rwxrwxrwx 1 root root    50 Oct 26  1985 vaadin-grid-sort-column.js
-rwxrwxrwx 1 root root    45 Oct 26  1985 vaadin-grid-sorter.js
-rwxrwxrwx 1 root root    50 Oct 26  1985 vaadin-grid-tree-column.js
-rwxrwxrwx 1 root root    50 Oct 26  1985 vaadin-grid-tree-toggle.js
-rwxrwxrwx 1 root root    38 Oct 26  1985 vaadin-grid.js
$
```
Not sure why the timestamps are so old, it's a fresh install.

**Comment by tomivirkki** [comment]
The install instructions on that page are unfortunately erroneous as `vaadin-treegrid` doesn't even exist, I'll inform the team to get the instructions updated.

Support for hierarchical data is baked into the `vaadin-grid` Web Component. See https://vaadin.com/components/vaadin-grid/html-examples/grid-tree-demos for examples.

Sorry for the inconvenience
