### ISSUE TITLE
Adding paper check box as an element in table causes it to have 2 check boxes in the grid

### ISSUE THREAD

**Issue by jclx** [vaadin/vaadin-grid#161]
If you take the demo/polymer.html and change the email td  (line 46) from:

``` xml
                    <td>{{item.user.email}}</td>
to:
                    <td><paper-checkbox checked>X</paper-checkbox></td>
```

It will show 2 check boxes and then the label.

This is very strange.

**Comment by tomivirkki** [comment]
I copied full source from the polymer integration example and changed {{item.user.email}} to X http://jsfiddle.net/tLbqtbv7/
Can't see the problem here. Please re-open if the issue remains.

**Comment by jclx** [comment]
My bad the paste of the paper check box html didn't display correctly. But the subject does say paper check box.
Change it to:
```xml
<td><paper-checkbox checked>x</paper-checkbox></td>
```

**Comment by jclx** [comment]
Also I cannot reopen the issue once it is closed.

**Comment by tomivirkki** [comment]
Ah, now I see it. Re-opened the issue.

**Comment by jouni** [comment]
Wontfix. As a workaround, use a JS column renderer function to add paper-checkbox in the cells.

**Comment by jouni** [comment]
Also, the upcoming 2.0 version doesn’t suffer from this issue.
