### ISSUE TITLE
Touch move does not cancel event

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#162]
In examples scrolling makes the all document move

**Comment by jounik** [comment]
I also noticed this yesterday on my iPhone.

**Comment by manolo** [comment]
Could you test last snapshot in your phone?
https://cdn.vaadin.com/vaadin-components/0.3.0-snapshot/vaadin-grid/demo/datasources.html

**Comment by jounik** [comment]
Works okay in the iOS Simulator, but still occasionally fails on my iPhone 5.

Also, if the grid doesn’t need vertical scrolling, it still blocks the page scrolling in that direction, which is problematic I think. It should detect when there is more rows/columns to show, and only block the page scroll in that direction only in that case.

**Comment by manolo** [comment]
Yep, I see, working on a solution on that.

**Comment by manolo** [comment]
review at : https://dev.vaadin.com/review/#/c/12078/

**Comment by manolo** [comment]
Patch 12078 is already merged.
Committed a second patch fixing issues when reaching edges, so as grid behaves like native scrollable panels: https://dev.vaadin.com/review/#/c/12091 
@jounik can you test again in your devices this url: https://cdn.vaadin.com/vaadin-components/0.3.0-snapshot/vaadin-grid/demo/datasources.html ?

Focus on scrolling on small grids, also to reach the edge in big ones, scrolling on headers, and zooming
