### ISSUE TITLE
max-height plus height-by-rows prevents Scrolling

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid#1621]
### Description
The grid shall be displayed inside another component and take as least space as possible. To achieve that, the grid is set to calculate the `height-by-rows` plus a `max-height` of `150px`.

The grid's height is set as huge as possible, but does not exceed the max-height value.

### Expected outcome
 As soon as there are more rows then the grid can display, a vertical scroll bar should appear.

### Actual outcome
The rows are cut off, no scroll bar appears.

### Side node
Setting max-height only without the height-by-rows property works. The scroll bar appears as soon as there are to many rows. Disadvantage is, that the taken space is more than needed.
Using flex-grow: 0 plus max height as an alternative does not work.

### Environment
- Java based Grid usage, Vaadin V14.beta1, grid-flow 3.1-SNAPSHOT
- Windows 10, Chrome Version 74.0.3729.157

**Comment by web-padawan** [comment]
Closing in favor of #1890
