### ISSUE TITLE
Resizable columns where last column is hidden adds unnecessary horizontal space

### ISSUE THREAD

**Issue by brp-oskar** [vaadin/vaadin-grid#1626]
### Description
If columns are resizable and the last column is hidden, there will be extra horizontal space added to the grid header. The unwanted result is that the horizontal scrollbar is displayed.

### Expected outcome
- Horizontal scrollbar should not be visible when there are enough space for each column.
- Hiding column shall update resizable css styles (currently using the attribute `last-column`).

### Steps to reproduce
1. Modify the `vaadin-grid-flow-demo` named ["Manually defining columns"](https://vaadin.com/components/vaadin-grid/java-examples/configuring-columns)
2. Change the checkbox "Toggle visibility of the ID column" to toggle visibility of column "Age", which is the last column.
3. Run the demo and select both checkboxes
4. The horizontal scrollbar appears

![image](https://user-images.githubusercontent.com/7449335/59347164-3df77280-8d14-11e9-899b-92d36ceeb9db.png)

Related issue: #1006

**Comment by werwolfberlin** [comment]
we have that too. it looks like there is some dependency to the --lumo-size/space definition

**Comment by yuriy-fix** [comment]
Dear @brp-oskar , 
Could you please confirm that the issue is still valid.
Cannot reproduce:
![example](https://user-images.githubusercontent.com/29372419/99385784-21347680-28da-11eb-9c87-37defa65c6a9.gif)

**Comment by brp-oskar** [comment]
I can't reproduce it either so it must have been fixed. You may close it.
