### ISSUE TITLE
Renderer functions not running render() inside methods

### ISSUE THREAD

**Issue by jantillonc** [vaadin/vaadin-grid#1640]
Hey guys, I'm creating a custom element using the exact same sample from https://glitch.com/edit/#!/cotton-felidae but I keep getting this error: Uncaught (in promise) TypeError: Cannot set property 'checked' of null ----> root.firstElementChild.checked = this.grid.detailsOpenedItems.indexOf(root.item) > -1;

Any ideas what could be causing this issue? Also, i noticed that the address column, index and checkbox are being rendered as [object Object] instead of the actual int/string/checkbox (seems like my renderers functions are not working as expected?) Any help will be greatly appreciated!

**Comment by web-padawan** [comment]
Looks like this can fix the problem, based on the glitch provided.

```ts
import {LitElement, html} from 'lit-element';
import {render, html as litHtml} from 'lit-html';
```

And then:

```ts
  toggleDetailsRenderer(root, column, rowData) {
    // only render the checkbox once, to avoid re-creating during subsequent calls
    if (!root.firstElementChild) {
      render(
        litHtml`
          <vaadin-checkbox 
            @checked-changed="${e => this._toggleDetails(e.detail.value, root.item)}"
          >
            Show Details
          </vaadin-checkbox>
        `, 
        root
      );
    }
    // store the item to avoid grid virtual scrolling reusing DOM nodes to mess it up
    root.item = rowData.item;
    root.firstElementChild.checked = this.grid.detailsOpenedItems.indexOf(root.item) > -1;
  }
```

See https://glitch.com/edit/#!/nine-whimsical-coast?path=app.js%3A113%3A2

This is probably caused by duplicated versions. Somehow it happens on Glitch.
