### ISSUE TITLE
Avoid using binary gender (male/female) in examples

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1657]
Using binary gender in the examples excludes all users who identify with non-binary gender, and can be considered discriminating.

Examples where we use male/female are in https://github.com/vaadin/vaadin-grid/blob/master/demo/grid-styling-demos.html

**Comment by jouni** [comment]
Closely related: https://github.com/vaadin/flow-and-components-documentation/issues/807

**Comment by Haprog** [comment]
Do you have an idea what would be a good solution? Would it be enough to have some samples where "gender" is shown as "Other"? Or would it be better to just remove all references to gender and (as necessary) come up with some other property instead for the sake of having some sample data?

**Comment by Haprog** [comment]
I just checked what options Facebook gives in your profile for setting "Gender". Nowadays they seem to have options "Male", "Female" and "Custom" and when you select "Custom" there's a text field where you can write whatever you want as the gender (and additionally also select a preferred pronoun from 3 options). That doesn't really help with the case of sample data though.

**Comment by knoobie** [comment]
FYI: In Germany we have a law since last year that we have to support 3 genders. Female, Male and divers. 

Could solve your problem as well?
