### ISSUE TITLE
Grid with frozen columns doesn't scroll on iOS 13

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1660]
Reproducible in the "Freezing column" demo at https://cdn.vaadin.com/vaadin-grid/5.4.6/demo/#grid-columns-demos

**Comment by yuriy-fix** [comment]
The fix is going to get shipped with:
- `vaadin-grid` [v5.5.0-alpha4](https://github.com/vaadin/vaadin-grid/releases/tag/v5.5.0-alpha4)
- `vaadin-grid` [v5.4.9](https://github.com/vaadin/vaadin-grid/releases/tag/v5.4.9)
