### ISSUE TITLE
Flaky test: scrolling-mode.html » scrolling mode » should defer adding scrolling state attributes

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-grid#1666]
`Flaky test: scrolling-mode.html » scrolling mode » should defer adding scrolling state attributes` this test seems to be flaky at least on Safari 13. Even testing locally reloading the test (http://0.0.0.0:3000/components/vaadin-grid/test/?grep=scrolling-mode%5C.html%20scrolling%20mode%20should%20defer%20adding%20scrolling%20state%20attributes) most of the time it fails but occasionally it also passes.

Not sure if this affects other browsers or older Safari.

This affects at least current `master` (5.5 alpha) and `5.4` branch.

This same test seems to be working fine (not flaky) on `5.2` and `5.0` branches, so it has become flaky later.

**Comment by web-padawan** [comment]
The tests have been updated on master and I didn't notice any flakyness for this test in Safari. Closing.
