### ISSUE TITLE
vaadin-grid-sort-column is adding data into empty cells after is sorts 

### ISSUE THREAD

**Issue by BenCoden** [vaadin/vaadin-grid#1669]
### Description
I have a table vaadin-grid, with sort-column, and in a few of these columns are editable. I renderer a text-field or date-picker, and a button to toggle read-only on those row 
Some times my data does not have a  date. 

### Expected outcome
When sorting the cells with no data to show at the top or bottom on the sort, depending on which arrow the user clicked. 

### Actual outcome
It adds seeming random dates to the empty cells 

### Live Demo
https://glitch.com/edit/#!/join/15f49db4-af69-481e-aef3-1806e451d56f

### Steps to reproduce
Sort on any column

### Browsers Affected
- [X ] Chrome
- [ X] IE 11
Other browsers are not used

**Comment by tomivirkki** [comment]
I think it's a matter of invalid binding at `value="${year}-${month}-${day}"`. If you look at the dom with the inspector, you can see that the fields that should be empty, actually have `value="--"`

**Comment by BenCoden** [comment]
Idk I added an If statement around the render() if there is no year, then it shouldn't render anything in the cell. It does as expected until you sort, and then it adds a random date.

**Comment by tomivirkki** [comment]
The date is not random, it's the date from the previous value the date picker instance had. The date picker instances are reused, so as you sort the grid, the date pickers don't change place but are assigned different data. You shouldn't skip the render part but instead make it render a proper (empty) value for an empty date picker.

**Comment by tomivirkki** [comment]
Just to clarify, applied the suggested changes to the glitch example. It should now work as expected (the scan date column): https://glitch.com/edit/#!/faithful-silver

**Comment by BenCoden** [comment]
Awsome thanks @tomivirkki
