### ISSUE TITLE
Skip GWT compilation in CI

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#167]
If the patch contains a test (and it should), it will automatically fail if no pre-compiled module was committed.

**Comment by jounik** [comment]
Compare if OS X and Windows produce the same output for the GWT compilation.

**Comment by manolo** [comment]
https://github.com/vaadin/vaadin-grid/pull/171

**Comment by tomivirkki** [comment]
The current implementation correctly skips gwt compilation if a commit containing java changes has a valid compiled gwt module

...but it's missing an essential part of failing the test if it doesn't. Instead it compiles it in CI and lets an erroneous commit pass.

Here's how it should work (if using hashes):

gulp gwt
- Only run manually by a developer, never by CI
- Always compiles the gwt module (as stated in readme)
- Appends the hash

gulp gwt:verify
- Only run by CI
- Verifies that the hash matches the java code
- Fails the build if the hash doesn't match

**Comment by manolo** [comment]
what about gulp test? should it trigger compilation ?

**Comment by tomivirkki** [comment]
As long as CI never compiles then it doesn't matter.
Personally I don't see a reason to automatically start the compilation in other tasks.
