### ISSUE TITLE
Vaadin-grid with vaadin-grid-tree-toggle does not have a expandAll

### ISSUE THREAD

**Issue by fireplace009** [vaadin/vaadin-grid#1675]
### Description
The `vaadin-grid` element should be able to open a tree structure with all nodes expanded.

### Expected outcome
Show a grid, and display all the nodes and leafs expanded.

### Actual outcome
So, now, seeing this option is not available,
I'm trying to expand all nodes manually after it shows the initial first root parent in the grid.
But this is not really working nicely. (Looks like my recursive javascript code expanding each item does not cleanly render (it's like it's too fast for the rendering to follow)

### Tested Browser

- [x] Chrome

Is there a better way ? 
Kind regards

**Comment by johnthad** [comment]
I am able to accomplish this starting with the top level node in my tree by adding them to the tree's `expandedItems` array: `catalogTree.expandedItems.push(...topItems);` where `catalogTree` is a `vaadin-grid` and `topItems` is an array of the first nodes in my tree. In a quick test, adding more items below the top level will also expand them.

**Comment by web-padawan** [comment]
Closing in favor of #1923 as both issues are now in the same repository (but the other one also mentions `collapseAll`).
