### ISSUE TITLE
Editing "2.0"

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#170]
Allow the end user to edit the cell data.

Options to have either one row, one column or all cells editable at one time.

How the editor is triggered should be configurable by the developer (e.g. start editing by pressing the enter key, by just clicking/focusing a row, long-tapping, etc.)

The commit/discard functionality should also be configurable, whether committing is buffered or not. Grid should really just send events when data is modified in the editor fields, and let the developer do what is needed in his application.

The Framework Grid has features to support these features. We need to design the declarative and imperative APIs for this.

**Comment by jounik** [comment]
I believe this needs a round of UX design, even though the Vaadin Framework has quite a clear vision how it should work.

**Comment by jouni** [comment]
With the upcoming 2.0, editing features can be built with custom templates, and the need for any built-in editing capabilities is reduced.

I’ll close this issue now, but I’m not saying we wouldn’t offer any convenience API for inline editing in the future.
