### ISSUE TITLE
Styling in vaadin grid of one page propagates in other pages.

### ISSUE THREAD

**Issue by Krishuthapa** [vaadin/vaadin-grid#1719]
I am using vaadin grid in LitElement. I have used vaadin grid in multiple pages. I am using dom-module to give styling to the header in vaadin grid like this:
```
 <dom-module id="ligand-grid" theme-for="vaadin-grid">
        <template>
          <style>
            [part~='header-cell'] {
              background: var(--color-grey-100);
            }
          </style>
        </template>
      </dom-module>

```
it works to color the header cells. But this CSS is also propagated in vaadin grids in other pages. How do I prevent it from happening and restrict the CSS change on the particular page only?

**Comment by tomivirkki** [comment]
You can give your grid an id or a class name and make the selector to only target the specific grids.

`<vaadin-grid class="ligand">`

The selector:
```css
:host(.ligand) [part~='header-cell'] {
  background: var(--color-grey-100);
}
```

**Comment by Krishuthapa** [comment]
thankyou @tomivirkki  it worked

**Comment by Krishuthapa** [comment]
@tomivirkki even if this method works.. the css is not applied while changing the view and navigating to the page containing the vaadin grid with this css from other pages. But once the page is refreshed, the css is automatically applied. What might be the reason for it. i am using version `5.5.3`

**Comment by tomivirkki** [comment]
All the style modules must be registered before the component is defined as a custom element. So having the styles added when you open a view is too late in case `vaadin-grid` is already defined somewhere else.

Using [`registerStyles`](https://github.com/vaadin/vaadin-themable-mixin#styling-in-javascript) instead of the Polymer dom-modules is recommended for styling (especially in non-Polymer apps). It also warns in the console in case a style is registered too late.

**Comment by Krishuthapa** [comment]
@tomivirkki  can you please show me how to represent above dom module css in form of registerStyles.

**Comment by tomivirkki** [comment]
```js
import { registerStyles, css } from '@vaadin/vaadin-themable-mixin/register-styles.js';

registerStyles('vaadin-grid', css`
  :host(.ligand) [part~='header-cell'] {
    background: var(--color-grey-100);
  }
`);
```

**Comment by tomivirkki** [comment]
>  I am using polymer for making the app

You mentioned LitElement in the first message so I assumed you're working with Lit, not Polymer

**Comment by Krishuthapa** [comment]
@tomivirkki  thankyou very much.it worked nicely.

**Comment by Krishuthapa** [comment]
@tomivirkki  suppose i have a vaadin grid in page 1 and 2 both. And in both pages i want to color header cell with different color. In that case too, this `registerStyles` would work?

**Comment by tomivirkki** [comment]
Yes, you can style the header cells in the same way with `registerStyles` and by using the same kind of scoping (with class names on the host grid)

**Comment by Krishuthapa** [comment]
I tried that but in doing so , the styling of vaadin grid on page one is removed and works fine when the registerStyles is removed from page 2. I have used different class names for both.

**Comment by tomivirkki** [comment]
Do you see the console warning I mentioned here https://github.com/vaadin/vaadin-grid/issues/1719#issuecomment-620439445

**Comment by Krishuthapa** [comment]
yes there is a warning in the console.

**Comment by tomivirkki** [comment]
So the proper fix is to not have the grid modifications defined in the views. Instead, you should run all the `registerStyles` before grid is imported.

**Comment by Krishuthapa** [comment]
you mean like this?

``` 

import {
  registerStyles,
  css as vaadinCSS
} from '@vaadin/vaadin-themable-mixin/register-styles';

registerStyles(
  'vaadin-grid',
  vaadinCSS` 
  :host(.vaadin-grid-enlarged) [part~='header-cell'] {
        background: var(--color-grey-100);
      }`
);

import '@vaadin/vaadin-grid';
```

**Comment by tomivirkki** [comment]
If that's the only place where you import grid then yes

**Comment by Krishuthapa** [comment]
Nom I have imported grids in the pages wherever I have used it.

**Comment by tomivirkki** [comment]
Like I said earlier, you need to have all your style overrides defined before the grid is imported the first time. You can, for example, move all your `registerStyles` invocations to you application's entry point. There's probably some index file or something. Use that instead of the views. Or to make it cleaner, have a separate file where all the `registerStyles` calls are and then import that file in your index.

**Comment by Krishuthapa** [comment]
yeah, that worked and possibly solved the issue that I had been facing.

**Comment by tomivirkki** [comment]
Great 👍
