### ISSUE TITLE
Changing data source while Grid is hidden results in a zero height Grid

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-grid#172]
If the Grid data source is changed while the component is hidden, it will result in a Grid that is of zero height. Resizing the browser window will cause some recalculation and the Grid becomes visible again.

See the attached gif and example code for details.
https://gist.github.com/tehapo/6b1f06084984ab926384

![out](https://cloud.githubusercontent.com/assets/368220/10016763/002c7a5c-6132-11e5-8a40-f8781f6b9f40.gif)

**Comment by tomivirkki** [comment]
Here's a JSFiddle with a workaround http://jsfiddle.net/56hrwe4s/

**Comment by jounik** [comment]
Make sure that the infamouse “hypnotoad” bug doesn’t reappear.

**Comment by Saulis** [comment]
Some findings we had with @tomivirkki and @cwayfinder:

Adding a `grid.isGridVisible()` check [here](https://github.com/vaadin/vaadin-grid/blob/ef7cbf46219b9011ad0efaee8515731dcaaaa02e/java/src/main/java/com/vaadin/components/grid/GridComponent.java#L472) will resolve the initial issue. However, we noticed that if `<vaadin-grid>` is using a static height, ie `style="height: 300px"` the fix doesn't help.
