### ISSUE TITLE
Vaadin grid columns appear shrinked.

### ISSUE THREAD

**Issue by Krishuthapa** [vaadin/vaadin-grid#1721]
I am using vaadin grid with lit-element. In the local environment, the vaadin grid after rendering recalculates the width and displays the content correctly. But in the production, the columns are shrunk and are not corrected even after the page refresh. The vaadin grid is used to render many custom elements and even canvas and I have 25 columns in it. How can I get solution to this issue? I have used auto-width attribute in the `<vaadin-grid-column>` and renderers to render content and headers.

**Comment by tomivirkki** [comment]
Haven't heard of this issue before. Can you attach an example app with minimal reproduction so we can take a better look?

**Comment by Krishuthapa** [comment]
![image](https://user-images.githubusercontent.com/41799251/80562693-2dbdb400-8a08-11ea-9776-69fa77c7c4bd.png)

it looks something like this although i have used auto-width in the `<vaadin-grid-column>`

**Comment by tomivirkki** [comment]
Do the columns look normal after the grid has received some data or do they remain shrinked like that?

**Comment by Krishuthapa** [comment]
they look shrinked even after the data is filled

**Comment by tomivirkki** [comment]
I see. Can you provide more information on how to reproduce the issue? An example app would help the most.

**Comment by Krishuthapa** [comment]
I cant share the example. But those columns contain the images displayed in canvas and some columns contain custom components and after the content is loaded in the table it remains shrunk in the production. But locally it remains shrank for few seconds and again becomes normal after the data is completely filled.

**Comment by Krishuthapa** [comment]
@tomivirkki  the issue is solved. I had used destructuring in `<vaadin-grid .items=[...this.content]` . After removing the restructuring it worked perfectly. But I am still confused about why destructuring caused such an issue. Can you please help me understand it?

**Comment by tomivirkki** [comment]
@Krishuthapa Glad that the issue got resolved. Not sure what caused the thing with destructuring in this case.
