### ISSUE TITLE
Sometimes ellipsis shown in selection column

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/vaadin-grid#1723]
### Description
The selection column of multiselect Grids sometimes shows ellipsis. Usually happens when the grid is added within a Dialog. I see similarity with previous issue #1523, but it's different.  
Vaadin version 14.1.26

### Expected outcome
No ellipsis shown in Grids selection column next to checkbox

### Actual outcome
When Grid is in a Dialog, the selection column shows an ellipsis

### Code for reproduction
```
@Route(value = "Test")
public class TestView extends VerticalLayout{
    public TestView() {
        TextField dialogWidth = new TextField("enter desired Dialog width, in pixels");
        dialogWidth.setValue("600");
        dialogWidth.setWidthFull();
        add(dialogWidth);

        add(new Button("Open Dialog with Person Grid", click -> {
            Dialog dialog = new Dialog();
            dialog.add(createPersonGrid());
            dialog.setWidth(String.format("%spx", dialogWidth.getValue()));
            dialog.open();
        }));

        Grid<Person> personGrid = createPersonGrid();
        add(personGrid);
    }

    private Grid<Person> createPersonGrid() {
        Grid<Person> personGrid = new Grid<>(Person.class);
        personGrid.setColumns("name", "age");
        personGrid.setSelectionMode(Grid.SelectionMode.MULTI);
        personGrid.setItems(
                new Person("Max", 21),
                new Person("Moritz", 22),
                new Person("Laurel", 23),
                new Person("Hardy", 24)
        );
        return personGrid;
    }

    public class Person {
        private String name;
        private int age;
        public Person(){

        }
        public Person(String name, int age){
            this.name = name;
            this.age = age;
        }
        public String getName() {
            return name;
        }
        public void setName(String name) {
            this.name = name;
        }
        public int getAge() {
            return age;
        }
        public void setAge(int age) {
            this.age = age;
        }
    }
}
```

### Steps to reproduce
1. Add the above TestView to a starter project
2. Open the page in a web browser.
3. Check that the Grid directly added to the view has no Ellipsis in the selection column
4. Click "Open Dialog with Person Grid"
5. Check that the Grid inside the Dialog has Ellipsis in the selection column, close dialog by outsideclick.
6. Repeat steps 4+5 several times, there seems to be no consistency.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge

![grid-selection-ellipsis](https://user-images.githubusercontent.com/13610722/80689498-bbafa280-8acd-11ea-930f-01186c04ea26.gif)

**Comment by tomivirkki** [comment]
I think it's about the selection column width being automatically calculated. The timing for auto-width doesn't probably take the dialog's opening animation into account so the selection column is assigned the effective width it has during the opening animation.

**Comment by KasparScherrer** [comment]
Thanks for the quick response. Your theory sounds probable, especially with the fact that the dialogs width doesn't matter.  One could set the width of the dialog to 1800px and still have this happen.

Do you know a workaround that I could use, until this issue is resolved and the fix released?

Can I also ask whether it makes sense to have auto-width on the selection column, seeing as this column always has the same content? Is the auto-width only there to account for custom stylings that would change the size of the selection combobox? 

And lastly, could this be labelled as `bug`, so I can prioritize it? Thank you

**Comment by tomivirkki** [comment]
>  Is the auto-width only there to account for custom stylings

Yes, this is the reason. With the Material theme, the width of the selection column might be different than what it is with Lumo.

**Comment by tomivirkki** [comment]
>Do you know a workaround that I could use, until this issue is resolved and the fix released?

```java
grid.getElement().executeJS('this.recalculateColumnWidths()');
```
...should work but the timing might be tricky. The dialog's opening animation is [0.25s](https://github.com/vaadin/vaadin-dialog/blob/3f3a613095ba395fa27e35ee658d236e5cff219d/theme/lumo/vaadin-dialog-styles.html#L34) so maybe 300ms timeout does the trick:

```java
grid.getElement().executeJS('setTimeout(function(){ this.recalculateColumnWidths() }, 300)');
```

**Comment by KasparScherrer** [comment]
`Uncaught TypeError: this.recalculateColumnWidths is not a function`  is shown when I tried this with a 300 ms timeout. I also tried a 600 ms timeout, same result.

**Comment by tomivirkki** [comment]
Which Vaadin version is this btw? I can't reproduce the issue on 14.2.0.beta1

![Kapture 2020-04-30 at 13 17 37](https://user-images.githubusercontent.com/1222264/80699648-04268a80-8ae5-11ea-8a9b-7c8fc5e6c9ef.gif)

**Comment by KasparScherrer** [comment]
I am using Vaadin 14.1.26

**Comment by tomivirkki** [comment]
This is strange. I tried with the same exact Vaadin version, Chrome (81) browser both Windows and Mac OS, but can't reproduce the issue.

**Comment by KasparScherrer** [comment]
I have just now tried again with a completely new spring-boot starter from [https://vaadin.com/start/v14](https://vaadin.com/start/v14) (14.1.28) added my Test View and ran the project -> The issue is still there. Using Chrome 81.0.4044.138 on a Windows 10 machine

**Comment by jcgueriaud1** [comment]
I've got the same issue (Grid inside a Dialog). Vaadin 14.1.27 on Chrome 81.0.4044.138  (Mac).

I applied this workaround:
grid.getElement().executeJs("setTimeout( () => $0.recalculateColumnWidths(), 300)");

**Comment by jcgueriaud1** [comment]
I applied a theme for this grid to remove the ... instead of calling the js function:
```
:host([theme~="my-workaround-theme"]) [part~="cell"] ::slotted(vaadin-grid-cell-content) {
    text-overflow: clip;
}
```

**Comment by KasparScherrer** [comment]
I can not use the theme workaround because I like (read: need) the ellipsis in all other columns than this one

**Comment by tomivirkki** [comment]
> I can not use the theme workaround because I like (read: need) the ellipsis in all other columns than this one

You could scope the selector to the first column only with:
```css
:host([theme~="my-workaround-theme"]) [part~="cell"][first-column] ::slotted(vaadin-grid-cell-content) {
    text-overflow: clip;
}
```

If you want to be even more specific about the column, you could use a classNameGenerator

**Comment by jcgueriaud1** [comment]
I'll update my workaround, thank you Tomi.

**Comment by KasparScherrer** [comment]
Thank you Tomi! This one I can use and works perfectly as a workaround.
