### ISSUE TITLE
LitElement|V5.5.2 | Hiding a column on the grid makes all of the row details to be hidden.

### ISSUE THREAD

**Issue by mihajlo-pejcinovski** [vaadin/vaadin-grid#1737]
### Description
1.When a column is hidden using the hidden attribute and if there are any opened
row details on the grid they are becoming hidden also. 
2.Having a hidden columns on the grid also affects the expand/collapse functionality of the 
row details.

### Expected outcome
1.If column is hidden or not opened row details should stay visible on the grid.
2.Row details should expand and collapse without any issues.

### Actual outcome
1.Row details are hidden
2.Clicking on a row doesn't display the details

### Steps to reproduce
1.Implement a vaadin-grid with row details and column hiding (using the hidden attribute) functionality.
2.Open couple of row details and leave them opened.
3. Try to hide at least one column and will make all of the opened row details gone.
4. While one column is opened also try to open any row details that has been closed it wont work.

### Browsers Affected

- [*] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
Hi, @mihajlo-pejcinovski
Confirmed the issue. It's most likely a regression from a recent optimization related to hidden columns, released with version 5.6.0.
