### ISSUE TITLE
Scroll stucks unpredictably in Safari iOS

### ISSUE THREAD

**Issue by vrepetenko** [vaadin/vaadin-grid#1740]
Hi,

vaadin-grid scroll does not work after several clicks (selection) on grid rows in iOS Safari. 
It works fine in Safari Development Mode (Responsive Design Mode) on macOS.

### Steps to reproduce
unzip and run sample project:
[grid-test.zip](https://github.com/vaadin/vaadin-grid/files/4689231/grid-test.zip)

open test page in Safari iOS,
scroll to the bottom, select row, scroll up/down, select next row ...
after several times scroll will stuck.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [x] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
Can't reproduce after https://github.com/vaadin/vaadin-grid/pull/1791 so assumed to be fixed
