### ISSUE TITLE
Regression: auto-width now causing lots of ellipsis

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-grid#1749]
### Description
I'm now seeing lots of ellipsis because of https://github.com/vaadin/vaadin-grid/pull/1745. Oddly enough, not on Safari though.

Columns defined as:
```
<vaadin-grid-sort-column path="rxNo" header="Rx" auto-width flex-grow="0"></vaadin-grid-sort-column>
<vaadin-grid-sort-column path="dispenseDate" header="Fill Date" direction="desc" auto-width flex-grow="0"></vaadin-grid-sort-column>
```

### Browsers Affected

- [X] Chrome 83
- [X] Firefox 77
- [ ] Safari
- [X] Edge 83
<img width="208" alt="chrome" src="https://user-images.githubusercontent.com/1920405/83805184-04cab780-a675-11ea-9e3a-039be0a36ad1.png">
<img width="220" alt="firefox" src="https://user-images.githubusercontent.com/1920405/83805187-05634e00-a675-11ea-9251-47f94905e5a0.png">

**Comment by moderndeveloperllc** [comment]
I did a bit of checking, and sure enough, `Math.ceil(c.getBoundingClientRect().width)` can give a result that is 1 more than `c.offsetWidth`. I did a quick console.log to see the differences:
```
    cols.forEach(col => {
      col._currentWidth = 0;
      col._boundingWidth = 0;
      // Note: _allCells only contains cells which are currently rendered in DOM
      col._allCells.forEach(c => {
        col._currentWidth = Math.max(col._currentWidth, c.offsetWidth);
        col._boundingWidth = Math.max(col._boundingWidth, Math.ceil(c.getBoundingClientRect().width));
      });
    });
    // [write] Set column widths to fit widest measured content
    cols.forEach(col => {
      col.width = `${col._currentWidth}px`;
      col.flexGrow = col._origFlexGrow;
      col._currentWidth = undefined;
      col._origFlexGrow = undefined;
      console.log(col.width);
      console.log(col._boundingWidth);
    });
```

Of my six columns (all `auto-width`), four had boundingWidths that were 1 more than the offsetWidth

**Comment by tomivirkki** [comment]
Hmm..that's strange. I tried switching `auto-width` on in all the columns in all the grid demos but didn't notice any difference compared to the previous version (some columns still had ellipsis with both versions). Any more details on how this regression could be reproduced?

Adding 1px buffer to the offset widths actually does help eliminate the ellipsis in some of the demos (not a regression, occurs with both versions). Can you check if changing `offsetWidth` to `offsetWidth + 1` [here](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid.html#L487) helps in your case.

**Comment by moderndeveloperllc** [comment]
@tomivirkki I think we were typing at the same time. The `+ 1` does help the issue. Of note may be that I have `flex-grow="0"` on these columns where it looks like the demo grids aren't constrained that way.

**Comment by tomivirkki** [comment]
Alrite, thanks for the report, made the draft PR. Will probably unblock it tomorrow. But I still haven't been able to repro the issue. Even with a 6-column grid and `flex-grow="0"` on each column. Wondering if it's about numeric content?
