### ISSUE TITLE
Properties from DataProviderMixin are not suggested in Visual Studio Code

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/vaadin-grid#1775]
When I add some properties to the vaadin-grid, the properties which are coming from DataProviderMixin are not suggested:
- DataProvider, pageSize, ...
It's working for other properties like size which is coming from GridScrollerElement

![vs_suggesstions](https://user-images.githubusercontent.com/51313578/87538534-0a201680-c6a5-11ea-9570-ea8d03c245de.png)

**Comment by web-padawan** [comment]
This appears to be an issue which was fixed by `lit-plugin` 1.2.0 version released tonight:

![grid-autocomplete](https://user-images.githubusercontent.com/10589913/87671759-8d5f6c00-c77a-11ea-8646-1f38e87cf91c.png)

Closing as won't fix.
