### ISSUE TITLE
Vaadin-Grid not scrolling in iOS 14

### ISSUE THREAD

**Issue by mvniemi** [vaadin/vaadin-grid#1786]
### Description
Vaadin Grid does not scroll in iOS 14

The grid element is "dead" to touch input, and does not scroll or pan at all.

### Steps to reproduce

Reproducible on the Live Demo page: https://cdn.vaadin.com/vaadin-grid/5.7.0/demo/#grid-basic-demos
It's occurring on both hardware (iphone X and ipad pro) running the iOS 14 Public Beta 5, and in iOS 14 simulator in xcode

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [X] iOS Safari
- [ ] Android Chrome

**Comment by mvniemi** [comment]
Still not working in iOS 14 Public Beta 6

**Comment by tomivirkki** [comment]
Thanks for the heads-up. Labeled as a blocker (will be fixed right away). This will however not block the release of V17 GA (due to iOS 14 not being stable yet).

**Comment by manolo** [comment]
Since actually it does not block platform release, probably it should be re-labeled as major

**Comment by mvniemi** [comment]
iOS 14 has been released, need this fix ASAP

**Comment by tomivirkki** [comment]
Released in [5.7.2](https://github.com/vaadin/vaadin-grid/releases/tag/v5.7.2)

**Comment by janarbis** [comment]
Hello there,

will this be part of the 14.3.7 release?

Best Jan

**Comment by tomivirkki** [comment]
Hi @janarbis, we're doing some internal testing right now, and soon after that backport the fix to Vaadin 14

**Comment by janarbis** [comment]
Hello @tomivirkki, thank you, is a workaround available until then?

**Comment by tomivirkki** [comment]
As a workaround (until the new versions have been integrated to be shipped with Vaadin):

## Vaadin 17 projects:
Update vaadin-grid version in package.json to 5.7.2:
```
"@vaadin/vaadin-grid": "5.7.2",
```


## Vaadin 16.3.X projects:
Update vaadin-grid version in package.json to 5.6.8:
```
"@vaadin/vaadin-grid": "5.6.8",
```

You can verify the grid version by running the following in the browser's console:
```js
customElements.get('vaadin-grid').version
```

**Comment by janarbis** [comment]
Hi @tomivirkki , it works, you saved my day! Thank you!

**Comment by fdieguez** [comment]
hi @tomivirkki. 
I change the version but it does not take the change. I work with vaadin 14.3.4
Then reappears again
"@ vaadin / vaadin-grid": "5.6.7"
it didn't work for me :(
