### ISSUE TITLE
Cannot access 'ActiveItemMixin'

### ISSUE THREAD

**Issue by Krishmanl** [vaadin/vaadin-grid#1787]
### Description
Couldn't load vaadin-grid in polymer3.

### Expected outcome
Display the vaadin-grid view

### Actual outcome
"Uncaught ReferenceError: Cannot access 'ActiveItemMixin' before initialization"

### Steps to reproduce
1. Add vaadin-grid in package.json.
2. Then do import '@vaadin/vaadin-grid/vaadin-grid.js';
3. Open the page in a web browser.

**Comment by Krishuthapa** [comment]
Even I have been facing the same issue. Can anyone help to solve it?

**Comment by Krishuthapa** [comment]
@tomivirkki  can you please help to solve the issue?

**Comment by tomivirkki** [comment]
Here's a working example project running Polymer 3 version of vaadin-grid: https://glitch.com/edit/#!/separated-comet

**Comment by web-padawan** [comment]
Please check that you don't have any duplicate versions, e.g. `npm ls | grep @vaadin/vaadin-grid`

**Comment by Krishmanl** [comment]
I built a polymer-3-starter-kit sample project according to the documentation. Documentation link below:
https://polymer-library.polymer-project.org/3.0/docs/apps/build-for-production

**Actual outcome**
   "Uncaught ReferenceError: Cannot access 'ActiveItemMixin' before initialization"

**Steps to reproduce**
   1) npm install -g polymer-cli
   2) mkdir my-app
   3) cd my-app
   4) polymer init polymer-3-starter-kit
   5) Add "@vaadin/vaadin-grid": "^5.7.0" in package.json.
   6) Do "import '@vaadin/vaadin-grid/vaadin-grid.js" in view1.js.
   7) polymer build
   8) polymer serve build/default

My changes below:
   package.json
        "dependencies": {
               ....
               "@vaadin/vaadin-grid": "^5.7.0",
               ...
        },

    src/view1.js module.
         ...
         import '@vaadin/vaadin-grid/vaadin-grid.js';
         ....

**Comment by tomivirkki** [comment]
Thanks for the example. Was able to repro. It's most likely a regression from https://github.com/vaadin/vaadin-grid/commit/9b0c8e700fa0269e18efb6f5c0f764f9ce1e7f5d

I expect this to get fixed by https://github.com/vaadin/vaadin-grid/pull/1789

**Comment by tomivirkki** [comment]
Tested the example with [5.7.1](https://github.com/vaadin/vaadin-grid/releases/tag/v5.7.1) and it's ok now
