### ISSUE TITLE
Recalculate column width on scrolling the grid.

### ISSUE THREAD

**Issue by NadeemShakya** [vaadin/vaadin-grid#1794]
### Description

I am currently using Vaadin Grid with **LitElement**.

In my scenario, I have a long grid(with lots and lots of rows). Certain rows at the bottom of the grid have a very long cell column. To avoid ellipsis on the long cell columns, I've applied `auto-width` props to the `vaadin-grid-column`. 

I am using renderer methods to render the header and body of the columns. For example: 
```
    <vaadin-grid
         .items="${this.data}"
          height-by-rows
          theme="wrap-cell-content column-borders"
        >
         <vaadin-grid-column
            frozen
            auto-width
            .headerRenderer="${this.renderHeader}"
            .renderer="${this.renderBody}"
          >
          </vaadin-grid-column>
    </vaadin-grid>

```
### Expected outcome

All the rows (including the rows at the bottom of the grid) with long cell columns should be rendered without an ellipsis.

![image](https://user-images.githubusercontent.com/32034842/93082529-cbacd500-f6b0-11ea-95f8-3ab19caa0bcd.png)

### Actual outcome

The rows at the bottom of the grid(which are visible only after scrolling down the grid) are rendered with an ellipsis.

![image](https://user-images.githubusercontent.com/32034842/93082455-b172f700-f6b0-11ea-9abd-9edf048ffe73.png)

### Browsers Affected

- [x] Chrome
- [x] Firefox

### Note

I've read from the documentation that:

```
For performance reasons, the column width is calculated automatically only once when the grid items are rendered for the first time and the calculation only considers the rows which are currently rendered in DOM (a bit more than what is currently visible). If the grid is scrolled, or the cell content changes, the column width might not match the contents anymore.
```
**_I was thinking about recalculating the column widths on scrolling the grid, but can't find any way to do so. How can I resolve this issue?_**

@tomivirkki @web-padawan

**Comment by tomivirkki** [comment]
This will probably not get added as a feature, but you can still listen to scroll events and add your own logic with something like `grid.$.table.addEventListener('scroll', grid.recalculateColumnWidths())`
