### ISSUE TITLE
right click context menu does not always work in vaadin-grid

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-grid#1804]
I am using vaadin-grid(version 5.2.0) in my project. In the grid, there is a column as follows

    <vaadin-grid-column>
        <template is="dom-if" if="{{SOME_BOOLEAN_CONDITION}}">
            <div on-dblclick="dbClickHandler" style="white-space:normal;text-align:center" title="TEST" data-index$="[[index]]">
                TEST DATA 1729
            </div>
        </template>
    </vaadin-grid-column>

The grid is equipped with vaadin-context menu(version 4.0.1). The problem that I am facing is that the right click must be exactly over the text in order for any event handler to be excecute. In my case the text is not filling the entire cell area, so if my right click position is not precise, then no action is fired. 

The context menu action handler is being passed a `MouseEvent` object from which I am extracting the `index` of the current row using `event.target.content.dataset.index`. This does not reurn anything if my right click is imprecise. Can someone please help regaring this.

Thanks

**Comment by web-padawan** [comment]
Thanks for the issue. Please consider using `grid.getEventContext()` API which is a proper way of handling listeners:

```js
grid.addEventListener('dblclick', function(e) {
  const index = grid.getEventContext(e).index;
  // check for conditions and do what you need
});
```

See full example here: https://cdn.vaadin.com/vaadin-grid/5.7.4/demo/#grid-event-context-demos
