### ISSUE TITLE
Grid configuration should be exportable to some GridConfig object to be re-used in a new session

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-grid#1807]
Expected:
all the subtleties of run-time UI-scoped state in the order of columns, the widths of those columns, sort orders et cetera, should be exportable, e.g. using

`Grid.GridConfiguration getConfig()`

where `Grid.GridConfiguration implements Serializable` or is otherwise somehow storable to persistent storage and where the Grid's configuration can be restored from, say using some

`restoreConfig(Grid.GridConfiguration config) throws Grid.ConfigNotApplicableException`

or such.

**Comment by tomivirkki** [comment]
This sounds more like application logic than a grid feature.

**Comment by enver-haase** [comment]
Can I disagree and escalate to PO? One of 'my' customers told me he'd expect that in a component.
Plus, we want to make the Grid more feature-rich if I understand the plans correctly.
This is a wish that is a new feature but certainly belongs in a component, otherwise the same behaviour would have to be reimplemented in a great number of applications.
