### ISSUE TITLE
Column reordering

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#181]
Add the Grid.java feature of column drag-and-drop reordering from Vaadin 7.5.

The `grid.columns` array should be reordered at the same time. The Grid sends a "reorder" event on the client-side (according to @wolfie).

![](https://trello-attachments.s3.amazonaws.com/5587f59b12cc8c6f2bbe897a/540x636/f162381ad25533c36420899cecacde70/v-grid--04-column-operators--move.png)

**Comment by jstanley1730** [comment]
This would be a great feature to have, we are replacing our datatables web component with the vaadin grid component and only thing keeping us from deprecating the datatables component is the requirement to have drag column reordering.  Is there a timeframe for this feature to be available?

**Comment by jounik** [comment]
Hi! No exact timeframe unfortunately. It is high on the priority list, but we are currently working on adding some more elements to the vaadin-core-elements bundle before we give more focus again to the grid.

**Comment by jouni** [comment]
Implemented in #394. Thanks to @djbowman1.

I’ll make some small style updates before we ship this, so that it resembles the design more closely.

**Comment by jouni** [comment]
Official documentation (asciidocs which will be deployed to vaadin.com/docs) is also missing.

**Comment by jouni** [comment]
We are about to start the beta period for the 2.0 version. Currently we have this feature (column reordering) implemented so that it only works on desktop devices (anything that supports native HTML5 drag'n'drop), but we plan to improve that so that it also works on touch devices.

Question to @djbowman1: if you would consider upgrading to 2.0, would you need to have column reordering on touch devices as well (namely Android and iOS), or would it be enough for your users to have that feature on desktop only?

We are thinking if we should hold back the feature completely before we have it working for touch devices as well.

**Comment by djbowman1** [comment]
I think that the domains that we develop for only have requirements for
desktop(specifically IE, chrome, and firefox) however a few of those are
nearing deployment I believe and I think we are going to hold off on
switching to 2.0 for awhile.

**Comment by jouni** [comment]
Alright, thanks a lot for the answer!
