### ISSUE TITLE
Customizable selection model

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#182]
The developer should be able to override the default index based selection model with a custom one, e.g. based on some ids in the database.

Consider the properties and attributes (for Polymer databinding) API when designing the selection models, perhaps flattening some of them to the top level of the grid object:

``` javascript
selection.mode -> selectionMode (notify: true)
selection.size -> selectionSize (notify: true)
selection.select() -> selectIndex()
selection.deselect() -> deselectIndex()
selection.selected() -> selectedIndexes()
selection.deselected() -> deselectedIndexes()
selection.selectAll() -> selectAll()
selection.clear -> deselectAll()
```

**Comment by jounik** [comment]
Consider #185 when designing this.

**Comment by jouni** [comment]
Invalid. The upcoming 2.0 has a much more flexible selection model.
