### ISSUE TITLE
Treegrid doesn't maintain states when using Tabs

### ISSUE THREAD

**Issue by alankaragarwal** [vaadin/vaadin-grid#1820]
I'm using 2 Tab and each Tab has one TreeGrid under it.
Code toggle TreeGrid when switching between Tabs using addSelectedChangeListener.

State of TreeGrid is being lost when switching tabs.
Fow example, if i extend a tree or scroll down in treegrid - these operations are resetted when i switch tabs
Attaching a sample project to replicate the issue
[my-starter-project.zip](https://github.com/vaadin/vaadin-grid-flow/files/5064827/my-starter-project.zip)

**Comment by tulioag** [comment]
Depends on https://github.com/vaadin/flow/issues/9175

**Comment by TatuLund** [comment]
I think this is related to https://github.com/vaadin/vaadin-grid/issues/1960 as well.

**Comment by tulioag** [comment]
Issue vaadin/flow#9175 is now fixed.  PR vaadin/vaadin-flow-components#228 might be unnecessary.

**Comment by tulioag** [comment]
Fixed by https://github.com/vaadin/vaadin-flow-components/pull/363
