### ISSUE TITLE
Right Click on grid inside ContextMenu, closing the ContextMenu

### ISSUE THREAD

**Issue by guygoldwasser** [vaadin/vaadin-grid#1827]
B"H
same to this https://github.com/vaadin/vaadin-date-picker-flow/issues/250
just with Grid.
while using ContextMenu with components inside, some events makes the ContextMenu to get closed

**Comment by tomivirkki** [comment]
Closing as inactive, especially if it's about the same as https://github.com/vaadin/vaadin-date-picker-flow/issues/250
