### ISSUE TITLE
GridViewIT.gridColumnApiTests fails for 14.3

### ISSUE THREAD

**Issue by mshabarov** [vaadin/vaadin-grid#1839]
GridViewIT.gridColumnApiTests has been failing since 20.05.2020:

GridViewIT.gridColumnApiTests:374 expected:<4> but was:<3>
 
https://bender.vaadin.com/viewLog.html?buildId=150462&buildTypeId=Flow_Components_ComponentSnapshots143_Grid

**Comment by web-padawan** [comment]
Closing as the tests are now run in the monorepo and there we have an improved setup which re-runs flaky tests.
Let's open a new issue where if this test appears to be flaky there as well.
