### ISSUE TITLE
Methods to allow manually setting certain rows of a grid to be unable to select

### ISSUE THREAD

**Issue by t0920008899** [vaadin/vaadin-grid#1840]
in some scenario, we might need to manually set rows, which meet certain conditions, to be unable to get selected.

**Comment by TatuLund** [comment]
Probably a duplicate of https://github.com/vaadin/vaadin-grid/issues/1180

**Comment by web-padawan** [comment]
Thanks, this is indeed a duplicate of #1180. Closing.
