### ISSUE TITLE
Column headers with components lose their sorting indicators with multiple header rows

### ISSUE THREAD

**Issue by mlindfors** [vaadin/vaadin-grid#1841]
Let's take an example view such as this:

```
public class MainView extends VerticalLayout {

	public static class Person {
		private String name;
		private String age;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getAge() {
			return age;
		}

		public void setAge(String age) {
			this.age = age;
		}
	}

	public MainView() {
		Grid<Person> grid = new Grid<>();
		grid.appendHeaderRow();
		grid.addColumn(row -> row.getName())
		.setHeader(new Span("Name"))
		.setFlexGrow(2)
		.setSortable(true);
		grid.addColumn(row -> row.getAge())
		.setHeader("Age")
		.setFlexGrow(2)
		.setSortable(true);

		grid.appendHeaderRow(); //causes the sorting indicators to disappear for the `Name` header

		ListDataProvider<Person> provider = DataProvider.ofCollection(new ArrayList<>());
		grid.setDataProvider(provider);
		for (int i = 0; i < 100; i++) {
			final Person person = new Person();
			person.setName("foo " + i);
			person.setAge("bar " + i);
			provider.getItems().add(person);
		}

		add(grid);
	}
}
```

With this the first column, which has a Span as the header, loses the sorting indicators, so the user can't sort the contents. The second column, which has just a String in the header, works fine. The first column still returns true when checked with isSortable, though.

If the second `grid.appendHeaderRow()` is moved right below the first call to appendHeaderRow and before the addColumn calls, all the columns work properly.

Observed behaviour: when doing things in certain order, column headers with components in them basically lose their sorting ability.
Expected behaviour: columns should retain their sorting capability regardless of the order of operations.

**Comment by Gubancs** [comment]
I'm having the exact same issue, any possible workaround exists?

**Comment by garaei** [comment]
Please fix the issue we need it urgently. 
Today I try to center align the individual cell in the header of the grid but no success..

Tried this but no effect:
`gridProduct.getColumnByKey("cnk").getElement().getStyle().set("text-align", "center").set("border", "1px solid green");`

Tried via .css but also no effect

`:host(.product-grid-header-center) [part="row"] [part~="header-cell"] ::slotted(vaadin-grid-cell-content) {
    text-align: center;
}`

Please fix the issue we need it urgently.

**Comment by web-padawan** [comment]
@garaei The fix was already merged and will be included to the next Vaadin maintenance release.
