### ISSUE TITLE
Grid pollutes window.vaadin

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#189]
window.vaadin is used by Vaadin 7, which relies on nobody else touching it. Grid seems to pollute this with some own method, which you can see by opening e.g. https://cdn.vaadin.com/vaadin-components/latest/vaadin-grid/demo/columns.html and looking at ```window.vaadin``` in the console

**Comment by jounik** [comment]
We could rename the namespace to `window._vaadin`. Would that be okay for @Artur-?

**Comment by manolo** [comment]
Couldn't we share window.vaadin for everything produced by vaadin? we could move jsinterop namespace to $wnd.vaadin.components for instance.
Otherwise we can use $wnd.vaadin-components instead which is more meaningful rather than _vaddin

**Comment by jojule** [comment]
window.vaadin should definitely be shared between all Vaadin products. window.vaadin.components sounds logical. we should eventually (in version 8?) move framework specific stuff to window.vaadin.framework

**Comment by manolo** [comment]
Moved namespace to vaadin.components.

**Comment by jounik** [comment]
How about `window.vaadin.grid`? Would be more explicit about what it relates to. Also, instead of having `window.vaadin.components.GridComponent()` we could have `window.vaadin.grid._constructor()`, which would be more clear that it’s some internal details rather than some public API.

**Comment by tomivirkki** [comment]
There's also some unneeded stuff under the namespace. Currently alongside "GridComponent" there's "GridCommit", "GridDataSource", "GridStaticSection" and "MAX_AUTO_ROWS". None of those are needed.

**Comment by jounik** [comment]
Good catch, thanks! `MAX_AUTO_ROWS` sounds like something which should be a public property that the developer can control. We have the feature in the backlog at least (#183, first checklist item). But as said, it should not be in the global namespace.

**Comment by manolo** [comment]
> How about window.vaadin.grid?
I'd rather have in the namespace 'components'. @jounik Does vaadin.components.grid work for you?

> there's "GridCommit", "GridDataSource", "GridStaticSection"
We use these objects in JS, so we need to export them and we must give them a namespace, I think vaadin.components.grid could be ok, @tomivirkki  does it work for you?

> MAX_AUTO_ROWS
I think it's not used in JS, since it's public it's exported by default, we should mark it as no exportable.

> MAX_AUTO_ROWS sounds like something which should be a public property

**Comment by jounik** [comment]
`vaadin.components.grid`is okay for me.

Should we consider renaming the other stuff under the namespace later, or would you want to do it now at the same time? Something to indicate that it’s private API.

And MAX_AUTO_ROWS, yes, let’s not export it now, and discuss it separately in #183.

**Comment by tomivirkki** [comment]
About the "GridCommit", "GridDataSource", "GridStaticSection", is it possible just to export the apis and not the classes? We get references to to objects elsewhere so we only need the apis exported.

**Comment by manolo** [comment]
@tomivirkki added a hack to remove all those objects from the namespace so as we don't expose those.
