### ISSUE TITLE
Reduce JS size

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#190]
270KB feels quite large for a grid component. Looking at the compile report, it seems that GQuery contributes to close to 50KB. Should be considered if it can be removed to reduce JS size.

**Comment by tomivirkki** [comment]
Experimented with this yesterday. Resulted in a working prototype (vaadin-grid without GQuery) whose size is roughly 70 KB smaller than that of the current master version.

**Comment by jounik** [comment]
Great to hear, that’s a whole lot less to download!

**Comment by tehapo** [comment]
Nice! :clap: :+1:

**Comment by tomivirkki** [comment]
Here's the experimental branch for this https://github.com/vaadin/vaadin-grid/tree/without-gq Still some issues remaining, especially with the test suite

**Comment by jouni** [comment]
Wontfix
