### ISSUE TITLE
Can't remove child items from TreeGrid by resetting data provider

### ISSUE THREAD

**Issue by robert-lee-hisl** [vaadin/vaadin-grid#1916]
Using Vaadin version 14.0.10, I can't remove child items with TreeGrid.

This is not a simple case of the number of rows being miscalculated.

The following code shows the problem; when I click the "click to break" button, an item is correctly removed from the tree; however, I can't then see the last item on the grid.

The bottom line (the third "D") shows a chevron to indicate that there are child items, but the child item does not show.

If I collapse the "E", then the final line shows as expected. But then if I try to expand "E" again, its child does not show until the second "D" is collapsed again.

A different behaviour occurs if you collapse "A" instead of "E"; the bottom line shows as expected when "A" is collapsed, but then remains showing when "A" is expanded again.

This may be related to vaadin/vaadin-grid-flow#792; because of that issue I can't use refreshAll() to update the data, but setting a new DataProvider does not work as a workaround.

```
 @Route(value = "treegrid")
 public class TreeGridView extends TreeGrid<TreeGridView.VO> {

    Button btnRemove = new Button("Click to break");

    public TreeGridView() {

        addHierarchyColumn(VO::getText)
                .setSortable(false)
                .setHeader(btnRemove);

        List<VO> data = asList(
                new VO("A", new VO("B", new VO("C"))),
                new VO("D"),
                new VO("E", new VO("B")),
                new VO("D"),
                new VO("D", new VO("This should still show!"))
        );
        setItems(data.stream(), vo -> vo.children.stream());
        expandRecursively(data.stream(), 5);

        btnRemove.addClickListener(e -> {
            data.get(0).children.get(0).children.clear();
  //            getDataProvider().refreshAll(); // doesn't work; only affects root items, presumably due to vaadin-grid-flow#792
            setItems(data.stream(), vo -> vo.children.stream());
            expandRecursively(data.stream(), 5);
        });

    }

    static class VO {
        String text;
        List<VO> children;

        VO(String text, VO... children) {
            this.text = text;
            this.children = new ArrayList<>(asList(children));
        }

        String getText() {
            return text;
        }
    }
 }
```

**Comment by yuriy-fix** [comment]
Dear @robert-lee-hisl , 

I have tried to reproduce the issue with latest supported 14 versions and on `master`. The issue seems to be fixed.
The referenced issue is also fixed and closed.

![fixed](https://user-images.githubusercontent.com/29372419/109285206-73662b80-7829-11eb-88d9-668b298de92a.gif)

Please re-open if you are still facing problems.
