### ISSUE TITLE
vaadin-grid not working on iOS (PhoneGap)

### ISSUE THREAD

**Issue by fadfood** [vaadin/vaadin-grid#192]
vaadin-grid is working great with IE, Chrome, Firefox. But when deployed through a phonegap application on iOS device or simulator, the grid is not showing. When the same app deployed on Android it is working fine.

Actually the grid and the data is there after I inspected the elements but it seems the css not loaded properly on iOS.

**Comment by jounik** [comment]
Thanks for the report! What exact PhoneGap and iOS versions are you using?

**Comment by fadfood** [comment]
PhoneGap 2.9.0 and on both iOS 8 AND 9.

**Comment by fadfood** [comment]
Please find a sample screenshot on iOS. Same code works fine everywhere (Android, Chrome, IE, FF)

![fullsizerender](https://cloud.githubusercontent.com/assets/14107343/10301714/d2a87c5c-6c0d-11e5-8672-ad5cf3b9b5d3.jpg)

**Comment by Saulis** [comment]
Hi there!

Is this still an issue with the latest version of `<vaadin-grid>` ? If so, could you provide us with an example app we could use to debug the issue.

Thanks!

**Comment by jouni** [comment]
Please try with the new 2.0 version, and report if you have problems in PhoneGap with it. I’m closing this issue for now.
