### ISSUE TITLE
addHierarchyColumn should allow to make the value not part of the toggle

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid#1955]
Currently, when adding a hierarchy column to a tree grid, the value (e.g. node name) is automatically part of the toggle. This overrides other events, like selection, which might be a bit intransparent for users, when clicking on a node name (or makes it even useless, when the tree only has the hierarchy column).

The addHierarchyColumn API should be extended by a boolean parameter `valueToggles` (or similar). When true, the current behavior is used. When false, the value will not be part of the toggle.

Template with parameter `true`
```
"<vaadin-grid-tree-toggle leaf='[[item.leaf]]' expanded='{{expanded}}' level='[[level]]'>[[item.name]]</vaadin-grid-tree-toggle>"
```

Template with parameter `false`
```
"<vaadin-grid-tree-toggle leaf='[[item.leaf]]' expanded='{{expanded}}' level='[[level]]'></vaadin-grid-tree-toggle> [[item.name]]"
```

**Comment by web-padawan** [comment]
Closing as duplicate of #1806
