### ISSUE TITLE
Expansion state is lost when reattaching TreeGrid

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid#1960]
The TreeGrid loses it's nodes' expansion states (i.e. everything up to the root is collapsed), when being reattached. 

Use case where this has an impact on the user experience:
A view with a tree, that is annotated as UIScoped in a CDI context (e.g. Spring). The user works in the tree, expands several nodes and switches the page (for whatever reason). When coming back, the previously instantiated view instance is reused and attached. Other states (selection for instance) are restored, the expansion states are not. The user has now to reopen all nodes as needed.

Request is, that the tree should keep it's expansion states to be reusable when reattached.

**Comment by web-padawan** [comment]
Should be fixed by vaadin/vaadin-flow-components#363. See also #1820 where the fix was discussed.
