### ISSUE TITLE
Add cell class name generator for header and footer rows

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-grid#1965]
Grid web-component issue here https://github.com/vaadin/vaadin-grid/issues/1623

### Description

A cell class name generator was added to the web component here https://github.com/vaadin/vaadin-grid/issues/1297 and the Flow Grid implementation is here https://github.com/vaadin/vaadin-grid-flow/issues/185

However, it does not allow generating classes for header or footer rows. In the issue, it is mentioned that this can be achieved by wrapping the contents of these cells in an element with the desired class name. This has at least two issues:

With this approach, it's impossible to target the cell itself, e.g. for setting background color
Styles for normal cells need to be in a <dom-module>, while other styles need to be in a <custom-style>
The solution could either be to set a separate generator for header and footer cells, or for the current implementation to also affect header and footer cells. The cells can still be targeted individually with [part~="header-cell"].

**Comment by tarekoraby** [comment]
> As a (really hacky) workaround you could try something like:
> 
> ```java
> grid.getElement().executeJs(
>                 "requestAnimationFrame(() => Array.from(this.$.header.children)"
>                         + ".forEach((row, index) => row.classList.add('custom-' + index)))");
> ```
> 
> This would add class names "custom-{rowindex}" to the `<tr part="row">` elements in the header (assuming they're available on `requestAnimationFrame`).


This workaround requires a small adjustment to work in later versions ( I tried it on 14.4.0. Perhaps due to some recent changes in the Grid's internal structure?)

```
grid.getElement().executeJs("requestAnimationFrame(() => Array.from(this.$.header.children[0].children)"
                        + ".forEach((row, index) => row.classList.add('custom-' + index)))");
```

**Comment by web-padawan** [comment]
Closing in favor of #1623 as both issues are now in the same repository.
