### ISSUE TITLE
ComponentRender not rendering buttons in simple grid.

### ISSUE THREAD

**Issue by bsutton** [vaadin/vaadin-grid#1976]
I've attached a minimal working demo of the problem.

Essentially the component render is failing to render a button.

The sample shows both a native button and a vaadin button.

The native button renders but the label is missing.
The vaadin button doesn't render at all.

I'm using vaadin 13.0.3.

Sample gradle project
[testgrid.zip](https://github.com/vaadin/vaadin-grid-flow/files/3056898/testgrid.zip)

Here is how the page renders.
![image](https://user-images.githubusercontent.com/900408/55768962-4c31d400-5ac2-11e9-890a-d65ca83f982f.png)

You can see here that the 'slot' in the DOM is actually empty for the vaadin-button and whilst the native button <button> is rendered its content is empty hence no lable.

![image](https://user-images.githubusercontent.com/900408/55769052-a0d54f00-5ac2-11e9-9c43-7be4aa4f5ff7.png)

**Comment by web-padawan** [comment]
The bug linked in the above comment https://github.com/vaadin/vaadin-grid/issues/1976#issuecomment-517692654 was fixed by https://github.com/vaadin/flow/pull/6144 so I'm closing this issue.
Please submit a new issue if you still experience this problem with Vaadin 14.x LTS or newer versions.
