### ISSUE TITLE
Grid sends a request for zero elements when starting up

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#198]
If using the function data source, the first call is for index=0 count=0, which seems odd and leads to difficult error checking code in server code. Is there a reason for this? I suggest removing this call.

**Comment by jounik** [comment]
This seems to originate from GridJsFuncDataSource.java#27 (`requestRows(0, 0, null);`)

**Comment by jouni** [comment]
Wontfix
