### ISSUE TITLE
Grid performance

### ISSUE THREAD

**Issue by Ramonrune** [vaadin/vaadin-grid#2003]
I have a grid with lazy loader, that show about 5000 elements, with pagination of 1000 elements per page.
This grid have 17 columns, and 9 columns have custom renderers.

In chrome performance test, it took me 32243 ms to load these 1000 itens:
Total 32243 ms
28164.8 ms Scripting
1581.1 ms Rendering
437.0 ms Painting
1066.3 ms Other
993.5 ms Idle

A script in client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:863 is consuming 79.6% (24.023ms) (Activity aA).

Obs:
Chrome Version 71.0.3578.98 (Official Release) 64 bits.

I think improving it will be a good feature for future developers.
Thanks

**Comment by web-padawan** [comment]
Closing in favor of #1509 as both issues are bow in the same repository.
