### ISSUE TITLE
Can't select row of grid on IE11( works fine in Google Chrome, Firefox, Safari)

### ISSUE THREAD

**Issue by YeTingGe** [vaadin/vaadin-grid#2030]
Description of the bug
  
 Create a Gird, set it in Grid.SelectionMode.MULTI mode, add to a SplitLayout.
    Then try to select any row by a single click to the checkbox.
Result:
    It does not work in IE11.  
    It works fine in Google Chrome, Firefox, Safari.
    Edge is not tested.

Minimal reproducible example
    private class HeadInfo {
    int index;
    String name;

      public HeadInfo(int index, String name) {
          this.index = index;
          this.name = name;
      }

      public int getIndex() {
          return index;
      }

      public String getName() {
          return name;
      }

    }
    private final Grid grid = new Grid<>();
    private final GridSelectionModel selectionMode = grid.setSelectionMode(Grid.SelectionMode.MULTI);
    private final Grid.Column idColumn = grid.addColumn(HeadInfo::getIndex).setHeader("ID")
    .setFlexGrow(0).setWidth("75px");
    private final Grid.Column nameColumn = grid.addColumn(HeadInfo::getName)
    .setHeader("Name").setFlexGrow(1);

    Expected behavior
    You can select any row display in Grid with a single click in IE11.

    Actual behavior
    Sometimes, you can select a row by click on the checkbox multiple times in IE11.
    Select all button always works fine.

**Comment by web-padawan** [comment]
Tried the component demos locally for `GridFlow` 4.3.0 (Vaadin 14.4.0) and did not see any issues in IE11:

![ie](https://user-images.githubusercontent.com/10589913/95464092-3ab0dd00-0982-11eb-992c-8b43961a31dd.gif)

Closing as inactive and not reproducible. Please submit a new issue if the problem persists.
