### ISSUE TITLE
Grid.select(item) does not highlight the newly selected row.

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-grid#2031]
If i select a row programmatically the row is not marked as selected

The select method i used is this:
```java
Grid.select(item)
```

A row selection with the mouse marks the selected row in light-blue, but the programmatic (pre)selection does not highlight the selected row

![image](https://user-images.githubusercontent.com/38694044/44737028-2b97a980-aaf1-11e8-8537-7f54f56613cc.png)

**Comment by web-padawan** [comment]
Tested with the following example and could not reproduce:

```java
Grid<String> grid = new Grid<>();
grid.addColumn(string -> string);
grid.setSelectionMode(SelectionMode.SINGLE);
grid.setItems("foo", "bar");
grid.select("foo");
add(grid);
```

Result:
<img width="606" alt="Screenshot 2020-10-12 at 22 47 45" src="https://user-images.githubusercontent.com/10589913/95784816-361b5a00-0cdd-11eb-8f70-8b7f2d2a2275.png">

See also the examples of programmatic selection: https://vaadin.com/components/vaadin-grid/java-examples/selection

Closing as invalid.

**Comment by mikethomas77055** [comment]
@web-padawan 
I'm also seeing this issue.  I tried your example and it worked fine.  However once I point the grid to an actual object (and not just the list of strings), that's where it breaks for me.  

here's my code:
![image](https://user-images.githubusercontent.com/38060296/100138103-2140f300-2e53-11eb-8278-6137e2e9f2dd.png)

here's a screenshot of the log output:
![image](https://user-images.githubusercontent.com/38060296/100138002-01113400-2e53-11eb-80ae-11e46e17fbfe.png)

here's a screenshot of what I see in the browser:
![image](https://user-images.githubusercontent.com/38060296/100138027-0a9a9c00-2e53-11eb-8267-be8c58b66a05.png)

as you can see in the screenshots, other than me calling on my specific class to populate the grid, it's identical to yours.  Also, based on the log output, it is "selecting" the first item fetched by default.  However in the browser, no row is highlighted.  I've greatly simplified this from what I'm trying to do for real.  I'm actually working with a multi-select for real, but this appears to be the same issue regardless so I'm just using a single select here.

thanks for your help.

**Comment by mikethomas77055** [comment]
@engor 
I ended up solving it by adding this to my AbstractEntity class (all of my entity classes extend AbstractEntity, so adding it to AbstractEntity solved this for all entities).

![image](https://user-images.githubusercontent.com/38060296/180828889-ce021c93-8a0b-4d42-b674-5e0c307f692b.png)

**Comment by engor** [comment]
@mikethomas77055 thanks for reply!
I found the reason of my issue - the Grid component works well, the reason was PaginatedGrid (I use it) which resets selection in it's onAttach event.
