### ISSUE TITLE
A basic grid is not sortable

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#2032]
```
public class FileList extends Grid<File> {
    public FileList(File folder) {
        super(File.class);
        setItems(folder.listFiles());
    }
```

Shows a lot of properties but nothing happens when you click on the headers?

**Comment by tomivirkki** [comment]
Just tested on Vaadin 14.4 and it works fine. Closing.

![Kapture 2020-10-16 at 13 36 08](https://user-images.githubusercontent.com/1222264/96248693-9e578d80-0fb4-11eb-86d5-778f2b52133b.gif)
