### ISSUE TITLE
(TypeError) : a is null when calling setItems on Firefox

### ISSUE THREAD

**Issue by Ramonrune** [vaadin/vaadin-grid#2033]
I have an application with two buttons and a grid, when i click in each of these buttons, grid will be updated with setItems(list). When application start, my grid has around 200 items on grid. The problem is, i'am scrolling this grid a little bit, and after it a click in a button, and "(TypeError) : a is null" happens (only on firefox).

Grid has some renderers (component renderers) like the following:

```
grid.addColumn(new ComponentRenderer<>(documentModel -> {

	TextField textField = new TextField();
	textField.addClassName("font-style");
	textField.setWidth("100%");
	textField.setValue(String.valueOf(documentModel.getDocId()));
	return textField;
	
})).setHeader("Access key").setFlexGrow(0).setWidth("400px").setKey("doc_id").setSortable(true)
				.setResizable(true);

grid.addColumn(new ComponentRenderer<>(documentModel -> {

	Div div = new Div();
	div.setWidth("100%");
	if (String.valueOf(documentModel.getDocNumber()).isEmpty()) {
		div.setText("Não disponível");
	} else {
		div.addClassName("font-style");
		div.addClassName("n-doc");
		div.setText(String.valueOf(documentModel.getDocNumber()));
	}
	return div;

})).setHeader("Document number").setFlexGrow(0).setWidth("150px").setKey("doc_number").setSortable(true)
				.setResizable(true);
```

The only thing that i do before setItems(list) is that i'am hiding some columns when i have clicked in the button. I'm using Vaadin 10.0.2 and Firefox 61.0.1 (64-bit) Quantum.

**Comment by tomivirkki** [comment]
Can't reproduce with Vaadin 14.4. Closing. In case this is still an issue, please provide a zip file of an example project (including the mentioned clickable buttons) with which the issue can be reproduced.
