### ISSUE TITLE
Grid row height is hiding content

### ISSUE THREAD

**Issue by Ramonrune** [vaadin/vaadin-grid#2034]
Basically, i have two buttons and a grid, when i click in each of these buttons, grid must be updated with new items. My grid have some component renderers for text fields, divs and others. What is happening is that when i click in a button to set new items on the grid, some times my content inside grid row is being hidden.

**Grid component renders:**

```
grid.addColumn(new ComponentRenderer<>(documentModel -> {

	TextField textField = new TextField();
	textField.addClassName("font-style");
	textField.setWidth("100%");
	textField.setValue(String.valueOf(documentModel.getDocId()));
	return textField;
	
})).setHeader("Access key").setFlexGrow(0).setWidth("400px").setKey("doc_id").setSortable(true)
				.setResizable(true);

grid.addColumn(new ComponentRenderer<>(documentModel -> {

	Div div = new Div();
	div.setWidth("100%");
	if (String.valueOf(documentModel.getDocNumber()).isEmpty()) {
		div.setText("Não disponível");
	} else {
		div.addClassName("font-style");
		div.addClassName("n-doc");
		div.setText(String.valueOf(documentModel.getDocNumber()));
	}
	return div;

})).setHeader("Document number").setFlexGrow(0).setWidth("150px").setKey("doc_number").setSortable(true)
				.setResizable(true);
```

**How it is looking some times:**
![how_it_is_looking_some_times](https://user-images.githubusercontent.com/16857245/43972789-f33d69e2-9cab-11e8-8bb1-f264372c62e5.PNG)

**How it should look:**
![how_it_should_look](https://user-images.githubusercontent.com/16857245/43972814-06be31cc-9cac-11e8-8be3-102e20d87f97.PNG)

I'm using Vaadin 10.0.2 and Google chrome v67.0.3396.99 (Oficial release) 64 bits.

**Comment by tomivirkki** [comment]
@johannest can you provide a minimal repro for this? Ideally a zip file of an example project where the issue reproduces.

**Comment by tomivirkki** [comment]
Can't repro with 14.4.0. Closing.
