### ISSUE TITLE
Unable programmatically deselect item in IE11

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-grid#2040]
After `grid.deselectAll()` was called, I expect any click on any item will select the item.

Assume the following code:
```
    @Id("grid")
    private Grid<String> grid;

        grid.setSelectionMode(Grid.SelectionMode.SINGLE);
        grid.addSelectionListener(e -> {
            e.getFirstSelectedItem().ifPresent(item -> System.out.println("Selected Item: " + item));
            grid.deselectAll();
        });

        grid.addColumn(s -> s);
        grid.setItems("1", "2", "3", "4", "5");
```

In IE11 I need an extra click on item for manually deselection (basically, item is deselected, but it is still so-called `activeItem`).

Then I tried to reset `activeItem` manually:
```
...
        grid.deselectAll();
        grid.getElement().setProperty("activeItem", null);
```
This hack fixes the issue only for the first two selections of the same item. 

For some reason only the following workaround fixes the issue:
```
...
       grid.deselectAll();
       getElement().callFunction("resetActiveItem");
```
where resetActiveItem method does: `this.$.grid.activeItem = null;`

Code example:
https://github.com/vaadin/skeleton-starter-flow-spring/compare/master...alexberazouski:grid-active-item

Run in production: `mvn spring-boot:run -Dvaadin.productionMode`

Bug is reproduced in IE11 only.

**Comment by tomivirkki** [comment]
Closing. Seems to work on V14.4
