### ISSUE TITLE
Calling DataProvider#refreshItem does not update on IE11

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-grid#2042]
The issue was first found on Bakery, but I created a testing project from the Skeleton. I have updated the dependencies to Flow `1.0.0.beta9` and Grid `1.0.0.beta10`.

I have a grid inside a template, which is being wired by `@Id`. Then, I set a data provider (the example was extracted from `vaadin-grid-flow` tests). When user selects a row and clicks on the button, then I get the selected item, change it and call `grid.getDataProvider().refreshItem(item)`. 

I have tested it on Chrome, Firefox and Safari (all latest) and it worked as expected both in dev and production mode.

When running in production mode in IE11, the item doesn't get updated (in Bakery, the only way to see the updated item is to refresh the page). 

Here is the example project [refreshing-grid-ie11](https://github.com/vaadin/vaadin-grid-flow/files/1966968/refreshing-grid-ie11.zip)

**Comment by tomivirkki** [comment]
Closing. Seems to work on V14.4
