### ISSUE TITLE
Empty Grid with column but no content gets a scrollbar

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/vaadin-grid#2045]
```
        Grid<String> grid = new Grid<>();
        grid.addColumn(String::toString).setHeader("String");
        add(grid);
```

Gives me a Grid with a scrollbar with 100% of the height of the Grid.

**Comment by web-padawan** [comment]
Tested this in Chrome, Safari and Firefox on MacOS + Chrome on Windows and could not reproduce:

![grid](https://user-images.githubusercontent.com/10589913/95457736-fcafbb00-0979-11eb-89de-7f1e9a2f29a8.png)

Closing as fixed.
