### ISSUE TITLE
Automated Performance Regression testing for Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid#2048]
Should have a test run on each PR validation for:
- time to render for initial load on basic case
- time to render for initial load with huge grid
- time to scroll to cell x, y when the grid is huge
- make sure there are only the expected pages requested from client->server side, no extra requests.
  - this needs to be verified for initial load and scrolling

**Comment by web-padawan** [comment]
The performance tests are [implemented](https://github.com/vaadin/vaadin-grid-flow/blob/master/vaadin-grid-flow-integration-tests/benchmark) and benchmarks are reported internally.
Flow components are moved to the monorepo, so issues related to test setup, benchmarks etc need to be submitted there.

Closing as done.
