### ISSUE TITLE
Add option to let scrollbar start below header

### ISSUE THREAD

**Issue by thigg** [vaadin/vaadin-grid#2082]
### Description
With a sticky header row, it would be good to have an option, which lets the scrollbar start, where the actual scrolling is happening.
Currently the scrollbar is always starting at the top of the grid. This feature would allow to let the scrollbar start below the header of the grid.

The scrollbar would start at the red line
![image](https://user-images.githubusercontent.com/7593137/99415708-649ddd80-28f8-11eb-9f3b-3efc233cd3b4.png)

**Comment by tomivirkki** [comment]
Hi @thigg, This is actually how it used to work with Vaadin 8 (https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features) During the Grid rewrite after Vaadin 8, we decided to keep the new Grid's DOM structure as simple as possible (the whole `<table>` structure inside one single scrollable container) and more importantly, have it rely on native scrolling. Changing the scrolling mode now would require a major refactoring of the Grid internals, so in practice, this is unfortunately not doable. Closing.
