### ISSUE TITLE
using grid.select(item) not highlighing or checking the item on the screen.

### ISSUE THREAD

**Issue by mikethomas77055** [vaadin/vaadin-grid#2086]
I saw issue #2031 was closed recently as unable to  reproduce, however I'm having the same issue.  When I call grid.select(item) in code, the item is selected in memory, however it's not highlighted/checked on the screen.  I've put some screenshots of a TestGrid class I wrote, a log entry showing that the item is in fact selected, and what I see in the UI.    In the previous issue, the issue was closed and some sample code was provided showing it works as expected.  I tried that sample code and it in fact worked as expected, however the sample code was populating the grid with a single column of strings.  When I reworked that sample code to pull values from the database to populate the grid it stops working.

here's my code:
![image](https://user-images.githubusercontent.com/38060296/100181051-157b1e00-2e9f-11eb-9445-87e8d66f3944.png)

here's a screenshot of the log output:
![image](https://user-images.githubusercontent.com/38060296/100181068-1f048600-2e9f-11eb-9517-9f2ee2a36c74.png)

here's a screenshot of what I see in the browser:
![image](https://user-images.githubusercontent.com/38060296/100181085-262b9400-2e9f-11eb-855b-1b11437199e8.png)

as you can see in the screenshots, other than me calling on my specific class to populate the grid, it's identical to yours. Also, based on the log output, it is "selecting" the first item fetched by default. However in the browser, no row is highlighted. I've greatly simplified this from what I'm trying to do for real. I'm actually working with a multi-select for real, but this appears to be the same issue regardless so I'm just using a single select here.

thanks for your help.

**Comment by tomivirkki** [comment]
Hi @mikethomas77055 

Tried with the following snippet, and for me the first items shows as selected just fine. Can you check if your SystemName class has errors in `equals` and `hashCode` implementations.

```java
public TestGrid() {
    DepartmentData departmentData = new DepartmentData(2000);
    Grid<Department> grid = new Grid<Department>();
    grid.addColumn(Department::getName);
    grid.setSelectionMode(SelectionMode.SINGLE);
    grid.setItems(departmentData.getRootDepartments());
    Department item = departmentData.getRootDepartments().get(0);
    grid.select(item);
    add(grid);
    for (Department department : grid.getSelectedItems()) {
        System.out.println(department.getName());
    }
}
```

**Comment by mikethomas77055** [comment]
I don't have any errors in equals or hashCode. 
your example showed selected in the UI?  Can you send me your 'DepartmentData' class so I can try for myself?

thank you,
-Mike

**Comment by tomivirkki** [comment]
Here's a copy-pasteable example:
```java
public TestGrid() {
  List<Person> people = new ArrayList<>();
  people.add(new Person("Lucas"));
  people.add(new Person("Maria"));
  people.add(new Person("Hans"));

  Grid<Person> grid = new Grid<Person>();
  grid.addColumn(Person::getName);
  grid.setSelectionMode(SelectionMode.SINGLE);
  grid.setItems(people);
  Person item = people.get(0);
  grid.select(item);
  add(grid);
  for (Person department : grid.getSelectedItems()) {
    System.out.println(department.getName());
  }
}

class Person {
  private String name;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Person(String name) {
    this.name = name;
  }
}
```

Result, after opening the browser (using Vaadin 14.4.3 (also tried with V18)):

<img width="499" alt="Screenshot 2021-01-28 at 17 48 32" src="https://user-images.githubusercontent.com/1222264/106162718-15deb080-6191-11eb-8c8e-8dc7ec2552be.png">

**Comment by mikethomas77055** [comment]
Thanks!  I was able to figure it out based on what you sent me.
