### ISSUE TITLE
Grid selection is not updated after item is removed from dataset and dataprovider is refreshed

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-grid#2099]
Vaadin 18.0.1
### Description
When
1) a row is selected in a Grid 
2) the corresponding item is deleted from the backing dataset
3) the DataProvider is refreshed
Then the Grid's selection will still contain the deleted item.

Happens on both single and multiselection, although multiselection is the more relevant case.

### Expected outcome
The selection set will not contain any deleted item(s).

### Actual outcome
Selection still contains any deleted item(s)

### Code example:
```java
public class MasterDetailView extends Div {

    public static class Person {
        String email;

        public void setEmail(String email) {
            this.email = email;
        }

        public String getEmail() {
            return email;
        }
    }

    private Grid<Person> grid = new Grid<>(Person.class, false);

    private Button removeLast = new Button("Remove last");
    private Button reportSelection = new Button("Report selection");

    public MasterDetailView(@Autowired PersonService personService) {
        setId("master-detail-view");
        // Create UI
        List<Person> people = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            Person person = new Person();
            person.setEmail("Email " + i);
            people.add(person);
        }

        add(grid);
        grid.addColumn("email").setAutoWidth(true);
        grid.setItems(people);

        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        grid.asMultiSelect().select(people.get(people.size() - 1), people.get(people.size() - 2), people.get(people.size() - 3));
        removeLast.addClickListener(e -> {
            people.remove(people.size()-1);
            grid.getDataProvider().refreshAll();
        });
        reportSelection.addClickListener(e -> {
            Set<Person> value = grid.asMultiSelect().getValue();
            String s = "";
            for (Iterator<Person> iterator = value.iterator(); iterator.hasNext(); ) {
                Person selected = iterator.next();
                s += selected.getEmail() + ";";
            }
            Notification.show("Selected emails: " + s);
        });
        add(removeLast, reportSelection);
    }
}
```
Instructions: Click "remove last" and then "report selection". You'll note that the selection still contains the removed item.

**Comment by tomivirkki** [comment]
I made sort of an inverted version of the example where pre-selected items are added to the Grid's items on button click. If we changed Grid to only accept known items in the list of selected items, this use-case wouldn't be supported either. It becomes more problematic if you want to use a lazily loading data provider with pre-selected items.

```java
public class MasterDetailView extends Div {

  public static class Person {
      String email;

      public void setEmail(String email) {
          this.email = email;
      }

      public String getEmail() {
          return email;
      }
  }

  private Grid<Person> grid = new Grid<>(Person.class, false);

  private Button addNew = new Button("Add new");
  private Button reportSelection = new Button("Report selection");

  public MasterDetailView() {
      setId("master-detail-view");
      // Create UI
      List<Person> people = new ArrayList<>();
      List<Person> newPeople = new ArrayList<>();
      for (int i = 0; i < 10; i++) {
          Person person = new Person();
          person.setEmail("Email " + i);

          if (i<6) {
            people.add(person);
          } else {
            newPeople.add(person);
          }
      }

      add(grid);
      grid.addColumn("email").setAutoWidth(true);
      grid.setItems(people);

      grid.setSelectionMode(Grid.SelectionMode.MULTI);
      grid.asMultiSelect().select(newPeople.get(newPeople.size() - 1), newPeople.get(newPeople.size() - 2), newPeople.get(newPeople.size() - 3));
      addNew.addClickListener(e -> {
          if (!newPeople.isEmpty()) {
              people.add(newPeople.get(0));
              newPeople.remove(0);
              grid.getDataProvider().refreshAll();
          }
      });
      reportSelection.addClickListener(e -> {
          Set<Person> value = grid.asMultiSelect().getValue();
          String s = "";
          for (Iterator<Person> iterator = value.iterator(); iterator.hasNext(); ) {
              Person selected = iterator.next();
              s += selected.getEmail() + ";";
          }
          Notification.show("Selected emails: " + s);
      });
      add(addNew, reportSelection);
  }
}

```

**Comment by mshabarov** [comment]
Deselection can be made in `DataProviderListener`. As soon as the `dataProvider::refreshAll` is called, the listener could take the backed items collection (or take the cached items from data communicator, in case of lazy loading), and then check which items are selected, nut not present in backed collection -> deselect those items.

**Comment by tomivirkki** [comment]
But then the use-case above wouldn't work (having pre-selected items). You might for example store the selection state in DB and have it applied for a new grid. You still want `getSelectedItems()` to return the full set even if some of the items haven't yet been loaded from the DB (by the Grid's data provider). If `refreshAll` would then remove the items it hasn't yet loaded, you'd lose the selection state.

**Comment by OlliTietavainenVaadin** [comment]
How about in an in-memory data provider? It sounds like lazy loading would indeed not work.

**Comment by tomivirkki** [comment]
The [example above ](https://github.com/vaadin/vaadin-grid/issues/2099#issuecomment-741601894) uses an in-memory data provider. The `setItems()` API is a helper that still [creates](https://github.com/vaadin/flow/blob/f3298e3e973f79c0f93687cd963fad55844eb27b/flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java#L66) a DataProvider under the hood and from Grid's point of view, the implementation shouldn't matter. It wouldn't be right to make Grid detect the DataProvider implementation and then add exceptional logic based on it (and not support the use case above). With [DataView](https://github.com/vaadin/vaadin-grid/issues/2100) it makes more sense since there is a dedicated API for item removal.

**Comment by OlliTietavainenVaadin** [comment]
Agreed.

**Comment by rolfsmeds** [comment]
Closing based on the discussion above.
