### ISSUE TITLE
<v-grid> cell.row.index behaves unexpectedly when used within a function inside custom renderer

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#21]
Given I have a `<v-grid>` with 3 rows, and I use `cell.row.index`:

``` js
grid.columns[0].renderer = function(cell) {
  // this works properly and renders value 0,1,2 in the column 
  cell.element.innerHTML = cell.row.index;
  cell.element.addEventListener('click', function() {
  // this however, will print value 2 on the console on every row
  console.log(cell.row.index);
  });
};
```

It seems that both the `cell` and `cell.row` are actually singletons which results in unexpected side-effects.

**Comment by Saulis** [comment]
As a workaround, you need to store the `cell.row.index` to a variable outside the event listener function.

**Comment by erinhong17** [comment]
I am also getting some odd side effects where each time i click on my paper-icon-button, the icon duplicates.

`this.$.grid.columns[9].renderer=function(cell){
					cell.element.innterHTML = ""; 

					var button = document.createElement("paper-icon-button"); 
					button.setAttribute("icon","menu"); 
					button.addEventListener("click",function(){
						console.log("detecting click!"); 
					}); 

					cell.element.appendChild(button); 

					cell.row.index; 

				}`

Do you have any idea why this might be happening? Thanks!

**Comment by erinhong17** [comment]
I'm also getting some odd side effects even though my cell.row.index has been stored outside the event listener function. Each time I click on my menu button, the icons duplicate. 
Of the three rows I have right now, the first row gets 3 after the first click while second and third row gets 2 after the first click... 

```
this.$.grid.columns[9].renderer=function(cell){
cell.element.innterHTML = ""; 

var button = document.createElement("paper-icon-button"); 
button.setAttribute("icon","menu"); 
button.addEventListener("click",function(){
console.log("detecting click!"); 
}); 

cell.element.appendChild(button); 
cell.row.index; 
}
```

Do you have any idea why that might be happening? This code is the only javascript in my file at the moment

**Comment by tomivirkki** [comment]
Hi @erinhong17,

There's a small typo in your example code that causes this:
`innterHTML` should be `innerHTML`

After fixing this, the code seems to work as expected

**Comment by jouni** [comment]
Wontfix, the workaround should be sufficient.
