### ISSUE TITLE
TreeGrid regression since 14.4.3

### ISSUE THREAD

**Issue by INPUTsys-Chris** [vaadin/vaadin-grid#2107]
### Description
TreeGrid since 14.4.3 displays blank areas when an initial scroll happens.

### Expected outcome
Scroll should work. Rows are displayed .
![grafik](https://user-images.githubusercontent.com/56319603/102370081-f31b8280-3fbc-11eb-8417-10a27cf1ceb0.png)

### Actual outcome
![grafik](https://user-images.githubusercontent.com/56319603/102369792-a3d55200-3fbc-11eb-8985-19ef44a22247.png)

### Steps to reproduce
```
public class GridScrollUi extends HorizontalLayout implements AfterNavigationObserver {

    private final List<Double> values;

    public GridScrollUi() {
        super();
        setDefaultVerticalComponentAlignment(Alignment.STRETCH);
        values = DoubleStream.generate(Math::random)
                .filter(item -> item != Double.MIN_VALUE)
                .limit(10000)
                .boxed()
                .collect(Collectors.toList());
    }

    @Override
    public void afterNavigation(AfterNavigationEvent afterNavigationEvent) {
        VerticalLayout layout = new VerticalLayout();
        layout.setMaxWidth("300px");
        layout.setMaxHeight("300px");

        List<Double> roots = new ArrayList<>();
        roots.add(Double.MIN_VALUE);

        TreeGrid<Double> treeGrid = new TreeGrid<>();
        treeGrid.addHierarchyColumn(item -> item);
        treeGrid.setItems(roots, value -> {
            if (value == null) {
                return roots;
            } else if (value == Double.MIN_VALUE) {
                return values;
            } else {
                return new ArrayList<>();
            }
        });
        layout.add(treeGrid);
        add(layout);

        // Initial scroll to bottom
        treeGrid.expand(Double.MIN_VALUE);
        int pos = values.size() - 1;
        treeGrid.select(values.get(pos));

        boolean isAtLeast14_4_3 = true;
        if (isAtLeast14_4_3) {
            treeGrid.scrollToIndex(pos);
        } else {
            // Vaadin < 14.4.3 needs this workaround and it more or less worked
            // see https://vaadin.com/forum/thread/18447912/possible-regression-in-new-grid-scroll-implementation
            // and https://github.com/vaadin/vaadin-grid/issues/1808
            treeGrid.getElement().executeJs("setTimeout(function() { $0.scrollToIndex($1) })", treeGrid.getElement(), pos);
            // Since there are many items, a delay is needed
            treeGrid.getElement().executeJs("setTimeout(function() { $0.scrollToIndex($1) }, 1500)", treeGrid.getElement(), pos);
        }
    }

}
```

### Browsers Affected

- [ X  ] Chrome
- [ X ] Firefox
- [ X ] Edge NEW

- [ ? ] Safari
- [ ? ] IE 11
- [ ? ] iOS Safari
- [ ? ] Android Chrome

**Comment by TatuLund** [comment]
I tried to reproduce this problem with the attached code using Vaadin 14.4.4, and it did not occur.

**Comment by INPUTsys-Chris** [comment]
Thanks for your work.

To verify it I tested it, again. I used 14.4.4, too.

I tested 2 different scenarios:
1. With @Route annotation
2. As a component inside another @Route, removing afterNavigation and putting everything inside the constructor

For both scenarios the output looks garbled, just like my screenshot.

**Comment by TatuLund** [comment]
I was able to reproduce this with my other test app. I noticed that the most likely reason is that I was using older version of the web component in the other one, that worked.

Esentially this issue is this bug re-emerged: https://github.com/vaadin/vaadin-grid/issues/1889

Thus I think, it is most likely a regression due this https://github.com/vaadin/vaadin-grid/commit/a34fc19d1810dcdd3608cdc9dc5075e7e9979ce4

**Comment by INPUTsys-Chris** [comment]
To sum it up:

Grid:
https://vaadin.com/forum/thread/18213846/strange-behaviour-using-grid-scrolltoend-vaadin-4-1-x was the first one. The garbled output looked identically to this one.
Bug: https://github.com/vaadin/vaadin-grid-flow/issues/944 was created.
Workaround: UI.getCurrent().beforeClientResponse(grid, ctx -> grid.scrollToEnd());

Grid/TreeGrid:
Since 14.3.8 problems regarding scrolling reappeared, the workaround didn't work anymore: https://vaadin.com/forum/thread/18447912/possible-regression-in-new-grid-scroll-implementation
Bug: https://github.com/vaadin/vaadin-grid-flow/issues/1131
Workaround: grid.getElement().executeJs("setTimeout(function() { $0.scrollToIndex($1) })", grid.getElement(), i);

Now: TreeGrid is affected.
@TatuLund you are right regarding https://github.com/vaadin/vaadin-grid/issues/1889
That is just a "duplicate" of my first ticket. To be correct, one was for scrollToIndex, one was for scrollToEnd

**Comment by INPUTsys-Chris** [comment]
@tulioag @tomivirkki 
Thank you for your hard work! Now we had time to test it.

The fix does not always work unfortunately. I simplyfied and slightly modified my test case:

```

@Route(value = "test___grid5")
public class TestTreeGrid5Ui extends HorizontalLayout implements AfterNavigationObserver {

    public TestTreeGrid5Ui() {
        setDefaultVerticalComponentAlignment(Alignment.STRETCH);
    }

    @Override
    public void afterNavigation(AfterNavigationEvent afterNavigationEvent) {
        TreeGrid<String> treeGrid = new TreeGrid<>();
        treeGrid.setSelectionMode(Grid.SelectionMode.SINGLE);
        treeGrid.addHierarchyColumn(item -> item);
        treeGrid.setItems(IntStream.range(10, 20)
                                  .boxed()
                                  .map(String::valueOf), parent -> {
            if (parent.length() > 2) {
                return Stream.empty();
            }
            return IntStream.range(1, 9)
                    .boxed()
                    .map(item -> parent + item);
        });
        treeGrid.setMinHeight("300px");
        addAndExpand(treeGrid);

        treeGrid.expand("19");
        treeGrid.scrollToIndex(14);
    }

}
```

Outcome is (Chrome, FF):
![grafik](https://user-images.githubusercontent.com/56319603/110442711-6237dd00-80bb-11eb-9d58-4ec5b3499b11.png)

Additional Info:
if I replace scrollToIndex with scrollToEnd no scrolling happens, maybe that's https://github.com/vaadin/vaadin-grid/issues/1857

**Comment by tomivirkki** [comment]
HI @INPUTsys-Chris 
If there's another related issue (with a different repro from the original), please create a new issue for it separately.

**Comment by INPUTsys-Chris** [comment]
Hi @tomivirkki 

since IMHO it's the same issue (but with slightly adopted test data) I thought I should mention it here. Do you want me really to create a new issue?

**Comment by sirbris** [comment]
like @INPUTsys-Chris I'm also still experiencing that rendering bug after scrollToIndex in TreeGrid with Vaadin 14.4.9

**Comment by INPUTsys-Chris** [comment]
Since this is closed and Tom Virkki said I should submit a new ticket -> Here it is:
https://github.com/vaadin/vaadin-grid/issues/2145
@sirbris Please upvote for the new one if you like
