### ISSUE TITLE
Ellipses in selection column

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-grid#2111]
I have observed that `vaadin-selection-column` should have a minimum size, otherwise `...` appears in the checkbox.

How to create the bug:
1. Go to [https://cdn.vaadin.com/vaadin-grid/5.7.7/demo/#grid-selection-demos](url)
2. Open console and go to the source of the first example. 
3. Navigate to the `vaadin-selection-column`  and set its `resizable` attribute from the console.
4. Now resize the first column of the example. 

Here is a screenshot.
![Screenshot from 2020-12-18 15-46-26](https://user-images.githubusercontent.com/1386911/102603022-4a019300-4148-11eb-8329-cd6d82bb3b48.png)

**Comment by yuriy-fix** [comment]
Dear @sudipta1411,
It seems to be working as expected.
What are you trying to achieve? Probably we can find a proper way to do that.

**Comment by sudipta1411** [comment]
@yuriy-fix My observation is that if the `vaadin-selection-column` is resized, then at some point `...` appears within the column, as shown in the screenshot above. Is this expected?

**Comment by rolfsmeds** [comment]
This is working as designed -- any content that overflows the cell is indicated with an ellipsis.

What we're wondering here is why you want to resize the selection column, as that should always be the same size, and I can't think of any reason why you'd want to do that.

(If the ellipsis appears in the selection column also when it's _not_ set to be resizable, then that would be a bug.)

**Comment by sudipta1411** [comment]
I accidentally made the column resizable in my project, that's when I see the ellipsis.
