### ISSUE TITLE
18.0.3 breaks grid in grid details

### ISSUE THREAD

**Issue by Traivor** [vaadin/vaadin-grid#2112]
### Description
In 18.0.3, a grid inside another grid's row details fails to render row data. The grid and its columns are there, but no data displays. 18.0.2 renders correctly.

### Expected outcome
Display data.

### Actual outcome
No data displayed.

### Steps to reproduce

1. Put a grid on the page.
2. Add a grid to be displayed by itemDetailsRenderer
3. Display a row's details and populate the internal grid with data.

### Browsers Affected

- [x] Chrome
- [x] Firefox

**Comment by yuriy-fix** [comment]
The issue was caused by https://github.com/vaadin/vaadin-flow-components/commit/8b5b88893fdf1954ee4eadf83c262d560a0415e6. It was reverted with https://github.com/vaadin/vaadin-flow-components/commit/7391d701aaa5c6ee9aa3c69d90080c64de8efe4d.
