### ISSUE TITLE
Clearing grid filtering is not working 

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/vaadin-grid#2124]
### Description
In Vaadin 18.0.5, filtering a grid seems to be working only in one direction: when items are filtered, the Grid's content is properly updated. However, when the filtering criteria is cleared, the Grid is not updated again. 

### Expected outcome
Clearing the filter should cause all Grid items to be displayed

### Actual outcome
Items are not updated

### Steps to reproduce
```
public class GridFilteringView extends VerticalLayout {

    ListDataProvider<Person> dataProvider;

    public GridFilteringView() {
        List<Person> personList = new ArrayList<>();

        personList.add(new Person( 68));
        personList.add(new Person(38));
        personList.add(new Person(53));
        personList.add(new Person( 37));
        personList.add(new Person(18));
        personList.add(new Person(28));
        dataProvider = new ListDataProvider<>(personList);

        Grid<Person> grid = new Grid<>(Person.class);
        grid.setDataProvider(dataProvider);

        IntegerField minAge = new IntegerField("Min age");
        minAge.setValue(0);
        minAge.setValueChangeMode(ValueChangeMode.EAGER);
        minAge.addValueChangeListener(e -> filterGrid(e.getValue()));

        add(grid, minAge);
    }

    private void filterGrid(Integer minAge) {
        dataProvider.addFilter(person -> {
            if (minAge == null) {
                return true;
            }
            return person.getAge() > minAge;
        });
    }

    public class Person {
        private int age;

        public Person( int age) {
            setAge(age);
        }
        public int getAge() {
            return age;
        }

        public void setAge(int age) {
            this.age = age;
        }
    }
}

```

Running this view, add some number to filter the age, then clear it again

**Comment by yuriy-fix** [comment]
In filterGrid you are adding new filter with `addFilter` and not removing those when the filter (field) value is changed.
For this specific case, the solution would be to use `setFilter` instead. Otherwise you can also write the logic for removing the previous filter with `previousValue` if needed.

**Comment by tarekoraby** [comment]
Confirmed. Using `setFilter `does seem to solve the issue. Many thanks!
