### ISSUE TITLE
Client-side exception thrown when hiding column, add item, and refresh data provider

### ISSUE THREAD

**Issue by drewharvey** [vaadin/vaadin-grid#2136]
Vaadin 14.4.8

### Description
Getting a client-side exception when doing the following sequence: instantiate grid, hide a column, add item to grid, and then call refreshAll on the data provider.

### Expected outcome
Grid should refresh, showing newly added item

### Actual outcome
Client-side exception is thrown.

### Live Demo
```
// 1. instantiate grid and columns
Grid<GridItem> grid;
grid = new Grid<>();
grid.addColumn(item -> items.indexOf(item)+1).setHeader("#");
grid.addColumn(GridItem::getA).setHeader("A").setKey("TEST");
grid.addColumn(GridItem::getB).setHeader("B");
grid.addColumn(GridItem::getC).setHeader("C");

List<GridItem> items = new ArrayList<>();
items.add(generateNewGridItem());
grid.setItems(items);

// 2. hide column
grid.getColumnByKey("TEST").setVisible(false);

// 3. add item to list
items.add(generateNewGridItem());

// 4. refresh data provider
grid.getDataProvider().refreshAll();

// exception is thrown 

```
![step-1](https://user-images.githubusercontent.com/2496955/109229757-01d2a280-7781-11eb-8348-29920749bb68.png)
![step-2](https://user-images.githubusercontent.com/2496955/109229765-05662980-7781-11eb-8dc4-abea967f1dac.png)
![step-3](https://user-images.githubusercontent.com/2496955/109229767-05fec000-7781-11eb-9274-f3dd439d818b.png)
![step-4](https://user-images.githubusercontent.com/2496955/109229769-05fec000-7781-11eb-8a4d-10a54b2f4db5.png)
 
### Steps to reproduce
1. initialize a grid: ex. 6 columns
2. hide one column - setVisible(false)
3. add new item into the grid
4. do grid refresh with `grid.getDataProvider().refreshAll();`

### Browsers Affected
Only tested on Chrome.
- [x ] Chrome (Latest Version 88.0.4324.190)
- [? ] Firefox
- [ ?] Safari
- [ ?] Edge
- [? ] IE 11
- [? ] iOS Safari
- [ ?] Android Chrome

**Comment by tomivirkki** [comment]
Tried with the following on Vaadin 14.4.8:

```java
List<Person> items = new ArrayList<>();

// 1. instantiate grid and columns
Grid<Person> grid;
grid = new Grid<>();
grid.addColumn(item -> items.indexOf(item) + 1).setHeader("#");
grid.addColumn(Person::getEmail).setHeader("A").setKey("TEST");
grid.addColumn(Person::getFirstName).setHeader("B");
grid.addColumn(Person::getLastName).setHeader("C");

items.add(new Person(100, "Lucas", "Kane", 68, new Address("12080", "Washington"), "127-942-237"));
grid.setItems(items);

// 2. hide column
grid.getColumnByKey("TEST").setVisible(false);

// 3. add item to list
items.add(new Person(101, "Foo", "Bar", 53, new Address("12080", "Washington"), "127-942-237"));

// 4. refresh data provider
grid.getDataProvider().refreshAll();

add(grid);
```

Works as expected:
![Screenshot 2021-02-26 at 9 17 00](https://user-images.githubusercontent.com/1222264/109268324-9554b380-7813-11eb-882e-707379f57645.png)


Please provide an example project that the issue can be reproduced with.

**Comment by drewharvey** [comment]
Maybe the issue is when each step is broken down into actions from the user.  In a fresh project, the following is giving me the exception.  When you run the project, as a user on the UI, click the buttons from top to bottom.  After the last button you will see the exception.

![grid-issue-gif](https://user-images.githubusercontent.com/2496955/109348454-c7750e00-7831-11eb-8c0d-de402b7ffcae.gif)

```
package org.vaadin.spring.tutorial;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import java.util.ArrayList;
import java.util.List;

@Route
public class MainView extends VerticalLayout { // implements LocaleChangeObserver {

    private Button btn1;
    private Button btn2;
    private Button btn3;
    private Grid<Person> grid;
    private List<Person> items = new ArrayList<>();

    public MainView() {
        btn1 = new Button("1. Add record", event -> {
            addRecord();
            btn1.setEnabled(false);
            btn2.setEnabled(true);
            btn3.setEnabled(false);
        });

        btn2 = new Button("2. Hide column 'A'", event -> {
            grid.getColumnByKey("TEST").setVisible(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(true);
        });
        btn2.setEnabled(false);

        btn3 = new Button("3. Add record", event -> addRecord());
        btn3.setEnabled(false);
        
        grid = new Grid<>();
        grid.addColumn(item -> items.indexOf(item)+1).setHeader("#");
        grid.addColumn(Person::getFirstName).setHeader("A").setKey("TEST");
        grid.addColumn(Person::getLastName).setHeader("B");
        grid.addColumn(Person::getHaircut).setHeader("C");
        grid.setItems(items);

        add(btn1, btn2, btn3, grid);
    }

    private void addRecord() {
        items.add(new Person("ted", "johnson", "bowlcut"));
        grid.getDataProvider().refreshAll();
    }

    public class Person {
        private String firstName;
        private String lastName;
        private String haircut;

        public Person(String firstName, String lastName, String haircut) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.haircut = haircut;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }

        public String getHaircut() {
            return haircut;
        }

        public void setHaircut(String haircut) {
            this.haircut = haircut;
        }
    }

}

```

**Comment by arenk** [comment]
@sosa-vaadin I have a similar issue with _setFooterTemplateOrRenderer.

More precisely: I'm getting a client-side exception when doing the following sequence: instantiate grid with a footer row, hide a column, update some grid properties (incl. text in the footer row of active columns), and then call refreshAll on the data provider.

An easy fix probably would be to add the same additional check as in #2144 `&& !this.hidden` to `_setFooterTemplateOrRenderer` in `vaadin-grid-column.js`

**Comment by sosa-vaadin** [comment]
@arenk Please open a ticket in https://www.github.com/vaadin/web-components so it will get done. After that, you can open a PR yourself and we'll take a look at it.
