### ISSUE TITLE
Getter for grid's selection mode

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid#2169]
Just a small request, but currently it appears a bit cumbersome to get the current selection mode of the grid. For this the user has to get the selection model and check it via instanceof if it is one of the basic subtypes. 

A simple "grid.getSelectionMode() == SelectionMode.MULTI" would be more appealing.

Request: Add a getter for selectionMode into Grid.

**Comment by tomivirkki** [comment]
Duplicate of https://github.com/vaadin/vaadin-grid/issues/2142 ?

**Comment by stefanuebe** [comment]
Yep. Sorry.
