### ISSUE TITLE
Feature Request - Multi Select with "Active" event

### ISSUE THREAD

**Issue by ValueBC** [vaadin/vaadin-grid#217]
Hi, this looks like an awesome grid and I can't wait to play with it. It seems that you can do a Multi Select, but I also then need access to the currently active record. The use case is; Big List, Pick interesting Rows, See Detail as each row is then selected. Should also be able to programmatically pick the active record. I have tried to make <iron-list> do this with no success yet.

**Comment by jounik** [comment]
Hi! I’m not sure if I completely understood what you mean by the “active” event or record. So first you would like to choose a subset of the rows in the grid (be that with the current selection model or something else), and then somehow just view those and their row details?

Can you write down more detailed steps the end user or the developer would do in this use case?

**Comment by jounik** [comment]
Reopen if you still feel this is relevant and can provide some more detailed use case.
