### ISSUE TITLE
Sorting fires four select events

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#218]
Select events should be fired when the selection changes. If you have nothing selected and sort by clicking a header, you get four select events. 

Reproducable using https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/selection.html by setting the first column in the first example to sortable

**Comment by jounik** [comment]
The event name is being renamed to "selected-items-changed", and so it only should be fired when the selected item set changes.

If you happen to have items selected, and you sort a column, that will cause the selection to be cleared and the event is fired. But it should of course not send four events.

**Comment by thejavatar** [comment]
Sorry, just to make it clear. Is it desired that the selections are cleared when trigerring sorting? If so, is there any known work-around to avoid that?

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version should not suffer from this issue.

Also, @thejavatar, in 2.0, you have actual item objects in the selectedItems array, not indeces, so it should be much better. Also, if you are using an in memory array for the items, sorting won’t clear the selection.
