### ISSUE TITLE
Chrome packaged apps error "window.onbeforeunload is not available in packaged apps."

### ISSUE THREAD

**Issue by agozie** [vaadin/vaadin-grid#219]
I get `window.onbeforeunload is not available in packaged apps.` and `window.onunload is not available in packaged apps.` with vaadin-grid in chrome packaged apps.

**Comment by jounik** [comment]
Hi, sorry for the long delay. This seems like something either GWT does by default of something the grid GWT code is doing. There should be no need for it to use those events.

We’ll investigate this at some point.

**Comment by agozie** [comment]
Any info on this?

**Comment by jounik** [comment]
Thanks for asking! We haven’t looked into it yet, unfortunately.

@manolo and @tomivirkki, any hunch where this might be coming from, and whether it’s actually necessary. My assumption is that it’s something related to the Vaadin Framework client side code, which is unnecessary for vaadin-grid, but for some weird reason still compiled into it.

**Comment by jouni** [comment]
Wontfix. This issue does not affect the upcoming 2.0 version, so please migrate to that if you are affected by this.
