### ISSUE TITLE
Scrolling stops on renderer elements (OS X Chrome and Safari)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#22]
If a custom renderer places extra elements (e.g. a `<div>`) inside the grid body cells, scrolling is unexpectedly stopped when the scroll events are caught by those elements (or so it seems).

Adding `pointer-events: none;` for the custom renderer elements works as a workaround, but that won’t work for custom renderers that require user input.

**Comment by tepi** [comment]
This is a bug in WebKit/Blink. See https://code.google.com/p/chromium/issues/detail?id=312427 for details.

Unfortunately there's no known work-around now (except pointer-events:none).

**Comment by jounik** [comment]
Since this affects renderers, the workaround is to re-use the renderer elements instead of always clearing the cell element in the renderer function. So something like this:

```javascript
grid.columns[0].renderer = function(cell) {
  var div = cell.element.firstChild;
  if(!div) {
    div = document.createElement("div");
    cell.element.appendChild(div);
  }
  // Update the rendered elements content
  // If there are child elements inside the 'div', those need to be re-used as well
  div.innerHTML = ...;
}
```

**Comment by jounik** [comment]
Now that we have an extra class name (`.scrolling`) on the `.vaadin-grid-body` element during scroll, we could use that to add `pointer-events: none;` to all renderer elements.

The extra `.scrolling` class should be prefixed also.

**Comment by jounik** [comment]
This issue seems to have been fixed in Chrome/Blink already, so you probably only need to test Safari and iOS.
