### ISSUE TITLE
Unable to initialize grid using light DOM with Javascript

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#220]
Similar to #104 but with the exception that the grid is not attached until everything is set up

```
document.body.innerHTML='<vaadin-grid><table><colgroup><col header-text="A column"></colgroup></table></vaadin-grid>';
```
and
```
var grid = document.createElement("vaadin-grid");
var table = document.createElement("table");
var colgroup = document.createElement("colgroup");
var col = document.createElement("col");
col.setAttribute("header-text","A column");
colgroup.appendChild(col);
table.appendChild(colgroup);
grid.appendChild(table);

document.body.appendChild(grid); // The light DOM should be read at this point, not earlier
```

should produce the same result. Right now, the first one works and the second one produces an empty grid. Looks like the light DOM is read before attach, is this intentional?

**Comment by manolo** [comment]
If vaadin-grid.html has been previously imported,  vaadin-grid is created as a customised element in the moment we create it with document.createElement, otherwise it should be just an HTMLElement.
When a vaadin-grid is initialised Polymer passes the light dom as parameter, and grid gets the `<table>`  element and parses it, otherwise grid ignores it. When table is added to an existing grid element it ignores it because changes to dom are not observer.  Nevertheless if the table existed when the element was created, the table is observed for changes because we suppose that grid is configured using DOM instead of API.

**Comment by Artur-** [comment]
The question is basically whether it would be smarter to read the light DOM in "attached" instead of "ready"?

**Comment by manolo** [comment]
The problem is that attached could be run many times (you can detach/attach as many times you want), while ready is run just once.

**Comment by Saulis** [comment]
We might want to use the `observeNodes` in Polymer 1.2.0: https://blog.polymer-project.org/releases/2015/11/02/release-1.2.0/

**Comment by manolo** [comment]
It's not a problem on observing nodes, but the time when the light dom is considered by the grid. It expects the table content be present when the grid is created, as well as it does not consider replacement of the original table node. 
So this specific issue is fixed reading the light dom in a different phase, although to cover all cases we should observe the light dom to see when the table is replaced. We already are observing changes in the  table node (attribute, children, etc) via de Object.observe api.

**Comment by Saulis** [comment]
>> It's not a problem on observing nodes, but the time when the light dom is considered by the grid. It expects the table content be present when the grid is created, as well as it does not consider replacement of the original table node. 

That's right, and `observeNodes` can be used to observe changes in the `<content>` element which enables observing the adding or replacing the table node regardless of time when it takes place.

**Comment by manolo** [comment]
I did some research:

### Initialisation:

 We have one method called `onready` callback:
```
public void init(Element container, Element table, 
    Element gridContainer,  Element measureObject)
```

 So the idea is to split init method in two, so as we can recompute dom configuration when the table is added
```
public void init(Element container, Element gridContainer, 
    Element measureObject)
public void readTable(TableElement table)
```

In the `ready` method we could have something like:

```
this._grid.init(this, Polymer.dom(this.root), this.$.measureobject);
this._table = this._findTableElement(Polymer.dom(this).children);
if (_table) {
  this._grid.readTable(this._table);
}
```

###  Observers

If the table is not present during the init, we should observe for dom changes somehow.

Using Polymer observer API we might observe changes in the root node and look for table additions:

```
if (this._table) {
  this._grid.readTable(this._table);
} else {
  Polymer.dom(this.root).observeNodes(function(info) {
    this._table = this._findTableElement(Polymer.dom(this).children);
  }.bind(this))
}
```

#### Problems:

  - for some reason adding a node to the grid, the observe callback is not fired.
  - Neither is found the new node using the `Polymer.dom(grid).children`


###  Attached


 We can evaluate the presence of the table in the time `attached` is called

 Something like this should work:

 ```
 if (!this._table) {
  this._table = this._findTableElement(this.childNodes);
  if (this._table) {
    this._grid.readTable(this._table);
  }
 }
 ```

#### Problems:

- `Polymer.dom(grid).children` does not report the table
- We can use this.childNodes instead which reports the table
- We cannot configure the grid if the table is added after the grid is attached

**Comment by manolo** [comment]
@Artur- Q: is it acceptable to use `Polymer.dom(grid).appendChild(table)` instead of `grid.appendChild(table)` ?

**Comment by Artur-** [comment]
Sure

**Comment by Saulis** [comment]
@tomivirkki has been prototyping a fix for #159, it might resolve this issue also?

**Comment by manolo** [comment]
Of course if we remove `<table>` in favour of `<template>` this should not be a problem, we have to check whether we need to observe light-dom when adding a `<template>` dynamically or it's handled in Polymer though

**Comment by jounik** [comment]
Depends on #311
