### ISSUE TITLE
Clear the datasource and re-render the grid.

### ISSUE THREAD

**Issue by JPaulDuncan** [vaadin/vaadin-grid#221]
I'm having trouble trying to get the grid to clear when I set the datasource to an empty array.  Is there an API I'm not seeing?  Similar to a "grid.ClearRows()" or something?

**Comment by jounik** [comment]
If you’re using the `grid.items` array property, the grid should clear itself automatically if you set it to an empty array:

```javascript
// Should clear any existing rows from the grid viewport
grid.items = [];
```

Can you paste an example how you’re trying to do it?

**Comment by JPaulDuncan** [comment]
I'm using 0.3.0-beta5 (I know it's not the latest..)

```
Polymer({
			is: 'base-grid',
            properties: {
				data: {
                    type: Array,
                    value: function() {
                        return [];
                    },
                    observer: 'dataChanged',
                    notify: true
                },
                columns: {
                    type:Array,
                    value: function () {
                        return [];
                    },
                    observer: 'columnsChanged'
                },
                model: {
                  type: String,
                    value: 'model'
                },
                remoteSort: Boolean, //TODO: Add functionality for sorting remotely vs. on server
                remoteFilter: Boolean, //TODO: Add functionality for filtering remotely vs. on server
                url: String
			},
            grid: {},
.
.
.
 dataChanged: function(newValue, oldValue) {
                if(scope.url) {
                    return;
                }

                if (newValue) {
                    if (newValue.length) {
                        data = newValue;
                    }
                }
                else {
                    data = [];
                }

                this.$.grid.data.source = data;

            }
```

It's company code, so this is about as much as I can share.  Essentially, we're using Polymer 1.0.5.  This code snippet is in our main.js file referencing a grid control on a main html page (v-grid).

HTML:
```
<base-grid id="mainGrid" columns="{{columns}}" data="{{users}}" on-model-selected="modelSelected"></base-grid>
```

Main.js file:
```
    var template = document.querySelector('template[is="dom-bind"]');
    template.user = {};
```

If I set the grid.data.source to an empty array it doesn't clear out; if I set it to null, it bombs Polymer; if I try to pop() the data, it doesn't clear out either.  I don't see an obvious way to notify the grid to re-render or any sort of function to clear it out directly to the grid.  

If I send it "new" data, it renders it just fine; it's the "after I bind it to actual data, then want to blank it out" that fails me.

It's probably obvious, but I'm more looks than brains, apparently.

**Comment by jounik** [comment]
Beta5, alright. This might be an issue we have since fixed. This PR feels like it’s at least related: https://github.com/vaadin/vaadin-grid/pull/65

Any reason you’re not updating (Polymer 1.1 perhaps)?

Try using `grid.data.clearCache()` if you haven’t already (`grid.clearCache()` since vaadin-grid 0.9.0-beta3 == vaadin-elements 0.3.0-beta10).

**Comment by JPaulDuncan** [comment]
I upgraded and now the thing thinks that addColumn() isn't a function...

**Comment by jounik** [comment]
Well that seems totally random, that method hasn’t been touched in a long time. Are you sure the element is upgraded before you try to use that method?

**Comment by jounik** [comment]
Please reopen if you still have issues related to this discussion.
