### ISSUE TITLE
Rename "rows" to "visible-rows"

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#222]
In order to avoid confusion between “items” and “rows” in the grid, the `rows` attribute should be renamed to `visible-rows` and the property to `visibleRows`.

To avoid confusion between `visibleRows` and `visibleColumns` (other returning a number and other returning an array), the `visibleColumns` property should be removed.

**Comment by tehapo** [comment]
A drafted release: https://github.com/vaadin/vaadin-grid/releases/tag/untagged-07686125baa1d8e555df

**Comment by tehapo** [comment]
Decided to remove old features instead of deprecation.

**Comment by wolfie** [comment]
waffle-poke
