### ISSUE TITLE
Touch scrolling not working on Surface device

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#224]
It’s not possible to scroll the grid using touch on Edge.
- [x] Find/order a touch device that runs Windows 8 or 10: Surface Pro 3 found from device desk
- [x] Verify the bug: yes, it’s there
- [x] Research how to fix (compare touch events and pointer events). Timebox to 1,5 person days.
- [ ] Estimate the fix
- [ ] Fix it in our fork first, let’s figure out the framework patch separately

**Comment by jounik** [comment]
@samie, could the framework team take this as a priority?

**Comment by Saulis** [comment]
Fiddled around with Vaadin Sampler using the Surface Pro (3?), Grid works on Chrome, but not with Firefox, Edge, IE11.

**Comment by Saulis** [comment]
Tested also on a Windows Phone 10 running Edge 21.10546.0.0 - sampler works, only a few glitches when scrolling / vaadin-grid scrolls, a bit raggedly though. Also, when a dataset reaches the bottom, the kinetic scrolling energy seems to transfer to scroll the window? :-O

**Comment by Saulis** [comment]
Framework has a related ticket: https://dev.vaadin.com/ticket/18737

**Comment by Saulis** [comment]
Update: looks like they have a fix pending in review for this.

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version does not suffer from this issue.
