### ISSUE TITLE
Deprecate "datasource" property

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#228]
The `datasource` property should be merged back to the `items` property (decided in [API review meeting](https://docs.google.com/document/d/1gbIuFLHjKOeNhysL7sJZDFTgrE00dx3gihLCDqdhaGc/edit)).

- [ ] Implementation
- [ ] Examples
- [ ] API docs

**Comment by wolfie** [comment]
waffle-poke.
