### ISSUE TITLE
Avoid recreating row html on click

### ISSUE THREAD

**Issue by cwayfinder** [vaadin/vaadin-grid#233]
If you define your data in the `tbody` element like in the following example:

``` html
<vaadin-grid selection-mode="disabled">
  <table>
    <colgroup>
      <col header-text="Name">
      <col header-text="Value">
      <col header-text="Progress">
    </colgroup>
    <tbody>
      <tr>
        <td>Project A</td><td>10000</td><td>0.8</td>
      </tr>
      <tr>
        <td>Project B</td><td>999999</td><td>0.8</td>
      </tr>
    </tbody>
  </table>
</vaadin-grid>
```

You can see that grid recreates row html on click. Therefore it is impossible to change the cells content dynamically, listen events, etc.

**Comment by cwayfinder** [comment]
Similar issue https://github.com/vaadin/vaadin-grid/pull/75

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version does not suffer from this issue.
