### ISSUE TITLE
Row details element is 1px too high

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#244]
If you inspect the example at https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/details.html you can see that the `.userdetailswrapper` element is 190px high, but the `.vaadin-grid-spacer` element wrapping it is 192px high (it has 1px border at the bottom, so it’s 1px too high). This is probably some sort of sub-pixel rounding error.

This makes it difficult to style the detail row because it overlaps the following row elements.

Either the wrapper element sizing should be fixed, or the following rows should be shifted down 1px to accommodate the full detail row.

**Comment by jounik** [comment]
Actually, this is most likely because the `.vaadin-grid-spacer` element styles are missing `box-sizing: border-box;`.

**Comment by jouni** [comment]
Wontfix
