### ISSUE TITLE
grid.selection.selectAll() doesn’t update the selection-mode attribute

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#247]
If you call `grid.selection.selectAll()`, the `selection-mode` attribute on the element is not updated to “all”. The `grid.selection.mode` property returns “all” correctly.

At the same time,  check that setting the select.mode property reflects correctly, and that selection.clear() correctly sets the attribute and property from "all" to "multi" (when in single-select mode, the mode doesn’t change when clear() is called).

**Comment by manolo** [comment]
Progress:
- One PR fixing the issue sending events from SelectionModels when something changes, this does not changes the actual use cases at all
- Preparing a simpler PR as Tomi suggested. It will break a couple of use cases which makes no so much sense
