### ISSUE TITLE
Frozen columns doesn’t take hidden columns into account

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#250]
Test case: http://jsfiddle.net/2byLd41r/

`frozen-columns` is set to “1”, and when you toggle the initially hidden “Name” column visible, now you actually have 2 frozen columns instead of 1.

**Comment by jounik** [comment]
From @jojule
> Sounds like correct behavior IF name was before the previously frozen column

From https://vaadin.com/api/7.5.9/com/vaadin/ui/Grid.html#getFrozenColumnCount()
> **getFrozenColumnCount**
Gets the number of frozen columns in this grid. 0 means that no data columns will be frozen, but the built-in selection checkbox column will still be frozen if it's in use. -1 means that not even the selection column is frozen.
NOTE: this count includes hidden columns in the count.

Sounds like a bug to me.

**Comment by jouni** [comment]
Wontfix. 2.0 does not have this issue.
