### ISSUE TITLE
Format autogenerated default header content

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#251]
Formatting rules:
- Drop everything up to last "."
- Strip all characters except a-z and 0-9
- Capitalize first letter
- Detect uppercase letters before lowercase letters and put a space in between

Add unit tests for all different formattings.

We should use the code from the Vaadin Framework if at all possible (SharedUtil.camelCaseToHumanFriendly).

**Comment by manolo** [comment]
@Jouni abut 'Strip all characters except a-z and 0-9' I think we only should strip characters meaning word separation and punctuation, otherwisefor instance  we will leave España as Espaa and こんにちは as nothing

**Comment by jounik** [comment]
Yeah, you might be right. But can those characters be used in JSON identifiers and JS object notations? Not really our problem if people want to abuse the "name" attribute for the column header when using light DOM or array data sources, though.

**Comment by manolo** [comment]
Yep all those character are valid js identifiers:

```
a = {"こんにちは": "こんにちは", "áéíóú": "foo"}
JSON.stringify(a)
"{"こんにちは":"こんにちは","áéíóú":"foo"}"

a.こんにちは
"こんにちは"
a.áéíóú
"foo"

```

**Comment by jounik** [comment]
In that case, I think you are very correct. Do you have a good solution already in mind? Would there be a ready-made regexp for a valid JS identifier available?

**Comment by manolo** [comment]
I think so, in my patch you can see how I just removed a bunch of characters normally used for separating words https://github.com/vaadin/vaadin-grid/pull/261/files#diff-41c6db1cbc5b996860e9fbdd93102f6fR86
