### ISSUE TITLE
Add size property

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-grid#265]
- Provide a separate property `size` which only sets the size of the data source and doesn't clear cache.
- Rename `clearCache(size)` to `refreshItems()` and remove the size argument to clearly separate functionality from setting the size.
- Document `refreshItems()` to clearly state that it needs to be called every time the order of the data has changed.
- Leave the `size` argument as optional in the data fetch callback to make it easy to use with infinite scrolling or data sources which return the size in the data response.
- When using array data sources, the `size` is set from the initial length of the array. 
- Expanding the `size` should request for missing rows if they should be visible in the viewport without calling `refreshItems()`.
- Update our examples to primarily display the usage of the new `size` property.
- Add an example use case in the data sources section how to use infinite scrolling with a data source with an unknown size.

**Comment by jojule** [comment]
Looks good. How does this affect items function?

**Comment by jounik** [comment]
> Leave the size argument as optional in the data fetch callback to make it easy to use with infinite scrolling or data sources which return the size in the data response.

So the items function, it’s parameters and the callback will stay the same, except that the second `size` parameter in the callback function will be optional.
