### ISSUE TITLE
Row Details - prevent previous selection from collapsing

### ISSUE THREAD

**Issue by musti2** [vaadin/vaadin-grid#269]
Not sure if this question/feature has been asked however i wonder if there's a way to expand multiple rows without the previous selected row collapsing? 

example:
https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/details.html

When selecting a new row, previous selection is hidden.

**Comment by tehapo** [comment]
It is possible to have multiple row details visible simultaneously. Opening the row details is done by using the `setRowDetailsVisible` method, which you can call multiple times. 

The example keeps track of currently open index and always closes it before opening the new row details, so by changing the logic a bit you could keep multiple details open.

Unfortunately the row details API is a bit limited, but there is an issue for improve things #223.

**Comment by jounik** [comment]
As @tehapo pointed out, this is currently possible, so I’m closing this issue.
