### ISSUE TITLE
deselected function returning empty array

### ISSUE THREAD

**Issue by musti2** [vaadin/vaadin-grid#274]
Hi Team,

I'm trying to toggle inspect if a row has been selected or deselected, however, the function grid.selection.deselected() is always returning an empty Array..

grid.addEventListener('selected-items-changed', function() {
   $log.info(grid.selection.selected()); // returns items that have been selected
   $log.info(grid.selection.deselected(); // always returns empty array
});

**Comment by jounik** [comment]
Hi, and thanks for reporting. This is actually a duplicate of #248, so you can track the progress there.

**Comment by musti2** [comment]
Ah awesome. Thank you! Nice job on the grid too!
