### ISSUE TITLE
Exception when adding a column and setting its header

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#287]
```
var g = document.createElement("vaadin-grid");
g.columns.push({});
g.header.getCell(0,0).content="foo";
```
-> Uncaught iB {f: "Index: 0, Size: 0", i: null}

If you give a dummy name when you push the new column, it works. 
If you wait for a while after pushing the empty new column before getting the header cell, it works.

**Comment by tomivirkki** [comment]
This works fine in vaadin-grid 1.1.0 so we'll consider this fixed. `Object.observe`, which was used in vaadin-grid 1.0.0 for catching changes to the columns array might have caused the issues.

Now that `columns` is no longer observed, the correct syntax for this is:
```
var g = document.createElement("vaadin-grid");
g.push('columns', {});
g.header.getCell(0,0).content="foo";
```
