### ISSUE TITLE
Header content is null for newly created column

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#288]
```
var g = document.createElement("vaadin-grid");
g.columns.push({name: "foo"});
```

```
console.log(g.header.getCell(0,0).content);
```

Expected output would be 'Foo' as shown in the header cell
Actual output is "null"

Be sure to wait before retrieving the cell to avoid #287

**Comment by tomivirkki** [comment]
Works as expected. cell.content and column.name are different properties.

Clearing cell.content (on default row) will make the cell display column.name (if available), but changing column.name will not directly affect cell.content property.

**Comment by Artur-** [comment]
I don't see how it is expected that cell.content does not return what is shown in the cell?

**Comment by tomivirkki** [comment]
Well, let's say you have both properties defined and you set cell.content = undefined; You expect cell.content to be something else than undefined after setting that?

**Comment by Artur-** [comment]
My assumption is that ```g.header.getCell(0,0).content``` always returns what is shown in the (0,0) header cell. Is that an incorrect assumption?

If you set cell.content to undefined, probably the header cell is empty and cell.content returns undefined or empty string

**Comment by Saulis** [comment]
I think I have to agree with @Artur- here, the column name is what you would expect `content` to return here. Also, setting explicitly `cell.content` to `undefined` should in my view also clear the header caption and not display the `column.name`.

I guess the challenge here is to determine in which cases `column.name` should be set as cell content and when not. Currently, the existence `cell.content` is used to determine whether to display the `cell.content` or the column name in the header elements DOM.

**Comment by tomivirkki** [comment]
Hmm...that's kind of like expecting column.width to also always equal to the current _visual_ width of the column.

If the api was changed as you suggest, what should happen if you change column name from one value to another (when it doesn't have content beforehand)? Should the cell display the old name (because cell.content would now have a value after the first change)?

**Comment by jounik** [comment]
Before continuing the discussion, I would like to hear a use case from Artur where the current behavior is problematic, as this was more or less a decision we made how this feature should work.

**Comment by jouni** [comment]
Won’t fix. I think this isn’t an issue for 2.0.
