### ISSUE TITLE
Clearing selection when clicking a selected row in a non-focused grid is strange

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#292]
Say you have a really simple Grid
## Name

John

The first time you click "John", the row is selected. You then move the focus elsewhere e.g. to a text field. When you want to move focus back to the grid (for whatever reason, keyboard navigation, scrolling with a wheel, ...), you have no option but to click on "John" again. This will deselect John but you will not realize it because of #291

**Comment by jouni** [comment]
This behavior will be left for the developer to define in 2.0. By default, I think we will only provide a way to select rows with explicit checkbox controls, even for single select. If they want to toggle the selection with row clicks, they need to add some extra code for that, or it might be a separate mode we have built-in.

**Comment by jouni** [comment]
Wontfix for 1.x. The default behavior has been changed in 2.0, and “click row to select” is now an opt-in feature. Also, the default styles have been changed, so there should be no confusion between a normal and selected rows by default.
