### ISSUE TITLE
Scaling animations break row height calculations

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#297]
Given a application where `<vaadin-grid>` is used inside `<paper-dialog>` with entry animation `scale-up-animation`: 

``` javascript
<!doctype html>
<html>

<head>
  <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>

  <link rel="import" href="bower_components/vaadin-grid/vaadin-grid.html">
  <link rel="import" href="bower_components/paper-dialog/paper-dialog.html">
  <link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html">
  <link rel="import" href="bower_components/paper-button/paper-button.html">
  <link rel="import" href="bower_components/neon-animation/animations/scale-up-animation.html">
</head>

<body unresolved>
  <template id="template" is="dom-bind">
    <style>
      #dialog {
        width: 800px;
        height: 600px;
      }

    </style>
    <div class="layout vertical">
      <paper-toolbar>
        <paper-button id="button" toolbar>SHOW GRID</paper-button>
      </paper-toolbar>
      <paper-dialog id="dialog" entry-animation="scale-up-animation">
        <vaadin-grid id="grid">
          <table>
            <colgroup>
              <col name="Foo">
              <col name="Bar">
            </colgroup>
          </table>
        </vaadin-grid>
      </paper-dialog>
    </div>
  </template>
  <script>
    document.addEventListener('WebComponentsReady', function() {
      var grid = document.querySelector("#grid");
      grid.items = [
        {Foo: 'foo', Bar: 'bar'},
        {Foo: 'foo', Bar: 'bar'},
        {Foo: 'foo', Bar: 'bar'},
        {Foo: 'foo', Bar: 'bar'}
      ];
      var dialog = document.querySelector("#dialog");

      var showButton = document.querySelector("#button");
      showButton.addEventListener("click", function(e) {
        dialog.open();
      });
    });
  </script>

</body>

</html>
```

The [row height autodetection](https://github.com/vaadin/vaadin-grid/blob/1d59dcc035a0a65e190578dc08644c3c5d2acf1b/java/src/main/java/com/vaadin/client/widgets/Escalator.java#L1938) in Escalator is run in the middle of the transform animation and the height is then calculated incorrectly. 

As discussed in the [original forum post](https://vaadin.com/forum#!/thread/11563252), one possible solution is to call `updateSize()` after `neon-animation-finished` is fired.

**Comment by jouni** [comment]
@tomivirkki, @Saulis, does this affect 2.0?

**Comment by tomivirkki** [comment]
@jouni Not as bad, but there's still an issue.
1. Open https://jsfiddle.net/8dxem7j8/
2. Open the dialog
3. Scroll all the way down
4. Close the dialog
5. Re-open

Now the items aren't visible at the scroll position the grid is at. Once you start scrolling the rows are repositioned. An easy fix would be to always reset scroll position to 0 when grid is detached.

**Comment by tomivirkki** [comment]
Works fine with the latest version. Closing.
