### ISSUE TITLE
flex height of vaadin-grid element

### ISSUE THREAD

**Issue by Qvatra** [vaadin/vaadin-grid#298]
Is there a way to set up height of `vaadin-grid` element to be equal to the height of the parent container?

the only thing I found is: `If vaadin-grid is not assigned any bounds externally it will size automatically by itself. By default it will take 100% of the horizontal space available and its default height depends on the number of contained data rows.`

I need `vaadin-grid` element to take 100% of the parent container height as well. 
any ideas?

**Comment by Saulis** [comment]
Hi!

By default, the height is set by multiplying the row height by `visible-rows` property + header + footer row heights. 

You can also define a height using plain CSS: e.g. `<vaadin-grid style="height:100%">`
