### ISSUE TITLE
Setting elements through content property allow sorting only from icon

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#302]
By design, focusable elements like `<input>` and `<a>` in the header content only allow sorting to happen by clicking the sorting icon.

When defining a header with a non-focusable element using the inline header definition, sorting can be triggered by clicking anywhere in the header element:

``` html
<thead>
  <tr>
    <th><label>foo</label></th>
  </tr>
</thead>
```

However, when the header is defined using the `content` property in the header cell, sorting can only be triggered from the icon, even if the element is non-focusable:

``` js
var label = document.createElement('label');
label.innerText = 'bar';

grid.header.getCell(0, 0).content = label; //can't trigger sorting by clicking on the label
```

Workaround; defining the header element contents as a string works:

``` js
grid.header.getCell(0,0).content = '<label>bar</label>';
```

**Comment by Saulis** [comment]
Current implementation is done in #252

**Comment by jouni** [comment]
Wontfix for 1.x. In the upcoming 2.0 version, you can choose whether to wrap the header content with `<vaadin-grid-sorter>`.
