### ISSUE TITLE
rowClassGenerator and cellClassGenerator locks JS thread in 1.0 FINAL if return empty string

### ISSUE THREAD

**Issue by ktiedt** [vaadin/vaadin-grid#305]
Pretty much stated in the subject however code snippet, this used to work pre 1.0, post 1.0 this would cause the browser tab to lock up (had to force close/kill it) - removing the return ''; line 'fixes' it but, it seems like an odd thing to cause a problem and more so considering the severity of the issue.

```
      this.rowClassGenerator = function(row) {
        if (row.data.isHeader) {
          return 'horizon-grid-header';
        } else if (row.data.isFiller) {
          return 'horizon-grid-filler';
        }
        return '';
      };
```

**Comment by Saulis** [comment]
This is most likely related with https://dev.vaadin.com/ticket/19364 and will be fixed once we update `<vaadin-grid>` to use the 7.6 version of the Framework Grid.

Could you verify if your snippet works if it returns null instead of empty? Thanks!

**Comment by ktiedt** [comment]
Will test that tomorrow in the office, although null for a function that returns strings is still weird ;)

**Comment by ktiedt** [comment]
Null works in our test case as well.

**Comment by Saulis** [comment]
OK good to know!

@jounik probably has a better timeframe for applying 7.6 Grid for `<vaadin-grid>`, but it probably won't happen before v1.1

**Comment by jouni** [comment]
Since @ktiedt hasn’t been asking for this in over a year, I assume this is no longer relevant, and I’m free to mark this as “wontfix” for 1.x. Also, the workaround seems really straightforward (returning `null` instead).

No similar issues should be present in the upcoming 2.0 version.
