### ISSUE TITLE
Width does not transition properly in print view

### ISSUE THREAD

**Issue by cpboyd** [vaadin/vaadin-grid#315]
I've noticed this on both Chrome and Firefox.

When trying to "print" the page, vaadin-grid doesn't seem to automatically adjust to fit within the container.

If you manually resize the window prior to printing, you can get the grid contents to fit.

Is there any recommended CSS workaround for this?

I've tried to manually set the width of vaadin-grid elements with CSS using `media @print{}` but this doesn't result in the actual table elements getting resized.

**Comment by jounik** [comment]
Thanks for the report!

For some reason Chrome and Firefox don’t relayout completely when switching to the print layout. Safari works as expected. It might have something to do with the hidden `<iframe>` element we use to detect size changes in the container element.

I don’t have any CSS workaround to offer right now :disappointed:

**Comment by jounik** [comment]
Not a complete workaround, but you could offer a custom "Print" button in the UI which would relayout the page and after that call "window.print()". If users hit "Ctrl/Cmd+P" or "File -> Print…" they will get a broken layout, so not sure if it really helps.

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version should not have this issue, as it relies more on plain CSS sizing. Please add comments if you have similar problems with 2.0.
