### ISSUE TITLE
Minor alignment issue with header and rows

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-grid#317]
In some situations the header is slightly longer than the rows that follow. See the attached screenshot for illustration of the problem.

Notice that this requires the Grid to have more than one column. For single column Grids the header aligns perfectly with the rows.

![screen shot 2016-01-27 at 14 47 32](https://cloud.githubusercontent.com/assets/368220/12614163/d53a98c2-c506-11e5-83a1-29547c85beb5.png)

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version should not have this issue.
