### ISSUE TITLE
Some Grid properties are exposed as obfuscated objects after GWT update

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-grid#318]
After GWT was updated, some of the Grid properties are exposed as obfuscated GWT objects. At least the following properties were found.

1) The `selection.selected` passes an object into the given callback function instead of the index. 

```
grid.selection.selected((i) => { console.log(i); });
> We {a: 7}
> We {a: 6}
```

2) The `grid.columns` array is populated with obfuscated objects.

```
grid.columns
> [uG, uG, uG]
```

These do **not** affect 1.0 version, but occur in `master` branch.

**Comment by manolo** [comment]
Well, that is not a problem in GWT but in the way we now use JsInterop to interact with native objects.
We are adding to the prototype custom java overlay methods used to correctly set/get properties, that implies that gwt adds those methods and obfuscate the names.
At a quick view there are different options:
- rollback to patch each single javascript object when it comes to GWT adding custom getters/setters, which was demonstrated that penalises performance.
- ask GWT to prefix overlay methods with the '_' character so as in browser debugger they are represented with the JS private convention.

**Comment by manolo** [comment]
Related with gwtproject/gwt#9314

**Comment by tomivirkki** [comment]
1) Fixed in https://github.com/vaadin/vaadin-grid/tree/fix/selected-types (still needs tests for PR)
2) Don't know if this poses a problem after all. The API's still work the same (for example grid.columns[0].flex)

**Comment by 368** [comment]
Hỗ trợ

**Comment by jouni** [comment]
Wontfix.
