### ISSUE TITLE
Details row demo on elements page breaks all other grids on page

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#319]
On the new Vaadin Grid demo page, uncommenting the last details row demo breaks other grids on the page. It seems like the other grids get 1px high rows for some reason. 

I was not able to reproduce this in a standalone project without Liferay. The offending code is commented out at the bottom of the vaadin-grid demo page in github and can be used to reproduce the problem on a local liferay deployment.

**Comment by tehapo** [comment]
Looks like the offending code has already been removed. Reopen if this should still be investigated further.

Also created pull request https://github.com/vaadin/elements-page/pull/8 while looking into this. 😄
