### ISSUE TITLE
refreshItems() does not scroll to the top

### ISSUE THREAD

**Issue by malthusyau** [vaadin/vaadin-grid#321]
The documentation of the refreshItems() method states:

> Clears the grid’s internal data cache, causing it to request the visible items in the grid viewport from the items property or the datasource function, and to scroll back to the top of the grid viewport.

If my understanding is correct, the grid is suppose to scroll to row 0, like scrollToStart(), but it doesn't do that.

**Comment by jounik** [comment]
Thanks for noticing!

@Saulis, @tomivirkki, do you remember anything about this? Can’t remember if we actually decided that it should scroll to the top when you refresh the items or not.

At the moment I feel like it should not scroll to the top (less side effects).

**Comment by Artur-** [comment]
Why should it scroll to top? What would you do to prevent it from scrolling to top? Sounds like a documentation bug to me

**Comment by tomivirkki** [comment]
Yeah, wouldn't make sense to "request the visible items in the grid viewport" and then change the scroll position right after. Documentation bug most likely.
