### ISSUE TITLE
provide a means to see actual click events vs selection events for rows

### ISSUE THREAD

**Issue by ktiedt** [vaadin/vaadin-grid#324]
sometimes a grid has actions that can be fired from data in the rows... it would be nice if we could still allow things like browser middle click or meta+click to do native things like open a link in a new tab etc.

**Comment by jounik** [comment]
Related to #144

**Comment by jouni** [comment]
I think version 2.0 has support for this, as you can attach click listeners to the column template elements and listen for click events on those. It’s not a “row click” precisely, but I think it should give you the same result.

I do think it’s a bit verbose, perhaps, to add a wrapping element for all column template content and attach event listeners to those. So even though I closed #144 as “wontfix”, I’m wondering if we should have some support for listening for row click events?

@Saulis and @tomivirkki, what do you think, what would technically be the best way to provide/implement this?

If we end up exposing something like `<vaadin-grid-row>` elements in the light DOM (this has been discussed multiple times), could the user then just add a click listener on the `<vaadin-grid>` element and check the `e.target` property if it was a row that was clicked?

Or should we fire custom events from inside the shadow DOM whenever a row is clicked.

Or should we include the needed information in the `active-item-changed` event (click/double-click/button), like proposed in #815?

**Comment by tomivirkki** [comment]
The developer doesn’t probably have much need for the actual row element on click, but for the item that’s currently bound to the row whose cell got clicked, right?

Adding a click listener to a wrapper element as @jouni instructed does the job and if click meta data isn’t needed `activeItem` gets you pretty far.

We could introduce a public “cell-tap” event that contains references to the corresponding item and column element as well as the original event/data from it.
This would be handy especially after https://github.com/vaadin/vaadin-grid/issues/492 gets implemented and defining a template becomes optional.

**Comment by ktiedt** [comment]
If you aren't killing native events to achieve these things, then yes, the discussed solutions should work... the original intent was to not force developers to "recreate" native handlers like "open in new tab" etc...

**Comment by madiganz** [comment]
Not sure if this is the best way to solve the problem, but in v3 I added this to vaadin-grid-active-item-behavior.html
```
_activateItem: function(e) {
      var clickedItem = e.detail.model.item;
      this.activeItem = this.activeItem !== clickedItem ? clickedItem : null;
      this.dispatchEvent(new CustomEvent('table-row-clicked', {detail: {data: this.activeItem}}));
      e.stopImmediatePropagation();
    },
```
This would someone to add an event listener for 'table-row-clicked' event and get/use the row's data.

**Comment by tomivirkki** [comment]
Closing in favour of
https://github.com/vaadin/vaadin-grid/issues/1318
and
https://github.com/vaadin/vaadin-grid/issues/1256
