### ISSUE TITLE
Tbody is empty but items is set

### ISSUE THREAD

**Issue by ryanwtyler** [vaadin/vaadin-grid#327]
![image](https://cloud.githubusercontent.com/assets/11950318/13252452/c09fba9c-da04-11e5-8cc2-555496327655.jpeg)
This only happens the first time I load the items via Ajax.

**Comment by jounik** [comment]
Thanks for the report! Would it be possible to get a runnable example that we can use to debug this (jsbin, jsfiddle, codepen, etc.)?

**Comment by ryanwtyler** [comment]
How do I link the polymer and vaadin dependencies?

**Comment by jounik** [comment]
Not sure what you mean by that. Do you need something else than vaadin-grid to reproduce the issue? If not, you can easily start a new Codepen by clicking the "Edit" buttons in the "Examples" section on https://vaadin.com/elements/-/element/vaadin-grid

**Comment by ryanwtyler** [comment]
i need iron-ajax and some other polymer elements

**Comment by ryanwtyler** [comment]
ok.  styles are messed up but you can see it's empty but when you click on "women" or "men" it populates.  clicking on "women" or "men" just filters the don-repeat
http://codepen.io/ryanwtyler/pen/RabxEy/?editors=1111

**Comment by ryanwtyler** [comment]
you can also see it here:  ryantyler.org/wl

**Comment by manolo** [comment]
Taking a look to your codepen example, it seems that there is a CORS problem and there is no data coming from your server service:

`XMLHttpRequest cannot load http://ryantyler.org/Wl/db.php?t=1&meetId=341. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.`

In your app, the table with id='myGrid' seems to have the data correctly. What should I focus on to see the issue ?

![screen shot 2016-03-09 at 10 38 39](https://cloud.githubusercontent.com/assets/161853/13631389/a66b320a-e5e4-11e5-99fd-1e4c52e3d636.png)

**Comment by ryanwtyler** [comment]
I'm sorry, you need to click on any item on that grid.  the page it links to is the page with the issue.

**Comment by kumpelblase2** [comment]
I experienced the same behavior. Calling `refreshItems()` did not make any difference at that point. But it is only happening every 3rd or 4th time I reload the page. Every other time, the items render fine. However, when it breaks, you can set the items how often you like, they will never get rendered.

The reason was a race condition in that the `items` property got populated from the ajax call before the grid was loaded _completely_. Delaying the update of `items` until the grid was fully loaded fixed this issue for me.

**Comment by manolo** [comment]
Could you call the `refreshItems()` in the promise returned by the grid to see if that fixes the problem?

```
grid.then(function(){
   grid.refreshItems();
})
```

**Comment by kumpelblase2** [comment]
That results in `then` being undefined at that point. Since I'm using it from GWT, the thing that worked for me in the end was this:
```java
Polymer.whenReady((o) -> {
    grid.setItems(items);
    grid.refreshItems();
    return null;
}, grid.getElement());
```
Anything else has a chance of running before everything is available on the grid.

**Comment by manolo** [comment]
Ah, GWT, are you using Widgets or the Elements components?

Anyway, as some background, the main problem in GWT when using widgets is that the import is done dynamically, and component could not be entirely initialised when it is used.
This problem happens as well in any other context or framework if you don't import your elements at the very beginning of your app start. And it's very common when using polymer elements in polyfilled browsers where the import process is asynchronous.

For reference this is related with  https://github.com/Polymer/polymer/issues/1756

**Comment by kumpelblase2** [comment]
Sorry for the late response, I am using it via Widgets. Looking at the Polymer issue, I had the same expectations coming in, so I guess I'll follow that issue instead. I'll try adding the imports in the HTML document instead if the improves anything, but I'm fine with the `Polymer.whenReady` solution for now.

Thanks.

**Comment by Saulis** [comment]
@ryanwtyler are you still experiencing the issue? http://ryantyler.org/wl seems to be working fine to me.

**Comment by jouni** [comment]
Please add a comment if you are still getting this issue. If you are, I encourage you to try to upgrade to vaadin-grid 2 and see if that fixes it.
