### ISSUE TITLE
<paper-button> styling issues

### ISSUE THREAD

**Issue by Paranaix** [vaadin/vaadin-grid#328]
`<vaadin-grid>` and raised `<paper-button>` currently don't really work in conjunction with each other due to the ominous `CONTENT_WRAPPER` in `JSStaticCell` which wraps cells in a span and sets `overflow: hidden`. Raised paper-button shadow borders and it's effects exceed their own size and won't get displayed.

**Comment by Saulis** [comment]
I recommend using a custom cell renderer for this:

For example:
```js
var currencyRenderer = function(cell) {
  if (cell.element.childElementCount === 0) {
    cell.element.innerHTML = '';
    var button = document.createElement('paper-button');
    cell.element.appendChild(button);
    button.raised = true;
   button.innerHTML = 'Press Me';
 }
};
```
That way you won't have the `<span>` around your button.

For more info, please see: https://vaadin.com/docs/-/part/elements/vaadin-grid/formatting.html

**Comment by jouni** [comment]
Wontfix, as this is somewhat expected behavior (the wrapper span for light dom content). Also, the upcoming 2.0 version is not affected by this issue.
