### ISSUE TITLE
Object.observe in chrome to be deprecated

### ISSUE THREAD

**Issue by jahglow** [vaadin/vaadin-grid#331]
'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details. vaadin-grid.min.js:166

**Comment by Juravenator** [comment]
+1

**Comment by mshahidkhan** [comment]
+1

**Comment by mshahidkhan** [comment]
One more... 
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by tehapo** [comment]
We aim to remove our usage of `Object.observe` in a future release. To future-proof your code, I would suggest you to use the array mutation [methods](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-mutation) of Polymer to modify arrays such as `grid.columns`.

Fortunately `vaadin-grid` contains a polyfill, which will be used after Chrome removes the method. So it will not break any existing functionality. Already verified this by testing in Chrome Canary.

**Comment by jounik** [comment]
Now that Chrome has removed this API, and the polyfill is less than great (consumes a lot of CPU), we need to drop the support for the current columns API.

As a heads-up, the current plan is to remove it in a minor version, 1.1 probably.
