### ISSUE TITLE
Programatically selecting/deselecting of hidden grid inconsistent

### ISSUE THREAD

**Issue by timeu** [vaadin/vaadin-grid#335]
Using `grid.selection.select` or `grid.selection.deselect` on a grid that is not visible (i.e. child of a `iron-pages` element) shows inconsistent behavior. Only the first row is select/deselected. All other rows won't change the selection state. It works fine, if the iron-page that contains the grid is visible.

**Comment by Saulis** [comment]
Here's a simple app reproducing the issue: http://plnkr.co/edit/BlhuI4XE5Etdc8vnETcr?p=preview

**Comment by Saulis** [comment]
As a slight workaround, `grid.refreshItems()` or `grid._grid.updateSize()` can be called manually after grid is visible to update the checkbox states.

**Comment by samiheikki** [comment]
Related:
https://vaadin.com/forum#!/thread/14344054
http://plnkr.co/edit/HWFgTNYPZyLN3DjvdLqi?p=preview

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version should not have this issue. Please upgrade to that, and add a comment if it does.

**Comment by robertop87** [comment]
Hi everyone,

is there a way to deselect All items?

**Comment by platosha** [comment]
@robertop87 `grid.selectedItems = [];` should do it.
