### ISSUE TITLE
Add ability to disable scroll/mouse events

### ISSUE THREAD

**Issue by billy-hardy** [vaadin/vaadin-grid#336]
Use case is to implement paging without chunking the data client side, since virtual paging is already done. So we need to turn off scrolling and just use the paging controls we provide (that way a "scroll trap" doesn't occur on the page).

**Comment by jounik** [comment]
The originating forum discussion: https://vaadin.com/forum/#!/thread/12636611

**Comment by bcrabbe** [comment]
+1. I have a page with 3 grids and its really difficult to scroll to the bottom of the page.

**Comment by jstanley1730** [comment]
+1 here as well, also need a way to get scroll events when scrolling over the vaadin grid element, we have another element we need to scroll along with the table

**Comment by Saulis** [comment]
As a workaround, you can try capturing the events.

```js
// for desktop users
grid.addEventListener('mousewheel', function(e) {
  e.stopPropagation();
}, true);

// for touch device users, might have unexpected side-effects.
grid.addEventListener('touchmove', function(e) {
   e.stopPropagation();
}, true);
```

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version has this fixed (no scroll trap), and you can see an example of a paging grid here: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha4/demo/pagination.html
