### ISSUE TITLE
Accessibility: Configure table caption, summary, tabindex and id

### ISSUE THREAD

**Issue by userquin** [vaadin/vaadin-grid#338]
How can I configure table caption, summary, tabindex and id?

I have configured this:

``` html
<vaadin-grid id="grid" items="[[data]]" on-selected-items-changed="_rowSelected">
   <table tabindex="0" summary="Some summary">
      <caption>Some caption</caption>

   </table>
   ....
</vaadin-grid>
```

but the resulting table has not any of the configured elements.

**Comment by jounik** [comment]
Hi,

I understand the use case for `tabindex`, and I we should proxy that to the correct element which should receive the keyboard focus.

For the `summary` attribute and `<caption>` element, what would you expect to happen? And why doesn’t the `id` attribute work?

**Comment by jouni** [comment]
I’m closing this issue as invalid, as it contains multiple separate issues. Please try the new 2.0 version and open new, separate issues for things that are still not working as expected. The use case for the `<caption>` and `<summary>` elements might be such, that we are not currently taking those into consideration in our a11y support in 2.0.
