### ISSUE TITLE
Vaadin-Grid as a Bower WebJar for Gradle and Maven

### ISSUE THREAD

**Issue by bartolom** [vaadin/vaadin-grid#339]
It would be nice to have the polymer based vaadin-grid element as a "Bower WebJar" packaged for Gradle and Maven so one can nicely pull it into a Java Spring Boot web application..

As a developer I can trigger the self-service creation of this artifact at http://www.webjars.org/bower by clicking the blue "Add a New Bower Webjar" button. When it would work it would automatically be deployed to Maven-Central which is very convenient for us Java Developers.

The first part looks good, and vaadin-grid is detected on Github. Also the version number "1.0.0" is detected correctly.

Unfortunatly there seems to be an issue with the Open Source license detected by webjars.org. 
"No valid licenses found. Detected licenses: Apache License 2.0"

This is the protocol of webjars.org. Please be aware that its in the reverse order (most recent line is at the top)

```
Failed! 
No valid licenses found. Detected licenses: 
Apache License 2.0 The acceptable licenses on BinTray are at: 
https://bintray.com/docs/api/#_footnote_1
License detection first uses the package metadata (e.g. package.json or bower.json) 
and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the 
master branch of the GitHub repo. 
Since these methods failed to detect a valid license you will need to 
work with the upstream project to add discoverable license metadata 
to a release or to the GitHub repo.  

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  

Created Bower WebJar 
Fetched Bower zip 
Generated POM 
Converted dependencies to Maven 
Got Bower info 
Determined Artifact Name: vaadin-grid 
Starting Deploy
```

When I follow the suggested link: https://bintray.com/docs/api/#_footnote_1 there seems to be the Apache-2.0 license amongs the long list:

"1. Available licenses: AFL-3.0, AGPL-V3, Apache-1.0, Apache-1.1, Apache-2.0, APL-1.0, APSL-2.0, Artistic-License-2.0, Attribution, Bouncy-Castle, BSD, ...."

I kind of assume that this might be just a naming problem like "Apache License 2.0" vs "Apache-2.0", so if one could adapt it on the vaadin site it might pass.

**Comment by bartolom** [comment]
This might be related:
https://github.com/webjars/webjars/issues/1020

It seems to be a bit more tricky for vaadin-grid. As far as I can see the bower.json and package.json seem to have the correct line that follows the referenced convention in https://spdx.org/licenses/.
```javascript
"license": "Apache-2.0",
```

I found two others project that are available as a "Bower Webjar" with Apache-2.0, so it must be technically possible.

https://github.com/SheetJS/js-xlsx
https://github.com/SheetJS/js-xlsx/blob/master/LICENSE
https://github.com/webjars/webjars/issues/1098

https://github.com/novus/nvd3/
https://github.com/novus/nvd3/blob/master/LICENSE.md
https://github.com/webjars/webjars/issues/1182
> jamesward commented on 28 Aug 2015
> This is available already as a Bower WebJar:
>"org.webjars.bower" % "nvd3" % "1.8.1"

Maybe webjars does still *first* check the LICENSE file and not package.json or bower.json.

The only unusual thing about the vaadin-grid LICENSE is that it's has a different order.
https://github.com/vaadin/vaadin-grid/blob/master/LICENSE

The typical start of Apache-2.0 on github seems to the equivalent of Line 178
https://github.com/vaadin/vaadin-grid/blob/master/LICENSE#L178

**Comment by bartolom** [comment]
I've got some feedback from jamesward in https://github.com/webjars/webjars/issues/1365 

jamesward commented 4 hours ago

>The problem is that the bower.json and package.json contain an invalid SPDX license identifier in `1.0.0`:
>https://github.com/vaadin/vaadin-grid/blob/1.0.0/bower.json#L7
>https://github.com/vaadin/vaadin-grid/blob/1.0.0/package.json#L6

>This has been fixed since 1.0.0 but we will need a new tagged release for it to work with Bower / NPM WebJars.

>The fallback to LICENSE on master should be working because the license is properly identified:
https://github-license-service.herokuapp.com/vaadin/vaadin-grid

>But I think we may not be using the fallback since the license was specified in metadata. It was just invalid. That might be something we can fix.

So there is a small fix on the webjars.org side, but it would also work when there would be a patch release on the Vaadin side, if I understand it correctly

**Comment by jounik** [comment]
Hi, and thanks for the investigation!

I don’t know what exactly has happened with the 1.0.0 stable release, as I specifically fixed this issue during in the release candidate (in fae46fb1958dff2452bc07ec638483a5e650a328). You can see it in the log for bower.json here: https://github.com/vaadin/vaadin-grid/commits/master/bower.json

Somehow the tag for 1.0.0 has been made from some other branch than master at the time.

We’ll make a new patch release for this, but can’t promise exactly when, as #318 might need to be resolved first.

**Comment by bartolom** [comment]
In the meantime someone else deployed vaadin-grid 1.1.0 and 1.1.1 to webjars.org, so this seems to be fixed now.
