### ISSUE TITLE
Vaadin-grid selected row background color needs a css variable

### ISSUE THREAD

**Issue by billy-hardy** [vaadin/vaadin-grid#341]
Add a css variable to background color for selected row, enabling developers to set background color without `::shadow` and `/deep/`

**Comment by OveysSafarnejad** [comment]
how can add some css to a row based on some fields values in vaadin 8 grid?

**Comment by tomivirkki** [comment]
Hi @OveysSafarnejad,
If the issue is about Vaadin Framework 8 Grid, [Here's](https://github.com/vaadin/framework) is the repository you're looking for. This is the repository of the `<vaadin-grid>` Web Component.
