### ISSUE TITLE
Selecting single result in a filtered grid causes entire grid to get selected

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#344]
If you filter down the contents of a grid to a single item and select that item with multi select mode activated, it will incorrectly select the entire grid.

Steps to reproduce: 
1. Go to https://vaadin.com/elements/-/element/vaadin-grid > Filtering demo
2. Type in 'aa' to narrow down contents to one row
3. Select row - observe that the select all checkbox gets selected
4. Clear filter - observe that entire grid is now selected

**Comment by jounik** [comment]
Works the other way as well:
1. Click the "select all" checkbox – all rows are selected
2. Filter to show just one row
3. Deselect that row
4. Clear filter – no rows are selected any more

**Comment by iures** [comment]
Any updates on this?

**Comment by NicolasRannou** [comment]
+1
