### ISSUE TITLE
Latest vaadin-grid and latest Polymer not working

### ISSUE THREAD

**Issue by rbjarnason** [vaadin/vaadin-grid#349]
I have used vaadin-grid in other projects past few months with great success, its a great element. However now when trying to add it to another project installing it with latest Polymer it does not work.

If I load data via ajax and do this.$.grid.items = detail.response I just get an internal v-grid spinner:
![vaadin-grid-error-1](https://cloud.githubusercontent.com/assets/43699/14499941/9e157b62-018f-11e6-9fcb-a5c24cafc100.png)

If I copy the "Inline Data" example from your website to my code I get a crash:
![vaadin-grid-error-2](https://cloud.githubusercontent.com/assets/43699/14499965/b4ea6956-018f-11e6-83ba-7fbc4cffa5e1.png)

I've spent 3-4 hours on this already, trying all the different methods, first with data via ajax but then different example with inline data.

If I add thead and header info to the table, I also get those Class$ error even if there is no inline data.

Any ideas?

**Comment by tomivirkki** [comment]
Hello, just tried our demos with vaadin-grid 1.0 and Polymer 1.4.0. Didn't have any issues.

Could you maybe provide a test case that we could use to identify the issue, a jsfiddle perhaps?

**Comment by rbjarnason** [comment]
Thanks @tomivirkki If it works with your demo then I doubt I can create a simple jsfiddle that will produce the problem.  My problem happens in a relatively large Polymer app, it's open source, I have replaced, temporarily, v-grid with a simple iron-list but the problem appears in the this element if I use v-grid instead of iron-list: https://github.com/rbjarnason/your-priorities-app/blob/master/client_app/elements/yp-user/yp-users-grid.html#L35

We are launching our app on the 29. April so I have limited time to track this down but I will try find the time to distill my problem to as simple test case as possible.  But I had tried for example to move the "Inline Data" v-grid example to my top level yp-app element but it had the same results.

**Comment by kito99** [comment]
+1 -- I have seen this issue as well. I have not seen a specific set of circumstances that can reproduce it, though. It's definitely causing issues with our testers. Considering rolling back Polymer.

**Comment by kito99** [comment]
FYI, I was able to reproduce this with Polymer 1.3.1 as well, although it happens less frequently..

**Comment by Saulis** [comment]
@rbjarnason @kito99 still having issues with this?

**Comment by kito99** [comment]
@Saulis: Nope. We haven't seen this in a long time.

**Comment by Saulis** [comment]
OK, I'll close this issue for now. Feel free to reopen if something comes up.
