### ISSUE TITLE
Remove hidden iframe

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#355]
Remove the hidden iframe used for resize events.

This would require that we remove the fixed pixel column measurements, and move to CSS based sizing using flex box.

How grid gets notified about the need to show more rows in the viewport needs to be solved somehow. One option is to only update the escalator row count when the user interacts with the grid somehow and on browser window resize.

**Comment by manolo** [comment]
Not only height but width is recomputed when the grid is notified by iframe changes.
Solutions:
 - replace iframe by object (we already used that in the beginning)
 - Only change sizes on window resize events
 - Wait until the user interacts with the grid, but this could have performance hits, trying to recompute sizes each time the user scrolls, overs, etc

**Comment by jouni** [comment]
Wontfix for 1.x. Invalid for 2.0.
