### ISSUE TITLE
Scroll bar doesn't stay visible only shows on scroll

### ISSUE THREAD

**Issue by summithca** [vaadin/vaadin-grid#358]
On Vaadin Grid for Polymer the Scroll Bar sets a visible / hidden tag in the div's style depending on scroll action. Visible upon scroll with mouse, hidden when action isn't called. How does one set this to stay visible?

**Comment by manolo** [comment]
You can change the behavior with CSS, try using these css selectors
.vaadin-grid-scroller[invisible]
.vaadin-grid-scroller[invisible]
.vaadin-grid-scroller-vertical[invisible]
.vaadin-grid-scroller-horizontal[invisible]

**Comment by jouni** [comment]
In the upcoming 2.0 version the scrollbars should behave more natively, so depending on the platform, they should always stay visible.
