### ISSUE TITLE
Unable to add any gwt widget inside VaadinGrid widget

### ISSUE THREAD

**Issue by rakesh-roshan** [vaadin/vaadin-grid#359]
`<v:VaadinGrid ui:field="vehicleTable">`
`         <table>`
`         <colgroup>`
`            <col name="vehicleName" header-text="{commonMsg.labelName}" width="150" sortable=""/>`
`              <col name="licensePlate" header-text="{vehicleMsg.labelLicensePlate}" hidable="" sortable=""/>`
`                <col name="vehicleYear" header-text="{commonMsg.labelYear}" hidable="" sortable=""/>`
`              <col name="licensePlate" header-text="{commonMsg.labelActions}" hidable=""/>`
`           </colgroup>`
`            <thead>`
`    			<tr>`
 `    				<th><g:Label text="Name"/> </th>`
`     				<th>License</th>`
`     					<th>Year</th>`
`   				<th>Actions</th>`
    				
`    			</tr>`
`    		</thead>`
`          </table>`

`        </v:VaadinGrid>`

Adding a <g:Label> throws an exception.

_Cannot find element with id "gwt-uid-26". Perhaps it is not attached to the document body._

**Comment by manolo** [comment]
We don't support adding widgets in the declarative html table, just elements.
This is in this way because we don't have a widgets hierarchy in the grid because of performance.

**Comment by rakesh-roshan** [comment]
Then how can I set the column names using internationalized text? I thought header-text in col element will be used for column names, but it is not so.
