### ISSUE TITLE
Click event on cell scrolls the viewport (IE)

### ISSUE THREAD

**Issue by davherrmann** [vaadin/vaadin-grid#364]
Hi there! 

If I have a partially visible grid (which is or is not focused) in the browser viewport (i.e. the top part visible), a click event in a cell causes a focus call on the v-grid element, which makes the IE scroll the element fully into the viewport. The same error might occur in Safari under OS X – see [Mousedown event on "select all" checkbox scrolls the viewport (OS X Safari)](https://github.com/vaadin/vaadin-grid/issues/53).

**Comment by jouni** [comment]
Wontfix for 1.x. The upcoming 2.0 version (now in beta) doesn’t suffer from the same issue, so please upgrade to that if possible (see the [migration guide](https://github.com/vaadin/vaadin-grid/wiki/Migration-from-1.*-to-2.0) for help).
