### ISSUE TITLE
Adding elements to the DOM programmatically is not working for IE11

### ISSUE THREAD

**Issue by teslor** [vaadin/vaadin-grid#377]
In IE11 all dynamically created DOM elements inside vaadin-grid elements are stripped out (also including created by custom data renderers).
Tested with version 1.1.0

**Comment by jouni** [comment]
Thanks for the report. So it works in all other browsers?

**Comment by teslor** [comment]
Yes, the same code in Chrome & FF is working ok. Also if I choose IE10 document mode in IE11 it also works ok. The problem is in standard (edge) mode in IE11. We are using vaadin-grid with Polymer 1.4.

**Comment by teslor** [comment]
Hi! Any thoughts about this issue? Can we hope for the fix? :)

**Comment by Saulis** [comment]
Hi there @teslor !

Could you elaborate a bit on what part of the DOM are you exactly touching and what are you trying to achieve? And simple example app would be awesome.

Here's a naive example as a basis I made for adding stuff to the element dynamically with a push of a button: http://plnkr.co/edit/NGEosmZvM6lw3dQlQWw0?p=preview . 

In general, adding elements dynamically inside cells is a bit problematic since the table cell elements are being reused – you'd need to keep track on the added elements vs. cells they've been added into.

**Comment by teslor** [comment]
Hi  @Saulis !

We create elements dynamically in the table header e.g. for filtering features and also use custom renderers for cells in some our tables.
Here is a simple example (input for filtering) based on yours:
http://plnkr.co/edit/fSsR7Ar40mrUh7HTO8uY?p=preview
(it's near the same as example in you manual for cell content - https://vaadin.com/docs/-/part/elements/vaadin-grid/headers.html)

The code in example works fine in all browsers, including IE11.
Also such code worked fine in our app too until we updated polymer & vaadin-grid.
Now in our app it works in Chrome & FF, and doesn't in IE11.

Here is fragment of our definitions in bower.js:
"dependencies": {
  "polymer": "Polymer/polymer#1.4.x",
  "vaadin-grid": "^1.1.0",
  "webcomponentsjs": "0.7.21",
},
"resolutions": {
  "polymer": "^1.0.0",
}

Common custom renderers now also doesn't work for us in IE11. They are rather simple as in your example (e.g., we use them to show icons instead of boolean values etc.)
So we cannot understand where is the problem. And why the same code works in all browsers except IE11 (& probably further versions of IE).

**Comment by tomivirkki** [comment]
Hi, tried the example you linked in the previous comment. It worked fine for me on IE11 (Edge mode) as shown in the image. What exactly is broken in the example?
![screenshot 2016-06-21 08 56 41](https://cloud.githubusercontent.com/assets/1222264/16256298/e50cf1d4-3859-11e6-9bce-6aa2899697dd.png)

**Comment by teslor** [comment]
@tomivirkki 
Hi! This example is just an illustration of code which is not working for us. I didn't write this concrete example is not working in IE11, quite the opposite I wrote "The code in example works fine in all browsers, including IE11."  The problem with such code is in our app, and only in IE.

**Comment by tomivirkki** [comment]
Sure, but without knowing the details of your actual app it's impossible for us to guess why it's breaking there but not in the example. Can you provide an example that breaks on IE11 the same way as in your app so we have something to start with?

**Comment by teslor** [comment]
Recently I had some debugging in IE11, it seems the problem is in .then() vaadin-grid method.
All dynamic components in our app are created inside this method.
For some reason in IE11 the grid inside this method is not actually ready to create elements.
Since in the examples above everything is ok probably we have problem because there are much code to execute, I don't know.
How I checked this:

I replaced our code

```
grid.then(() => {
...code...
}
```

with:

```
setTimeout(() => grid.then(() => {
...code...
}), 0);
```

And after this change the elements are correctly created in IE11 too.
What do you think about this? Thanks!

**Comment by tomivirkki** [comment]
Ah, I see.
There's a lot of asynchronous stuff going on inside of grid and there may still be some timing issues we're not aware of/haven't covered in then(). Need to look into this more. Nice if you've found a workaround for now 👍

**Comment by jouni** [comment]
We are not considering any further fixes for 1.x. Please upgrade to 2.0 (now in beta) if possible.

**Comment by kito99** [comment]
@jouni has this been fixed in 2.0?

**Comment by jouni** [comment]
@kito99 you can add/remove vaadin-grid-column elements programmatically. Changing the templates inside the column elements is not supported, but you can instead either have two separate columns you switch between, or use data binding or dom-if inside the templates to change the contents. Here’s an example of that: https://cdn.vaadin.com/vaadin-grid/2.0.0-beta1/demo/crud.html

**Comment by jouni** [comment]
Here’s an example of dynamically adding columns to the grid: https://cdn.vaadin.com/vaadin-grid/2.0.0-beta1/demo/columns.html#dynamic-columns-using-dom-repeat
