### ISSUE TITLE
Paper-input inside vaadin-grid

### ISSUE THREAD

**Issue by DeadcatDev** [vaadin/vaadin-grid#380]
Hi, have following problem with very simple table:

```
<vaadin-grid>
    <table>
        <colgroup>
            <col>
            <col>
            <col>
        </colgroup>
        <tbody>
    <template is="dom-repeat" items="{{pages}}">
        <tr>
            <td>
                <a on-tap="unbindPage">
                    <iron-icon icon="icons:arrow-back"></iron-icon>
                </a>
            </td>
            <td>
                {{item.name}}
            </td>
            <td>
                <paper-input
                        id="position-{{item.id}}"
                        name="position-{{item.id}}"
                        value="{{item.position}}"
                ></paper-input>
            </td>
        </tr>
    </template>
        </tbody>
    </table>
</vaadin-grid>
```

Input is not-clickable nor editable. It may save on-change but im not able to add any value to paper-input because of (probably) focus on row.

Any idea how to use paper-input inside grid table? Also no value inside paper-input on start (value exists).

**Comment by manolo** [comment]
Just a comment  `grid.set('items.rowIndex.name', e.detail.value)` in last code block  is better since the grid gets notified that the object changed and would update anything needed.
