### ISSUE TITLE
tick.svg is omitted by Polymer CLI build

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#384]
When building an app with Polymer CLI, the tickmark gets left out. 

![bnqalcaghg](https://cloud.githubusercontent.com/assets/883698/15874191/e55e65d6-2cb6-11e6-9771-b718ca8382e5.gif)

**Steps to reproduce**
1. Init a project with `polymer init app-drawer-template`
2. `bower install vaadin-grid`
3. Import and add Vaadin grid to `my-view1.htm`l
4. Run polymer build
5. Serve built folder `polymer serve build/bundled`

**Comment by jouni** [comment]
Is it only the tick, or are the sort indicators also missing? Sounds like the same issue as with vulcanize, described here: https://github.com/vaadin/vaadin-grid/issues/323#issuecomment-188793176

**Comment by Saulis** [comment]
Are you still able to reproduce this? I can't, using `polymer-cli` `v0.12.0` and `vaadin-grid` `v1.1.0`

**Comment by jouni** [comment]
Wontfix for 1.x. 2.0 is not affected by this, and should vulcanize as expected.
