### ISSUE TITLE
--vaadin-grid-header-row-height

### ISSUE THREAD

**Issue by nika-begiashvili** [vaadin/vaadin-grid#385]
I think in firefox if you set --vaadin-grid-header-row-height to 5px for example, selection stops working

**Comment by Saulis** [comment]
Hi!

Could you be able to provide an app where this happens?

Tried reproducing the issue here: http://jsbin.com/yinifohate/edit?html,output, but for me atleast Firefox seems to be selecting the rows just fine.

**Comment by jouni** [comment]
Cleaning up. Please reopen if this is still an issue for you.
