### ISSUE TITLE
Sort order indicators missing

### ISSUE THREAD

**Issue by McPringle** [vaadin/vaadin-grid#386]
vaadin-grid 1.0.0
Polymer 1.4.0
Firefox 42.0
Internet Explorer 11.0.9600.18163

**Comment by Saulis** [comment]
Hi!

Would you be able to provide an example app where this happens? 

Tried to reproduce with https://cdn.vaadin.com/vaadin-core-elements/1.0.0/vaadin-grid/demo/sort.html running Firefox 46 on OSX and IE11 on Win 7 but they both work just fine.

**Comment by McPringle** [comment]
Thank you for you response! It looks like there is a problem with the server or port because if I serve the HTML with WebSphere I see the icons and if I serve with pythons HTTP server they are missing (but only the icons used by vaadin-grid are missing, other iron-icons on paper-buttons etc. are working). Please give me a few days to investigate the source of the problem.

**Comment by Saulis** [comment]
OK, the difference might be that `vaadin-grid` uses SVG icons defined in CSS as urls whereas `<iron-icon>` uses svg elements embedded in the html. Maybe the Python server doesn't allow fetching SVG files?

**Comment by Saulis** [comment]
@McPringle did you find the issue?

**Comment by McPringle** [comment]
Oh yes, sorry for not coming back. I forgot this issue. I found out that the Python HTTPServer did not deliver SVG files. So it is *no* problem with *vaadin-grid*! Thank you for you demand, @Saulis
