### ISSUE TITLE
vaadin-grid: updating while scrolling

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#388]
_From @ccschneidr on June 13, 2016 7:45_

Vaadin Grid looks great and fulfills many of our need for a data table. One issue I could not yet resolve is "flickering" while scrolling to new records. The actual flickering is not caused by the grid but by the elements shown, but the grid is the only thing that can help: when inserting something different than text (e.g. images) these elements might take a short time to load. On the other hand elements reused while scrolling probably animate to their new state when inserted at the other end. To avoid this kind of user-irritating effects I would like to increase the number of invisible rows / amount of invisible space when scrolling. Is this already possible? If no would it be easy to introduce? Or do you have another idea to allow data elements to initialize themselfes for some time before showing them to the user (at least for slow scrolling)?

_Copied from original issue: vaadin/vaadin-core-elements#57_

**Comment by Saulis** [comment]
Unfortunately there isn't any public parameters available that could be modified to increase the amount of row elements. There is one internal parameter really deep inside, but increasing that will only help when scrolling down, so I'm afraid there aren't any easy fixes for this.

Btw, have you tried using `<iron-image>` for images with `preload` ? Should replace the image with a placeholder while loading, I'd imagine that could be atleast a slight improvement for the flickering.

**Comment by ccschneidr** [comment]
Well, yes, I have a special component for images. But as you said it does not really solve the overall problem. That parameter for scrolling down would be interesting - that's the more important case anyways. Can I patch it locally to give it a try? How can I find it? Maybe it's worth exposing it then...

**Comment by Saulis** [comment]
Well, like I said it's pretty deep in there and you need to add some extra files to be able to compile it 😄 

Please try https://gist.github.com/Saulis/01a75d082e5ccaabe98d9ff003a310de if it works any better for you. That applies +10 more TR elements below when its being scrolled down.

**Comment by ccschneidr** [comment]
Hmm, it does not seem to be a drop-in replacement for my 1.0.0 version. It just prints
```
vaadin-grid.min.js:480 Uncaught TypeError: Cannot read property 'appendChild' of undefined
_.init @ vaadin-grid.min.js:480
ready @ vaadin-grid.html:1014
_invokeBehavior @ polymer-micro.html:433
_doBehavior @ polymer-micro.html:428
_readySelf @ polymer-mini.html:88
_ready @ polymer-mini.html:75
_tryReady @ polymer-mini.html:60
_initFeatures @ polymer.html:3584
createdCallback @ polymer-micro.html:189
window.Polymer @ polymer-micro.html:61
(anonymous function) @ vaadin-grid.html:711
```
when I use it instead of mine.

**Comment by Saulis** [comment]
@ccschneidr oh right, I compiled that from the master version, can you try with that?

**Comment by ccschneidr** [comment]
Sure. Thanks.
Nope, it only makes the trace shorter:
```
vaadin-grid.min.js:480 Uncaught TypeError: Cannot read property 'appendChild' of undefined
window.Polymer @ VM19104 polymer-micro.html:61
```

**Comment by Saulis** [comment]
Hmm, ok I've pushed my test version of the grid including the javascript file to branch `increase-buffer`, can you try installing that?

**Comment by ccschneidr** [comment]
Yeah, works like a charm in the datasources demo. It makes scrolling down a way better user experience :-)
But 63eb68 contains only changes to the minified version. What's the actual source difference and how would I transfer it to 1.0 to test it? Or should I try to build a complete dist?

**Comment by Saulis** [comment]
If you're working on top of `1.0`, you can try changing https://github.com/vaadin/vaadin-grid/blob/1.0/java/src/main/java/com/vaadin/client/widgets/Escalator.java#L2940 to add more than `+1` and then recompiling with `gulp gwt`. 

For later versions it gets a bit trickier since we've dropped our own fork of `Escalator.java` from the repo and use the vanilla one.

**Comment by ccschneidr** [comment]
Hmm, later versions? Maybe I'm missing something. I was using the "latest" release v1.0.0 from here https://github.com/vaadin/vaadin-core-elements/releases, and thought this would match to the "1.0" git branch.
But building the 1.0 branch fails early for me; `npm install` fails with
```
npm WARN package.json vaadin-grid@1.0.0 No repository field.
npm WARN package.json vaadin-grid@1.0.0 license should be a valid SPDX license expression
/
> vaadin-grid@1.0.0 install D:\Workspaces\Motion\git\vaadin-grid
> bower install --allow-root

npm WARN unmet dependency D:\Workspaces\Motion\git\vaadin-grid\node_modules\gemini requires chalk@'^0.5.1' but will load
npm WARN unmet dependency D:\Workspaces\Motion\git\vaadin-grid\node_modules\chalk,
npm WARN unmet dependency which is version 1.1.3
npm WARN unmet dependency D:\Workspaces\Motion\git\vaadin-grid\node_modules\web-component-tester\node_modules\wct-local\node_modules\launchpad\node_modules\rest
ify\node_modules\vasync requires verror@'1.6.0' but will load
npm WARN unmet dependency D:\Workspaces\Motion\git\vaadin-grid\node_modules\web-component-tester\node_modules\wct-local\node_modules\launchpad\node_modules\rest
ify\node_modules\verror,
npm WARN unmet dependency which is version 1.6.1
```
leaving a subsequent `gulp gwt` with `Error: Cannot find module 'tough-cookie'`
Any more info on how to build than [here](https://github.com/vaadin/vaadin-grid)?

**Comment by Saulis** [comment]
the `vaadin-core-elements` bundle only has the most recent stable versions, for newer stuff you want to look into each individual repository: https://github.com/vaadin/vaadin-grid/releases

Looks like one of the npm dependencies doesn't install.. does `npm install tough-cookie` work?

**Comment by Saulis** [comment]
@ccschneidr any progress?

**Comment by ccschneidr** [comment]
At least I have migrated to 1.1.0-beta4. But I still was not able to use the version from the repository in my project. I need to try that before getting back to the scrolling issue.

**Comment by ccschneidr** [comment]
Confirmed to work very well with the "increase-buffer" branch in my application (without rebuilding). But npm install does not work for me either.
It would be great if this modification or even an option for it could make it into a release. But I guess it would require a change to the project containing the Escalator.java, doesn't it?

**Comment by Saulis** [comment]
Yeah it would most likely require a PR somewhere [here]( https://github.com/vaadin/vaadin/blob/master/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2874).

**Comment by jouni** [comment]
@ccschneidr, would you be able to upgrade to 2.0, as we are not considering any further fixes for 1.x? The buffer of elements is much bigger in the new version, and should produce a smoother scrolling experience.

**Comment by ccschneidr** [comment]
I will certainly try it when I have time. I'm currently distracted by other projects. But when I get back to this I'll have a look at upgrading.

**Comment by tomivirkki** [comment]
Closing as inactive.
