### ISSUE TITLE
column.headerContent property doesn't seem to work

### ISSUE THREAD

**Issue by dirtysanchez69** [vaadin/vaadin-grid#391]
I can't seem to set **column.headerContent** programmatically.

I'm following this doc:
![snap 2016-06-20 at 20 20 40](https://cloud.githubusercontent.com/assets/10526720/16214268/8872b39a-3724-11e6-85a4-f00a11cc794a.png)

     <body>
          <vaadin-grid selection-mode="multi">
               <table>
                     <col name="firstName">
                     <col name="lastName">
                     <col name="email">

               </table>
          </vaadin-grid>

          <script>

               document.addEventListener("WebComponentsReady", function () {

                    var grid = document.querySelector("vaadin-grid");

                    grid.items = [
                         { "firstName": "Hugo", "lastName": "Romero", "email": "hugo.romero@example.com" },
                         { "firstName": "Nieves", "lastName": "Diez", "email": "nieves.diez@example.com" },
                         { "firstName": "Esteban", "lastName": "Vega", "email": "esteban.vega@example.com"},
                         { "firstName": "Roxane", "lastName": "Diez", "email": "roxane.diez@example.com" }
                    ];
   
                   // LOOK HERE
                   grid.columns[0].name = "hello";  // this works
                   grid.columns[1].width = 100;  // this works
                   grid.columns[0].headerContent = "test";  // this doesnt work
                   grid.columns[1].headerContent = "test1";  // this doesnt work
                   console.log(grid.columns);
   
              });
       </script>
     </body>

This is the visual output:
![snap 2016-06-20 at 20 28 45](https://cloud.githubusercontent.com/assets/10526720/16214407/e89266b6-3725-11e6-90a6-d2c87701bf51.png)

Here's the output to the console ***console.log(grid.columns);***
Interestingly "headerContent" in the only one that is automatically open. All other properties show "(...)" as their value until clicked.

![snap 2016-06-20 at 20 34 06](https://cloud.githubusercontent.com/assets/10526720/16214451/5891d12c-3726-11e6-8bbc-e207bc3a9776.png)

Another point of interest is that if I do not specify any properties in my code, headerContent does not show in the console, while the other ones still do.

Am I doing this wrong?
Are the docs outdated?

**Comment by Saulis** [comment]
Hi!

Yeah the docs are unfortunately outdated, so the `headerContent` property has actually been removed before `1.0.0`. 

The way to access the header contents is `grid.header.getCell(0,0).content = 'foo'`

I'll update those docs.

**Comment by Saulis** [comment]
Fixed in 17e491b and released in `v1.0.1`.

**Comment by dirtysanchez69** [comment]
Is there any way to set it from ***grid.addColumn()*** ??

This is what I would like to do:
          grid.addColumn({
            headerContent: "Column Title", // doesnt work
            name: "propertyName", // works
            sortable: true
          });

**Comment by tomivirkki** [comment]
Hi
Can't set an explicit header title with addColumn function but setting the content afterwards is just a oneliner:

```
grid.addColumn({
  name: "propertyName",
  sortable: true
});
grid.header.getCell(0, grid.columns.length - 1).content = "Column title";
```

**Comment by dirtysanchez69** [comment]
Ok, that's actually exactly what I've done. Glad to know it's the correct method.

Thanks a lot, Tomi
