### ISSUE TITLE
IE 11 Issue - sort order icon size issue

### ISSUE THREAD

**Issue by amit-gajjar** [vaadin/vaadin-grid#392]
The sort order icon size is not appropriate on IE 11. The icon is displayed very tiny. It is fine on other browsers, but not working as expected on IE 11. I tried to modify the CSS and it works on IE 11 as well as other browsers. 

Below is code snippet, changing from padding-left to margin-left fixes it.

`.vaadin-grid-header [class*="sort-"]:after {
    font-size: 8px;
    margin-left: 8px;
    width: 1em;
    min-width: 12px;
    display: inline-block;
}`

also there is one more issue on IE 11, on click of the column name the sort event is not triggered, need to click on sort icon or near by the column name, but click on column name is not working.
It would be great you can provide fix for IE 11.
![ie11_issue_sort_icon](https://cloud.githubusercontent.com/assets/17540232/16224599/55e7ab8c-37c0-11e6-9d25-051d1b43fd0e.jpg)

Thanks in advance.

**Comment by tomivirkki** [comment]
Hi @amit-gajjar

Have you tried with the newest release (1.1.0) yet? The sorting icons look ok to me and seems that the issue with clicking the column name is fixed as well.

Here's the demo I tested with https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/sort.html

**Comment by jouni** [comment]
Are you still having this issue @amit-gajjar? We are not considering any further fixes for 1.x, and encourage everyone to upgrade to 2.0.
