### ISSUE TITLE
Problem with bootstrap and menu of hidable columns

### ISSUE THREAD

**Issue by terracott** [vaadin/vaadin-grid#396]
Hello!

In my project I use bootstrap styles and vaadin-grid. And I found some problem: when click on a menu item (Show/Hide columns) it disappears.

To reproduce the problem, I used an existing example: https://jsfiddle.net/1xpexv2v/ (add bootstrap.min.css as external resource and define hidable columns).

**Comment by tomivirkki** [comment]
Hello @terracott,

There seems to be a global CSS rule for `hidden` class name in Bootstrap that forces elements with that class to have `display: none`.

With native shadow enabled this wouldn't be a problem but as shady DOM is still the default with Polymer, components' local DOMs are exposed to leaks such as this.

You can get around this issue by forcing `display: table-cell` on the hidden element with a stronger selector than the one in Bootstrap.

For example:

```
vaadin-grid .column-hiding-toggle {
  display: table-cell !important;
}
```

https://jsfiddle.net/1xpexv2v/1/

**Comment by terracott** [comment]
Thanks!
