### ISSUE TITLE
Calling refreshItems () too soon causes exception

### ISSUE THREAD

**Issue by dickp** [vaadin/vaadin-grid#405]
After updating to v1.1.0 from v1.0.1 I was suddenly getting an exception when calling refreshItems () on a grid.

I need to trigger a re-render of certain columns when a configuration property changes, so I have an observer for it.  This observer fires when the property is set for the first time at application startup, which worked fine with v1.0.1.

The refreshItems () method calls this._grid.getDataSource().refreshItems() - but when the observer fires, the grid's _itemsChanged () observer has not yet fired (the observer fires before my element's ready () callback has been called).  This leads to this._grid.setDataSource() not yet being called, so getDataSource() returns undefined.  Hence the exception.

I can't see anything obvious in the diff between 1.0.1 and 1.1.0 that would cause _itemsChanged () to be called later.

A simple workaround is to check grid.items is defined before calling grid.refreshItems ().

**Comment by manolo** [comment]
grid uses promises to notify when it's ready. You can use the `grid.then(function(){})` instead. Can you try it and report whether that works for you ?

**Comment by dickp** [comment]
Yes, that works too.

Thanks.
