### ISSUE TITLE
Integration of Vaadin-elements in Seed Project

### ISSUE THREAD

**Issue by abhibly** [vaadin/vaadin-grid#406]
Hello...I have read the documentation regarding setup of vaadin elements in angular2 application.I am using anguar2 seed project (reference-> https://github.com/mgechev/angular2-seed).I couldnt find systemjs.config.js in that repo.I want to know whether defining the packages of vaadin elements in system js file is necessary.If it is not necessary to define them in systemjs file how can i use vaadin elements.is there any alternate way that i can use them in this project. Thanks...

**Comment by manolo** [comment]
We still do not support angular2-seed not have experimented our components with it.
You should be able to setup following our documentation a project based on the starter angular project or using the angular2-cli which seems the two more popular options.
We will discuss internally if we support the seed project as well.

**Comment by jouni** [comment]
Hi! We are not actively supporting the use of our elements in Angular. I suggest you try to ask for help in the [angular-polymer project](https://github.com/platosha/angular-polymer).
