### ISSUE TITLE
Capturing click event on a cell

### ISSUE THREAD

**Issue by misoucouma** [vaadin/vaadin-grid#407]
Hi,
Is there any built in event that we can capture when a user clicks on a cell ?
I am trying to add editing capabilities to the grid, so I need to to capture the click event and the underlying object used in binding.

**Comment by mshahidkhan** [comment]
You can use cellRenderer, append a custom element (button/anchor) in the cell and user your own on-click/on-tap action.
Check this out -
http://codepen.io/mskhan0781/pen/jqQBQr?editors=1111

**Comment by manolo** [comment]
@mshahidkhan :  That is a good example thanks for sharing.
@misoucouma : The grid handles all click events of its children in order to focus and select the component. The way to capture events is that you use cellRenderer as @mshahidkhan suggest, but you have to stop-propagation to avoid the grid reusing the event.
There is a PR #408 in review to ignore clicks over certain html elements, that would mitigate that you have to stop-propagation, but anyway you need to use cellRenderers.
Since the grid reuses cells because of performance you have to be aware that you add the event once.

**Comment by misoucouma** [comment]
that was exact what I was looking for. I actually had a trouble with the event firing more than once.
I solved  the issue by attaching the click event to the lower level child of the TD cell.  Also, to get the column name from the cell that has received a click, cols of the colgroup must have attribute "name"

**Comment by manolo** [comment]
Well, you have the cell info including column name, column index, data, row index, etc, in the moment the current cell is renderer.
Also you can figure-out when you have to setup the dom-tree and start listening for events.

Hope this example helps you:

```
column[0].renderer = function(cell) {
  var first = !cell.element.hasChildNodes();

  if (first) {
    // Add the DOM structure the first time to improve performance.
    cell.element.innerHTML = "<my-element></my-element>";
  }
  var elem = cell.element.querySelector("my-element");
  if (first) {
    // Add event listener first time
    elem.addEventListener('click', function(ev){
      // Avoid grid handling click for selection
      ev.stopPropagation();
      // We have current cell info in the element
      columnName = elem.cell.columnName;
      columnIndex = elem.cell.index;
      rowIndex = elem.row.index;
      myEventHandler(rowIndex .... );
      
    });
  }

  // Save cell info in element because the cell instance is reused.
  elem.cell = {
    index: cell.index,
    columnName: cell.columnName,
    data: cell.data,
    row: {index: cell.row.index, data: cell.row.data}
  };
};

```

**Comment by jouni** [comment]
This use case should be easily accomplished in the upcoming 2.0 version (now in beta).

We are not planning on doing any enhancements regarding this for 1.x. I hope the workarounds provided in this issue are enough.

**Comment by luochenhuan** [comment]
@jouni  I am implementing similar function in 2.0, but I couldn't find an easy way to accomplish it. Could you elaborate on how to achieve it in 2.0?

**Comment by luochenhuan** [comment]
Actually I figured it out. For those who are looking into the same problem, just add a listener on `cell-activate` event, which could be found [here](https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-cell-click-mixin.html#L42).
