### ISSUE TITLE
Vaadin-grid show/hide the columns by click method using angular2

### ISSUE THREAD

**Issue by suma-nunna** [vaadin/vaadin-grid#409]
Hi

I have a vaadin-grid in my  angular2 project with different columns like (column heder: firstname, lastname, age, city, country). I'm trying for the functionality to hide and show a particular column. whenever i clicked on column header of firsname then only the lastname column has to display in the vaadin-grid.

Can any one help me to acheive my task.

Thank you.

**Comment by sharathsjc** [comment]
Me too having the same issue...... need some help guys....... even tried with jquery but no use

**Comment by platosha** [comment]
Hello, see the detailed answer in [the StackOverflow topic](http://stackoverflow.com/a/38400114/4901319).

**Comment by sharathsjc** [comment]
Thank you @platosha , will check now

**Comment by suma-nunna** [comment]
Thanks @platosha
