### ISSUE TITLE
Inconsistent fonts across vaadin elements -- Should mirror paper styles. 🖊

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-grid#410]
Currently, vaadin-grid, vaadin-upload, vaadin-date-picker and vaadin-combo-box treat fonts differently. They should all instead use paper styles as a default and expose mixins for changing styles.

Problems specifically are:
- date-picker applies --paper-font-common-base
- upload applies --paper-font-button
- combo-box does nothing about fonts
- grid uses font-family: arial

**Comment by jouni** [comment]
Version 2.0 does not use Material design styling by default and does not import paper styles. We’ll keep this in mind when adding the material inspired theme for 2.0.

Wontfix for 1.x.
