### ISSUE TITLE
select row and go to route?

### ISSUE THREAD

**Issue by BenevidesLecontes** [vaadin/vaadin-grid#416]
Hi all! Is possible to select a row and go to a specific route? Eg: details/id.

**Comment by Saulis** [comment]
Hi!

You can listen to `selected-items-changed` and then redirect the browser based on the selection.

Please see https://vaadin.com/docs/-/part/elements/vaadin-grid/vaadin-grid-selection.html#vaadin-grid.selection.selected for details.

**Comment by jouni** [comment]
Closing, as this is more a question than an issue. Please ask questions on https://gitter.im/vaadin/vaadin-core-elements or https://vaadin.com/forum/#!/category/9848927
