### ISSUE TITLE
Deleting last entry from grid dataset throws Error

### ISSUE THREAD

**Issue by AlexNasonov** [vaadin/vaadin-grid#417]
If I splice last entry from grid data and run 

```
grid.items = this.data;
grid.size = this.data.length;
grid.refreshItems();
```

I get `vaadin-grid.min.js:408 Uncaught TypeError: Cannot read property 'Kd' of null`
Not much helpful as I don't have dev version vaadin-grid script ((

**Comment by Saulis** [comment]
Hi!

When using an array with `items` property, make sure you use the Polymer methods like `pop`, `splice`, etc. to modify the array.

Here's an example: http://jsbin.com/zozazi/edit?html,output

**Comment by AlexNasonov** [comment]
I do it via splice, like:
```
var index = data.indexOf(item);
 if (index > -1)  data.splice(index, 1);
grid.items = data || [];
grid.size = data.length;
grid.refreshItems();
```

**Comment by tehapo** [comment]
Just to clarify a bit, Sauli was suggesting to use Polymer's own [array mutation methods](https://www.polymer-project.org/1.0/docs/devguide/properties#array-mutation).

I modified the previous JS Bin example to use Polymer's `splice` method.
http://jsbin.com/turifuzuha/edit?html,output

**Comment by AlexNasonov** [comment]
My strategy was to create new array and replace table items array as whole - in this case I had this error only if I remove last item.
If I use `this.splice()` directly on items array, it throws error each time i run remove an item((( 
so it's even worse)))

**Comment by AlexNasonov** [comment]
http://jsbin.com/yateru/edit?html,output
throws
vaadin-grid.min.js:410 Uncaught TypeError: Cannot read property 'Nd' of null

if you try to remove item on select

**Comment by tehapo** [comment]
Seems like the issue here is that `vaadin-grid` gets a bit confused over deleting the row while it is also being focused and selected.

If you clear the selection before the removal, you get rid if the error.
```javascript
if (selected.length > 0) {
   grid.selection.clear().then(function() {
     for (let i of selected) {
       self.removeItem(i);
     }
   });
}
```

**Comment by jouni** [comment]
Wontfix for 1.x, as we are not planning on doing any more fixes for 1.x, and the workaround provided by tehapo is viable.

This issue does not affect the upcoming 2.0 version (now in beta), and we encourage you to upgrade to that as soon as possible.
