### ISSUE TITLE
Grid is resizing very slow

### ISSUE THREAD

**Issue by vimalraj-a** [vaadin/vaadin-grid#419]
I am using vaadin-grid v1.1.1. Vaadin Grid is awesome. But, It seems slow  on resizing and initial render.
I ran Chrome's Timeline Analyser then I came to know that `getBoundingClientRect` called many times during the window resize. If this can be fixed, vaadin-grid become super awesome and run like breeze.

**Chrome Timeline - Grid with 133 records**
![Chrome Timeline](https://cloud.githubusercontent.com/assets/13977942/17567696/0c38dcb6-5f5e-11e6-9221-fa32a64ccda1.png)

**Comment by Saulis** [comment]
Hi!

Thanks for the report! We are aware of the performance issues regarding resizing and do our best to improve in the future releases.

**Comment by jouni** [comment]
Please upgrade to version 2.0 (now in beta), which should be much, much in many regards, including resizing performance.

We are not considering any further performance improvements for 1.x.
