### ISSUE TITLE
Column Reordering Bug?

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-grid#427]
I'm just trying out the column reordering at https://github.com/vaadin/vaadin-grid/commit/d252b3f94f10cdce8f693b3ebfefb7f5f30c5237 and I'm getting a weird behaviour where switching the last two columns seems to do nothing but change the headers sometimes.

See: 
![reorder-bug](https://cloud.githubusercontent.com/assets/4591840/17823637/6159612e-6612-11e6-8963-b3fb142271bf.gif)

Relevant code snippet is: 
```html
<vaadin-grid column-reordering-allowed frozen-columns="1">
        <table>
          <colgroup>
            <col>
            <col>
            <col>
            <col>
          </colgroup>
          <thead>
          <tr>
            <th>Frozen column</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>1</td>
            <td>Alice</td>
            <td>Williamson</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Florence</td>
            <td>Lewis</td>
            <td>Male</td>
          </tr>
          <tr>
            <td>3</td>
            <td>Trevor</td>
            <td>Ramirez</td>
            <td>Female</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Herbert</td>
            <td>Collins</td>
            <td>Genderqueer</td>
          </tr>
          <tr>
            <td>5</td>
            <td>Roy</td>
            <td>Spencer</td>
            <td>Male</td>
          </tr>
          </tbody>
        </table>
      </vaadin-grid>
```

There's nothing fancy there.

**Comment by juniperbelmont** [comment]
Um... it seems to be working worse than I thought it would:
![reorder-bug-2](https://cloud.githubusercontent.com/assets/4591840/17823956/fa1e1aa2-6613-11e6-9805-7d56f1c3e38e.gif)

When I select a row, all of the columns revert to their original locations.

**Comment by juniperbelmont** [comment]
I should have done this earlier, but I can also reproduce this bug in stable Safari and Firefox.

**Comment by tehapo** [comment]
This is actually not a bug, but a limitation of using light DOM or plain arrays for data. When using column reordering, you must use objects data and bind them to the column configuration properly.

Made a PR https://github.com/vaadin/vaadin-grid/pull/432 to document this limitation and also prevent such partial reordering effects seen before.
