### ISSUE TITLE
Row details broken (regression)

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#428]
Details in latest does not work : 
https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/details.html

Otherwise it works in : 
https://vaadin.com/docs/-/part/elements/vaadin-grid/details.html

**Comment by PIR3M** [comment]
I've just tested with Chrome (55) and Firefox (50).
vaadin-grid  1.2.0.
The demo is not working. the detail expands but with empty content. I think there's something weird inside the `rowDetailsGenerator` function. Inside the function, the `getItem` method callback is never called...
