### ISSUE TITLE
Sorting by multiple columns functionality

### ISSUE THREAD

**Issue by fafcrumb** [vaadin/vaadin-grid#431]
The [docs on sorting](https://vaadin.com/docs/-/part/elements/vaadin-grid/sort.html) demonstrate the functionality to have multiple columns with an active sort, and have the headers numbered accordingly. However, clicking on headers clears this ordering and only makes the header you just clicked on active.
Is there some option somewhere to make the sorting order the order the columns are clicked in?
If not, is it something that can be added?
Can I implement it myself in my own project? If so, what should I be looking to change?

**Comment by manolo** [comment]
If I understand correctly, you want to multi-sort using the mouse. To do that you have to click on the header at the same time you push the shift key. does it work for you ?

**Comment by jouni** [comment]
Shift-click is not very intuitive or discoverable, and we should possibly rethink the interaction for column sorting.

Here’s my current opinion:
- Column sorting should be tri-state, and cycle between these states with click/tap
  - Default: the user has not explicitly sorted that column (the column can still be sorted by the data source)
  - Ascending
  - Descending
- No modifier keys necessary for multi-column sorting, as the user can independently click the headers to sort any column
- The sort order is determined by the order in which columns are sorted ascending/descending. If a column state changes from descending -> default, it is removed from the sort order, and the remaining columns are automatically shifted in the order by one.

**Comment by jouni** [comment]
@Saulis’s iron-data-table works exactly like this (scroll down to the sorting demo): https://saulis.github.io/iron-data-table/demo/filtering.html

**Comment by fafcrumb** [comment]
Thanks for the help guys.

The behavior @jouni describes is exactly what I envisioned, and would be excellent to have as an option in a future update.

For now, shift click is fine, but to help those who missed it like me, it would be worth mentioning this in the [docs on sorting](https://vaadin.com/docs/-/part/elements/vaadin-grid/sort.html).

**Comment by tehapo** [comment]
@fafcrumb It is mentioned in the ["new" version of docs](https://vaadin.com/docs/-/part/elements/vaadin-grid/vaadin-grid-sorting-data.html).

The page you linked is actually an old version, but seems to still be indexed by Google. 😄

**Comment by manolo** [comment]
Committed a proposal to change the behaviour in Vaadin Framework.
You can try it out by installing this branch: `bower install vaadin-grid#feature/sort-3-states`

**Comment by jiewmeng** [comment]
Is there an option to multi sort by default. Problem with this is on mobile there is not shift click?

**Comment by jouni** [comment]
FYI, [2.0.0-pre.2](https://github.com/vaadin/vaadin-grid/releases/tag/v2.0.0-pre.2) now has the built in sorting helper elements that work like described here (tai-state). You can try the [demo online](https://cdn.vaadin.com/vaadin-core-elements/preview/vaadin-grid/demo/sorting-filtering.html).

**Comment by jouni** [comment]
Not really sure if we want to do this change for the 1.x version, though.

**Comment by jouni** [comment]
Wontfix for 1.x. Please upgrade to 2.0 (now in beta), which has the tri-state behavior by default. Also, multi-column sorting is now opt-in. See the updated examples: https://cdn.vaadin.com/vaadin-grid/2.0.0-beta1/demo/sorting-filtering.html
