### ISSUE TITLE
Rename `columnReorderingAllowed` to just `columnReordering`?

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-grid#438]
`columnReorderingAllowed` is probably misnamed. It is a rather long name and it feels badly aligned, having `allowCustomValue` in `<vaadin-combo-box>` and `allowOutsideScroll` in `<iron-dropdown>`.

I think, we should neither rename the grid property after the combo-box one, nor the other way around, as they have a different meaning. Allow something means enable the feature that was disallowed or forbidden before. As for the column reordering, the feature is not forbidden but rather disabled by default.

My proposal: rename to `columnReordering`. It is shorter and makes more sense overall, IMO.

```html
<vaadin-grid column-reordering></vaadin-grid>
<!-- VS -->
<vaadin-grid column-reordering-allowed></vaadin-grid>
```

```javascript
grid.columnReordering = true;
// VS
grid.columnReorderingAllowed = true;
```

The auto-generated Java method names would be:

```java
void setColumnReordering(boolean value) { }
boolean hasColumnReordering() { }
```

**Comment by manolo** [comment]
Just a couple of thoughts
- columnReorderingAllowed is how the framework name the property and related method.
- To be coherent with combo or dropdown we should rename to allowColumnReordering instead. 
- columnReordering without the imperative allow does not sound well to me

**Comment by jouni** [comment]
I feel it’s too late to change this now, as we already released a beta version with the current API.
