### ISSUE TITLE
Refactor colspan API to <vaadin-column-group>

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#441]
``` html
<vaadin-grid>

  <vaadin-grid-column frozen="start">
    <template class=“header>Index</template>
    <template>[[index]]</template>
  </vaadin-grid-column>

  <vaadin-grid-column-group frozen="start">
    <template class=“header>Name</template>

    <vaadin-grid-column>
      <template class=“header>First Name</template>
      <template>[[item.firstName]]</template>
    </vaadin-grid-column>
    <vaadin-grid-column>
      <template class=“header>Last Name</template>
      <template>[[item.lastName]]</template>
    </vaadin-grid-column>
    <vaadin-grid-column>
      <template class=“header>Nickname</template>
      <template>[[item.nickName]]</template>
    </vaadin-grid-column>
  </vaadin-grid-column-group>
  ...
</vaadin-grid>
```
#### `frozen` attribute/property

The `frozen` attribute is only allowed on the top-most level (direct child of `<vaadin-grid>`). All others are ignored. This seems like the approach that causes the least amount of confusion for users.

The attribute can have `start` and `end` values, to specify where to freeze the columns. The default should be `start` (if unspecified).

**Comment by jouni** [comment]
Run a quick hallway test for the proposed API to see if people understand what is happening.

**Comment by jouni** [comment]
Added a section about frozen columns in the description.

**Comment by Saulis** [comment]
@jouni we were thinking about not including the `start` and `end` parameters at this point as the right aligned frozen columns isn't finalized yet.?

**Comment by jouni** [comment]
@Saulis, sure. I was about to write that in the description, but thought you’d do it like that anyway, so I didn’t bother 😄

**Comment by Saulis** [comment]
Got some comments about the API from Artur:

1) How do you know/define on which header row "index" header in this case goes? 1st or 2nd?

2) If you want to group footers differently from headers, how does that happen?

3) In case you want to dynamically group/ungroup columns, you kinda need to rebuild the whole columns configuration by wrapping/unwrapping some columns.

In general he found the column API a bit confusing, a plain `<table>` would've made more sense for him.

**Comment by jouni** [comment]
Hmm, good comments.

1) My idea was that they always start to stack from bottom up. So if you have a plain column, without any grouping, that header is closest to the data rows. From there on, each new column group would be added on top of the previous groups header. If a group doesn’t specify a header, then that header cell is empty.

2) That’s a good question, seems like you can’t. But I’m also wondering what the use case for that is.

3) Not a very common use case, I would say. Is it any easier with "colspan", though?

We are in any case dropping the `<table>` configuration, so we need to consider some other alternative perhaps then.

**Comment by Saulis** [comment]
1) would row spanning the "index" header in this case be an option? By default aligning the content to either top, center or bottom and the user could override that by placing a flexbox or whatever inside and doing the alignment by themselves?

for 2), one possibility for the user is get really creative with the group header/footer template and place a flexbox inside etc etc.

**Comment by Saulis** [comment]
Some comments from Dmitrii:

4) Found the term "group" a bit confusing at first, he thought it relates somehow in expanding/collapsing the columns for first, last and nicknames. "Header Level" or similar was something that he would've expected instead.

**Comment by jouni** [comment]
1) sure, it’s an option. Not completely sure if that would be expected behavior

2) can you provide a more detailed example how that might work?

**Comment by jouni** [comment]
FYI, Ext JS talks about "grouped column headers". Kendo UI uses "multi-column headers".

**Comment by Saulis** [comment]
For 2) I mean you can have:
 ```html
<template is="footer">Wide</template>
```
single footer cell that spans over 3 columns, and 

```html
<template is="header">
  <div class="header">
    <div>Foo</div>
    <div>Bar</div>
  </div>
</template>
```
header will also span over 3 columns, but visually has two cells.

**Comment by Saulis** [comment]
Comments from Johannes D:

5) Not so familiar with `<template>` syntax, in general could be better to only have a template for cell and then some custom element for the header. Was a bit worried about huge-bloating-long-custom-element-names.

```html
<vaadin-grid-column>
  <vaadin-grid-header>Foo</vaadin-grid-header>
  <template>Bar</template>
</vaadin-grid-column>
```

6) Had a good point about `<vaadin-grid-column-group>` not being very explicit on what "grouping" actually means/does in this context. He still guessed that we were after visual header grouping. 

Not sure if it's just something we could address with documentation and examples or should the API be more explicit, like `<vaadin-grid-column-group spanning>` or `<vaadin-grid-multi-header>`

7) About 1) he that it could be good to somehow give the user control over the alignment. 

8) I asked also about switching the order of the spanned on non-spanned header rows (Name goes below the First, Last, Nick header cells) – moving the `<template is="header">` element below the columns inside the group might not be a good idea since it's again quite implicit. Instead we could maybe have an `align` attribute or something on the header element?

**Comment by Saulis** [comment]
Tuomas got the API, gave a +1 for rowspanning the "index" cell and couldn't up for a use case for 8).

**Comment by Saulis** [comment]
Had a long chat with Rolf:

as we started, he was really looking for more semantics in general, especially for the templates we have inside columns. The header template was quite clear as it had `class="header"` but the other one wasn't. We discussed the option of wrapping those up in an element such as `<vaadin-grid-column-header>` and `<vaadin-grid-cell>`, which would add more verbosity, but would be more explicit and understandable.

After some more discussion, we ended up having this idea of having the `header` template as optional and having something like a caption property for the column:

```html
<vaadin-grid-column caption="First Name">
  <template>[[item.firstName]]</template>
</vaadin-grid-column>
```

In his view, this is the most common case, and expressed in this way also compact and understandable at the same time. So no need for a wrapper elements in this case. 
And in the case when someone would like to add some custom HTML into the header, they would add another template, but then both of the templates would need to have an explicit attribute that would define the *role* of the template.

```html
<vaadin-grid-column>
  <template class="header">
    <b>First Name</b>
  </template>
  <template class="body">[[item.firstName]]</template>
</vaadin-grid-column>
```

9) I got the impression that he liked the proposed API with these minor adjustments:

```html
<vaadin-grid>

  <vaadin-grid-column caption="Index">
    <template>[[index]]</template>
  </vaadin-grid-column>

  <vaadin-grid-column-group caption="Name">
    <vaadin-grid-column caption="First Name">
      <template>[[item.firstName]]</template>
    </vaadin-grid-column>
    <vaadin-grid-column>
      <template class="header">Last Name</template>
      <template class="body">[[item.lastName]]</template>
    </vaadin-grid-column>
    <vaadin-grid-column>
      <template class="header">Nickname</template>
      <template class="body">[[item.nickName]]</template>
    </vaadin-grid-column>
  </vaadin-grid-column-group>
  ...
</vaadin-grid>
```

10) As an additional feature, he would like to be able somehow add style classes directly on the templates, without wrapping the contents inside an additional element. 

For example: 

<vaadin-grid>

  <vaadin-grid-column caption="Index">
    <template>[[index]]</template>
  </vaadin-grid-column>

  <vaadin-grid-column-group caption="Name">
    <vaadin-grid-column caption="First Name">
      <template>[[item.firstName]]</template>
    </vaadin-grid-column>
    <vaadin-grid-column>
      <template [header]>Last Name</template>
      <template [body]>[[item.lastName]]</template>
    </vaadin-grid-column>
    <vaadin-grid-column>
      <template [header] class="nickname">Nickname</template>
      <template [body]>[[item.nickName]]</template>
    </vaadin-grid-column>
  </vaadin-grid-column-group>
  ...
</vaadin-grid>

**Comment by jouni** [comment]
+1 for Rolf’s suggestion about more semantics, and the convenience `caption` attribute. Though, I think a `header` attribute might be more appropriate, if the explicit template identifier is also “header”.

Sidenote: the `[header]` syntax looks like it’s a mistake. Did you just mean a regular attribute (`<template header>`), or do the square brackets actually have a purpose?

**Comment by jouni** [comment]
We probably will still start by first making the more verbose `<template header>` support, and add the convenience way `<vaadin-grid-column header="...">` later.

**Comment by jouni** [comment]
I’m still confident that this API is working, and an improvement over the previous API.

**Comment by Saulis** [comment]
Yeah I got the impression that people who "got" the column API in general, got the idea of grouping.

**Comment by jouni** [comment]
Questions from @manolo:

> based on the ticket, we should implement frozen=start and frozen=end, but I think it should be easier just mark frozen columns/groups with the frozen boolean attribute.

`<vaading-grid-column frozen>` === `<vaadin-grid-column frozen="start">`
So you have a boolean attribute, if you omit the value, and it defaults to the current behavior (freeze to the left edge). If this seems wrong to you, what is your suggestion? How do we mark columns frozen to the right edge?

> Additionally, I think the api could be simplified, so instead of marking all blocks for instance: group1(column1+column2)=frozen and column3=frozen, we could mark column3 as frozen and everything at the left would be frozen until we support multiple frozen positions.

That might be possible, not completely sure about all edge cases. I’m just a bit worried about how column reordering and frozen columns play together.

> Otherwise what happens if the user marks column3? since column2 and column1 are not marked we cannot frozen anything until the user corrects the mistake of no frezing left blocks

We discussed this with Sauli and Tomi, and agreed that this is a known issue we just document. If you freeze a column in the middle of the grid, it will actually be frozen in that place, so it will float in place. So it’s the developers responsibility to make sure to freeze columns starting from either left or right end.

> Another question is if we should ignore any frozen marks nested in a group if the group is not marked, or freze all siblings of this column in the group ?

We planned that we ignore any nested frozen attributes. They only have an effect on the top level (direct children of `<vaadin-grid>` element).

**Comment by manolo** [comment]
I understand the proposal. But right now I think we were leaving cases where frozen columns are not at the left. So all my questions were for this case. Can you re-read the questions again but not thinking on supporting right or middle positions ?

**Comment by jouni** [comment]
Alright, I’ll re-read and try to rephrase the best I can:

You can ignore frozen="start" and frozen="end" at this point, it will be a future enhancement (#455).

We don’t do any implicit decision on behalf of the developer based on whether some columns before a certain column are not frozen. If the developer decides to freeze column3, and columns1–2 are not frozen, column3 will just float in the middle while column1–2 will still move horizontally while scrolling, and there will be a blank gap between column2 and column4.

Did that clear up anything?

**Comment by jouni** [comment]
Also, "freeze in the middle" is never going to be an actual feature we support. It just happens to work that way, but it’s not a use case we support or document.

**Comment by manolo** [comment]
> column3 will just float in the middle while column1–2 will still move horizontally while scrolling, and there will be a blank gap between column2 and column4.

But floating in the middle is also a feature we are not covering at this point. So I think we should do nothing with that column. Every frozen column after a gap should be just ignored.

**Comment by jouni** [comment]
Sure, we could do that, but it feels like unnecessary code and complexity when we can just document this behavior. I would even say that it would be unexpected and confusing for the developer that sometimes the attribute does something and other times not.

**Comment by jouni** [comment]
Less “magic” is better 🙂

**Comment by manolo** [comment]
That is what I meant, simplest and no code is to ignore any frozen attribute if it's out of the expected order.

**Comment by Saulis** [comment]
Well, actually simplest is just to add the `frozen` attribute to the cells corresponding a frozen column. Anything on top that like trying to figure out if something is in "expected" order adds complexity. I have to agree with @jouni on this, let's start with less and add on top of that later if needed.

**Comment by components-stalker** [comment]
Comment: 1) add `colspan`  attribute for header cells. 2) Replace `is` usage with `class` 3) ?
