### ISSUE TITLE
Row elements overflow the grid outer border

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#444]
Depending on the viewport width, sometimes the row elements cover the right edge border of the grid:

![](https://dl.dropboxusercontent.com/u/427102/screenshots/Screen%20Shot%202016-08-25%20at%2015.52.39.png)

**Comment by Saulis** [comment]
So this happens on Safari: 
![jezkundkij](https://cloud.githubusercontent.com/assets/1039468/22244974/5a787d36-e236-11e6-91a9-6017bf25d266.gif)

**Comment by tomivirkki** [comment]
There's a (not that elegant) workaround for this at https://github.com/vaadin/vaadin-grid/tree/fix/2.0-safari-overflow

Instead of merging that let's rather wait and see if the issue disappears in the hybrid version. Let's consider the workaround the last resort.
