### ISSUE TITLE
key events and editable content

### ISSUE THREAD

**Issue by ccschneidr** [vaadin/vaadin-grid#447]
Hi all,

I'm trying to make some cell editable by simply adding the contentEditable attribute. While this works like a charm in principle the default keybindings of the grid somewhat spoil the experience. E.g. the arrow keys select/scroll the cells first and only when it cannot move to that direction any more the key reaches the editable cell and the cursor moves. Additionally the visual focus is moved from the cell to the row a short time after clicking it - but that does not prevent using it.
Is there a way to disable the keys or prevent the grid from capturing it temporarily? Or will probably preventing to move the focus already help with the keys? (does not look like it would)

Regards,
Christian

P.S. realizing this is not a forum - is there a better place to ask such questions?

**Comment by ccschneidr** [comment]
I've found a solution with JavaScript (and jQuery)
```
   function stopEventPropagation(event)
   {
      if ($(event.target).closest("[contentEditable]").length > 0)
      {
         event.stopPropagation();
      }
   }
   for (let type of ['click', 'mousedown', 'mouseup', 'keydown', 'keyup'])
   {
      vGrid.addEventListener(type, stopEventPropagation, true);
   }
```

**Comment by tehapo** [comment]
@ccschneidr Great that you found a solution and sorry for not getting an answer to your question from our team earlier.

For future reference, we do actually have a couple of channels for discussion.
* https://vaadin.com/forum#!/category/9848927
* https://gitter.im/vaadin/vaadin-core-elements
