### ISSUE TITLE
Disappearing scrollbars on Win10 + Chrome

### ISSUE THREAD

**Issue by wolfie** [vaadin/vaadin-grid#450]
Grid shows scrollbars only intermittently, after scrolling with the scroll wheel. 

While this is natural in OSX and iOS, this feels alien in Windows. I'm guessing the expectation in Linux is the same.

**Comment by wolfie** [comment]
Actually, this seems to be a grid 1.x problem. And seems to appear only in the [split panel](https://vaadin.com/elements/-/element/vaadin-split-layout) example ("Nested split layouts").

Can only reproduce with Chrome 52.0.2743.116 m. Microsoft Edge and IE11 seem to be unaffected (they always show the scrollbar)

**Comment by tomivirkki** [comment]
Is this still relevant now that the split panel example uses newest vaadin-grid? https://github.com/vaadin/elements-page/issues/12

**Comment by hyyan** [comment]
I am having the same problem without using vaadin split layout , the wired thing is that the examples in vaadin website are working normally , in the beginning I thought it is something related to my project , but after copying the following example from vaadin website into its own page , I found that it does not work too .

```html
<script src="https://cdn.vaadin.com/vaadin-core-elements/latest/webcomponentsjs/webcomponents-lite.min.js"></script>
<link rel="import"
      href="https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-grid/vaadin-grid.html">

<style>

  #frozen {
    height: 300px;
  }

</style>
<vaadin-grid id="frozen" frozen-columns="2">
  <table>
    <colgroup>
      <col name="firstName"/>
      <col name="lastName"/>
      <col name="email" width="250"/>
      <col name="address.phone" hidable/>
      <col name="address.street" hidable/>
      <col name="address.city" hidable/>
      <col name="address.state" hidable/>
      <col name="address.zip" hidable/>
      <col name="address.country" hidable hidden/>
    </colgroup>
  </table>
</vaadin-grid>

<script>
  (function() {
    HTMLImports.whenReady(function() {
      var grid = document.querySelector('#frozen');

      getJSON('https://demo.vaadin.com/demo-data/1.0/people', function(json) {
        grid.items = json.result;
      });

    });

    function getJSON(url, callback) {
      var xhr = new XMLHttpRequest();
      xhr.onreadystatechange = function() {
        if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
          callback(JSON.parse(xhr.responseText));
        }
      };
      xhr.open('GET', url, true);
      xhr.send();
    }
  })();
</script>
```
Chrome is known to have a scrollbars issues , but that was in the earlier versions , so I do not think it is chrome issue in this case . if this might help my chrome version is `Version 54.0.2840.99 m`

**Other major browsers are not affected by this issue .**

Thanks in advance

**Comment by hyyan** [comment]
@tomivirkki anything new about this issue ?

**Comment by tomivirkki** [comment]
Hi @hyyan,
Sorry, missed your last message for some reason.
Seems like there's an issue with the Grid trying to determine native scrollbar size.
I'll tag this issue as a bug.

As a workaround wrapping the grid in another web component's local DOM or a dom-bind template resolved the issue for me: https://jsfiddle.net/4bzqbqo9/

**Comment by hyyan** [comment]
@tomivirkki thanks for the response , it seems you are right wrapping the vaadin grid in a dom-bind template  works , but only for dom-bind templates  , as I am using the grid inside another web component and I am still facing this issue .

**Comment by tomivirkki** [comment]
@hyyan Tried wrapping the same example as a web component here: https://jsfiddle.net/vLswg8e6/
Seems to be working ok.

**Comment by hyyan** [comment]
@tomivirkki very interesting , you are right again , the fiddle you have prepared seems to work even though I am using vaadin in the same way you used ,  inside another element , but along with polymer app layout elements and neon-animated-pages , something wrong is going on with this mix  , I will try to investigate the problem more this evening to find out what is wrong and report back .

Thanks again

**Comment by jouni** [comment]
We are not planning on doing further fixes for 1.x. Please upgrade to 2.0 (now in beta), which should behave more natively when it comes to scrollbars, and not have this issue.
