### ISSUE TITLE
Calling grid.size programmatically fails

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#454]
Calling `grid.size = 10` fails unless a size has been set prior in the grid tag . 

http://jsbin.com/riyufahube/edit?html,output

**Comment by mbana** [comment]
I can't this to "work" either, please see this comment: https://github.com/vaadin/vaadin-grid/issues/337#issuecomment-246189005.

**Comment by Saulis** [comment]
Fixed in `v2.0.0-pre.2`

**Comment by Saulis** [comment]
This remains to be an issue when `dataSource` is set before `size`
