### ISSUE TITLE
JavaScript API not working in Angular 2 rc6 

### ISSUE THREAD

**Issue by jiveshrelhan** [vaadin/vaadin-grid#465]
```
var grid = this.grid.nativeElement;
grid.addColumn({name:'shift');
grid.columns[2].setName = "Shift" **//Failed**
grid.columns[0].sortable = true; 
grid.sortOrder = [{column: 0, direction: "asc"}]; **//Failed**
grid.setFrozenColumns=2; **//Failed**
```

API calls not working as expected

**Comment by tehapo** [comment]
There seems to be some errors in the code snippet you provided.

1) There is a syntax error on the second line. The column object is missing a closing bracket.
`grid.addColumn({name:'shift');`
Should be:
`grid.addColumn({name:'shift'});`

2) The line `grid.columns[2].setName = "Shift"` should not be necessary at all. The default heading for a column is the `name` property capitalized (which would be "Shift" in this case).

3) You should define frozen columns by setting the `frozenColumns` property as follows:
`grid.frozenColumns = 2;`

If you still get errors after fixing these problems, please send a more detailed report on what kind of error messages are you seeing.

**Comment by jiveshrelhan** [comment]
Please find actual code snippet below 
var grid = this.grid.nativeElement; 
    grid.addColumn({name:'shift',src:this.response["Shift"]}); // Shift column added with data as blank. :-1: 
    grid.columns[0].sortable = true; // Got an up arrow on column which is fine. :+1: 
    grid.sortOrder = [{column: 0, direction: "asc"}]; // After click, grid is not reloaded in ascending order. :-1: 
    grid.frozenColumns=2; // It worked.

I want to pull dynamic columns from back end (Including Column Header & Row Data). 
Can you provide any docs as vaadin documentation lacks implementation snippets for APIs call ?

**Comment by Saulis** [comment]
@jiveshrelhan how are you defining the data for your grid? Automatic sorting only works for array data and `v1.2.0-alpha1` or newer.

**Comment by jouni** [comment]
Hi! As we are no longer actively supporting the use of our elements in Angular, I’m closing this issue.

Please open a new issue in the [angular-polymer](https://github.com/platosha/angular-polymer) project if you still have problems using Polymer elements (including Vaadin elements) in Angular.
