### ISSUE TITLE
[Angular2] Using paper-button inside the cell

### ISSUE THREAD

**Issue by Chabane** [vaadin/vaadin-grid#468]
Hi,

I added a paper-button inside a cell. After clicking on the button nothing happens, the function is never called.

  ```
<vaadin-grid>
      <table>
        <colgroup>
          <col name="firstName">
          <col name="lastName">
          <col name="action">
        </colgroup>
        <thead>
          <tr>
            <th>firstName</th>
            <th>lastName</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody *ngFor="let item of items">
          <tr *ngIf="item.isActive">
            <td>{{item.firstName}}</td>
            <td>{{item.lastName}}</td>
            <td><paper-button (click)="edit(item)">edit</paper-button></td>
          </tr>
        </tbody>
      </table>
    </vaadin-grid>
```

```
edit(item) {
    console.log(item);
  }
```
Have you an idea about that?

Thanks.

**Comment by tehapo** [comment]
Unfortunately using light DOM data does not support custom elements with event handlers. You would need to use a function or array data source instead and create a renderer to produce the `paper-button` inside the cell.

Please see the documentation for more details:
https://vaadin.com/docs/-/part/elements/vaadin-grid/vaadin-grid-data-formatting.html
