### ISSUE TITLE
[Angular2] ngModel problem - input never populated

### ISSUE THREAD

**Issue by Chabane** [vaadin/vaadin-grid#470]
Hi,

I tried to add an input into a table, but the input is never populated : 

```
<vaadin-grid>
      <table>
        <colgroup>
          <col sortable name="race">
        </colgroup>
        <tr *ngFor="let cat of cats">
          <td>
            <input [(ngModel)]="cat.race" type="text" />
          </td>
        </tr>
      </table>
    </vaadin-grid>
```

With a simple table, that's work fine : 

  ```
<table>
        <tr *ngFor="let cat of cats">
          <td>
            <input [(ngModel)]="cat.race" type="text" />
          </td>
        </tr>
      </table>
```

**Comment by Saulis** [comment]
Hi!

Declarative bindings don't unfortunately work inside the `<table>` element like that. Please see https://github.com/vaadin/vaadin-grid/issues/380#issuecomment-224876764 for the explanation for a similar problem in Polymer.

Closing this as duplicate for #380
