### ISSUE TITLE
Mousewheel input could be set to passive

### ISSUE THREAD

**Issue by sandro-k** [vaadin/vaadin-grid#472]
I am getting the following warning:

> Handling of 'mousewheel' input event was delayed for 101 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.
> 
> vaadin-grid.min.js:626

Maybe https://rbyers.github.io/scroll-latency.html can help to reduce the latency

_EDIT_ I am inspecting the warning, maybe it is some logic on my side that is causing the issue.

**Comment by jouni** [comment]
Hi @sandro-k, any update on this?

**Comment by sandro-k** [comment]
I will check this in Thursday

**Comment by jouni** [comment]
Please upgrade to 2.0 (now in beta). It should not have such heavy computation for wheel events, and possibly this issue should not affect it.
