### ISSUE TITLE
Auto Format header name: incorrectly insert space between capital letters

### ISSUE THREAD

**Issue by field210** [vaadin/vaadin-grid#475]
When the header name contains all-capital words, vaadin-grid will incorrectly insert space between capital letters.  
`ABC Word` will be shown as `AB C Word`.
`ABC_WORD` will be shown as `AB C WORD` 

Could I disable the auto-formatting feature in the vaadin-grid element?

**Comment by Saulis** [comment]
You can customise the header cell contents if the auto-generation isn't working for you, see: https://vaadin.com/docs/-/part/elements/vaadin-grid/vaadin-grid-headers.html

**Comment by field210** [comment]
Could I disable the auto-generated style for header?
https://plnkr.co/edit/G9CldaFtDdiY620usHYU?p=preview

**Comment by PAX523** [comment]
Hi! I'm bound to an old Vaadin version (7.5). Is there any workaround to disable this auto-spacing feature? Your link doesn't work anymore.

**Comment by tomivirkki** [comment]
Hi @PAX523, this is an outdated ticket. Closing. Vaadin Framework (7, 8) -related issues are at https://github.com/vaadin/framework/issues

**Comment by PAX523** [comment]
For all others: You can skip this "auto-spacing feature" by resetting the column names explicitely:

            grid.getColumn(columnId).setHeaderCaption(columnId.getDisplayName());
