### ISSUE TITLE
vaadin-grid 2 and Angular 2

### ISSUE THREAD

**Issue by niveo** [vaadin/vaadin-grid#478]
How can I use vaadin-grid 2 in Angular 2?

**Comment by Saulis** [comment]
Hi!

The `v2.0.0-pre.1` doesn't have support for Angular 2 templating yet, but we have planned to add to support for it. Stay tuned!

**Comment by vipdorian** [comment]
Hi, just saw the alpha2 for vaadin-grid.
Any news about implementing it with angular 2 ?

**Comment by macjuan** [comment]
Unfortunately we have decided to stop angular 2 development and concentrate fully to Polymer.

**Comment by vipdorian** [comment]
Ok, thanks

2017-02-14 6:13 GMT-05:00 Juha Seppänen <notifications@github.com>:

**Comment by jouni** [comment]
As commented by Juha, we are no longer actively supporting the use of our elements in Angular. You could try to seek help from the [angular-polymer](https://github.com/platosha/angular-polymer) project, which has been moved to community support.
