### ISSUE TITLE
@type annotations for function appear to be invalid

### ISSUE THREAD

**Issue by achernya** [vaadin/vaadin-grid#483]
It looks like the `@type` annotations used for function are not valid Closure annotations, resulting in the following errors:

1x:
WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
       \* @type {(Array<Object>|function)}
3x:
WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
     \* @type {function}

Specifying the full function type should correct these issues.

**Comment by Saulis** [comment]
Hi!

I think the problem is fixed by just using `Function` instead of `function` – can you try out how the branch `fix-annotations` works for you? Thanks!
