### ISSUE TITLE
Keyboard navigation - Cell Focus and Item Activation

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#487]
The user should be able to navigate the rows using the arrow keys.

Consider if the "row click event" should be fired when the user presses the enter key when a row is focused.

**Comment by jouni** [comment]
When implementing this, try not to introduce #53 for 2.0.

**Comment by Saulis** [comment]
WAI ARIA authoring practices for Grid Keyboard Navigation: https://www.w3.org/TR/wai-aria-practices-1.1/#grid

**Comment by Saulis** [comment]
Goal for this ticket:
- Add functionality to navigate (move focus) between cells
- Add functionality to activate (which will select/deselect) the row containing the focused cell

**Comment by jouni** [comment]
I would like to have a discussion about row vs. cell navigation. What are the use cases for cell navigation? Should we offer row and cell navigation as mutually exclusive options for the developer, or is it a mode the end user can trigger?

Also, one issue that came up with the recent TreeGrid component for Vaadin Framework, is that usually a tree hierarchy is expanded using the right arrow key and collapsed using the left arrow key. But in the Vaadin Framework Grid (and vaadin-grid 1.x), those keys are reserved for cell navigation, so the tree expansion requires the user to press Alt+Right/Left to expand/collapse the hierarchy.
