### ISSUE TITLE
Binding to the "hidden" attribute creates new columns

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-grid#490]
Here is an example on plunker: https://embed.plnkr.co/lINN7DOuOVyUxtWSvAXE/
### Summary

The `hidden` attribute of a column in a `<vaadin-grid>` is bound to a property of the host component:

``` html
<colgroup>
  <col name="version" hidable hidden="[[!visible]]" />
  <col name="summary" />
  <col name="reported" />
</colgroup>
```

As a result every time the visibility is toggled, a new column added to the grid.
### Expected behavior

Consider the [plunker example](https://embed.plnkr.co/lINN7DOuOVyUxtWSvAXE/) above. The first column (version) is hidden or visible according to the checkbox value. The list of columns whose visibility can be toggled (appears after clicking on the ||| button in the top right corner) remains the same -- it has the only column called 'Version'). This should be the same for both grids on the page.
### Actual behavior

Consider the [plunker example](https://embed.plnkr.co/lINN7DOuOVyUxtWSvAXE/) above. The top grid is broken whereas the bottom one works as expected. When the column visibility toggles, the formatting of the date in the last column switches to default. Also it looks like each off-on cycle creates a new entry in the columns list.

**Comment by jouni** [comment]
I guess this is due to the fact that the whole grid is reinitialized when the light dom is manipulated, so and all the column renderers are lost at the same time.

The light dom support is mostly there just for initial configuration, not much else is guaranteed to work unfortunately.

**Comment by jouni** [comment]
As we are not planning on doing any further improvements to the light DOM support for 1.x, I’m closing this as “wontfix”. The upcoming 2.0 version (now in beta) doesn’t suffer from this issue.
