### ISSUE TITLE
No spinner showing for lazy load in 2.0

### ISSUE THREAD

**Issue by milleraundra** [vaadin/vaadin-grid#491]
When my grid tries to lazy load in more data, scrolling is temporarily halted and a transparent overlay comes up, but no spinner. Is a loading spinner a part of this new version?

**Comment by Saulis** [comment]
Hi!

Which browser are you using? 

Looks like the spinner doesn't indeed show up when using native shadow and Chrome, but when using Shady DOM, it seems to be working?
