### ISSUE TITLE
Click events are not working in vaadin-grid with Safari and webcomponents.js

### ISSUE THREAD

**Issue by sandro-k** [vaadin/vaadin-grid#498]
When using `vaddin-grid` with Safari Version 9.1.3 (10601.7.8) on Desktop and `webcomponents.js` not `webcomponents-lite.js` then the grid is not responding to click events to sort or select items.
# Expected Output

https://jsbin.com/qoqaxijeke/edit?html,output
# Actual Output

https://jsbin.com/yicegogese/edit?html,output

PS. was really hard to track down..

**Comment by tomivirkki** [comment]
Closing as wontfix
