### ISSUE TITLE
Body scrollbars blink on OS X + Firefox when scrolling Grid

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#499]
Happens at least on our `demo/index.html`

Only on Firefox and only when scrollbars are set to "visible when scrolling" in OS X. The body doesn't seem to actually scroll anywhere though.

![xuliufh15l](https://cloud.githubusercontent.com/assets/1039468/19675272/fa875092-9a95-11e6-80c6-39876e65fde8.gif)

**Comment by jouni** [comment]
Can’t reproduce with the current demo pages (Firefox 48.0.1).

**Comment by jouni** [comment]
I no longer see it flashing during scrolling, only when I hit either the top or bottom of the grid body.
