### ISSUE TITLE
Row focus event in multi selection mode

### ISSUE THREAD

**Issue by aruntk** [vaadin/vaadin-grid#501]
I have a vaadin grid with multi selection enabled. I want to get the focused row (not selected) to show related data on another pane. Is there and event for that? If not would you consider creating one? Thank you. :)

**Comment by samiheikki** [comment]
Hi! There isn't unfortunately a suitable API for it. But we are bringing this feature in 2.0 version,  which is currently in alpha-preview. The development version, can be found in here: https://github.com/vaadin/vaadin-grid/tree/2.0-dev. But it's not yet recommended to use, as the API is changing constantly.
