### ISSUE TITLE
Observe light DOM for column tree changes

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#503]
- Reset `columns` property whenever `<vaadin-grid-column>` or `<vaadin-grid-column-group>` is added or removed directly under `<vaadin-grid>` or inside any `<vaadin-grid-column-group>`
- Make sure `<template is="dom-repeat">` with some columns works nicely.
- Make sure columns can also be passed through a `<content>` element from a parent?

**Comment by Saulis** [comment]
For future reference: `<slot>` elements fire `slotchanged` events when things happen, should be more simple to use than mutation observers, once we switch over to Polymer 2.0

http://hayato.io/2016/shadowdomv1/#events-to-react-the-change-of-distributions

**Comment by Saulis** [comment]
Regarding the `dom-repeat` issue mentioned in the snippet, did some digging on the root cause and looks like `Templatizer` doesn't really work flawlessly as we call `templatize` multiple times for the same templates. The problem hasn't popped up before when using properties from parent scope, but apparently using a template inside a template works a bit differently. 

Did a quick test where templates were templatized only once (inside `<vaadin-grid-column>` and it seemed to fix the issue immediately. So, here's one more reason to start using content distribution for headers and footers instead of templates which would allow us to move body templatizing back to column elements and remove a bunch of templatizer hacks at the same time.

**Comment by platosha** [comment]
I think I've bumped into the same `Templatizer` issue a while ago when prototyping something for the combo-box. No wonder.

**Comment by Saulis** [comment]
I've just verified that both `<content select="...">`  and `<slot name="...">` seem to distribute element from only the immediate children of the light DO. Which effectively means that we can distribute contents from inside `<vaadin-grid-column>`
