### ISSUE TITLE
Max-width not respected when resizing column (v1.2.0)

### ISSUE THREAD

**Issue by gtaylor20** [vaadin/vaadin-grid#512]
In v1.2.0, when I resize a column that has max-width specified, the column can go wider than its max.  And, after that, resizing other columns has "jumping" results.  I have set up a demo at:
[http://plnkr.co/edit/DIvwXKbTtXlKnoZq3Adn?p=preview](url)

**Comment by tomivirkki** [comment]
Thanks for the report. I get the same 'jumpy' behaviour in the example even if I remove the max-width from the column so it shouldn't be related to that.

**Comment by tomivirkki** [comment]
Closing as wontfix
