### ISSUE TITLE
Can vaadin-grid(v1.2.0) lazy load work on angular2(release 2.0)?

### ISSUE THREAD

**Issue by coin-web** [vaadin/vaadin-grid#513]
Can vaadin-grid(v1.2.0) lazy load work on angular2(release 2.0)?
On the website  address: "https://vaadin.com/elements/-/element/vaadin-grid",
the angular2 example for vaadin-grid lazy load is not working in the angular2 project.
If you update the implement now?

**Comment by tomivirkki** [comment]
Hi @coin-web 
Created an example Plunk for lazily providing data for `<vaadin-grid>` 1 in an Angular 2 app:
https://plnkr.co/edit/QBlJr8?p=preview
