### ISSUE TITLE
Missing dependency: paper-checkbox

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-grid#514]
`<paper-checkbox>`, although imported in vaading-grid-selection-behavior.html, is missing from bower.json dependencies (listed in `devDependencies`, but not in plain `dependencies`).

**Comment by jouni** [comment]
We probably won’t be using paper-checkbox in the final version, but for now I guess it should be added as a dependency.

**Comment by Saulis** [comment]
This will be fixed as part of #519
