### ISSUE TITLE
Disable keyboard "space" toggle selection

### ISSUE THREAD

**Issue by dam0vm3nt** [vaadin/vaadin-grid#517]
There should be a way to disable or change the keybindings in order to allow using some keys inside cell renderer, for example a `paper-input` to edit the cell value.

At the momento pressing the "space" key will toggle selection and eat the event.

**Comment by tomivirkki** [comment]
Hi @dam0vm3nt 
If you customize the content of a cell using a cell renderer you can stop the keydown events from propagating yourself. Here's an example: https://jsfiddle.net/e5s94nvp/

Please re-open if this doesn't solve the issue
