### ISSUE TITLE
Refine Selection API

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#519]
I have found these issues when implementing the component demo:

- When grid.multiSelection changes from true to false, all selected items should be reset.
- selected-items-changed event is fired twice
- In multi-selection mode if there are some items selected and you click on select-all it should toggle selections
- Clicking on a row in multi-selection it should select/deselect the row. Since cell-click event is fired, prevent default could work for not selecting the row.
- There should be a way to enable selection single, it might be by default or might be disabled and enabled with `single-selection` flag.
- Clicking on a row in single-selection should toggle selection

**Comment by Saulis** [comment]
> selected-items-changed event is fired twice
If you look at `event.detail.path`, you'll see it's fired first for `selectedItems.splice` and then for `selectedItems.length`, which is normal behaviour for Polymer notification events for arrays.

> In multi-selection mode if there are some items selected and you click on select-all it should toggle selections
What do you mean by toggling?

For clicking rows, we're most like going to have something like `selectionEnabled` which `iron-data-table` and `iron-list` both have: https://elements.polymer-project.org/elements/iron-list#property-selectionEnabled

**Comment by jouni** [comment]
We haven’t properly designed the selection modes for grid 2.0, so there are probably issues there still.

**Comment by Saulis** [comment]
Going to add a link to a specs document here:

**Comment by Saulis** [comment]
Question: should we add the "indeterminate" mode to the "Select All" checkbox?

**Comment by jouni** [comment]
+1 from me, and dropping any built in support for “select all” for remote data (but having examples how to do that), as discussed in our team chat.

**Comment by Saulis** [comment]
Let's get the ball rolling:

We'll use this ticket to do the following changes:
- `<vaadin-grid-multi-select-column>` will be exposed as public element
- `multiSelection` property will be dropped
- "Select All" checkbox within the new column element will be hidden if `items` is not set
- `selectedItems.inverted` will be dropped
- An example is added for a simple "Select All" functionality for a function data source
- `selectedItem` property will be dropped
- Add new property that will  toggle selection for an item on `cell-click` event (name undecided)
- An example is added for a "single selection" style selecting on `cell-click`

I'll add a new ticket for preserving the selection during filtering and sorting.

**Comment by manolo** [comment]
We should make a separate ticket about implementing the feature where "select all" checkbox changes to checked when all items are manually checked. Also, indeterminate mode should be added.

**Comment by Saulis** [comment]
Also, let's add a separate ticket/discussion related with customizing the event(s) which will toggle selection on an item.

**Comment by Saulis** [comment]
Just realised we can't maybe just set `items` to `selectedItems` when "select all" is clicked – it needs to take into account if there are filters active.
