### ISSUE TITLE
Column reordering and sorting causes bug

### ISSUE THREAD

**Issue by calebmchenry** [vaadin/vaadin-grid#520]
When vaadin grid columns are sortable and has column reordering enable it causes any given column to not be able to sort after manually scrolling. 

NOTE: This bug appears on Chrome v54 and Firefox v49 but does not appear on Chrome v53

Example: https://jsfiddle.net/gpzqxn8w/ 
1) scroll vertically via the scroll bar
2) click on a column to sort

You will notice that the column does not sort

**Comment by jouni** [comment]
The same happens on Safari 10 as well. You can, however, sort the frozen column after scrolling manually with the scrollbar.

**Comment by jouni** [comment]
Can’t reproduce anymore, the jsfiddle work as expected. Please comment if you still have this issue.

Also, we encourage everyone to upgrade to the upcoming 2.0 version (now in beta).
