### ISSUE TITLE
Mousedown event on "select all" checkbox scrolls the viewport (OS X Safari)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#53]
If I have a partially visible grid (which is not focused) in the browser viewport (i.e. the top part visible), a mousedown event on the "select all" checkbox will cause a focus call on the v-grid element, which will make the browsers scroll the element fully into viewport. This makes the subsequent mouseup event miss the "select all" checkbox, and the selection mode is not changed.

The issue was introduced in 7b8c3c57da72f7053105c116e38cc8c036fffc6b

**Comment by amahdy** [comment]
This issue happens for any selection checkbox, not just select all. Able to reproduce in Chrome OSX.

**Comment by amahdy** [comment]
Solving this https://dev.vaadin.com/ticket/18521 and removing the 'focusGridIfSelectAllClicked' method at all should resolve this.

**Comment by jouni** [comment]
Won’t fix for 1.x. 2.0 does not exhibit the same behavior, at least for now. Once we keyboard navigation (#487) is added for 2.0, we should try to avoid reintroducing this bug.
