### ISSUE TITLE
Copying from Safari and pasting into a spreadsheet fails

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#533]
Currently used div wrappers don't copy-paste nicely, change div -> span

**Comment by jouni** [comment]
A span element with a display value other than inline/inline-block/inline-flex might also cause trouble, so take that into account.

**Comment by tomivirkki** [comment]
Right, changing the current div to display inline-flex (currenlty flex) is propbably the best way to go
