### ISSUE TITLE
Sorting with computed binding generates error

### ISSUE THREAD

**Issue by bennypowers** [vaadin/vaadin-grid#541]
I'm using 2.0.0-pre.2. when sorting a table that displays data via a computed binding, I receive an error.

    <vaadin-grid-column>
      <template class="header">
        <vaadin-grid-sorter path="date" direction="desc">
          Date
        </vaadin-grid-sorter>
      </template>
      <template>[[_formatDate(item.date)]]</template>
      
    </vaadin-grid-column>

    _formatDate: (date) => {
      var theDate = new Date(date);
      return theDate.toISOString().slice(0,10);
    },

since _itemChanged() fires twice for each row, the first time it fires, date is undefined. I solved the problem by adding an if (date) {...} block. maybe this should be in the docs?

**Comment by Saulis** [comment]
Hi!

As we discussed shortly earlier in Slack, I was unsuccessful in reproducing the issue. Would you be able to provide a isolated test app which we could use to debug the issue?

**Comment by jouni** [comment]
@bennypowers, same thing for this: can you upgrade to 2.0.0-beta1 and see if you still have this issue?

**Comment by bennypowers** [comment]
Using the new filter in 2.0.0-beta1 it worked. Thanks!
