### ISSUE TITLE
vaadin grid not show content

### ISSUE THREAD

**Issue by rumes** [vaadin/vaadin-grid#543]
I'm try to integrate vaadin grid to angular 2 project. it show the grid component but not the content.

**home.component.ts** 
  
     
      import { Component, OnInit } from '@angular/core';
      import { User } from '../user/user';
      import { UserService } from '../services/user.service';
 
    @Component({
    templateUrl: 'home.component.html',
    
      })
 
    export class HomeComponent implements OnInit {
    users: User[] = [];
    constructor(private userService: UserService) { }
 
    ngOnInit() {
        // get users from secure api end point
        this.userService.getUsers()
            .then(users => this.users = users);
    }

 
    }

**home.component.html**

               <vaadin-grid [items]="users">
			<table>
				<colgroup>
				  <col name="name" sortable="true" sort-direction="asc">
				  <col name="username">
				  <col name="email">
				  <col name="type">
				  <col >
				</colgroup>
			</table>
		</vaadin-grid>

and 
**User service **

         import { Injectable } from '@angular/core';
         import { Http, Headers, RequestOptions, Response } from '@angular/http';
         import { Observable } from 'rxjs';
         import 'rxjs/add/operator/toPromise';
 
         import { AuthenticationService } from './authentication.service';
         import { User } from '../user/user';
 
        @Injectable()
         export class UserService {
        constructor(
            private http: Http,
            private authenticationService: AuthenticationService) {
        }
 
    

       getUsers(): Promise<User[]> {
       let headers = new Headers({ 'Authorization': 'Bearer ' + this.authenticationService.token });
       let options = new RequestOptions({ headers: headers });
       return this.http.get('/api/users', options)
               .toPromise()
               .then(response => response.json())
               .catch(this.handleError);
       }

        private handleError(error: any): Promise<any> {
          console.error('An error occurred', error); // for demo purposes only
          return Promise.reject(error.message || error);
       }

  }

**Comment by samiheikki** [comment]
Hi! Are you using https://github.com/vaadin/angular2-polymer adapter in your project?
Also changing the Polymer to use shadow dom will help. Before the first Polymer import (probably before the vaadin-grid import) Add this:
```
<script>
  window.Polymer = {
    dom: 'shadow'
  }
</script>
```
