### ISSUE TITLE
Demos aren't working in IE11

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#544]
![111](https://cloud.githubusercontent.com/assets/6059356/20599677/b131421e-b24f-11e6-95a1-8726a67bedbd.png)

**Comment by limonte** [comment]
This is related to all our demos. 
The simplest and ugly way to fix this is to add

```js
window.addEventListener('WebComponentsReady', function() {
    // Async call needed here for IE11 compatibility.
    Polymer.Base.async(function() {
      ...
    });
})
```

to every example. 

The nicer way will be to extend `iron-demo-helpers` to get rid of `Polymer.Base.async(function() {` in every example.

**Comment by limonte** [comment]
Related to: https://github.com/vaadin/vaadin-combo-box/issues/345

**Comment by limonte** [comment]
Waiting for https://github.com/PolymerElements/iron-demo-helpers/pull/46 to be merged

**Comment by jay8t6** [comment]
Isnt this related to the special table parsing rules? 

See below:
https://github.com/Polymer/polymer/issues/1567
https://github.com/Polymer/polymer/issues/4135#issuecomment-258910550
