### ISSUE TITLE
Header click throws error when using detailed-events

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-grid#546]
Copied from the [gitter chat](https://gitter.im/vaadin/vaadin-core-elements?at=583841d08d65e3830e9bc537):

> waksiu @waksiu
> I found one more issue with vaadin-grid after adding detailed-events='["click"]':
> <vaadin-grid #grid [items]="getItems" selection-mode="multi" size="50" (selected-items-changed)="onSelect()" detailed-events='["click"]'>
> when user clicks on area above rows (e.g: clicks on grid header) or below rows errors is raised:
> ```
> zone.js:158 Uncaught TypeError: Cannot read property 'Ld' of null
>     at tF._.getElementDetails (http://localhost/bower_components/vaadin-grid/vaadin-grid.min.js:484:74)
>     at HTMLElement._onDetailed (http://localhost/bower_components/vaadin-grid/vaadin-grid.html:1484:32)
>     at HTMLElement.handler (http://localhost/bower_components/polymer/polymer.html:561:17)
>     at ZoneDelegate.invokeTask (http://localhost/node_modules/zone.js/dist/zone.js:265:35)
>     at Zone.runTask (http://localhost/node_modules/zone.js/dist/zone.js:154:47)
>     at HTMLElement.ZoneTask.invoke (http://localhost/node_modules/zone.js/dist/zone.js:335:33)
> ```

**Comment by tomivirkki** [comment]
Closing as wontfix
