### ISSUE TITLE
Preserve selection when filtering and sorting on a remote data source

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#547]
Continued from #519 

During filtering and sorting, cache is cleared so that new items will be fetched.

When using a remote data source which always returns new objects, the current selection object-wise comparison won't work.

One option would be to define a primitive value on the objects to use for comparison:

- Expose `itemIdPath` (name TBD) property define a property to be used for comparison
- When `itemIdPath` is in use populate `selectedItems` with the id values instead of items

TBD: shall we have an "indeterminate" state in the "Select All" checkbox

Also, TBD: Anton's suggestion that "Select All" state should reflect always the state of the filtered items. (would require exposing a property for filtered items)

**Comment by jouni** [comment]
> TBD: shall we have an "indeterminate" state in the "Select All" checkbox

Seems so #573

**Comment by tomivirkki** [comment]
The newest version has `itemIdPath`. Closing
