### ISSUE TITLE
Wrong selection animation

### ISSUE THREAD

**Issue by amahdy** [vaadin/vaadin-grid#55]
- Go to this demo: http://vaadin.github.io/components-examples/v-grid/selection.html
- Select a row.
- Click on Select All check box.

The previously selected row stays highlighted.

A bit related:
- Select a row.
- Click outside the grid to loose focus.
- Click on a different row.

The previously selected row makes an un-selection animation, this should originally happen after clicking outside so the animation is too late.

**Comment by amahdy** [comment]
Root cause:
In Vaadin Grid, by default `v-grid-row-focused` class is added to the first `tr`. It seems that in the current design, one exact `tr` must have this class.

This conflicts with the current CSS:
```css
:focus .v-grid-row-focused {
...
}
```

Since the class `v-grid-row-focused` is always present, extra unneeded animation happens.

Proposed solutions:
1. Update our CSS rules and probably not use `:focus`.
2. If it's a bug against Vaadin Grid design, remove the class `v-grid-row-focused` when it's not needed.

***Note*** `v-grid-row-focused` is completely different than `v-grid-row-selected`.

**Comment by jounik** [comment]
I’ve noticed this also, but haven’t considered it a priority yet. If possible, I would definitely opt for removing the `v-grid-row-focused` classname from all the rows when the grid if blurred/unfocused.

If we do that, we can also stop using `:focus` at the same time.

**Comment by amahdy** [comment]
Working on a fix now for the main Vaadin Grid code. This should fix **many** issues in components.

**Comment by amahdy** [comment]
https://dev.vaadin.com/ticket/18521

**Comment by jouni** [comment]
Thanks to @Artur-, this issue is progressing 👍

**Comment by jouni** [comment]
Probably not worth fixing any more. Closing as “won’t fix”.
