### ISSUE TITLE
Sorting the grid causes page to scroll to the top of the table

### ISSUE THREAD

**Issue by alexyans** [vaadin/vaadin-grid#550]
I can't figure out where the `scroll` Event is emitted from but it seems to be emitted directly on `document`. I couldn't find any relevant information in the docs either. Is there any way to override this, without overriding the default behavior in general?

**Comment by alexyans** [comment]
UPDATE: issue is fixed if a `min-height` is set on `vaadin-grid`. I have no idea why that is required, but it seems like a bug.

**Comment by alexyans** [comment]
@jouni This is the issue I was talking about on Slack. I couldn't reproduce in the demos, but at least now we have a lead.

**Comment by jouni** [comment]
Thanks, we’ll have a look!

In the meantime, would you have some time to test the upcoming 2.0 version and provide some feedback? You can install the 2.0-dev branch to get the very latest version.

**Comment by alexyans** [comment]
Sure thing :)

**Comment by jouni** [comment]
@alexyans, any update on this? Have you tried the 2.0 versions yet (beta1 out today)? We are not planning on doing any further improvements or fixes to 1.x, so I would encourage you to upgrade to 2.0 as soon as possible.

**Comment by tomivirkki** [comment]
Closing as wontfix
