### ISSUE TITLE
API required to add columns  (2.0)

### ISSUE THREAD

**Issue by craigbroadbear** [vaadin/vaadin-grid#563]
This would be really nice.  There does not seem a way to add columns dynamically at the moment.

**Comment by Saulis** [comment]
Hi there!

You can use a `<template is="dom-repeat">` to add/remove `<vaadin-grid-column>` elements dynamically. You can also just add elements manually with `Polymer.dom(grid).appendChild(column)`

**Comment by craigbroadbear** [comment]
Thanks for the reply.  Not sure how to do that, as we have items for the grid and items for the dom-repeat.   Note the [[ what to put here? ]] 

    <vaadin-grid id="grid" items="[[items]]">
          <template is="dom-repeat" items="[[names]]" as="col">
              <vaadin-grid-column>
                  <template class="header">
                      <div>[[col]]</div>
                  </template>
                  <template>[[ what to put here??]]</template>
              </vaadin-grid-column>
          </template>
      </vaadin-grid>

**Comment by Saulis** [comment]
You're on the right tracks there, I guess in most cases you would have a function which you return a specific property from the items depending on the column: `<template>[[_getValue(item, col)]]</template>` 

This, however doesn't currently work for technical reasons :( we have a ticket #531 for it and will resolve it before the first alpha.

So, for now you need to stick to manually adding and removing elements. Also, depending if you're talking about just adding or removing one or two columns, you might be ok just by hiding columns dynamically?

**Comment by craigbroadbear** [comment]
Looks like I will have to go back to using 1.0.   My use requires dynamically created columns.  The appendChild method won't really work as data binding will be lost I think.

**Comment by Saulis** [comment]
Data binding should work, there are couple of ways to add the templates: http://jsbin.com/ruqetar/edit?html,output

**Comment by craigbroadbear** [comment]
Thanks!  I will give it a shot.
