### ISSUE TITLE
Inconsistent item paths between templates and filter + sorter helpers

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#566]
Users might easily end up accidentally prefixing the `path` with `item`, since it's used like that in the templates. The following snippet is from an actual user.

```html
<vaadin-grid-column>
  <template class="header">
    <vaadin-grid-sorter path="item.id">
      Id
    </vaadin-grid-sorter>
  </template>
  <template>[[item.id]]</template>
</vaadin-grid-column>
```

I'm proposing we prefix the `path` with item, so it becomes more apparent that the property is related with the item.

```html
<vaadin-grid-column>
  <template class="header">
    <vaadin-grid-sorter item-path="id">
      Id
    </vaadin-grid-sorter>
  </template>
  <template>[[item.id]]</template>
</vaadin-grid-column>
```

**Comment by Saulis** [comment]
As a comment, `path` can be used freely as a key when doing filtering or sorting in custom function data sources, so they don't necessarily need to be tied to the object model. (think about SQL where clauses)

**Comment by jouni** [comment]
> As a comment, path can be used freely as a key when doing filtering or sorting in custom function data sources, so they don't necessarily need to be tied to the object model. (think about SQL where clauses)

So we would always require the `item.` prefix when referring to the object model properties? Sounds good to me. Needs to be clearly marked in the release notes then.

**Comment by Saulis** [comment]
Well, yes – we need to have the path to conform the object model only when `items` with the internal filtering/sorting is in use.

So I guess we have now at least three options:
1. Support both `item.id` and `id` paths
2. Support only prefixed `item.id` path
3. Support only unprefixed `id` path and change the property name to `item-path` or similar.

Technically, the implementation is pretty much the same, so it comes down to which option is the easiest to understand/communicate.

**Comment by jouni** [comment]
Option n.3 is the worst option IMO.

I vote for option n.1, If we can show a console warning when `items` is set and the path is not prefixed with "item". In other words, always require the "item" prefix for the path when `items` is used. When `dataProvider` is used, the path can be anything.

**Comment by Saulis** [comment]
Decided to fire a warning/error when an item being filtered/sorted doesn't have the parentproperty of the subproperty used as `path`.
