### ISSUE TITLE
Add a property for item that user last interacted with

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#567]
### As a developer, I want to be able to present item details in a separate view

Currently, you can somewhat use `selectedItem` property, but in #519 it's planned to be dropped.

Alternatively, you can listen to `cell-click` and pick up the clicked item from there.

Current API:

```html
<my-item-overlay id="details">
  <template is="dom-bind" id="detailsTemplate">
    <div>[[item.value]]</div>
  </template>
</my-item-overlay>
<vaadin-grid on-cell-click="_details">
  <vaadin-grid-column>
     ...
  </vaadin-grid-column>
</vaadin-grid>
<script>
  _details: function(e) {
    this.$.detailsTemplate.item = e.detail.model.item;
    this.$.details.opened = true;
  };
</script>
```

Proposal: add `activeItem` property which will hold the item object user has last interacted with, either by clicking or by hitting space/enter on keyboard.

- We can have a CSS mixin for the "active" item, which wouldn't have any styles by default.
- `activeItem` goes to `null` when the currently active item is interacted with.

This would allow doing more of the "single-selection" use cases purely declaratively.

New API:

```html
<!-- Disclaimer: haven't tried if toggling the opened using an object works, but in theory it should :-) -->
<!-- Another declarative approach for opening would be to have on-active-item-changed="_details.open()" -->
<my-item-overlay opened="{{activeItem}}">
  <template is="dom-bind" item="[[activeItem]]">
    <div>[[item.value]]</div>
  </template>
</my-item-overlay>
<vaadin-grid active-item="{{activeItem}}">
  <vaadin-grid-column>
   ...
  </vaadin-grid-column>
</vaadin-grid>
```

**Comment by jouni** [comment]
Can the active item be cleared, set to null/undefined? Does that make sense semantically?

**Comment by platosha** [comment]
Have you considered calling it `focusedItem`?

**Comment by Saulis** [comment]
@platosha I have, but focused has a different meaning in this case, as focus is something that can move independently from the "active" state (for example when keyboard navigating).

**Comment by Saulis** [comment]
Few comments from discussions with @platosha and @tomivirkki :

- `activeItem` doesn't yet basically do anything inside the grid, we'll add `active` attribute to the row elements to enable styling later, when all the style mixins are added.
- we won't atleast yet add `[[active]]` template variable until a use case for it emerges
