### ISSUE TITLE
Improve scroll behavior

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#574]
After #442 (“scroll trap”) was fixed, the behavior of native `overflow: auto;` elements is not really that great for the use case of our data grid.

We might want to only allow the wheel/scroll events to pass the grid after a certain timeout after we’ve reached the end of the scrolling region. So basically, if the user is close to the end of the grid, and does one long and fast swipe, the grid should scroll to the bottom, but the page should not scroll from that gesture yet. Only after about 200ms after the bottom of the grid is reached, should the next swipe scroll the whole page.

**Comment by tomivirkki** [comment]
Did a quick proto for this at https://github.com/vaadin/vaadin-grid/tree/fix/2.0-wheel-cancel
Ramped up the period to 500ms to avoid accidental swipes.

**Comment by jouni** [comment]
I would say that is a good improvement on the behavior 👍 Feel free to do a PR from it!
