### ISSUE TITLE
Selected row style not applied or applied erroneously when “Select all” checkbox is used

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#582]
In the “Select All with Data Source” demo, when you select individual rows with the checkbox, the row gets the darker background to indicate the selection. But when you select all rows using the “select all” checkbox in the header, none of the rows get the selection style.

After that, deselecting a row adds the selection style to that (now unselected) row.

![](https://www.dropbox.com/s/z96h3gd5z9npu88/Kapture%202016-12-19%20at%2012.36.21.gif?raw=1)

**Comment by Saulis** [comment]
Yeah, we'll need to wait until a mixin is available from #534.
