### ISSUE TITLE
Active item should not change when interacting with focusable items in the cells

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#584]
The default checkboxes used for the `<vaadin-grid-selection-column>` toggle the row details visibility as well as the selection. It should only toggle the selection.

![](https://www.dropbox.com/s/s1lqcc6984kgo05/Kapture%202016-12-19%20at%2014.29.52.gif?raw=1)

**Comment by Saulis** [comment]
This is happening on Safari I presume. Looks like `<input type="checkbox">` nor `<button>` focus on click on FF nor Safari 9 at least. With tabbing focusing works. 

Grid ignores clicks inside "focusable" elements using `document.activeElement` check which obviously doesn't work in this case.

Did not see this coming :-)
