### ISSUE TITLE
Get Selected Row Index When Data Is Loaded Using Ajax

### ISSUE THREAD

**Issue by hyyan** [vaadin/vaadin-grid#589]
Hello 

I think calling `grid.selection.selected()`  returns the wrong index of selected row .

**Problem**

I load items using ajax from json file located on my hard disk , so no API or any thing that might cause a problem  , just something simple ,
after that I use vaadin items function to paginate the returned json response , and save the paginated data into a variable , so far everything seems good and the grid is displayed correctly .

Then I do bind an event to get the selected row , and to get the index of selected row using `grid.selection.selected() ` , but this method return the index of selected row according to the full size of json response not according to the paginated data , for example if I have a response size `500` and the paginate function returns the first `70` items everything works fine when I scroll , the new paginate items which will be displayed is for example [ 70 , 140 ] , now if I try to select item  `90` for example the  `grid.selection.selected()`  returns `90` , which I consider a little bit wired if I am understanding the what this method is really for , cause the returned value in this case must be `20` according to the current items displayed in the grid , or ????

I can not provide my whole code , but here is a snippet to explain more :

```js
_onRowSelectListener: function(e){
   var selected =  paginateItems[grid.selection.selected()[0]] ;
   ......
}

grid.items = function(){
  this.debounce('user-mangers-data', function(params, callback) {
    getJSON('data.json',function(json) {

      items = json.slice();

      // paginate data
      items = items.slice(
        params.index,
        params.index + params.count
      );
      paginateItems = items
      callback(items);

    }.bind(this));
  }.bind(this), 250);
}

```

Please correct me if I am understanding this wrongly  , and help me solve this issue 
Thanks in advance

**Comment by Saulis** [comment]
Hi @hyyan!

I think you have a slight misunderstanding there, the `grid.selection.selected()` is always returning the index relative to the full size of the items. Basically what the data source function is used for is just to fetch items that are not in the cache – in other words, items that are at any given time visible might not be the items that were fetched last.

Looking at your example, if you're always fetching the full set of data from your JSON file, it might just better to assign it as an array:

```js
getJSON('data.json', function(json) {
  grid.items = json.slice();
});
```

**Comment by hyyan** [comment]
@Saulis thank you for the clarifying , you are right I misunderstood this method , the example was was just to explain the idea , I am using a real API im my app but I think I have to keep track  of current items my self here , It would be just nice if I can get current items from the grid directly , it is something I am not able to figure how to do , is there any suggestion ?

**Comment by hyyan** [comment]
@Saulis  closing this issue , cause as it seems I do not need to keep track  of grid items my self , I can just use https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-grid/#vaadin-grid:method-getItem,

Thanks
