### ISSUE TITLE
Header is jumping if scrolling grid with PgDown/PgUp

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#595]
Linux/Chrome 55:

![recorded](https://cloud.githubusercontent.com/assets/6059356/21390810/60b998b6-c791-11e6-9bdd-0ac494718e41.gif)

**Comment by jouni** [comment]
Can’t reproduce in Chrome, Safari or Firefox in macOS. @limonte, can you try the latest 2.0-dev version, see if it’s fixed. We did some changes to the CSS after this, I think.

**Comment by limonte** [comment]
Seems to be fixed :+1:
