### ISSUE TITLE
Cursor and scrollbar thumb are moving with different speeds

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#598]
Speed of scrollbar thumb isn't calculated properly, it's less than the speed of mouse cursor:

![recorded](https://cloud.githubusercontent.com/assets/6059356/21391276/a802aada-c793-11e6-8e88-8c86e3fae991.gif)

Linux/Chrome 55

**Comment by jouni** [comment]
Which browser? I suppose it’s on Linux, right? 

I can’t reproduce this on any browser on macOS. Can you try the latest beta demos, see if it’s still an issue? https://cdn.vaadin.com/vaadin-grid/2.0.0-beta1/demo/index.html

**Comment by limonte** [comment]
Seems to be fixed :+1:
