### ISSUE TITLE
 Cell content overflow and alignment

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#605]
This issue covers two aspects of these two topics (alignment and overflow): the default behavior and the ways the developer should be able to modify those defaults. Feel free to split into separate issues if it’s easier to process that way – but as these two are connected, it feels natural to talk about them in the same context.

#  Content overflow

## Text

There are two natural possibilities: wrap the text to multiple lines (and let the cell height grow), or keep the text on one line and truncate the overflowing text with an ellipsis. A third option would be just to clip the text, but that’s the least desired behavior, and I don’t think we need to consider it.

![screen shot 2016-12-22 at 15 14 37](https://cloud.githubusercontent.com/assets/66382/21426749/642d3a98-c859-11e6-996f-2a8046e81903.png)

If we someday have automatic column width computations, it might be that the content always fits the cell on one line (as we are about to drop max-width for columns also). I will consider this as an edge case of the latter options (no wrapping, truncate text), which doesn’t require extra considerations.

### Default behavior

I propose we go with text wrapping by default. Truncation should be possible to do, and we should consider providing a convenient way to enable that for the whole grid or per column.

## Other content (images, UI controls/widgets)

Here, we also have two options: let the row height grow (do not clip the content), or clip the content (fixed cell width/height).

### Default behavior

Similarly, as with text, we should let the row height grow. Column width is dictated by the grid for now, but it can be dictated by the content as well in the future.

# Content alignment

We need to consider both vertical and horizontal alignment inside the cell. To put it simply, it should be possible to align the content in all the 9 common locations from “top left” to “bottom right”. That said, we can only have one default, and we should probably provide conveniences only for some of those alignments.

### Default behavior

The "safest" default seems to be “middle left”. It works as users expect for one line texts and other content that is relatively close to the line-height of the text content. Also, it looks decent visually even when some cell contents are taller than others – albeit not being the most reader-friendly.

Here’s a wireframe I used as help when thinking about the different cases: https://www.figma.com/file/OwTNkylkCNIRVuxYcg1IuNGd/Data-grid-cell-alignments

### Conveniences

I propose we provide two convenience alignments out-of-the-box:
- “top left”: if the row contains multiline text, it is usually preferable to align them to the top
- ”middle right": for numeric data (we might want to consider “top right” at the same time.

**Comment by jouni** [comment]
After writing this, I started to think about one more option for the default vertical alignment, and if it’s technically possible – to align by default to the baseline (I know we briefly mentioned this with @platosha), and if that would cover both single and multi-line content nicely, as you could fine-tune the alignment of non-text elements also with the `vertical-align` property (with pixel values).

**Comment by snooze67** [comment]
Hi. 

We are using vaadin grid for our project.
And we have this critical issue, we need to have the "wrap " content overflow

Do you know when this can be implemented ?

Because we have to release a version of our product soon.

**Comment by tomivirkki** [comment]
Hi @snooze67,

You can already make text wrap inside the grid cells by using the style mixins:
```
<custom-style>
  <style>
    vaadin-grid {
      --vaadin-grid-cell: {
        white-space: normal;
      }
    }
  </style>
</custom-style>
```

**Comment by snooze67** [comment]
This isn't enough, the cell height must be sized to fit the content and it is not.
If i do that i just have a text line, the other are hidden

**Comment by tomivirkki** [comment]
Hmm....works for me. Although i'm using a synchronous data source in my example. If you populate the grid cells lazily (custom datasource for example), you'll need to ask the internal `<iron-list>`to recalculate row heights afterwards. For this you can call `grid.notifyResize()` after the text is in place.

**Comment by snooze67** [comment]
oh maybe i don't have the good version ...

Does the vaadin grid in 7.7.9 using this ?

**Comment by tomivirkki** [comment]
Oh, you’re talking about the Vaadin Framework’s grid, not the `<vaadin-grid>` element?

I think the framework grid doesn’t support variable row heights. It calculates a static row height after the first rows are rendered and from there on uses that height for each row. You can find the Vaadin framework repository [here](https://github.com/vaadin/framework).

**Comment by snooze67** [comment]
Ok sorry for that. I was googling for my problem with the grid component and i didn't notice that was grid element.

But It is a bit confusing that they don't have the same features. (for variable row height)

**Comment by jouni** [comment]
> But It is a bit confusing that they don't have the same features. (for variable row height)

Yeah, I understand it’s probably confusing. vaadin-grid v1 was the same as the framework grid, but we decided it was better to reimplement the whole thing in pure polymer, to better serve our and our users needs. We will eventually replace the grid in the framework with this implementation, so you’ll get variable row heights there as well.

**Comment by LiquidAdamJaffe** [comment]
Hi, I'm trying to get text-overlow: ellipses to work in cells in the <vaadin-grid> component.  Can this be done?

**Comment by luochenhuan** [comment]
Any update on this ticket?

I tried to add 
```
 --vaadin-grid-cell: {
        white-space: normal;
      }
```
and call `grid.notifyResize()` with no effect. The row doesn't expand height nor does the cell text wrap to multiple lines.

**Comment by jouni** [comment]
@luochenhuan which version are you using? If you are using v4 (pure Polymer 2 version), you need to use “theme modules” to add styles for the internal parts.

Here’s an example how to add text wrapping: 

```html
<dom-module id="vaadin-grid-styles">
  <template>
    <style>
      :host [part~="cell"]:not([part~="details-cell"]) ::slotted(vaadin-grid-cell-content) {
        white-space: normal;
      }
    </style>
  </template>
</dom-module>
```

Place that in your index.html or in a separate HTML import.

**Comment by luochenhuan** [comment]
@jouni  Thank you for the reply. Why the old way doesn't work?

This may not be related to vaadin: I looked into vaadin-grid source code and find `part` attribute set for cells, but when I inspect the web page using dev tools, I could only see `vaadin-grid-cell-content `. How can I find the attributes in chrome's dev tools, and if not, why?

**Comment by jouni** [comment]
> @luochenhuan 
> Why the old way doesn't work?

See https://github.com/vaadin/vaadin-grid/issues/1132#issuecomment-347521175

**Comment by hussain21j** [comment]
@tomivirkki 
The cusotm style worked perfectly for me with polymer 2.0

**Comment by web-padawan** [comment]
Few notes: 

1. `text-overflow: ellipsis` is added in bbd821b89b71652c38d2d47f9f2da73b19dc446d and is available since 5.3.0 stable release
2. `text-align` column helper property is available since 5.2.0 stable release
3. the `wrap-cell-content` Lumo theme variation is available since 5.0.0 stable release

Most of the action points have been implemented, so let me close this issue as outdated.
@jouni if you would like something else from this ticket to be implemented, please create a new one.

**Comment by nicolasr75** [comment]
Your documentation here: https://vaadin.com/docs/latest/ds/components/grid/#columns
tells us to use "left, center, right". The example, however, uses "end". Would be nice to have this consistent. Looks like "end" works.  Just out of couriosity, was there any specific reason to favor "end" instead of "right"?

**Comment by web-padawan** [comment]
@nicolasr75 Thanks for pointing out. We added `start` and `end` for RTL (right-to-left) support. Will update the docs accordingly.
