### ISSUE TITLE
Protect cell-content wrappers from accidental style leaks

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#607]
Plain "cell-content" is too general a class name and makes the wrapper vulnerable to external style leaks. Prefixing the name with "vaadin-grid" helps to some extent but even the used tag `div` might cause problems.

Should consider using custom elements as cell content wrappers.

**Comment by jouni** [comment]
@tomivirkki, do we have any plans for this yet? I guess this can be fixed after 2.0 stable, but would be nicer to do something before it.

**Comment by tomivirkki** [comment]
@jouni Sure, we can fix this during the beta period.
