### ISSUE TITLE
SCRIPT1006: ')' expected - Deploying angular-cli app with polymer on production

### ISSUE THREAD

**Issue by Chabane** [vaadin/vaadin-grid#611]
Hello,

I deployed an angular-cli app with polymer on production. I got this error (only) when I refresh the page on
IE11 : 

![image](https://cloud.githubusercontent.com/assets/1231559/21479486/28d37f8a-cb55-11e6-9fec-e9b26950e097.png)

The last end of the second line of the image above
![image](https://cloud.githubusercontent.com/assets/1231559/21479498/3fdf8610-cb55-11e6-9cfd-7431c622dca9.png)

Any idea?

**Comment by manolo** [comment]
Seems a timeout issue, could you try to import the polyfill and your elements very soon in your index.html, and wait to start your ui ?

**Comment by jouni** [comment]
As we are no longer actively supporting the use of our elements in Angular, I’m closing this issue.

That said, we encourage people to try to make them work together, and you should join the [angular-polymer](https://github.com/platosha/angular-polymer) project and see if you can get help from there.
