### ISSUE TITLE
Observe activeItem.* for property changes

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#617]
Given the use case of using `activeItem` as a key for opening, for example, a separate detail view, the observer would enable adding two-binding to the detail view.

**Comment by jouni** [comment]
How much work is it to support this? Also, it seems there are some spelling errors in the description.

**Comment by Saulis** [comment]
I'd say somewhere around 2-3 story points – it's mostly about just reusing the same functionality we have for the two-way binding of `item` in the templates.
