### ISSUE TITLE
Simplify the boilerplate needed for adding a new demo page

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#622]
In vaadin-grid 1.x there is a component that simplifies the process. Re-use it.

**Comment by jouni** [comment]
Which element are you referring to?

**Comment by limonte** [comment]
I believe it's `<demo-navigation>`, we already added it: https://github.com/vaadin/vaadin-grid/blob/2.0-dev/demo/columns.html#L29

**Comment by jouni** [comment]
Well, closing then 😄
