### ISSUE TITLE
Initial drag of resizable columns fires events

### ISSUE THREAD

**Issue by billy-hardy** [vaadin/vaadin-grid#624]
If I have a resizable column, the initial drag (before releasing) causes column-resize events to be fired for the total number of columns I have (not the number of resizable ones). We auto save and apply these widths when we get the event, so this causes us not to be able to resize at all.

https://jsfiddle.net/byufLz2h/

**Comment by billy-hardy** [comment]
Update: It fires as many events as there are non-hidden columns.

https://jsfiddle.net/byufLz2h/2/

**Comment by jouni** [comment]
We encourage you to upgrade to the upcoming 2.0 version (now in beta), as we are not planning on doing any more fixes to the 1.x version.

**Comment by tomivirkki** [comment]
Closing as wontfix
