### ISSUE TITLE
Grid is initially rendered empty with an extra horizontal scrollbar

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#626]
Tested using v2.0.0-pre.2

See https://jsfiddle.net/eprzythj/

Although data is available, an empty grid with a horizontal scrollbar is initially rendered

**Comment by jouni** [comment]
Reproducible in Chrome. Can’t see it in Safari.

**Comment by jouni** [comment]
Seems to be fixed already. Tested using the latest beta1: https://jsfiddle.net/ykssxtxs/1/
