### ISSUE TITLE
Old data is rendered if no new data is provided

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#627]
Tested using v2.0.0-pre.2

See https://jsfiddle.net/5jan63js/

When setting only 2 items and setting size to 100, the 2 items are not only rendered on rows 0 and 1, but also once more when you scroll down

**Comment by jouni** [comment]
Still reproducible with the latest version (beta1). Scroll to row 500 and you see the data again: https://jsfiddle.net/exneb3gj/2/

**Comment by jouni** [comment]
@tomivirkki, this is a duplicate of #1124

**Comment by tomivirkki** [comment]
At least #1124 should now hide the rows with old data
