### ISSUE TITLE
Grid doesn't scroll to actual end of the table if user press End button on keyboard

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#630]
Live example: http://signell.net/artur/newgrid/example.php

![recorded](https://cloud.githubusercontent.com/assets/6059356/21526482/37e27ace-cd2d-11e6-923d-095142d5e1ab.gif)

Linux/Chrome 55

**Comment by Saulis** [comment]
Related with #487

**Comment by limonte** [comment]
Fixed in https://github.com/vaadin/vaadin-grid/pull/662
