### ISSUE TITLE
Resizing row details does not work as expected

### ISSUE THREAD

**Issue by merlinnot** [vaadin/vaadin-grid#635]
Row details cannot be resized after expanding, grid rows are stuck in position relative to initial height.

**Comment by tomivirkki** [comment]
Hello @merlinnot,
Just to clarify, are you using `vaadin-grid` version 1 or 2? Both seem to be lacking public API for notifying the grid of a resize.

**Comment by merlinnot** [comment]
v2

**Comment by tomivirkki** [comment]
Hi again
Created a quick prototype that should cover the case: vaadin-grid#feature/2.0-notify-resize-proto
Let me know if this works the way you'd expect it to
