### ISSUE TITLE
iron-ajax response in vaadin-grid doesn't display in template

### ISSUE THREAD

**Issue by dezechristophe** [vaadin/vaadin-grid#636]
hello,
If I have an iron-ajax in a dom-repeat, I can't display response from that iron-ajax request in that dom-repeat.

In my case, {{serverConfig.adresse_ip_eth0}} display nothing in template....

handleConfigResponse function can display my ajax response , serverConfig .

It works well If I remove vaadin-grid tags!

`        
<vaadin-grid>
            <table>
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Module</th>
                        <th>Variante</th>
                        <th>Libellé</th>
                        <th>accès EAD</th>
                        <th>info ssh</th>
                    </tr>
                </thead>
                <tbody>
                    <template is="dom-repeat" items="{{serveursItems}}" rendered-item-count="{{renderedCount}}" as="serveur">
                        <tr>
                            <iron-ajax url="config.json" handle-as="json" verbose="true" on-response="handleConfigResponse" last-response="{{serverConfig}}" auto>
                            </iron-ajax>
                            <td>
                                <a href="https://{{appConfig.serveur}}:8070/genconfig/serveur/{{ serveur.id }}/modif_config" target="_blank">{{ serveur.id }}</a>
                            </td>
                            <td>
                                {{serveur.module_actuel}}
                            </td>
                            <td>
                                {{serveur.variante}}
                            </td>
                            <td>
                                <a href="https://{{appConfig.serveur}}:8070/serveur/etat?id={{ serveur.id }}" target="_blank">{{ serveur.libelle }}</a>
                            </td>
                            <td>
                                <acces-ead ip="{{serverConfig.adresse_ip_eth0}}"></acces-ead>
                            </td>
                            <td>
                                <acces-ead ip="{{serverConfig.adresse_ip_eth0}}"></acces-ead>
                            </td>
                        </tr>
                    </template>
                </tbody>
            </table>
        </vaadin-grid>
`

**Comment by samiheikki** [comment]
Hi,

<vaadin-grid> 1.X doesn't observe ligh dom manipulations, so for example using the dom-repeat template doesn't work. Instead you should bind your data to the items property: `<vaadin-grid item="{{serveursItems}}">`.

Other option would be to use <vaadin-grid> 2.0 alpha version. It for example supports the dom-repeat templates. https://github.com/vaadin/vaadin-grid/tree/2.0-dev
