### ISSUE TITLE
Localization with Polymer app-localize-behavior not working

### ISSUE THREAD

**Issue by MMJM** [vaadin/vaadin-grid#647]
I have a very simple Polymer element hosting a Vaadin Grid and using the app-localize-behavior for localization.

Here is the Vaadin Grid definition
```

    <vaadin-grid id="lazy" visible-rows="20">
      <table>
        <colgroup>
          <col name="number" width="80"/>
          <col name="firstName" sortable/>
          <col name="lastName" sortable/>
          <col name="email" sortable/>
        </colgroup>
        <thead>
        <tr>
          <th>#</th>
          <th>[[localize('First Name')]]</th>
          <th>{{localize('Last Name')}}</th>
          <th>{{localize('Email')}}</th>
        </tr>
        </thead>
      </table>
    </vaadin-grid>
```

Here is the Polymer Localization stuff.

```
      behaviors: [
        Polymer.AppLocalizeBehavior
      ],

      properties: {
        language: {
          value: 'zh'
        },
        resources: {
          value: function() {
            return {
              'en': { 
                'First Name': 'First Name',
                'Last Name': 'Last Name',
                'Email': 'Email'
                },
              'zh': { 
                'First Name': '名字',
                'Last Name': '姓',
                'Email': '电子邮件'
                },
            }
          }
        }
    }
```

Changing the language at runtime does not reflect the translation changes in the Grid.

However, if I use a normal HTML Table it all works fine.

Is this a bug or should Localization be handled differently?

**Comment by tomivirkki** [comment]
Hi @MMJM,
Unfortuntely `vaadin-grid` 1.x doesn't support data binding inside the `<table>` configuration. You can workaround this limitation by defining an external component with the binding handled and then placing that component as the content of a `vaadin-grid` header cell programmatically. Here's a live example: https://jsfiddle.net/nuofp25k/

If it's an option, please try `vaadin-grid` 2 ([currently at alpha1 stage](https://github.com/vaadin/vaadin-grid/releases/tag/v2.0.0-alpha1)) which supports data binding in the header templates as you'd expect.

**Comment by MMJM** [comment]
Thanks for your assistance and I will give vaadin-grid 2 a go. Is there a timeline for this to be released?

And thanks Vaadin for the great elements.

**Comment by jouni** [comment]
Hi! Version 2.0 just reached beta, so please try upgrading to that if at all possible. We are expecting a few week beta period, after which we will tag the final 2.0 version. This depends on the amount of bugs found during the beta, of course, so it might be delayed further.

Also, we are not planning on doing any further development for 1.x.

**Comment by tomivirkki** [comment]
Closing as wontfix
