### ISSUE TITLE
items added using columns[index].renderer don't get updated

### ISSUE THREAD

**Issue by osvaldoM** [vaadin/vaadin-grid#654]
I added the dates in the "data e hora" column (represented by a timeStamp in the model) using cell render as seen in the image below

![image](https://cloud.githubusercontent.com/assets/11247633/21990301/ed6a8498-dc16-11e6-84fa-2d7cdfed5dd9.png)

the problem is that when i change sort order all of the other cellls change value except the ones added using cell render as you can see in the image below. the "provincia" column for instance  had the order updated but the "data e hora" column did not

![image](https://cloud.githubusercontent.com/assets/11247633/21990364/34cf479c-dc17-11e6-9d36-b1f5a8eb72c4.png)

**Comment by limonte** [comment]
Hi @osvaldoM,

Are you using <vaadin-grid> 1 or 2?

**Comment by osvaldoM** [comment]
i'm using v1

**Comment by tomivirkki** [comment]
We're no longer maintaining 1.x. Closing as wontfix
