### ISSUE TITLE
Strange interaction between tables in different elements, header merges with item 0

### ISSUE THREAD

**Issue by dmurph** [vaadin/vaadin-grid#657]
This is on Vaadin v2.0.0-alpha

I'm trying to use vaadin-grid in a couple different custom elements. It works normally on the first loaded element, I have two grids, and they both render just fine.

However, in the second element (which I use iron-pages and app-route to make visible), it seems like the header and the first element are merged. When I inspect them, the divs look correct, it just looks rendered UNDER the header. See the screenshots

This is a grid in the first element:
![screen shot 2017-01-16 at 8 24 43 pm](https://cloud.githubusercontent.com/assets/294026/22007734/06291388-dc2a-11e6-8259-f4b7dd03f774.png)
(and dev tools)
![screen shot 2017-01-16 at 8 24 57 pm](https://cloud.githubusercontent.com/assets/294026/22007736/062953c0-dc2a-11e6-8d46-64bdc0e8ab59.png)

Grid in the second element:
![screen shot 2017-01-16 at 8 25 05 pm](https://cloud.githubusercontent.com/assets/294026/22007737/06299510-dc2a-11e6-9ed9-3efc240f34ac.png)
(and dev tools)
![screen shot 2017-01-16 at 8 25 18 pm](https://cloud.githubusercontent.com/assets/294026/22007735/062932e6-dc2a-11e6-9fcd-21e7cab06ce0.png)

**Comment by dmurph** [comment]
note that the effect reverses depending on which 'page' I load first.

**Comment by dmurph** [comment]
I found that this happens when using <iron-pages>. If the component is in an iron-page, which IS NOT loaded, then it is loaded, the first element will be gone. Attached example, use 'polymer serve' or whatever webserver command you like
[test2.zip](https://github.com/vaadin/vaadin-grid/files/710127/test2.zip)

**Comment by dmurph** [comment]
it looks like the translate is wrong in css:

```html
<table>
<caption class="style-scope vaadin-grid-table">
    <div is="vaadin-grid-sizer" class="style-scope vaadin-grid-table" style="top: 105px;">
        <vaadin-grid-sizer-cell class="cell style-scope vaadin-grid-sizer" style="flex-grow: 1; flex-basis: 100px;">&nbsp;</vaadin-grid-sizer-cell>
        <vaadin-grid-sizer-cell class="cell style-scope vaadin-grid-sizer" style="flex-grow: 1; flex-basis: 100px;">&nbsp;</vaadin-grid-sizer-cell>
        <template is="dom-repeat" as="column" class="style-scope vaadin-grid-sizer"></template>
    </div>
</caption>
<thead id="header" is="vaadin-grid-table-header" class="style-scope vaadin-grid-table" has-templates="" style="transform: translate3d(0px, 0px, 0px);">
    <tr is="vaadin-grid-table-header-row" class="style-scope vaadin-grid-table">
        <th is="vaadin-grid-table-header-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">#</div>
        </th>
        <th is="vaadin-grid-table-header-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">Letter</div>
        </th>
    </tr>
</thead>
<tbody id="items" class="style-scope vaadin-grid-table" style="height: 105px; border-top-width: 0px; border-bottom-width: 0px;">
    <tr is="vaadin-grid-table-row" class="style-scope vaadin-grid-table" style="transform: translate3d(0px, 0px, 0px);">
        <td is="vaadin-grid-table-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">0</div>
        </td>
        <td is="vaadin-grid-table-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">a</div>
        </td>
    </tr>
    <tr is="vaadin-grid-table-row" class="style-scope vaadin-grid-table" odd="" style="transform: translate3d(0px, 35px, 0px);">
        <td is="vaadin-grid-table-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">1</div>
        </td>
        <td is="vaadin-grid-table-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">b</div>
        </td>
    </tr>
    <tr is="vaadin-grid-table-row" class="style-scope vaadin-grid-table" style="transform: translate3d(0px, 70px, 0px);">
        <td is="vaadin-grid-table-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">2</div>
        </td>
        <td is="vaadin-grid-table-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;">
            <div class="cell-content style-scope person-session-view">c</div>
        </td>
    </tr>
</tbody>
<tfoot id="footer" is="vaadin-grid-table-footer" class="style-scope vaadin-grid-table" style="transform: translate3d(0px, 0px, 0px);">
    <tr is="vaadin-grid-table-footer-row" class="style-scope vaadin-grid-table">
        <td is="vaadin-grid-table-footer-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;"></td>
        <td is="vaadin-grid-table-footer-cell" class="style-scope vaadin-grid-table" style="flex-basis: 100px; flex-grow: 1;"></td>
    </tr>
</tfoot>
</table>
```

**Comment by dmurph** [comment]
I found what needs to happen which isn't happening. The following code resizes the columns for the header:
https://github.com/vaadin/vaadin-grid/blob/v2.0.0-alpha1/vaadin-grid-table.html#L352

When the vaadin-grid is in a hidden element (where display: none), when it initialized, the height of the header and footer are initially 0.

When the iron-pages makes the element (which has the grid) visible, the above code is never run again. So the first row is forever hidden under the header.

I'm not sure the best place to put this code, or the best way to do this.

**Comment by tomivirkki** [comment]
Hi @dmurph,
Right, the header/footer measurement part must be re-run on appear. Good find, thanks for the report. Will fix asap.

**Comment by dmurph** [comment]
Thanks!
