### ISSUE TITLE
Elements with "position: fixed" around grid with "height: auto" disappear on scrolling

### ISSUE THREAD

**Issue by pdesjardins90** [vaadin/vaadin-grid#659]
```html
<style>
  vaadin-grid { 
    height: auto;
  }

  .fixed-element {
    position: fixed;
    bottom: 50px;
    right: 50px; 
  }

</style>

<vaadin-grid items="[[someItems]]">
  <vaadin-grid-column>
    <template class="header">Some property</template>
    <template>[[item.someProperty]]</template>
  </vaadin-grid-column>        
</vaadin-grid>

<div class="fixed-element">I disappear on scroll</div>
```

Feed it enough items for a document scroll to be possible and you'll see the lower right text disappear.
I use version 2.0.0-alpha1 with polymer 1.7

**Comment by pdesjardins90** [comment]
I use version 2.0.0-alpha1 with polymer 1.7

**Comment by Saulis** [comment]
Which browser are you on? Couldn't reproduce the issue with https://jsfiddle.net/Saulis/c374vdaf/ using Chrome, FF or Safari (9) on OSX. (nevermind the jagging scrolling, it's a jsfiddle issue)

**Comment by pdesjardins90** [comment]
Using chrome on osx, but reading on gitter I think it may be linked to it being contained in an iron-pages?

**Comment by pdesjardins90** [comment]
Alright I managed to reproduce the bug in a standalone project and here it is (sorry for markdown, couldn't find an updated polymer cdn for the jsfiddle) :

```html
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/app-layout/app-header-layout/app-header-layout.html">
<link rel="import" href="../../bower_components/vaadin-grid/vaadin-grid.html">

<dom-module id="grid-bug-app">
  <template>
    <style>
      .content-area {
        max-width: 1200px;
      }

      vaadin-grid {
        height: auto;
      }

      .fixed-element {
        position: fixed;
        bottom: 50px;
        right: 50px;
      }

    </style>

      <app-header-layout has-scrolling-region fullbleed>
        <div class="content-area">
          <vaadin-grid items="[[someItems]]">
            <vaadin-grid-column>
              <template class="header">Some property</template>
              <template>[[item]]</template>
            </vaadin-grid-column>
          </vaadin-grid>

          <!-- <template is="dom-repeat" items="[[someItems]]">
            <div>[[item]]</div>
          </template> -->

          <div class="fixed-element">I disappear on scroll</div>

        </div>

      </app-header-layout>

  </template>

  <script>
    Polymer({
      is: 'grid-bug-app',

      ready: function() {
        var items = []
        for(var i = 0; i < 200; i++) {
          items.push('foo' + i)
        }
        this.someItems = items
      },

      properties: {
        someItems: {
          type: Array
        }
      }
    })
  </script>
</dom-module>
```

The problem lies with the app-header-layout, when it has the 'has-scrolling-region' turned on, the fixed element disappears. It only does so when the grid is present, you can try commenting it out and de-comment the dom-repeat to compare.

**Comment by Saulis** [comment]
hmm.. this seems to be working for me: https://jsfiddle.net/Saulis/5byt8115/

**Comment by pdesjardins90** [comment]
Ok look at this one then: https://jsfiddle.net/pdesjardins90/7saj3rsf/

Just changed the max-width to something even smaller

**Comment by Saulis** [comment]
We were able to reproduce the issue now, thanks!

Looks definitely like a rendering issue in Chrome, since there's no problem in Safari nor Firefox – also, the same issue seems to appear when using `<iron-list>` so it's probably related to translating row elements when scrolling.

Here's the bad news: we can't probably do much to fix this issue.

Good news is we have a possible workaround for you: https://jsfiddle.net/Saulis/7saj3rsf/4/

Adding a `transform: translateZ(0)` to your fixed element seems to help.

**Comment by pdesjardins90** [comment]
Perfect! Thank you for your patience, it's very appreciated.
