### ISSUE TITLE
Calling function 'PolymerElement', function calls are not supported. Angular 2 

### ISSUE THREAD

**Issue by feniixx** [vaadin/vaadin-grid#663]
I'm trying to implement `<vaadin-grid>` element, I followed the [Angular CLI Quicktart with Polymer](https://vaadin.com/docs/-/part/elements/angular2-polymer/ng-cli-webpack.html) of yours, followed all the steps but when I runned the app the console output this error:

>ERROR in Error encountered resolving symbol values statically. Calling function 'PolymerElement', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/jonathan/Projects/WebStormProjects/CDA/src/app/app.module.ts, resolving symbol AppModule in /Users/jonathan/Projects/WebStormProjects/CDA/src/app/app.module.ts

angular-cli:  **1.0.0-beta.25.5**
angular: **2.3.1**
angular2-polymer: **1.0.0**
vaadin-grid: **1.2.1**

# App

src/app/app.module.ts
```ts
import { BrowserModule } from [email protected]/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from [email protected]/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { PolymerElement } from '@vaadin/angular2-polymer';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent,
    PolymerElement('vaadin-grid')
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule { }
```

src/app/app.component.ts
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  
  people = [
    {
      "firstName": "Tyler",
      "lastName": "Evans",
      "email": "tyler.evans@company.com"
    },
    {
      "firstName": "Adrian",
      "lastName": "Rogers",
      "email": "adrian.rogers@company.com"
    },
    {
      "firstName": "Sofia",
      "lastName": "Hernandez",
      "email": "sofia.hernandez@company.com"
    },
    {
      "firstName": "Joseph",
      "lastName": "Long",
      "email": "joseph.long@company.com"
    },
    {
      "firstName": "Alice",
      "lastName": "Roberts",
      "email": "alice.roberts@company.com"
    }
  ]
  
}
```

src/app/app.component.html
```html
<h1>{{title}}</h1>
<vaadin-grid [items]="people">
  <table>
    <colgroup>
      <col name="firstName">
      <col name="lastName">
      <col name="email">
    </colgroup>
  </table>
</vaadin-grid>
```

**Comment by undersail** [comment]
I met the similar issue. :(

**Comment by Saulis** [comment]
Hi there!

`angular2-polymer` `v1.0.0` supports Angular 2 `v2.1.2` and earlier only. Please see https://github.com/platosha/angular-polymer for more.

**Comment by jouni** [comment]
As we are no longer actively supporting the use of our elements in Angular, I’m closing this issue. But, we hope people still try to use them together, and you can see if you can find help from the angular-polymer project Sauli linked in the previous comment.
