### ISSUE TITLE
Change "dataSource" to "dataProvider"

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#666]
In order to be consistent with the API naming in Vaadin Framework, we should consider renaming the `dataSource` property to `dataProvider`. The framework has limitations that prevented it from using `DataSource` as the class, and had to use a bit less nice (but still very okay) `DataProvider`.

I don’t remember there being any other major elements that use `dataSource`, so this would not cause major confusion for Polymer/JS users, as it would still be a new property that is specific to vaadin-grid.

**Comment by jouni** [comment]
FYI, @Legioth, the team agreed to make this change. I assume you are in favor of this change – just checking, that if this is not mandatory, we should avoid any unnecessary work here.

**Comment by Legioth** [comment]
Please do if it can be done without too much overhead. Lets think things through again if it turns out that significant effort would be needed.

**Comment by manolo** [comment]
Since it is grid 2.0, It should be done with zero effort just `s/dataSource/dataProvider/g`

**Comment by jouni** [comment]
You could draft some release notes already and add a mention about this change.
