### ISSUE TITLE
dom-repeat inside row-details doesn't size correctly

### ISSUE THREAD

**Issue by hegsie** [vaadin/vaadin-grid#693]
I tried putting a dom-repeat template inside the row-details template and the row-details doesn't expand properly so you can see everything in the details pane.

**Comment by platosha** [comment]
I assume you’re talking about the upcoming `<vaadin-grid>` v2.0.

Thank you for trying and giving feedback!

I’ve tried to reproduce this issue, it indeed does not size properly at the moment. http://jsbin.com/ganazaviya/edit?html,output

**Comment by Saulis** [comment]
Related with #635
