### ISSUE TITLE
Question : How to manage Bulk Action Buttons for Selected Rows?

### ISSUE THREAD

**Issue by atifwaqar** [vaadin/vaadin-grid#703]
Is there an easy way to :
1. have action buttons in every row?
2. have action buttons in the Header Row?
3. enable Header Row action buttons if a Row(s) is selected, and disable row level action buttons?

**Comment by Saulis** [comment]
Hi! Are you using `<vaadin-grid>` 1.x or 2.0 ?

**Comment by atifwaqar** [comment]
I downloaded it from [here](https://github.com/vaadin/vaadin-grid). I guess its V1.

**Comment by atifwaqar** [comment]
I am using vaadin for first time, and currently i'm evaluating this webcomponent . So switching versions is not an issue for me.

**Comment by Saulis** [comment]
@atifwaqar I recommend using the upcoming 2.0 for now on.

Here's a simple fiddle how you can create dynamic content: https://jsfiddle.net/Saulis/e4565Lh6/

**Comment by atifwaqar** [comment]
@Saulis I am now using 2.0. And I have searched each an every demo, and document of Vaadin-grid, but we couldn't find what we are looking for. 
I'll try to explain our need in following image : 
![1](https://cloud.githubusercontent.com/assets/4388707/23013246/1cd220c6-f42a-11e6-8b9b-ba11a66574bf.jpg)


We want to have action buttons on each row, as well as for selected rows. but when 1 or more rows are selected, we want to disable the row level buttons, and enable the bulk action buttons.

**Comment by Saulis** [comment]
OK, so something like this: https://jsfiddle.net/Saulis/ejt5gjvm/

**Comment by atifwaqar** [comment]
@Saulis This is exactly what we needed. Thank you very much  :)
