### ISSUE TITLE
Datasource switch and loadPage bug

### ISSUE THREAD

**Issue by tdesc** [vaadin/vaadin-grid#708]
Hello,

When changing datasource with 800+ records to one with <10 
keeps calling loadPage from old dataset. _pagesForPhysicalItems returns list of pages from old dataset.

2.0.0-alpha2

**Comment by Saulis** [comment]
Hi!

Can you provide a snippet that reproduces the error or modify this one: https://jsfiddle.net/Saulis/2eaozjd1/ ?

As a sanity check, make sure you update the `size` property accordingly in the grid to reflect the number of items in the data source.

Thanks!

**Comment by tdesc** [comment]
Thanks for clarification. My problem was dynamic columns created "after" first data portion comes from ajax request. Switch between datasource with columns recreation. Unfortunately recreation of this test is quite complex.

**Comment by tomivirkki** [comment]
Re-open if still relevant
