### ISSUE TITLE
vaadin-grid Polymer 2.0 support

### ISSUE THREAD

**Issue by macjuan** [vaadin/vaadin-grid#710]
<p>Developers can use vaadin-grid with Polymer2 projects</p>

[See more on IDEA 210 vaadin-grid Polymer 2.0 support](https://app.prodpad.com/ideas/210/canvas)

Premilinary Steps: (by @Saulis)
- [ ] ~~In preparation for using `<slot>`, place cells inside shadow root of `<vaadin-grid>`~~
- [x] Switch `<content>` for `<slot>` and `::content` to `::slotted()`
- [x] Replace custom elements extending native elements
- [ ] ~~Separate "fixed" elements sections to improve UX~~
- [x] Revise and fix multi-property observers with checks for `undefined` values
- [x] Replace `<style is="custom-style">` with `<custom-style>`
- [x] Modify the `Templatizer` functionality to work with both v1 and v2
- [ ] Deprecate CSS mixins
- [ ] ~~Modify scroller internals to use a flexbox~~

Other notable changes:
- `Polymer.dom(x).querySelectorAll(..)` returns `NodeList` instead of `Array`
- `<slot>` without a name cannot have fallback/default content
- `Polymer.Settings.useNativeShadow` -> `Polymer.Settings.useShadow`
- `Polymer.dom.flush()` no longer flushes mutation observers, they need to be explicitly flushed.
- adding listeners using `target.click`: `_onClick` in `listeners` block doesn't work

**Comment by Saulis** [comment]
Also, we can most likely have only shadow root between the cell containers in `<vaadin-grid>'s light DOM and the cells.

**Comment by jouni** [comment]
Regarding the proposal of refactoring fixed elements to their own containers (which is currently struck out), to which I commented that it prevents the use of `:hover` styles for the rows:

We should evaluate the tradeoffs here. Is it more beneficial to have the scrolling more smooth,  at the expense of making it more difficult to add hover styles?

I mean, we could move the fixed elements to their own containers and then add mouse event listeners for the row elements that toggles a `[hovered]` attribute on the row element, which could then be used by the theme. This wouldn’t be any different from what we are doing with vaadin-text-field and its `[focused]` state toggling.

So, how big of a performance and styling convenience penalty would we get from toggling the ´[hovered]` attribute on each row (it should probably be prevented during scrolling anyways) vs. the performance penalty we get from supporting fixed elements inside the scrolling container?

**Comment by jouni** [comment]
Added one more thing to consider during this refactoring: deprecate CSS mixins.

**Comment by lchen2017** [comment]
We do see a lot of errors under Polymer 2.0 with 2.1-polymer-2 branch, so my question is when vaadin-grid will be available for alpha testing .

**Comment by platosha** [comment]
@lchen2017 as soon as we can. Unfortunately, it turned out to be challenging to port such a complex element, but we are actively working on it these days. Please keep watching this issue to track the progress.

**Comment by lchen2017** [comment]
@platosha  Thanks!  are there any tasks we can help with?

**Comment by Saulis** [comment]
A small update for those interested: the `2.1-polymer-2` contains the latest development branch regarding Polymer 2 support.

Current situation: all tests are currently passing on *Chrome* + Polymer `2.0.0-rc.3`, both on native Shadow and Shady. Although at least Firefox and Safari seem to be working also, there might be some small issues here and there. We're going to address those next and then make sure everything still works with Polymer 1.x.

If you try the dev branch out and find problems, please don't file new issues at this point yet, but instead add a comment here or contact us in the Gitter chat room. Thanks!

**Comment by victorhooi** [comment]
Curious - what does moving this from in-progress to backlog mean, for those of us hoping to use vaadin-grid under Polymer 2.x? =)

**Comment by Saulis** [comment]
Hi @victorhooi!

We had to change priorities for a week or two to work on other things, but rest assured, we'll pick it back up shortly. 
Meanwhile, you can try out how the `2.1-polymer-2` works for you.

**Comment by andersforsell** [comment]
@Saulis I'm having trouble in getting all dependencies right with bower install. Its complaining about "ECONFLICT Unable to find suitable version for webcomponentsjs". (using Polymer-cli@next)

Can you give a hint on how to get it right?

**Comment by Saulis** [comment]
@andersforsell hmm strange.. which exact version of Polymer CLI are you running? Mine reports `0.18.0-pre.15`

Tried clearing out my bower cache and everything and everything seems to install smoothly. 
Can you join me in our [Gitter](https://gitter.im/vaadin/vaadin-core-elements/) chat for further discussions? Thanks!

**Comment by victorhooi** [comment]
I'm also seeing weirdness/issues around package versions. I'm running Polymer CLI `0.18.0-pre-15`.
```
victorhooi@victorhooi-macbookpro /p/t/vaadin-grid-test> polymer --version
0.18.0-pre.15
```
I create a new Polymer 2.0 project:
```
polymer init polymer-2-starter-kit
```
I then try to install vaadin-grid:
```
victorhooi@victorhooi-macbookpro /p/t/vaadin-grid-test> bower install --save vaadin/vaadin-grid#2.1-polymer-2
bower vaadin-grid#2.1-polymer-2       not-cached https://github.com/vaadin/vaadin-grid.git#2.1-polymer-2
bower vaadin-grid#2.1-polymer-2          resolve https://github.com/vaadin/vaadin-grid.git#2.1-polymer-2
bower vaadin-grid#2.1-polymer-2         download https://github.com/vaadin/vaadin-grid/archive/2.1-polymer-2.tar.gz
bower vaadin-grid#2.1-polymer-2          extract archive.tar.gz
bower vaadin-grid#2.1-polymer-2         resolved https://github.com/vaadin/vaadin-grid.git#85bca5cb14
bower iron-resizable-behavior#^1.0.5      cached https://github.com/PolymerElements/iron-resizable-behavior.git#1.0.5
bower iron-resizable-behavior#^1.0.5    validate 1.0.5 against https://github.com/PolymerElements/iron-resizable-behavior.git#^1.0.5
bower iron-scroll-target-behavior#^1.1.0  cached https://github.com/PolymerElements/iron-scroll-target-behavior.git#1.1.1
bower iron-scroll-target-behavior#^1.1.0         validate 1.1.1 against https://github.com/PolymerElements/iron-scroll-target-behavior.git#^1.1.0
bower polymer#^1.6.1                               cached https://github.com/Polymer/polymer.git#1.8.1
bower polymer#^1.6.1                             validate 1.8.1 against https://github.com/Polymer/polymer.git#^1.6.1
bower iron-a11y-keys-behavior#^1.1.9               cached https://github.com/PolymerElements/iron-a11y-keys-behavior.git#1.1.9
bower iron-a11y-keys-behavior#^1.1.9             validate 1.1.9 against https://github.com/PolymerElements/iron-a11y-keys-behavior.git#^1.1.9
bower iron-a11y-announcer#^1.0.5                   cached https://github.com/PolymerElements/iron-a11y-announcer.git#1.0.5
bower iron-a11y-announcer#^1.0.5                 validate 1.0.5 against https://github.com/PolymerElements/iron-a11y-announcer.git#^1.0.5
bower webcomponentsjs#^0.7.24                      cached https://github.com/Polymer/webcomponentsjs.git#0.7.24
bower webcomponentsjs#^0.7.24                    validate 0.7.24 against https://github.com/Polymer/webcomponentsjs.git#^0.7.24
bower webcomponentsjs#^v1.0.0-rc.5                 cached https://github.com/Polymer/webcomponentsjs.git#1.0.0-rc.7
bower webcomponentsjs#^v1.0.0-rc.5               validate 1.0.0-rc.7 against https://github.com/Polymer/webcomponentsjs.git#^v1.0.0-rc.5

Unable to find a suitable version for iron-resizable-behavior, please choose one by typing one of the numbers below:
    1) iron-resizable-behavior#2.0-preview which resolved to 4c10452634 and is required by app-layout#d1aa650ded, iron-pages#798b292446
    2) iron-resizable-behavior#^1.0.5 which resolved to 1.0.5 and is required by vaadin-grid#85bca5cb14

Prefix the choice with ! to persist it to bower.json

? Answer 1

Unable to find a suitable version for iron-scroll-target-behavior, please choose one by typing one of the numbers below:
    1) iron-scroll-target-behavior#2.0-preview which resolved to 3ec8fe6009 and is required by app-layout#d1aa650ded
    2) iron-scroll-target-behavior#^1.1.0 which resolved to 1.1.1 and is required by vaadin-grid#85bca5cb14

Prefix the choice with ! to persist it to bower.json

? Answer 1

Unable to find a suitable version for polymer, please choose one by typing one of the numbers below:
    1) polymer#^1.1.0 which resolved to 1.8.1 and is required by iron-a11y-announcer#1.0.5, iron-a11y-keys-behavior#1.1.9, iron-resizable-behavior#1.0.5, iron-scroll-target-behavior#1.1.1
    2) polymer#^1.6.1 which resolved to 1.8.1 and is required by vaadin-grid#85bca5cb14
    3) polymer#^2.0.0-rc.1 which resolved to 2.0.0-rc.3 and is required by app-layout#d1aa650ded, app-route#8f4f7acc27, iron-a11y-keys-behavior#fa811ff11f, iron-behaviors#a27904b516, iron-checked-element-behavior#6257d75137, iron-flex-layout#ec9a1f91d9, iron-form-element-behavior#e5975d6a19, iron-icon#55fe529584, iron-iconset-svg#1ba09ae80e, iron-localstorage#5603bdcd15, iron-location#9ba94fa17b, iron-media-query#6dc49cdc2b, iron-meta#1421651c70, iron-pages#798b292446, iron-resizable-behavior#4c10452634, iron-scroll-target-behavior#3ec8fe6009, iron-selector#e7107b383f, iron-validatable-behavior#325063248a, paper-behaviors#b66457441b, paper-icon-button#ffb9c64bcf, paper-ripple#f82228704f, paper-styles#86e6abcc81, polymer-starter-kit

Prefix the choice with ! to persist it to bower.json

? Answer 3

Unable to find a suitable version for iron-a11y-keys-behavior, please choose one by typing one of the numbers below:
    1) iron-a11y-keys-behavior#2.0-preview which resolved to fa811ff11f and is required by iron-behaviors#a27904b516, paper-ripple#f82228704f
    2) iron-a11y-keys-behavior#^1.1.9 which resolved to 1.1.9 and is required by vaadin-grid#85bca5cb14

Prefix the choice with ! to persist it to bower.json

? Answer 1

Unable to find a suitable version for webcomponentsjs, please choose one by typing one of the numbers below:
    1) webcomponentsjs#^0.7.24 which resolved to 0.7.24 and is required by polymer#1.8.1
    2) webcomponentsjs#^1.0.0-rc.4 which resolved to 1.0.0-rc.7 and is required by polymer-starter-kit
    3) webcomponentsjs#^v1.0.0-rc.5 which resolved to 1.0.0-rc.7 and is required by polymer#2.0.0-rc.3

Prefix the choice with ! to persist it to bower.json

? Answer 3
bower webcomponentsjs#^v1.0.0-rc.5                install webcomponentsjs#1.0.0-rc.7
bower vaadin-grid#2.1-polymer-2                   install vaadin-grid#85bca5cb14
bower iron-a11y-announcer#^1.0.5                  install iron-a11y-announcer#1.0.5

webcomponentsjs#1.0.0-rc.7 bower_components/webcomponentsjs

vaadin-grid#85bca5cb14 bower_components/vaadin-grid
├── iron-a11y-announcer#1.0.5
├── iron-a11y-keys-behavior#fa811ff11f
├── iron-resizable-behavior#4c10452634
├── iron-scroll-target-behavior#3ec8fe6009
└── polymer#2.0.0-rc.3

iron-a11y-announcer#1.0.5 bower_components/iron-a11y-announcer
└── polymer#2.0.0-rc.3
```

Is the above expected?

**Comment by Saulis** [comment]
@victorhooi hi!

Yes, currently it's expected since we are still having Polymer `1.x` dependencies as defaults for the hybrid version, which requires dependency resolution when using Polymer 2. 

After the hybrid is released, the plan is to start working towards a Polymer 2-only version which will have the Polymer `2.0` dependencies.

**Comment by nicolasr75** [comment]
I am trying to use the Polymer-2 version in Chrome with the simple binding example and get

    this._debounceTemplate is not a function
    at HTMLElement._sizeChanged (vaadin-grid-table.html:557)

I find the following implementation in Polymer 1.0

    _debounceTemplate: function (fn) {
        Polymer.dom.addDebouncer(this.debounce('_debounceTemplate', fn));
    }

Any idea how I could fix this in vaadin-grid-table.html to make progress?
Thanks, Nicolas

**Comment by Saulis** [comment]
@nicolasr75 which branch/version of `vaadin-grid` are you using?

**Comment by nicolasr75** [comment]
@Saulis Sorry, I forgot. I use 2.1-Polymer-2.

**Comment by Saulis** [comment]
@nicolasr75 can you double-check that?
The line [vaadin-grid-table.html:557](https://github.com/vaadin/vaadin-grid/blob/2.1-polymer-2/vaadin-grid-table.html#L557) doesn't call `_debounceTemplate`

Try calling `bower cache clean` and reinstalling `vaadin-grid` to make sure you're running the latest version of the branch.

**Comment by nicolasr75** [comment]
@Saulis You are right, somehow my packages were messed up. With a new project everything so far works as expected. Sorry for wasting your time. Keep up the good work!

**Comment by amahdy** [comment]
+1

**Comment by lchen2017** [comment]
We have migrated all other components to Polymer 2.0 except vaadin-grid. Question is which branch can be used right now, 2.1-polymer-2-rebased or something else. Also, which branch (Polymer 2.0 compatible)  is working in IE 11? Thanks!

**Comment by Saulis** [comment]
@lchen2017 there's a  `v3.0.0-alpha1` release with Polymer 2.0 support.

**Comment by lchen2017** [comment]
@Saulis  Thanks. Appreciate if you can update us on support for IE11.

**Comment by manolo** [comment]
v3.0.0-alpha1 should work for IE11. Does not work for you?

**Comment by lchen2017** [comment]
@manolo No, it doesn't work.

**Comment by manolo** [comment]
what version of polymer are you using ? Are you compiling your javascript to ES5 ?

**Comment by lchen2017** [comment]
@manolo It doesn't work with Polymer 2.0 when we use vaadin 2.1-polymer-2 code. We will try release v3.0.0-alpha1 and let you know. Thanks!
