### ISSUE TITLE
vaadin-combo-box Polymer 2.0 support

### ISSUE THREAD

**Issue by macjuan** [vaadin/vaadin-grid#711]
<p>Ability to use vaadin-combo-box with in Polymer2 app.&nbsp;</p>

<p>With this developers can use combo-box in Polymer2 projects</p>

[See more on IDEA 217 vaadin-combo-box Polymer 2.0 support](https://app.prodpad.com/ideas/217/canvas)

**Comment by Saulis** [comment]
Let's move this to combo-box repo!
