### ISSUE TITLE
Filters with empty string value should be omitted

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#714]
In applications where `<vaadin-grid-filter>` default values are set to `''`, and after `dataProvider` is set, (usually) unnecessary data requests are fired.

Proposing we handle empty string values the same way as `undefined` or `null` values and remove such filters from the filter array.

See console logs here.
https://jsfiddle.net/Saulis/zpm0phwa/

Here's a [user reported](https://gitter.im/vaadin/vaadin-core-elements?at=58a42adede50490822ce5837) configuration which ends up firing 4 requests (one for each filter) to the data provider in the beginning
![pacoferre](https://cloud.githubusercontent.com/assets/1039468/22974413/d20bf7d2-f38a-11e6-9e49-3255aff879ae.png)

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
