### ISSUE TITLE
Page -1 is requested when size is decreased during a previous data request

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#715]
See the consoles. Should omit requesting page for `-1`.

https://jsfiddle.net/Saulis/f4s3ojdL/

**Comment by tdesc** [comment]
_eagerlyLoadPages: function() {
    ...
        if(prev>-1) this._loadPage(prev);
        if(next>-1) this._loadPage(next);
      }
    },

**Comment by tdesc** [comment]
Other related thing even with grid.size = 0, attaching data-source cause trying to loadPage, it seems to be unnesessary.

**Comment by tomivirkki** [comment]
@Saulis Does the issue still exist? I don't see "-1" in console in the jsfiddle
