### ISSUE TITLE
recreation of Details template on data-source change 2.0

### ISSUE THREAD

**Issue by tdesc** [vaadin/vaadin-grid#719]
I've created polymer component that I use as row details.
It's nothing special, but data-source change recreate rowDetailsTemplate 
and it cause of recreation of Details template (ready and attached both called) as many rows I have in model.
1) Run test, it will display 1 row.
2) Tap on it, show/hide Details.
3) Switch datasource. 

Console full with attached and ready console.log messages
P.S. scrolling down 1000 items list after slowdown grid and show Detail template after each row.

https://jsfiddle.net/4404skph/

**Comment by Saulis** [comment]
Hmm, can't seem to be able to reproduce the issue. After I switch the data source no details are shown. (as there shouldn't be since the item objects have changed)

**Comment by jouni** [comment]
@tdesc can you please try the latest 2.0.0-beta1 and report back if you still have this issue? Thanks!
