### ISSUE TITLE
takes a long time to become responsive with large dataset

### ISSUE THREAD

**Issue by Stefdv** [vaadin/vaadin-grid#722]
'large dataset'  is not really that large...only 3K items. However ..compared to iron-list ( 1.4.1) it takes a very long time ( seconds ) before the grid becomes responsive ( responsive -> user can interact ).
I tried it by 'streamin' the items and by setting the whole array at once.
With iron-list the list is responsive almost instant.

**Comment by tomivirkki** [comment]
Hi @Stefdv 
Are you using `<vaadin-grid>` 1 or 2?

**Comment by jouni** [comment]
I’m pretty sire it is v2. Sauli and @Stefdv have been talking about this recently in Gitter. You can check that for more context.

**Comment by tomivirkki** [comment]
Ok, the number of items in the grid’s data set doesn’t affect it’s performance. Here’s a example of a grid with a billion items: http://jsbin.com/jenicocito/edit?html,output

**Comment by tdesc** [comment]
http://jsbin.com/juvodo/1/edit?html,output

**Comment by Stefdv** [comment]
hey..sorry for my late reply.
Yes, using V2.
@tomivirkki if i take your example but use some 'sucar' in the template like a paper-card the list slows down.
@tdesc yes, that is the situation i'm experiencing

**Comment by tomivirkki** [comment]
Looking at the example by @tdesc it seems at least that modifying the columns rapidly creates a loop (if you toggle fast between “big” and “small” column layouts in the example). We’ll look into this.
