### ISSUE TITLE
Middle mouse button does not have expected behaviour.

### ISSUE THREAD

**Issue by Avocher** [vaadin/vaadin-grid#735]
Hey, 
Is there a way to enabe scrolling when clicking the middle mouse button?

**Comment by tomivirkki** [comment]
Hi @Avocher,

Is there some specific setup where this doesn’t work as expected? Tried it on OS X / Firefox and at least that combo seems to work:
![kapture 2017-02-24 at 13 44 29](https://cloud.githubusercontent.com/assets/1222264/23302612/08f5b13e-fa98-11e6-83da-e8a37317ea0a.gif)

**Comment by Avocher** [comment]
Hey,
It doesn't work on my current setup on windows 10 using the latest chrome or firefox.

Here are some of your demos where it doesn't work:
https://vaadin.com/elements/-/element/vaadin-grid
https://demo.vaadin.com/expense-manager/

**Comment by tomivirkki** [comment]
Ah, yes those demos are still using `<vaadin-grid>` 1 which apparently doesn’t support middle mouse scrolling. Please try the following demos that are running `<vaadin-grid>` 2

https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha2/demo/
https://vaadin.github.io/expense-manager-demo

**Comment by Avocher** [comment]
Yes, seems to work fine in version 2, I guess you can close the ticket. :)
