### ISSUE TITLE
Multi-column sorting should be opt-in

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#742]
When using `<vaadin-grid-sorter>` elements, the default behavior should be that only one of them is “active” at any time, so that the grid is sorted by one column at a time.

Multi-column sorting should be an opt-in feature, either by the developer of by the end user.

In vaadin-grid 1.x, it’s opt-in by the end user (shift-click or long-tap), but that makes it really difficult to discover. I suggest we make it opt-in for the developer in 2.0, so that the developer needs to do some extra configuration to enable multi-column sorting, and then it will function like it does currently for the end user (normal clicks change the column sorting independently from other columns).

### API proposal
- By default, the `<vaadin-grid-sorter>` element overrides the sorters array with just one sorter element (which in result resets all other vaadin-grid-sorter elements)
- Add a new `independent` attribute for the `<vaadin-grid-sorter>` element. When that attribute is added, that sorter does not reset the whole sorters array, but instead prepends itself to the array.

Another option would be to introduce some attribute/property on the vaadin-grid level, that would affect all vaadin-grid-sorter elements simultaneously.

**Comment by Saulis** [comment]
I think we should go with a grid-level property, since property on the `<vaadin-grid-sorter>` would imply the user having to apply the property on each sorter.
