### ISSUE TITLE
iron-list-behavior and calculating currentPage

### ISSUE THREAD

**Issue by tdesc** [vaadin/vaadin-grid#751]
_increasePoolIfNeeded

**Comment by Saulis** [comment]
Hi!

Could you elaborate a bit more what's the issue you're facing? A code snippet in jsbin.com or jsfiddle.net would be awesome.

Thanks!

**Comment by web-padawan** [comment]
Closing per above comment. I suppose this is related to the old release, so consider taking a look at the latest versions, and if the issue persists, please provide us with more detailed description.
