### ISSUE TITLE
Should sorting path be a property on <vaadin-grid-column>

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#769]
Why is it that we need to define a <vaadin-grid-sorter> element for sorting and not setting a property on the column like for resizing/reordering? Feels a bit inconsistent.

Without reading docs my intuition would have been to use something like `<vaadin-grid-column sort-by="item.user.name.last" resizable> </vaadin-grid-column>`

**Comment by tomivirkki** [comment]
This is similar to https://github.com/vaadin/vaadin-grid/issues/492

**Comment by jouni** [comment]
I would say this is a duplicate of #492.
