### ISSUE TITLE
ES6 syntax in 2.0.alpha3

### ISSUE THREAD

**Issue by gluwer** [vaadin/vaadin-grid#771]
I've updated from alpha2 to alpha3 and cannot longer minify using uglify because of ES6 syntax element. Haven't checked exactly which, but after reverting to alpha2 everything works fine. Is it intentional?

**Comment by limonte** [comment]
There are several uglify plugins and a lot of ways to use to use those plugins (gulp/webpack/etc). Show your code so we can find the cause of this issue and fix it.

**Comment by gluwer** [comment]
Hi,

The way to reproduce:

```
npm i polymer-cli
node_modules/.bin/polymer init application
```

Then add below to the application element:

```
<link rel="import" href="../../bower_components/vaadin-grid/vaadin-grid.html">
<link rel="import" href="../../bower_components/vaadin-grid/vaadin-grid-filter.html">
<link rel="import" href="../../bower_components/vaadin-grid/vaadin-grid-sorter.html">
```

and now run `node_modules/.bin/polymer build`. You fill get an error in vaadin-grid-sorter.html.

**Comment by Saulis** [comment]
https://github.com/vaadin/vaadin-grid/blob/v2.0.0-alpha3/vaadin-grid-sorter.html#L156 should probably be `_getClosestCellContent: function() {`
