### ISSUE TITLE
Announcer stretches scroll width

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#773]
The `#announcer` in `<vaadin-grid-sorter>` seems to cause extra scroll width for the grid

![screenshot 2017-03-06 15 03 49](https://cloud.githubusercontent.com/assets/1222264/23611115/52b50b10-027e-11e7-95ba-fe2218520e1b.png)

**Comment by platosha** [comment]
Suggested fix: add `position: relative;`to the `<vaadin-grid-sorter>` host styles.
