### ISSUE TITLE
<x-array-data-provider items="..."> could be confusing in the demos

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-grid#776]
The helper element name contains `data-provider`, while the element exists to help setting the grid `items` array, not the `dataProvider` callback.

Maybe rename the helper element to `<x-items-array>`?

**Comment by platosha** [comment]
For example, the sorting and filtering page contains “When using a data provider” in the description texts, and then `<x-array-data-provider>` with `items` in the demo code. This makes me wonder if the description text concerns this demo code or not.

**Comment by Meai1** [comment]
How do I fill these items out? I copy pasted the code from the sample page but there are no items in the grid

**Comment by web-padawan** [comment]
The demos are removed on master and the new documentation (currently WIP) will not be using this helper. Closing.
