### ISSUE TITLE
Adding isn't working in the CRUD example

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#793]
Can be reproduced here: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha4/demo/crud.html

![recorded](https://cloud.githubusercontent.com/assets/6059356/23751368/a3a72e24-04d9-11e7-92d7-0fd4ffc18fe6.gif)

**Comment by Saulis** [comment]
Fixed in https://github.com/vaadin/vaadin-grid/commit/c5e99a9b3f80d06846f93b99e2b8fab19d289475

**Comment by limonte** [comment]
https://www.youtube.com/watch?v=KEkrWRHCDQU
