### ISSUE TITLE
Redux dataProvider example

### ISSUE THREAD

**Issue by codingnube** [vaadin/vaadin-grid#794]
Hi Team,
Please let us know whether [Redux](http://redux.js.org/docs/introduction/) can be used along with vaadin-grid or not. Is it recommended? Pointers on advantages or disadvantages will be highly appreciated. Is it possible to add an example using a Redux dataProvider to these amazing [demos](https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha4/demo/data.html). Thank you all.

**Comment by jouni** [comment]
I don’t think anyone from our team has any real experience with Redux, unfortunately (maybe @samiheikki?).

I’m not sure if vaadin-grid itself adds anything extra on top of just using Polymer together with Redux. There are two videos regarding that topic, which could provide some answers for you: 

- [How to use Redux in Polymer -- Polycasts #61](https://www.youtube.com/watch?v=PahsgJn0sgU)
- [Asynchronous Actions with Redux -- Polycasts #62](https://www.youtube.com/watch?v=y2FxAT1u8pU)

**Comment by Saulis** [comment]
There's also documentation related with Web Components and ReactJS: https://facebook.github.io/react/docs/web-components.html

**Comment by samiheikki** [comment]
Hey! Redux can be used along with vaadin-grid out of the box. Once you create a Redux store and create an behavior out of it (https://github.com/tur-nr/polymer-redux). You can just bind some property to vaadin-grid: Like this: 

```
<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="bower_components/vaadin-grid/vaadin-grid.html">
<link rel="import" href="redux-store.html">

<dom-module id="my-grid">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <vaadin-grid items="[[persons]]">

      <vaadin-grid-column width="50px" flex-grow="0">
        <template class="header">#</template>
        <template>[[index]]</template>
      </vaadin-grid-column>

      <vaadin-grid-column>
        <template class="header">Name</template>
        <template>[[item]]</template>
      </vaadin-grid-column>

    </vaadin-grid>

  </template>
  <script>
    Polymer({
      is: 'my-grid',
      behaviors: [ReduxBehavior],
      properties: {
        persons: {
          type: Array,
          statePath: 'persons'
        }
      }
    });
  </script>
</dom-module>
```

@Saulis don't mix up redux with react ;)

**Comment by samiheikki** [comment]
Don't think it should be added as an example to our demos. Data is binded the same way to vaadin-grid, whether redux is used or not.

**Comment by codingnube** [comment]
@jouni @Saulis  Thanks for the pointers. @samiheikki Special thanks to yourself. Well, I'd say that you've given a demo already. Works like a charm. Cheers :thumbsup:
