### ISSUE TITLE
Should not change Active Item when clicking on row details

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#797]
Can be reproduced here: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha4/demo/row-details.html#expanding-items-without-data-binding

The mouse click on row details should not close the row details.
 
Actual result (left click on row details closing row details):

![recorded](https://cloud.githubusercontent.com/assets/6059356/23790308/353f4c1a-0587-11e7-91f6-543b5059dc0c.gif)

Expected result: click on row details does not close the row details

**Comment by aruntk** [comment]
Due to this I'm not able to copy text from row details pane. Any workarounds?

**Comment by tomivirkki** [comment]
If you want to bind the opening to activeItem then you'll need to prevent activeItem from clearing on details click. For Example `wrapper.addEventListener('click', e => {e.stopPropagation()}, true)` where `wrapper` is the container for all elements in the details. In the demo's case it's the `<div class="details">` element

**Comment by aruntk** [comment]
@tomivirkki Thanks for the comment. In addition to click event propagation should be stopped for mouse events also. To prevent gestures from propagating.

**Comment by jouni** [comment]
@tomivirkki, any chance of just implementing the prevention in the grid directly? I bet everyone would like it to behave like that, and would not expect the details row/cell to “activate” the main row.

This affects the `auto-select` property of `vaadin-grid-selection-column` as well: #1173
