### ISSUE TITLE
Demos with custom dom modules don't work on IE11

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#799]
Since IE11 uses a polyfill for `<template>`, any `<script>` inside a template is run during init.

Demo which include a template containing custom `<dom-module>` and `<script>` which calls `Polymer({..})` will fail in IE11.

Adding a `WebComponentsReady` listener should fix this issue.

**Comment by platosha** [comment]
Note: In IE11, `<demo-snippet>`’s code snippet shows `<template>` contents as empty. This is, probably, due to the `<demo-snippet>` incompatibility with the `<template>` polyfill.

The demos work fine, though.
