### ISSUE TITLE
Material Design styling?

### ISSUE THREAD

**Issue by victorhooi** [vaadin/vaadin-grid#807]
There was a comment from @jouni here:

https://github.com/Saulis/iron-data-table/issues/167#issuecomment-262441225

that the plan was to ship MD-inspired styles alongside vaadin-grid 2.0. Is that still the case?

The MD specs for data-tables are here:

https://material.io/guidelines/components/data-tables.html#

**Comment by jouni** [comment]
Almost. For 2.0, we have an example how to style it for MD. 

Once we have the Polymer 2 version done, and our new theming/styling solution in place, then we will release a supported MD theme for vaadin-grid as well.

**Comment by jouni** [comment]
Here’s the current example: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha4/demo/styling.html

**Comment by victorhooi** [comment]
Ah awesome, that's pretty nifty.

I noticed there's some weird glitches - e.g.:

<img width="460" alt="screen shot 2017-03-17 at 13 27 44" src="https://cloud.githubusercontent.com/assets/243499/24026478/8c1c69ee-0b15-11e7-8021-86742f9b232f.png">

but I'm guessing it's all still pretty fresh =).

**Comment by victorhooi** [comment]
To clarify - is vaadin-grid 2.0 a hybrid element, or the Polymer 2.0 version you mentioned?

If hybrid - is there a timeframe for the native Polymer 2.0 version?

**Comment by jouni** [comment]
What browser did you use and see the glitches?

vaadin-grid 2.0 == Polymer 1 only
vaadin-grid 2.1 == hybrid
vaadin-grid 3 (probably) == Polymer 2 only

**Comment by victorhooi** [comment]
Aha, I just assumed it was still in flux so didn't bother digging into it =).

This issue reproduces on Chrome 59.0.3043.0 (i.e. current canary build) and is quite visible there - the white tick basically touches the right-hand side of the box.

I also just tested on Safari 10.0.3 (12602.4.8) - the issue is less pronounced there - but it still does seem slightly to the right:

<img width="536" alt="screen shot 2017-03-17 at 17 37 23" src="https://cloud.githubusercontent.com/assets/243499/24031804/b3bfeea8-0b38-11e7-97e4-d0984670d9c5.png">

Thanks for clarifying the situation around Polymer 1.0 vs Polymer 2.0 support. Polymer 2.0 is due to be released any day now (RC3 is out now). Do you have any ideas about the timeline for vaadin-grid 2.1 then?

(I see 2.1-dev is already a branch).

**Comment by dsyrstad** [comment]
What's the status on this? I'm on version 5.0.3 right now and there is little support for styling. Specifically I cannot get row background-color hovers to work. I'd like a full material design styling. It looks like there were styling features in 2.x and 3.x for this (see https://cdn.vaadin.com/vaadin-grid/3.0.0/demo/styling-material.html is a full working example), but those styling features have been removed in 5.x (apparently).

**Comment by jouni** [comment]
5.0 has a new styling system, based on [vaadin-themable-mixin](https://github.com/vaadin/vaadin-themable-mixin/wiki). It’s more flexible than the old system based on mixins.

The new Material design theme is currently being worked on at https://github.com/vaadin/vaadin-material-theme/blob/master/vaadin-grid.html, and will eventually be moved over to this repo (just like Lumo currently is).
