### ISSUE TITLE
JS Grid 1.2.0 - Cannot set property 'colSpan' of undefined

### ISSUE THREAD

**Issue by tonosama-atlacatl** [vaadin/vaadin-grid#808]
I'm running into this crippling bug:

1. Set all columns as "hidable".
2. "hide" more than 1 column by using the built in dropdown menu.
3. Scroll to the very bottom of the grid.
4. Try turning all hidden columns to visible..... <BOOOM!>, you get: **Cannot set property 'colSpan' of undefined** 
5. The grid is now crippled, the only solution is to refresh.

> Uncaught TypeError: Cannot set property 'colSpan' of undefinedwu @ vaadin-grid.min.js:239Iu @ vaadin-grid.min.js:241_.Yc @ vaadin-grid.min.js:241_.Id @ vaadin-grid.min.js:409iz @ vaadin-grid.min.js:310Gz @ vaadin-grid.min.js:318$x @ vaadin-grid.min.js:323gA @ vaadin-grid.min.js:334DC @ vaadin-grid.min.js:416Pr @ vaadin-grid.min.js:422_.tb @ vaadin-grid.min.js:187Sg @ vaadin-grid.min.js:58Pd @ vaadin-grid.min.js:631
> vaadin-grid.min.js:239 Uncaught TypeError: Cannot set property 'colSpan' of undefinedwu @ vaadin-grid.min.js:239Iu @ vaadin-grid.min.js:241_.Yc @ vaadin-grid.min.js:241_.Id @ vaadin-grid.min.js:409iz @ vaadin-grid.min.js:310Gz @ vaadin-grid.min.js:318Ly @ vaadin-grid.min.js:350$x @ vaadin-grid.min.js:323Xx @ vaadin-grid.min.js:285fy @ vaadin-grid.min.js:337_.tb @ vaadin-grid.min.js:400Sg @ vaadin-grid.min.js:58Pd @ vaadin-grid.min.js:631
> vaadin-grid.min.js:57 Uncaught Class$S192: Exception caught: (TypeError) : Cannot set property 'colSpan' of undefined(anonymous function) @ vaadin-grid.min.js:57

My setup:
Loading the grid into Dart and passing a dataprovider as a List of Maps, everything else works, row selection, sorting, etc. 

Simple example:
`<vaadin-grid id="grid" class="flex" items="{{gridData}}" >`
`            <table>`
`              <colgroup id="colgroupElement">`
`                <col name="firstName" hidable>`
`                <col name="lastName" hidable>`
`                <col name="email" hidable>`
`              </colgroup>`
`            </table>`
`</vaadin-grid>`

**Comment by tomivirkki** [comment]
Can confirm this happening on Safari 10. Will mark as a bug. If at all possible, consider switching to using `<vaadin-grid>` 2 (currently in beta review) https://github.com/vaadin/vaadin-grid/releases/tag/v2.0.0-alpha4

**Comment by tomivirkki** [comment]
Closing as wontfix
