### ISSUE TITLE
Can't freeze last column (v2.0.0-beta1)

### ISSUE THREAD

**Issue by gabrielle-perez-movile** [vaadin/vaadin-grid#823]
I need to freeze the last column (first from right to left), but, when I put "frozen" attribute on it, the column "disappears". According to devTools the column was placed in the left part of the screen with width and height equal to 0 and display none;

**Comment by jouni** [comment]
Hi! If you are looking for the feature that allows you to freeze a column to the right edge of the grid viewport, that if unfortunately not yet supported. Subscribe to issue #455 (and vote for that if you want by adding a 👍🏻 reaction to the issue description).

**Comment by jouni** [comment]
So, for now, you can only freeze columns starting from left to right.

**Comment by jouni** [comment]
I’ll close this as a duplicate of #455
