### ISSUE TITLE
Row details does not have proper index value

### ISSUE THREAD

**Issue by Torins** [vaadin/vaadin-grid#837]
According to the documentation in vaadin-grid, all templates used inside vaadin-grid have access to a few built-in variables, including:

"index": Number representing the row index

In case of multiple row details open at the same time, the template instances all get the same value (which I think is the index of the last details opened), instead of each getting their row's index.

**Comment by Saulis** [comment]
Thanks for the report!

Was able to reproduce the issue here: https://jsfiddle.net/7hb6jwv8/2/

**Comment by Torins** [comment]
Thanks for making the jsfiddl :)
I've looked into vaadin-grid-row-details-behavior and as far as I can see, "index: true" needs to be added to the _instanceProps object in _rowDetailsTemplateChanged.

I don't know if that causes any unexpected side effects though, I hadn't had the time to browse the code more, sorry

**Comment by Saulis** [comment]
Yes the `index: true` should fix the issue, running tests now to see everything is still working.
