### ISSUE TITLE
Animating width change

### ISSUE THREAD

**Issue by Torins** [vaadin/vaadin-grid#839]
Hey, I wanted to animate adding new (hidden) columns with a slide-in animation and figured I could do it by adding transition to width changes.

Unfortunately, it requires adding css to td and th tags, which I believe is impossible with the shadow dom enabled.

Is there any other way and if not, may I request an option to do such animations?

example: https://jsfiddle.net/7hb6jwv8/4/

**Comment by Saulis** [comment]
Hi!

You are correct, shadow DOM prevents styling the `<th>` and `<td>` elements directly.

An alternative, although hacky solution, would be to create the animation by changing the `column.width` through javascript.

As a feature request, I think we could expose a CSS property which you allow defining `transition` effects for the cells.

**Comment by tomivirkki** [comment]
The `[part~=cell]` (`<td>`, `<th>`) elements can be styled nowadays using the [themable mixin styling mechanism](https://github.com/vaadin/vaadin-themable-mixin/wiki) so this kind of animated column width change is doable.
