### ISSUE TITLE
Response times is decreasing significantly if cell height less than 30px. (Depends on number of columns) v2

### ISSUE THREAD

**Issue by SenerDemiral** [vaadin/vaadin-grid#841]

**Comment by SenerDemiral** [comment]
It may seem silly to you, but you can see if you add 25 columns and 100 rows to your demo.

**Comment by Saulis** [comment]
Hi!

The lower the row height is, the more row elements need to be created to fill out the viewport. Also, adding more columns increases the amount of cell elements rendered in the DOM. 

Depending on the hardware you're running on, there's a threshold at which point the number of elements in the DOM gets too large for the performance to be smooth.

We are constantly looking for performance improvements, limiting the number of elements in the DOM is something we can optimize only to a certain limit, unfortunately. 

So my recommendation is to try to find ways of limiting amount of columns needed to display on the grid.

**Comment by SenerDemiral** [comment]
Thanks
