### ISSUE TITLE
Details row space does not get collapsed when closed

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-grid#845]
**Version:** 2.0.0-beta3

When I close the details row, the space it took does not collapse. 

![vaadin-grid-2-beta3-collapse](https://cloud.githubusercontent.com/assets/883698/24783015/975c3fb6-1afe-11e7-86f9-067052717c89.gif)

The app is built with polymer-cli@next with the following build options:
```
"builds": [{
    "name": "bundled",
    "addServiceWorker": true,
    "bundle": true,
    "js": {
      "compile": true,
      "minify": true
    },
    "css": {
      "minify": true
    },
    "html": {
      "minify": true
    }
  }]
```

**Comment by Saulis** [comment]
I guess this has something to do with the build since the row details demo we have works as expected. As a workaround, calling `grid.notifyResize()` on `expanded-items-changed` should help.

**Comment by manolo** [comment]
@vaadin-marcus could you share your demo code?

**Comment by vaadin-marcus** [comment]
@manolo - sorry, missed this entirely. Code is here https://github.com/vaadin/patient-portal-demo-polymer
build with `polymer build` and select a patient, then journal.
