### ISSUE TITLE
Provide horizontal infinite scrolling  (for columns)

### ISSUE THREAD

**Issue by rajaraodv** [vaadin/vaadin-grid#851]
It would be great if you also provide horizontal infinite scrolling  (for columns) which is one of the use cases for enterprises with 100-500 columns. 

This is pretty cool BTW.

**Comment by platosha** [comment]
Thanks for your feature request.

Such a feature requires quite a bit of rewrite for the scrolling code. Unfortunately, we can not add major features in near future, before we are done with Polymer v2.0 upgrade.

**Comment by web-padawan** [comment]
Closing in favor of #1575 which is more recent and contains the link to prototype.
