### ISSUE TITLE
Strange check of this._pendingRequests.length > 0;

### ISSUE THREAD

**Issue by tdesc** [vaadin/vaadin-grid#854]
vaadin-grid-data-provider-behavior.html
loadPage function
242 line
this._loading = this._pendingRequests.length > 0;
and in clearCache function
_pendingRequests = {};

**Comment by web-padawan** [comment]
The relevant code updated in 25b5630 and is hopefully not that strange now 😄 
Closing as inactive, sorry about not answering earlier.
