### ISSUE TITLE
Sorting not possible in IE11 when the header has a filter

### ISSUE THREAD

**Issue by jacsbro** [vaadin/vaadin-grid#862]
I have a header defined like this:

```html
  <template class="header">
    <vaadin-grid-filter path="publicId" value="[[_filterStationId]]" on-value-changed="_filterChanged">
      <input placeholder="ID" value="{{_filterStationId::input}}" focus-target></input>
      <vaadin-grid-sorter path="publicId" on-direction-changed="_directionChanged"></vaadin-grid-sorter>
    </vaadin-grid-filter>
  </template>
```

Sorting and Filtering the column works well in Chrome 57 and Firefox 52. Unfortunately in IE11 it is not possible to click on the sorting indicators. When i remove the filter I'm able to sort but I need filters too.

The only workaround I found up to now is moving the vaadin-grid-sorter outside the vaadin-grid-filter like this:

```html
<vaadin-grid-filter path="publicId" value="[[_filterStationId]]" on-value-changed="_filterChanged">
  <input placeholder="ID" value="{{_filterStationId::input}}" focus-target></input>
</vaadin-grid-filter>
<vaadin-grid-sorter path="publicId" on-direction-changed="_directionChanged">ID</vaadin-grid-sorter>
```

But I do not like this because it wastes vertical space and looks odd.  Surrounding the filter/sorter with a span looks good in Chrome/FF. IE does not render the sorter.

Any ideas / workarounds?

**Comment by tomivirkki** [comment]
@jacsbro Thanks for the report, fix pending at https://github.com/vaadin/vaadin-grid/pull/865. 

Meanwhile, the span workaround you mentioned should work. The "ID" text gets visible if you add explicit width `style="width: 45px"` to the `<vaadin-grid-sorter>`.

**Comment by jacsbro** [comment]
Thanks @tomivirkki, and thanks to the vaadin team for providing vaadin-grid !

 Looking forward to #865. In the meantime the suggested workaround works for me.

**Comment by tomivirkki** [comment]
Let's keep the issue open so the PR doesn't get ignored by reviewers. Once the PR gets merged, it will automatically close this issue also :)

**Comment by jacsbro** [comment]
Of course! Sorry for the inconvenience - I suppose I just clicked the wrong button :-)
