### ISSUE TITLE
Sorting/Filtering - Grid unresponsive

### ISSUE THREAD

**Issue by dezwei** [vaadin/vaadin-grid#871]
Hey

I have a grid with 
`          <template class="header">
            <vaadin-grid-sorter path="rank">
              <vaadin-grid-filter path="rank" value="[[queryParams.rank]]">
              </vaadin-grid-filter>
            </vaadin-grid-sorter>
`

when i sort/filter around 130 data its unresponsive for some seconds.

BUT
When i open details and then sort or filter its running smooth like hell.
When i close details its unresponsive again.

**Comment by dezwei** [comment]
#856

**Comment by Saulis** [comment]
Hi @dezwei!

Could you post a more verbose example (preferably a runnable snippet in jsfiddle) which shows all the relevant parts like how you assign data etc.

Sorting and filtering > 200 items works just fine in our examples.

**Comment by tomivirkki** [comment]
Closing as inactive.
