### ISSUE TITLE
Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule  in C:/Users/Desktop/angular-cli-vtp/node_modules/angular2-datatable/node_modules/@angular/core/src/metadata/ng_module.d.ts

### ISSUE THREAD

**Issue by annaimaha** [vaadin/vaadin-grid#873]
Just upgraded to Angular 2.0.0 and 4.0.0

I am getting the error below:

Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule  in C:/Users/Desktop/angular-cli-vtp/node_modules/angular2-datatable/node_modules/@angular/core/src/metadata/ng_module.d.ts

**Comment by platosha** [comment]
@annaimaha hi, this seems to be not related with `<vaadin-grid>` element. We don’t have any Angular-related code here in this repo. It is definitely not `<vaadin-grid>` that calls the `makeDecorator` function and causes this error.
