### ISSUE TITLE
vaadin-grid should have `as` attribute

### ISSUE THREAD

**Issue by bennypowers** [vaadin/vaadin-grid#875]
`vaadin-grid` should implement an `as` attribute which would function the same as `dom-repeat`'s `as`. Users may refrain from using `as` in dom-repeats in order to match vaadin-grid's markup, but semantic markup is preferred. 

Providing this feature would allow a better developer experience, bringing vaadin-grid more closely in line with established community standards. 

For example:

```html
<template is="dom-repeat" items="[[videos]]" as="video">
  [[video.id]]
  [[video.title]]
  •••
</template>
```

Users should have the option to define an as on vaadin-grid as well:

```html
<vaadin-grid items="[[videos]]" as="video">
  <vaadin-grid-column>
    <template>[[video.id]]</template>
  </vaadin-grid-column>
</vaadin-grid>
```

**Comment by web-padawan** [comment]
Support for Polymer data bindings will be removed when we eventually rewrite grid to LitElement. So we are not going to add new features related to Polymer `<template>` system. Closing.
