### ISSUE TITLE
Convert to ES6

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-grid#878]
re enable iphone ipad tests

**Comment by tomivirkki** [comment]
Known issues that need to be taken care of in scope of this:
- [ ] `<iron-list>` is currently inherited by the `<vaadin-grid>`. Mark all iron-list public API's as `@private` (but do it in vaadin-grid-scroller) so they don't end up in the apidoc
- [ ] `scrolling` attribute should not be applied to host. Move it to the `#scroller` element instead and rescope selectors
- [ ] Scope `VaadinGridScroller` under Vaadin.Grid like the rest of the modules
- [ ] Column resizing needs to mind affecting padding/border etc of `<th>` elements also when computing minimum width for a column
- [ ] Mobile Chrome doesn't allow horizontal touch scrolling over the header
- [ ] While reordering column groups, not all cells have the correct indicator colors
- [ ] Grabbing a column resizer handle can activate column reordering
- [ ] Fix layout issues in IE11
