### ISSUE TITLE
Variable row height in grid

### ISSUE THREAD

**Issue by BrianSiimAndersenEG** [vaadin/vaadin-grid#879]
Are there any plans to support variable row height for grid? And if so - when can it be expected?

We're using Vaadin 8 and would love to use the grid, but we need variable heights for the grid rows, which are not supported. It's supported in table and hat means that we're stuck with the table - unfortunately...

**Comment by BrianSiimAndersenEG** [comment]
Closed again - should have been created for the framework...

**Comment by jouni** [comment]
Yeah, vaadin-grid v2 (this repo) does support variable row height. So when we eventually implement the server side java connector for it, you will get it there as well.
