### ISSUE TITLE
Pressing Space when a header cell is focused updates activeItem

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#881]
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-grid/demo/selection.html#selection-using-active-item example

- Click a row -> row becomes selected
- Press Shift-Tab x 2 -> keyboard focus moves to the header
- Press Space -> row selection is cleared

The same does not happen when you click the header with a mouse, which to me indicates the the `activeItem` is updated differently when using the mouse or the keyboard.

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
