### ISSUE TITLE
Filtering using data provider does not scroll to the top

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#882]
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-grid/demo/sorting-filtering.html#filtering-with-data-provider

- Scroll to the bottom of the grid
- Type “a” in the first name filter -> You see the grid spinner
- Scroll the grid up to around rows 140 -> The rows get updated, and the scroll height is also updated (you can’t scroll back to row 199 anymore)

**Comment by samiheikki** [comment]
Issue most likely in rest api as that is returning an error.
https://github.com/vaadin/demo-data I'll see if I can get this repo launched locally and make a fix there. And after that fix, the url should be updated in this example.

**Comment by samiheikki** [comment]
Discussed with @tomivirkki and decided to close the ticket.
