### ISSUE TITLE
Firefox 53.0.2 (64 bit, Windows) scrolls only <see Mouse Properties> pixels every notch (WheelEvent.deltaMode is not used)

### ISSUE THREAD

**Issue by Darsstar** [vaadin/vaadin-grid#883]
How to reproduce: go to https://cdn.vaadin.com/vaadin-grid/2.0.0/demo/row-details.html and scroll.

Related: https://github.com/vaadin/framework/issues/6578, https://github.com/vaadin/framework/issues/6384

In my case it scrolls 3 pixels per notch:
![image](https://cloud.githubusercontent.com/assets/104949/25944547/ffc61062-3643-11e7-86ab-b4b1022d7c02.png)

@manolo [Was able to reproduce the issues but asked me to open a new issue under the correct project.](https://github.com/vaadin/vaadin-core-elements/issues/117)
His suggested solution is to pickup the JSNI block used by the framework: https://github.com/vaadin/framework/commit/f4069826

**Comment by tomivirkki** [comment]
`deltaMode` is considered nowadays https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-scroll-mixin.html#L101 Closing
