### ISSUE TITLE
Vaadin grid 3.0.0-alpha1 demo menu CSS is not aligned with other core-elements demos

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid#888]
This is the current one

![screen shot 2017-06-02 at 09 16 06](https://cloud.githubusercontent.com/assets/161853/26715015/4b39e924-4774-11e7-8260-291e28311339.png)

It should look:

![screen shot 2017-06-02 at 09 16 12](https://cloud.githubusercontent.com/assets/161853/26715022/4e9042da-4774-11e7-9a8f-60a22f8da7ed.png)

**Comment by web-padawan** [comment]
The issue is for the old version. Demos have been since changed, so closing this as outdated.
