### ISSUE TITLE
V8 Grid.java should have firstVisibleRowIndex() method

### ISSUE THREAD

**Issue by vasbork** [vaadin/vaadin-grid#894]
Hi!
In many apps it is VITAL to have a method that returns the first (or top) row index of grid's viewport. It is urgent for situations when grid switches between several datasets, as well as in many other practical cases. Without such functionality Grid remains a fancy looking toy for a significant number of tasks. Even the old deprecated Table suggested some kind of solution with its getCurrentPageFirstItemId() method.  Here's a link from Vaadin Forum about this theme: https://vaadin.com/forum#!/thread/14448976

**Comment by tomivirkki** [comment]
Hi @vasbork,
If the issue is about Vaadin Framework 8 Grid, [Here's](https://github.com/vaadin/framework) is the repository you're looking for. This is the repository of the `<vaadin-grid>` Web Component.

**Comment by vasbork** [comment]
Hi Tomi,
pardon, closing it here!
