### ISSUE TITLE
Resizing the first column crashes IE11

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#896]
IE11 crashes when the first column is resized:
https://cdn.vaadin.com/vaadin-grid/2.0.2/demo/columns.html#reordering-and-resizing-columns

**Comment by samiheikki** [comment]
IE11 crash required me to first reorder the first column and **then** resize it. Plain resize did not crash IE.

**Comment by tomivirkki** [comment]
This can be worked around for now by adding a hidden column before the rest of the columns (in case the first column must be resizable):
```
<vaadin-grid-column hidden>
  <template></template>
</vaadin-grid-column>
```

**Comment by tomivirkki** [comment]
Doesn't reproduce anymore with the newest releases
