### ISSUE TITLE
error with lazyRegister set in window.Polymer

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-grid#898]
If I set lazyRegister:

```
      window.Polymer = {
        dom: 'shadow',
        lazyRegister: 'max',
      };
```

then I get an error about the tr element not having a method toggleAttribute:

```
Uncaught TypeError: el.toggleAttribute is not a function
    at HTMLElement.<anonymous> (vaadin-grid-table.html:580)
```

**Comment by tomivirkki** [comment]
The rows in `<vaadin-grid>` 2 are extended native elements `<tr is=“vaadin-grid-row”>` and `lazyRegister` in `max` mode [doesn’t handle](https://www.polymer-project.org/1.0/docs/devguide/settings) such cases.

This doesn’t occur in the hybrid version (currently [v3.0.0–alpha1](https://github.com/vaadin/vaadin-grid/releases/tag/v3.0.0-alpha1)) anymore where the rows are plain custom elements.
