### ISSUE TITLE
vaadin-grid-table-body overflows

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-grid#905]
Demo: https://jsbin.com/yokewut/edit?html,output

You can see that it creates extra scrollbars and empty space in the bottom as vaadin-grid-table-body overflows (even tough not visible)

**Comment by davidmaxwaterman** [comment]
I get this in my app too (or something that is very similar). I have 1000 rows, so the gap is pretty huge. A solution would be very nice.

**Comment by jay8t6** [comment]
Can you guys add a mixin for vaadin-grid-table-body? I am noticing that its adding a scrollbar whenever the number of rows change while switching the data. If I add overflow: hidden property to #items, it never happens.

**Comment by web-padawan** [comment]
I could not reproduce this issue with the lates web component version:
https://glitch.com/edit/#!/ebony-brassy-polish?path=index.html

We no longer support `vaadin-grid` version 3, and now it is very outdated. it is recommended to use the most recent version (currently 5.x) which gets all the fixes.

There hasn't been any activity in this issue for a while. Closing as stale.
