### ISSUE TITLE
BAS feature: waterfall header shadow

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-grid#906]
Grid needs a following feature for BAS: Waterfall header shadow. When grid is scrolled up, the header shadow is not visible and once the user starts scrolling down, the shadow appears. Quite similar as in [app-header]

(https://www.webcomponents.org/element/PolymerElements/app-layout/elements/app-header).

Add attributes: "scrolled-top" and "scrolled-bottom" to the host elements. Using theme in a theme is taken care of in vaadin/vaadin-themes#42.
Add tests and mention of the new state attributes in the apidocs.

<img width="846" alt="screen shot 2017-06-13 at 11 31 27" src="https://user-images.githubusercontent.com/8615573/27073264-ebe85ec2-502b-11e7-8d02-f0e64e6f7417.png">

**Comment by manolo** [comment]
Not a blocker for BAS but nice to have asap. We are going to ES6 first and then with this.

**Comment by jouni** [comment]
Related: #526

**Comment by tomivirkki** [comment]
The `overflow` state attributes were added to the grid. "no-row-borders" variant uses them to implement the feature described in the ticket. Closing.
