### ISSUE TITLE
duplicate rows with lazy load

### ISSUE THREAD

**Issue by ruwentos** [vaadin/vaadin-grid#907]
We use vaadin-grid 2.0.3 with polymer. Windows 7, browsers: FireFox 54.0, Chrome 58
Our case is to show a list of about 360 items. We implemented lazy load. Everything seems to work properly.
At a closer look we can detect duplicate items in the grid. If we check the params variable from the dataProvider function while loading we can see strange things. 
First load we expect params.page = 0 and params.pageSize = 50 (what is default). That is the case. But right after the first call of dataProvider. The grid calls again and this time with params.page = 1 and params.pageSize = 50. So we miss the first row.
After scrolling down, we see calls of dataProvider with params.page = 2, params.page = 3,  params.page = 4,  params.page = 5,  params.page = 6,  params.page = 7 right after each other always with params.pageSize = 50. The index does not increase on a appropriate amount even when we scroll to the bottom of all 360 items.
We did not have that issue with the 1.* version.
Lazy load works as expected when the list of all items is smaller then 50.

Does someone else have seen that behavior?

greetings

S.

**Comment by jouni** [comment]
Hi,

The function data provider request object has changed a bit from 1.2 to 2.0. In 1.2, the request object had `index` and `count` that corresponded directly to row numbers. In 2.0, you have have `page`, that indicates the page to fetch, that contains as many rows of data as `pageSize` indicates.

I think the problem here is that you didn’t notice this change.

**Comment by jouni** [comment]
If you want to use the same backend still with 2.0, you can convert the `page` to `index` by multiplying `page` with `pageSize`:

```javascript
var index = params.page * params.pageSize;
```

**Comment by ruwentos** [comment]
Thank you jouni. You are perfectly right. Problem solved.

**Comment by jouni** [comment]
Great, glad to help. I’ll close this then :)
