### ISSUE TITLE
vaadin-grid is not working with polymer

### ISSUE THREAD

**Issue by robertop87** [vaadin/vaadin-grid#908]
Please more details here.
Basically I couldn't get vaadin-grid working on polymer.
 
https://stackoverflow.com/questions/44622389/vaadin-grid-is-not-working-with-polymer

**Comment by Sahero** [comment]
I had the same issue. It worked for me after I updated the vaadin-grid to 3.0.0-alpha2. But I don't know the reason behind this.
Thanks.

**Comment by Saulis** [comment]
Added a comment to stack, looks to me like you're running Polymer 2.0. v2.0.3 and Polymer 1.9 works just fine: https://jsfiddle.net/Saulis/arqt8nnc/

**Comment by davidmaxwaterman** [comment]
Is it possible to use v3.0.0-alpha2 with polymer 1.9?

**Comment by Saulis** [comment]
@davidmaxwaterman yes, `3.x` is a hybrid element so it works with both Polymer 1.7 (or later) and Polymer 2.0.
It does, however, default its dependencies to hybrid elements so you might need to resolve some conflicts while installing. Alternatively, if you use `polymer-cli` you can use `polymer install --variants` which will avoid these conflicts by installing P1 and P2 variants.

**Comment by web-padawan** [comment]
The dependencies for 3.x fixed in #1059 and released in v3.1.0
And the initial question was answered above, so I'm closing this issue.
