### ISSUE TITLE
Filtering numerically/with regex?

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-grid#909]
I'm using vaadin-grid-filter, but it seems to filter by string. Is there a way to specify the filter, so that I can (effectively) filter numerically?

IE, I want to filter all rows with '0', and so want to specify a regex of '/^0$/' so I don't also get '10' and such like.

Ref:
https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-array-data-provider-behavior.html#L127

**Comment by tomivirkki** [comment]
Hi Max, sorry for the delay.
The built-in array data provider only filters by text and there’s currently no public APIs for changing that. If you’re brave enough, you can always override the private [`_filter`](https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-array-data-provider-mixin.html#L136) function.

Filtering can be fully customized as described in “Filtering with Data Provider” [demo](https://vaadin.com/elements/vaadin-grid/html-examples/grid-sorting-filtering-demos) by defining a custom `_dataProvider`. Of course then you’ll lose all the conveniences of the array data provider.

**Comment by web-padawan** [comment]
For anyone interested in this, I'm leaving here a permalink to `_filter` function:
https://github.com/vaadin/vaadin-grid/blob/06fdf4ecc8d32575ebbc1de9e994683e707f85e0/src/vaadin-grid-array-data-provider-mixin.html#L140

Closing per above comment as answered.
