### ISSUE TITLE
paper-dropdown-menu is clipped

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-grid#910]
vaading-grid v2.0.3

If I put a paper-dropdown-menu in a cell of the grid, when clicked and the menu opens, the content of the menu seems to be clipped.

I see that .vaadin-grid-cell ::content > vaadin-grid-cell-content has overflow: hidden, and I can override that with --vaadin-grid-body-cell, but it doesn't seem to have any effect.

Any insight into how to get this working welcome. In the meantime, I'll see if I can figure it out and/or come up with a simple demo of the problem.

**Comment by Saulis** [comment]
Hi!, This is a duplicate issue of #842.
