### ISSUE TITLE
Polymer-2-starter-kit and Vaadin Grid

### ISSUE THREAD

**Issue by EvD92** [vaadin/vaadin-grid#917]
Hey all,

I'm using the starter kit from polymer init.

I've got some issues with: bower install --save vaadin/vaadin-grid

Unable to find a suitable version for iron-resizable-behavior, please choose one by typing one of the numbers below:
    1) iron-resizable-behavior#2.0-preview which resolved to a448923e68 and is required by app-layout#1233b73c35, iron-pages#639f541e10
    2) iron-resizable-behavior#^1.0.5 which resolved to 1.0.6 and is required by vaadin-grid#2.0.3

Unable to find a suitable version for iron-scroll-target-behavior, please choose one by typing one of the numbers below:
    1) iron-scroll-target-behavior#2.0-preview which resolved to 02176d80e6 and is required by app-layout#1233b73c35
    2) iron-scroll-target-behavior#^1.1.0 which resolved to 1.1.1 and is required by vaadin-grid#2.0.3

Unable to find a suitable version for polymer, please choose one by typing one of the numbers below:
    1) polymer#^1.1.0 which resolved to 1.9.2 and is required by iron-a11y-announcer#1.0.6, iron-a11y-keys-behavior#1.1.9, iron-resizable-behavior#1.0.6, iron-scroll-target-behavior#1.1.1
    2) polymer#^1.6.1 which resolved to 1.9.2 and is required by vaadin-grid#2.0.3
    3) polymer#^2.0.0-rc.3 which resolved to 2.0.1 and is required by app-layout#1233b73c35, polymer-starter-kit
    4) polymer#^2.0.0-rc.1 which resolved to 2.0.1 and is required by iron-meta#7404b31da3

Unable to find a suitable version for iron-a11y-keys-behavior, please choose one by typing one of the numbers below:
    1) iron-a11y-keys-behavior#2.0-preview which resolved to 90c3c3370c and is required by iron-behaviors#cdcb3a8fb0, paper-ripple#7f7a6d9c6e
    2) iron-a11y-keys-behavior#^1.1.9 which resolved to 1.1.9 and is required by vaadin-grid#2.0.3

Unable to find a suitable version for webcomponentsjs, please choose one by typing one of the numbers below:
    1) webcomponentsjs#^0.7.24 which resolved to 0.7.24 and is required by polymer#1.9.2
    2) webcomponentsjs#^1.0.0-rc.7 which resolved to 1.0.1 and is required by polymer-starter-kit
    3) webcomponentsjs#^v1.0.0 which resolved to 1.0.1 and is required by polymer#2.0.1

When just picking all for Vaadin and starter kit I can't even load the app correctly.
I've managed to find a way to get it working, however it triggers the next problem:
- GET https://website/undefined 404 () iron-list-behavior.html:569

Which results in ugly rows when I start scrolling...

Anyone got a fix/solution for this?

**Comment by H3dz** [comment]
What's in your bower.json file?

I use "vaadin-grid": "vaadin/vaadin-grid#3.0.0-beta1"
and it works we no issues.

**Comment by web-padawan** [comment]
I have tried installing both 3.0.2 and 4.0.0 versions with the `polymer-2-starter-kit` and everything works now. Therefore I am closing this issue.
