### ISSUE TITLE
How to set row style conditionally 

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-grid#922]
Hello everyone,

this question is for grid 3.0.

Is there any way to set a rows color (background and/or text) conditionally based on its [item]] (e.g. if [[item]] property "hasErrors" is true, set row background color to red)? Until now, I couldn't find any demos or examples where this is done.

Every help is appreciated :)

Regards,
Michael

**Comment by platosha** [comment]
@Mika83AC It is not possible to change the row styles specifically. But you can change the appearance of cell content using wrappers:

```html
<style>
  [has-errors] {
    background-color: red;
  }
</style>

<vaadin-grid>

  <vaadin-grid-column>
    <template class="header">First Name</template>
    <template>
      <div has-errors$="[[item.hasErrors]]">
        [[item.firstName]]
      </div>
    </template>
  </vaadin-grid-column>

  <vaadin-grid-column>
    <template class="header">Last Name</template>
    <template>
      <div has-errors$="[[item.hasErrors]]">
        [[item.lastName]]
      </div>
    </template>
  </vaadin-grid-column>

</vaadin-grid>
```

**Comment by Mika83AC** [comment]
Hm... that's not truly satisfying as only a part of the cell get's styles because of the parents padding which prevents the div to span the full cell:

![image](https://user-images.githubusercontent.com/3017748/27958894-64e51c6e-6325-11e7-9b5b-784468fc6e29.png)

Is there any way to style the div's parent? Otherwise this solution can only help on styling the text and not the cell/row background.

**Comment by platosha** [comment]
@Mika83AC you should be able to remove the builtin cell padding using CSS mixins:
```html
<custom-style>
  <style>
    vaadin-grid {
      --vaadin-grid-cell: { padding: 0; }
    }
  </style>
</custom-style>
```

Then padding can be added back inside the cell wrappers using regular CSS.

The rows are shadow DOM the grid, conditional styling directly on the rows is not supported, unfortunately.

**Comment by Mika83AC** [comment]
Oh, sure, you're right! 😄

**Comment by bennypowers** [comment]
If your goal is to spread an overlay over the row, the following styles work without needing to change global padding:

```css
      [deleting] {
        opacity: 0.75;
        background-color: var(--paper-grey-500);
        z-index: 1;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        position: absolute;
      }
```
