### ISSUE TITLE
Putting row-details template inside a <slot> ?

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-grid#923]
Hello everyone,

is it possible to put the row-details template for a vaadin-grid inside a <slot>?

Here's my "poly-grid" element where I want to be able to plug-in various rowDetail templates, depending on the context where the grid is used:

```
<dom-module id="poly-grid">
   <template>
      <vaadin-grid items=[[data]]>
         <!-- SLOT FOR A OPTIONAL ROW TEMPLATE -->
         <slot name="rowDetailTemplate"></slot>

         <!-- columns etc ..... -->
      </vaadin-grid>
   </template>
</dom-module>
```

Now, when using my poly-grid, I'd like to plug-in the rowDetail template:

```
<poly-grid id="grid1">
   <template slot="rowDetailTemplate" class="row-details">
      <div >         
         <div class="details">
             <p>Hello! I'm the row detail for [[item.firstName]]!</p>
           </div>
        </div>
   </template>
</poly-grid>
```

Doing so, nothing happens when expanding a row.

Changing my poly-grid and call-site like below, the row detail appears when expanding a row, but contains the non-evaluated content of the row details -> "Hello! I'm the row detail for [[item.firstName]]!":

```
<dom-module id="poly-grid">
   <template>
      <vaadin-grid items=[[data]]>
         <!-- SLOT FOR A OPTIONAL ROW TEMPLATE -->
         <template class="row-details">
            <slot name="rowDetailTemplate"></slot>
         </template>

         <!-- columns etc ..... -->
      </vaadin-grid>
   </template>
</dom-module>
```
```
<poly-grid id="grid1">
   <div slot="rowDetailTemplate" class="details">
      <p>Hello! I'm the row detail for [[item.firstName]]!</p>
   </div>
</poly-grid>
```

So that isn't working too because the [[item.firstName]] doesn't get evaluated.

I tried some more variants, but non of them got working like expected.

What am I doing wrong? Is it possible at all? Any ideas?

Regards,
Michael

**Comment by platosha** [comment]
This use case is not supported, as of now. We might consider adding support for this, though.

See also: #890.

**Comment by Mika83AC** [comment]
That would be highly appreciated. 

I'm trying to build a general purpose grid based on the vaadin-grid. For now I've already solved the column generation by just passing an array of objects to my grid and the columns are generated from that in a dom-repeat. Sorting and Filtering this is also solved.

But then I got stuck trying to pass in a row-detail template via a <slot>. So I hope that your considerations will result in a feature. :)

Thx and best regards,
Michael

**Comment by ChetaRaul** [comment]
Hello,

have the same problem, I use vaadin-grid-4.0.0-alpha5 and it works well for the first row but for the others row it does not work.

![vaadin-grid](https://user-images.githubusercontent.com/32925915/31812965-595db63e-b58d-11e7-80bd-1ab7e494a66a.gif)

**Comment by jwhentsch** [comment]
Hello,
I came to the exact same problem and would really like to see support for a slottable details template which contains data bindings that get resolved to the exact time.
Thanks in advance,
jwh

**Comment by tomivirkki** [comment]
Grid's light DOM changes are observed but currently only changes to column elements are processed.

Related https://github.com/vaadin/vaadin-grid/issues/1196

We'll get this fixed soon.

**Comment by Ch3rlO** [comment]
Any chance of adding this feature?
