### ISSUE TITLE
It is not possible implement a custom sort on column

### ISSUE THREAD

**Issue by Eymerich01** [vaadin/vaadin-grid#926]
There is case where is need specify a custom sort for each column . it is not possible. Right?

**Comment by Mika83AC** [comment]
It is possible. 

You could use the dataProvider which NEEDS a custom filter/sort, or if you use the items property , just filter/sort the source data array how you need it and reassign the result to the items property.

Working nice and really fast for me (both ways).

Michael

**Comment by Eymerich01** [comment]
Thx for you answer!
Have you an example that explain what you said?

Al

**Comment by Mika83AC** [comment]
This is the most basic example possible and not very "clean", but it should guide you to the "right" path. :)

[http://jsbin.com/vaqoxolire/1/edit?html,output](url)

**Comment by justinplatz** [comment]
This issue is still not fixed, and the code snippet above is taken down.

**Comment by tomivirkki** [comment]
As @Mika83AC mentioned, `dataProvider` can be used to implement any kind of custom sorting/filtering. The ["Filtering with Data Provider"](https://vaadin.com/elements/vaadin-grid/html-examples/grid-sorting-filtering-demos) example shows how to implement this.
