### ISSUE TITLE
A way to specify scrollTarget

### ISSUE THREAD

**Issue by andrew-silva-movile** [vaadin/vaadin-grid#932]
Hi Guys,
I'm using the element in Polymer 1.9, I added a `vaadin-grid` with another `vaadin-grid` inside `row-details`, it is working great, but I'm getting two horizontal scrolls, one in the main `vaadin-grid` and another in `row-details`.

There is a away to set scrollTarget of `vaadin-grid` inside `row-details` to use "vaadin-grid-table"?

**Comment by samiheikki** [comment]
Hi! Can you share a snippet of your code.

**Comment by tomivirkki** [comment]
Closing as inactive
