### ISSUE TITLE
Feature request: drag/drop between grids

### ISSUE THREAD

**Issue by christophe-g** [vaadin/vaadin-grid#935]
Hey, 
thanks for this component !

I don't think there is an easy way to drag/drop row items from one grid to another ? Is this a feature the Vaadin Team might consider ?

**Comment by samiheikki** [comment]
Hi! You could be able to use HTML5 Drag and Drop and use dom-if in both grids to either show/hide the column (haven't tested tough). Even tough this sounds like a cool feature, we will not implement it at the moment as it would require for the grid access the whole document/other elements which is something we are not at the moment planning for. Closing this issue now, but reopening again if it comes viable. Thanks for your request!
