### ISSUE TITLE
vaadin-grid-selection-column: binding problem with internal template

### ISSUE THREAD

**Issue by christophe-g** [vaadin/vaadin-grid#937]
In the example below `selected` is not properly bound to template instance (e.g. clicking on the checkbox input will not select the item - and when the item is selected, checkbox does not reflect proper state). 

Tested with v3.0.0 - chrome 60.

```html
 <vaadin-grid-selection-column >
          <template >
                  <input aria-label="Select Row" type="checkbox" checked="{{selected}}" ></input>
            </template>
 </vaadin-grid-selection-column>
```

https://jsfiddle.net/krikrou/8akgbocq/2/

**Comment by tomivirkki** [comment]
What's missing from your example above is the event name in two-way binding `{{selected::change}}`.

The fiddle has it but there's an error in the syntax (needs two colons `{{selected::change}}` instead of one `{{selected:change}}`)

**Comment by christophe-g** [comment]
ooups sorry - over simplified my use case and created another problem!
However, problems remain when items are set after grid instantiation, as reported in #938 .
