### ISSUE TITLE
vaadin-grid-selection-column: problem with internal template and items set after grid instantiation 

### ISSUE THREAD

**Issue by christophe-g** [vaadin/vaadin-grid#938]
There are two problems illustrated here:
https://jsfiddle.net/krikrou/8akgbocq/9/

The first one is that `selected`  binding does not work: checkbox is checked on click, but the item is not actually selected, as per grid `selectedItems`.

The second one lies with header template and is happening even when items are defined before grid rendering:  changing state of `selectAll` does not propagate to `vaadin-grid-selection-column` and has no effect on grid items selection.  

I could make it work only by adding a `on-tap` `_onSelectAll` listener and changing the `headerTemplate.templatizer.dataHost` when preparing the template, as in : 

```html
<template class="header">
     <paper-checkbox checked="{{selectAll}}"  on-click="_onSelectAll" ></paper-checkbox>
</template>
```

in vaadin-grid-selection-column.html:
```js
ready: function() {
        var headerTemplate = this._prepareTemplatizer(this._findTemplate('template.header') || this.$.defaultHeaderTemplate);
        // needed to override the dataHost correctly in case internal template is used.
        headerTemplate.templatizer.dataHost = this;  //headerTemplate === this.$.defaultHeaderTemplate ? this : this.dataHost;
        this.headerTemplate = headerTemplate;

```

Problem previously reported in #937, but over simplified.

**Comment by moderndeveloperllc** [comment]
@christophe-g I noticed on your jsfiddle that you are using polymer 1.x. The {{selected}} seems to work if you are using polymer 2.

**Comment by christophe-g** [comment]
@moderndeveloperllc - thanks !

You are right, it works with Polymer 2. Unfortunately, I cannot upgrade yet. 
The issue related to `selectAll` remains though.

**Comment by web-padawan** [comment]
We no longer support `vaadin-grid` version 3, and now it is very outdated. Please consider using the most recent version (currently 5.x) which gets all the fixes.

There hasn't been any activity in this issue for a while. Closing as stale.
