### ISSUE TITLE
Scrolling is super-slow in Win/Firefox

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#939]
Scrolling is something like 10-20 times slower than in Chrome.

To clarify, scrolling is not “janky”, but the scroll wheel event just moves the scroll position really small amounts. Scrolling is fast if you drag the scrollbar.

Win 7 / Firefox 54

**Comment by limonte** [comment]
Just checked this issue again and the issue is still present in `4.0-preview` branch.

**Comment by jouni** [comment]
No problem with scrolling in Firefox 55 on macOS.

Column group headers are broken, though :)

**Comment by jouni** [comment]
Confirmed as well, the scrolling is slow on Win10 Firefox 55.

**Comment by jouni** [comment]
Added a small clarification to the description.

**Comment by johannesh2** [comment]
We are currently using 3.0 in Bakery and this affects us.
