### ISSUE TITLE
Missing border when using a "row-details" template

### ISSUE THREAD

**Issue by robotoer** [vaadin/vaadin-grid#942]
Currently when expanding the last row of a vaadin-grid causes the requested "row-details" template to be displayed underneath the row with no divider present between the "row-details" template and the last row itself.

Here's an example of the bug on: https://cdn.vaadin.com/vaadin-grid/3.0.0/demo/row-details.html

![Image of Issue](http://g.recordit.co/cm7cxTgGCY.gif)

**Comment by samiheikki** [comment]
Thanks for the bug report

**Comment by web-padawan** [comment]
This wasn't fixed for 3.x but we don't have this issue on master using `src`, `lumo` or `material`.

We no longer support `vaadin-grid` version 3, and now it is very outdated. Please consider using the most recent version (currently 5.x) which gets all the fixes.

Closing as won't fix.
