### ISSUE TITLE
Allow the developer to create wrappers around <vaadin-grid-column>

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-grid#952]
Question: has a `<vaadin-grid-column>` to be a direct child (in the dom tree) of the `<vaadin-grid>`?

Or is it possible to have the `<vaadin-grid-column>` inside a custom element `<my-grid-column>` which I'll then use as a child of the `<vaadin-grid>`?

I'm trying this in various versions, but I'm always failing. No columns are generated when `<vaadin-grid-column>` is a child custom element outside the element where the `<vaadin-grid>` is used.

Any help or ideas are welcome!

Regards,
Michael

**Comment by manolo** [comment]
vaadin-grid-column only can be a direct child of vaadin-grid or vaadin-grid-column-group

**Comment by jouni** [comment]
Hi! Thanks for the question.

What are you trying to do exactly? What’s the use case you have, I’m interested in hearing.

Also, for initial questions, we recommend our Gitter chat instead of GitHub issues: https://gitter.im/vaadin/vaadin-core-elements

**Comment by Mika83AC** [comment]
Hey @jouni,

I'm trying to build a "base grid" implementation, using your vaadin-grid. More exactly, I'm heavily extending (building arround) the vaadin-grid with all the functionality I need for a grid in our applications.

These are:
- Dynamic column generation from an array of column data
- Conditional row/cell styles from an array of conditions
- Computed column contents based on the grid-data & passed computation functions
- Extended filter functionalities (wildcards, logic operations like "> 20" e.g.)
- Multi selection on desktop (like known from Windows by pressing Shift) & mobile
- Context menu on desktop & mobile
- some more but minor things

As this generates a lot of JS code and markup, I started to factor out parts of my "my-grid" implementation to seperat components like "my-grid-column-header", "my-grid-column-content". My next try was to factor out a whole "my-grid-column" (which then will use "my-grid-column-header" and "my-grid-column-content"), but here I got stuck as it seemed it has to be direct child of vaadin-grid without any "component barrier". That's the reason for my question here and hoping it would be possible ;) That could make my implementation much more clean than having all these things in one component. 

Thx for the link to your gitter, I'll use it next time!

**Comment by jouni** [comment]
Thanks for the detailed explanation! Some of those are actually in our future enhancements list :)

I would like if we could enable this kind of extendability that could also be encapsulated nicely. @tomivirkki, do you have ideas what the blockers are?

Are you using vaadin-context-menu, btw?

**Comment by Mika83AC** [comment]
Yes, I'm using the vaadin-context-menu, but have an unsolved issue with it's mobile functionality when using a plain html menu instead of paper-menu: [https://github.com/vaadin/vaadin-context-menu/issues/90](https://github.com/vaadin/vaadin-context-menu/issues/90)

The issue was closed but is still unsolved for me. Maybe you can reopen it, I can't ;)

**Comment by jouni** [comment]
Reopened.

**Comment by Mika83AC** [comment]
Regarding the vaadin-context-menu, the same question arrises: has the vaadin-context-menu to be in the same dom-module than then vaadin-grid it is listening on, or can I factor out the vaadin-context-menu to another component which I then use inside my main grid implementation? 

I tried it but the vaadin-context-menu doesn't become visible when the context menu open event fires. I guess it's a "paint" problem. I can see the vaadin-overlay being created in the dom (Chrome DevTools -> Elements), but that's all. The menu itself doesn't open (or maybe opens but has a wrong z-index... ?).

**Comment by manolo** [comment]
Sorry I'm a bit lost here, what is the concrete issue that should be fixed here? Title should be updated.

**Comment by jouni** [comment]
@manolo, the developer should be able to create wrappers around `<vaadin-grid-column>` (and possibly `<vaadin-grid-column-group>`) to provide some encapsulated features for the columns. That’s at least one thing, if I understood correctly.

**Comment by Mika83AC** [comment]
Yes, that's what I'm intending to do 👍

**Comment by Mika83AC** [comment]
Should this issue maybe reopened as it is a pending consideration?

**Comment by tomivirkki** [comment]
If the columns are wrapped inside another element's shadow root, grid probably shouldn't try to access them.
With `<vaadin-grid>` 4 though, the column elements can be extended. However, Grid uses querySelector to find column in it's own light dom by exact tag names and doesn't cover custom tags at the moment.

**Comment by yveslange** [comment]
Hi @tomivirkki,

any updates to have custom content (<slot></slot>) for cells ?

**Comment by tomivirkki** [comment]
@yveslange This feature is shipped.

For the original issue, nowadays it's possible to extend the column classes so that custom functionality can be added on top of the base class. As long as the extended class satisfies [this](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid-dynamic-columns-mixin.html#L138) condition, it's considered a column by the grid. Please reopen if there's still some issue regarding this.
