### ISSUE TITLE
Polymer lint complains on data-provider

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-grid#958]
It's probably all in the title. I have this output from linting:

```
 <vaadin-grid id="grid" data-provider="{{dataProvider}}" class="ey-table" style="height:100%">
                               ~~~~~~~~~~~~~

src/ey-blocks/ey-vaadin-datagrid.html(8,31) error [set-unknown-attribute] - data-* attributes must be accessed as attributes. i.e. you must write:  data-provider$="{{dataProvider}}"
```

But using it as an attribute, even if I don't have errors, doesn't work (empty grid, of course).

**Comment by web-padawan** [comment]
Related [issue](https://github.com/Polymer/polymer-linter/issues/68) for `polymer-linter`.

**Comment by andreabioli** [comment]
Good point, but maybe, for formal correctness, you should NOT use this kind of solution, so to avoid any conflict and/or problem... (very personal opinion, of course... :-) )

**Comment by web-padawan** [comment]
@andreabioli I mean that, unless this issue is fixed on the linter side, there is nothing to do here (the only option is to rename property name which would be breaking change).

**Comment by andreabioli** [comment]
Yes, unfortunately it would be a breaking change... :-(

**Comment by web-padawan** [comment]
Polymer CLI has not been updated for a while and it's unlikely that they ever fix that.

We recommend using [lit-analyzer](https://github.com/runem/lit-analyzer) for `lit-html` templates, and there you should bind to property:

```js
render() {
  return html`
    <vaadin-grid .dataProvider="${this.dataProvider}"></vaadin-grid>
  `;
}
```

We are not going to change the property name. So I'm closing this issue.
