### ISSUE TITLE
Unable to sort by index

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#962]
The following doesn’t seem to work out of the box with an array data source:

```html
<vaadin-grid-column>
  <template class="header">
    <vaadin-grid-sorter path="index">#</vaadin-grid-sorter>
  </template>
  <template>[[index]]</template>
</vaadin-grid-column>
```

Tested using 4.0-preview

**Comment by tomivirkki** [comment]
Path is always relative to the `item` property as documented in https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-sorter.html#L111

Index, expanded, selected are instance properties that you can bind to in templates but can't filter, sort by.
You can always add generated `item.index` property to your items and sort by that

**Comment by jouni** [comment]
Closing for now. Please add comments if you think this is something you would like to have.

**Comment by tomivirkki** [comment]
Sounds a bit dangerous to inject values into a client's data. It might accidentally get reflected to a database or something.

**Comment by jouni** [comment]
That’s true. I kinda knew that was a silly suggestion, but I’m just trying to get you to think of better solutions :)
