### ISSUE TITLE
how to styling the checkbox in vaadin-grid-selection-column?

### ISSUE THREAD

**Issue by robertop87** [vaadin/vaadin-grid#969]
I did not see a explicit mixin to customize style of checkboxes in the vaadin-grid-selection-column.

Could you please show us, how to do that?

**Comment by tomivirkki** [comment]
There's no mixin for the selection column checkbox. Instead you can provide it a template with a checkbox of your choice and style that instead.

Here's an example https://cdn.vaadin.com/vaadin-grid/3.0.0/demo/styling-material.html of replacing the default checkbox with a paper-checkbox

**Comment by robertop87** [comment]
Great!, thank you :)
