### ISSUE TITLE
cloneNode(true) doesn't work on vaadin-grid element

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-grid#976]
I'm attempting to dynamically create a number of grids on my page based on hierarchical data being returned from a data source (row groups). I have one element created in my `<template>` that I'm attempting to `cloneNode(true)` based on how many categories my data source returns. 
```
<div id="results">
  <vaadin-grid id="patientGrid" column-reordering-allowed>
  //Three resizable column definitions
  </vaadin-grid>
</div>
```

I then have in my JS
```
let clone = this.$.patientGrid.cloneNode(true);
clone.id = 'patientGrid2';
this.$.patientGrid.items = request.response.items1;
clone.items = request.response.items2;
this.$.results.appendChild(clone);
```

Basically, the cloned grid object gets header cells that have the same `id` and `slot` numbers. These headers do not display for the cloned object. The <vaadin-grid-cell-content> elements for the data itself are created in the cloned object, but no data is actually displayed.

Is there a way around this, or do I need to import a template for each row group? As sometimes a picture is worth a thousand words, I've attached a few to illustrate what's going on. The black boxes are the correct, redacted data.

<img width="979" alt="clonedgrid" src="https://user-images.githubusercontent.com/1920405/30217672-7dd342d6-947c-11e7-84b7-ebcdeb15bcc4.png">

<img width="628" alt="clonedoutput" src="https://user-images.githubusercontent.com/1920405/30217707-9a1255f4-947c-11e7-8907-4f6b87c5bcae.png">

**Comment by moderndeveloperllc** [comment]
@jouni @manolo Any thoughts on this? If cloning isn't the preferred way, any thoughts on dynamically generating multiple grids per view? I'm loathe to use `importHref` as that is going away in Polymer 3 and dynamic `import()` hasn't been finalized/shimmed yet, so no moving over to Polymer 3 anytime soon.

**Comment by tomivirkki** [comment]
Hi @moderndeveloperllc, cloning the grid using `cloneNode` is problematic since, as you’ve noticed, also the light dom nodes will be copied. You would have to remove all the `<vaadin-grid-cell-content>` elements manually upon cloning to make it work.

Is it an option for you to use `<dom-repeat>` instead? If not, what about defining a template (with a grid in it) of which you can stamp instances manually?

**Comment by moderndeveloperllc** [comment]
@tomivirkki I'll try those two ideas.
