### ISSUE TITLE
Stilying input of vaadin-grid-filter

### ISSUE THREAD

**Issue by robertop87** [vaadin/vaadin-grid#977]
is there a mixin or approach to customize the style of input element in the vaadin-grid-filter?

**Comment by tomivirkki** [comment]
You can replace the default input with any input as done here: https://cdn.vaadin.com/vaadin-grid/3.0.2/demo/sorting-filtering.html

...and then apply any styles to that input. For example: https://cdn.vaadin.com/vaadin-grid/3.0.2/demo/styling-valo.html
