### ISSUE TITLE
Sorting bug when property is nested more than two levels

### ISSUE THREAD

**Issue by steltz** [vaadin/vaadin-grid#980]
I ran into a small bug in `vaadin-grid-array-data-provider-behavior.html` when I tried to sort on column data that is more than two levels nested.

Object of data I'm sorting:
```
{
  "name": "App 1",
  "metrics": {
    "builds": {
      "past24": 0,
      "pastWeek": 0
    },
    "deploys": {
      "past24": 0,
      "pastWeek": 0
    },
    "qualityScans": {
      "past24": 0,
      "pastWeek": 0
    },
    "securityTests": {
      "past24": 0,
      "pastWeek": 0
    }
  }
}
```
The bug is in how the path to the `parentProperty` is set:

```
var parentProperty = path.replace(/\.[^\.]*/, ''); // a.b.c -> a.b
if (Polymer.Base.get(parentProperty, items[0]) === undefined) {
  console.warn(
    'Path "' + path + '" used for ' + action + ' does not exist in all of the items, ' + action + ' is disabled.'
  );
  result = false;
}
```

`path` = "metrics.builds.past24"
`path.replace(/\.[^\.]*/, '')` = "metrics.past24"

The parentProperty should equal `metrics.builds`

To fix this issue, you could do something like:

`var parentProperty = path.substring(0, path.lastIndexOf(".")); `

Let me know if you want me to issue a PR.

Thanks for creating this web-component!

**Comment by tomivirkki** [comment]
Hi @steltz
Which version of `<vaadin-grid>` are you using? The issue was fixed in https://github.com/vaadin/vaadin-grid/commit/29141930d6594d120af6a51f5cf2a7cc72b3de5d and at least both `<vaadin-grid>` 3 (hybrid) and 4 (P2, alpha) should have it fixed.
