### ISSUE TITLE
[Question] How to put the filter input out of the vaadin-grid? (Polymer)

### ISSUE THREAD

**Issue by robertop87** [vaadin/vaadin-grid#988]
Hi guys,

I'm trying to put the filter-input out of the vaadin-grid, and this should filter by text search in all vaadin columns. Then my first big question is: how to bind the paper-input value into vaadin-grid-filter value and hide it?

```html
<paper-input value="{{filter}}"></paper-input>

<vaadin-grid>
  <vaadin-grid-column>
      <vaadin-grid-filter>
         <!-- Hide this in the column header and use the {{filter}} value -->
      </vaadin-grid-filter>
  </vaadin-grid-column>
</vaading-grid>
```

**Comment by tomivirkki** [comment]
Hi @robertop87, you can completely customize filtering/sorting by using `dataProvider` like in this example: https://cdn.vaadin.com/vaadin-grid/3.0.2/demo/sorting-filtering.html#filtering-with-data-provider

The built-in `vaadin-grid-filter` helper only filters by one item sub-property.

If you want to hide the default filtering helpers and bind custom values to them, that should also be doable. Just apply any wanted string to the `value` property of a filter: https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-filter.html#L47
