### ISSUE TITLE
IONIC 3: Uncaught (in promise): TypeError: Cannot read property 'nativeElement' of undefined TypeError:

### ISSUE THREAD

**Issue by DanielCarrilloHerrera** [vaadin/vaadin-grid#989]
Hi lads. How are you?. I am having a problem with a Geolocation app that does not runs because of one error that I couldn't fixed it. This is the error message:

`Uncaught (in promise): TypeError: Cannot read property 'nativeElement' of undefined TypeError: Cannot read property 'nativeElement'`

This is the code that is generating the problem. This one is inside a function called loadMap()

`    this.geolocation.getCurrentPosition().then((position)=>{

      let latLng = new google.maps.LatLng(position.coords.latitude,
                                          position.coords.longitude);
      
      let mapOptions = {
        center: latLng,
        zoom: 15,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      }
      
      this.map = new google.maps.Map(this.mapElement.nativeElement, mapOptions);

    }, (err) => {
      console.log(err);
    });
`

Thanks for your help!

**Comment by tomivirkki** [comment]
Hi @DanielCarrilloHerrera, Hmm, I don't quite understand how this issue relates to `<vaadin-grid>` element? I'll re-open this if it turns out to be a `<vaadin-grid>` issue
