### ISSUE TITLE
Use `aria-rowcount` and `aria-rowindex` attributes

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#991]
Improve screen reader support by adding correct [aria-rowcount](https://www.w3.org/TR/wai-aria-1.1/#aria-rowcount) and [aria-rowindex](https://www.w3.org/TR/wai-aria-1.1/#aria-rowindex) attributes to the DOM.

**Comment by knoobie** [comment]
> Do you happen to know how well screen readers support those attributes?

I could find at least some information on NVDA (https://github.com/nvaccess/nvda/pull/7410) 

So it's just a matter of time until all support this.

**Comment by web-padawan** [comment]
Implemented in #1023 and released in [4.0.0](https://github.com/vaadin/vaadin-grid/releases/tag/4.0.0).
