### ISSUE TITLE
Unable to have dynamic height on row details

### ISSUE THREAD

**Issue by leelakrish** [vaadin/vaadin-grid#993]
I have a simple table in the row details section of a grid and have functionalities like add remove rows. When I do that the height of row details is not adjusting or increasing instead It has the scroll.

**Comment by tomivirkki** [comment]
If you make asynchronous changes to grid content, you should invoke `grid.notifyResize()` to make grid recalculate sizing and positioning. Reopen if this doesn't work.

**Comment by leelakrish** [comment]
notifyResize() isn't working with inner Grid.

**Comment by tomivirkki** [comment]
What do you mean by inner grid? Is there another grid wrapped inside your details row?

**Comment by leelakrish** [comment]
Yes I am.   
<vaadin-grid id="parentGrid" items="[[data]]" active-item="{{activeItem}}" selected-items="{{selectedRowItems}}">
      <div class="inner-container">
        <template class="row-details">
           <vaadin-grid id="innerGrid">
           </vaadin-grid> 
       </template>
     </div>
</vaadin-grid>

**Comment by tomivirkki** [comment]
So are you removing items from the grid inside details row? Have you assigned the wrapped grid's `height: auto` so that it actually resizes to match the number of rows it has?

I would help us a lot if you could provide a live example so we can see live what the issue is?

**Comment by leelakrish** [comment]
Yes i I have height: auto first time it resize and matches in the inner grid. But when i start adding a row or removing a row in the inner grid the resize isn't working.
