### ISSUE TITLE
height: auto & Firefox issue

### ISSUE THREAD

**Issue by mmport80** [vaadin/vaadin-grid#995]
This feature works really well on Chrome but not on Firefox. See screenshot below - a scrollbar is used instead.

```
vaadin-grid {
        height: auto;
      }
```

![image](https://user-images.githubusercontent.com/7381367/30641876-e93b36d8-9e08-11e7-8799-edccc714ac12.png)

**Comment by tomivirkki** [comment]
The feature works for me on Firefox at least in this demo https://cdn.vaadin.com/vaadin-grid/3.0.2/demo/data.html

Which version of the `<vaadin-grid>` are you using?

**Comment by mmport80** [comment]
I am using 3.0.1.

The demo works for me also! OK, that gives me some confidence, I will close.
