### ISSUE TITLE
Transpilation of Dependencies

### ISSUE THREAD

**Issue by mmport80** [vaadin/vaadin-grid#996]
I have built a web component on top of the wonderful Grid components.

I use polymer.json to set up transpilation / build instructions for my component to compile to ES5, as described here,

https://www.polymer-project.org/2.0/docs/tools/polymer-json

but unfortunately the Vaadin dependencies in 'bower_components' do not get compiled automatically, just copied into the build directory.

I suspect I am missing something obvious (the really obvious thing is polymer serve) but I am embedding this into a larger application...

Another obvious thing is Polymer 3...

I realise this may not be the correct forum for this type of query, but I spent a lot of time looking and couldn't find anywhere ... Thanks.

**Comment by web-padawan** [comment]
@mmport80 here is the workflow which works perfectly:

1. make sure you have latest `polymer-cli` installed (current version: 1.5.7):
```
npm i -g polymer-cli
```
2. init the app with starter kit:
```
polymer init polymer-2-starter-kit
```
3. install latest vaadin-grid:
```
bower install vaadin-grid --save
```
4. include the HTML import into the file, e. g. `my-view1`, and place the component in the template

5. run the build:
```
polymer build
```
6. serve and check the output:
```
polymer serve build/es5-bundled
```

For large application, you might need to implement custom build with `gulp`, so take a look at [polymer-build](https://github.com/Polymer/polymer-build) library. Anyways, you can rely on official tools by Polymer team, there is nothing to do for us in Vaadin here. Therefore I am closing this issue.

If you still need help, please ask the question in the Polymer Slack. Personally, I would recommend [#tools](https://polymer.slack.com/messages/C2NH75P0D) channel for your issue, but for any elements-related questions feel free to ping us in the [#vaadin](https://polymer.slack.com/messages/C6ULJ2F7S) channel as well.
