### ISSUE TITLE
Very poor performance for the multiple columns (40+)

### ISSUE THREAD

**Issue by knoga** [vaadin/vaadin-grid#997]
For the multiple columns (40+) performance is very poor. The grid (v 3.0.2) is practically impossible to use in Mozilla Firefox (v55). In the Chrome is a little better. However I have the impression that grid in version 2.0 is more efficient. This may be due to the transition to slots...

**Comment by tomivirkki** [comment]
40+ columns is a lot. Grid currently only has virtual scrolling for rows but not for columns so any new column will result in new DOM elements. We've been thinking of different approaches to improve the performance for grids with lots of columns but there are no decisions on this yet.

You can improve the performance for now by not having all the columns visible at the same time (using column hiding feature for example).

In case you're using Polymer 2, you could also try `4.0-preview` branch (temporary branch!) if the performance is any better than with grid 3

**Comment by knoga** [comment]
Yes, the 4.0-preview version is much more efficient. It is already known release date of the final version? But... styles from 3.0 not working properly in the 4.0

**Comment by tomivirkki** [comment]
We're planning to release 4.0.0-alpha1 next week. Beta hopefully within a month. Grid 4.0 has completely different styling APIs from 3: we’ve dropped style mixins in favour of “shadow parts”. Ground level approach in styling is to define a style module with a “theme-for” attribute. For example:
```
<dom-module id="my-app-grid-styles" theme-for="vaadin-grid">
  <template>
    <style include="vaadin-grid-default-theme">
      [part~="header-cell"] {
        background: blue;
      }
    </style>
  </template>
</dom-module>
```
The parts and state attributes you can target in the modules are currently documented here: https://github.com/vaadin/vaadin-grid/blob/4.0-preview/vaadin-grid.html#L61

Vaadin also provides complete customizable theme packages like [Valo](https://github.com/vaadin/vaadin-valo-theme) that you can just drop on a page with Vaadin elements. The themes can be customized on a high level via CSS properties. Documentation on this at: https://cdn.vaadin.com/vaadin-valo-theme/0.3.1/demo/index.html

**Comment by knoga** [comment]
Thank you very much for your help. Good luck...

**Comment by yveslange** [comment]
Hi, version `4.0.x` is way more efficient thant `v3.0.2`. It is usable with 90+ columns (still a bit laggy and slow). 

The loading time is pretty slow and the grid is usable after that the 230+ warnings stops.

![debounce](https://user-images.githubusercontent.com/17984393/31732328-7557c0c4-b438-11e7-9fb6-ab62c27c9df7.PNG)

 Any idea how to fix those warnings ?

**Comment by yveslange** [comment]
The solution was to update from Polymer 2.0.x to `Polymer 2.2.0`. The grid with 90 columns is ready after 20sec of loading time.

**Comment by yveslange** [comment]
Is it possible to know when the columns of the grid are ready ? My goal is to display a "loader" while the grid is generating the columns (and/or rows) and is not ready to be used.
